Die meisten Nutzer sind sich der Auswirkungen bewusst, die der
fortschreitende Prozess des Pornokonsums, der zur Suche nach Neuem und
Eskalation führt, auf das Belohnungs- und Sexualsystem ihres Gehirns
hat. Sie sind sich jedoch nicht bewusst, welche Auswirkungen dies auf
ihr Energieniveau hat.

Eine der Feinheiten der Pornofalle ist, dass die Auswirkungen auf
unseren Körper und unsere Psyche so allmählich und unmerklich ablaufen,
dass wir sie nicht wahrnehmen und sie als normal ansehen. Der Effekt ist
ähnlich wie bei schlechten Essgewohnheiten: Wir sehen uns Menschen an,
die stark übergewichtig sind, und fragen uns, wie sie es sich erlauben
konnten, diesen Zustand zu erreichen. Aber stell dir vor, es wäre über
Nacht passiert, du wärst schlank und muskulös ins Bett gegangen und
hättest kein Gramm Fett an deinem Körper und wachst auf und findest dich
dick, aufgedunsen und dickbäuchig. Anstatt ausgeruht und voller Energie
aufzuwachen, fühlst du dich elend, lethargisch und kannst kaum die Augen
öffnen.

Du hast Panik und fragst dich, was für eine schreckliche Krankheit du
dir über Nacht eingefangen hast, und doch ist die Krankheit genau
dieselbe. Die Tatsache, dass es zwanzig Jahre gedauert hat, bis du dort
angekommen bist, ist irrelevant. Porno ist dasselbe. Wenn es möglich
wäre, deinen Geist und deinen Körper sofort in die Zukunft zu versetzen,
um dir einen direkten Vergleich zu geben, wie du dich fühlen würdest,
wenn du nur drei Wochen lang mit Porno aufhören würdest, wäre das alles,
was du brauchst, um überzeugt zu sein. Die Frage, ob du dich wirklich so
gut fühlen würdest oder was das wirklich bedeutet, lautet: *\"Bin ich
wirklich so tief gesunken?* Du würdest dich nicht nur gesünder und
energiegeladener fühlen, sondern auch viel mehr Selbstvertrauen und eine
höhere Konzentrationsfähigkeit ausstrahlen.

Der Mangel an Energie, Müdigkeit und alles, was damit zusammenhängt,
wird gerne unter den Teppich des \"Älterwerdens\" gekehrt. Freunde und
Kollegen, die ebenfalls einen sesshaften Lebensstil führen, verstärken
die Normalisierung dieses Verhaltens noch. Der Glaube, dass Energie ein
ausschließliches Vorrecht von Kindern und Teenagern ist und dass das
Alter in den Zwanzigern beginnt, ist ein weiteres Symptom der
Gehirnwäsche, ebenso wie die Unkenntnis über Ess- und
Bewegungsgewohnheiten als Folge der verstärkenden Wirkung der
Dopamin-Desensibilisierung.

Kurz nachdem du mit den Pornos aufgehört hast, wird dich das neblige und
schwüle Gefühl verlassen. Der Punkt ist, dass du mit Pornos ständig
deine Energie verbrauchst und dabei die neurologische Chemie deines
Belohnungskreislaufs durcheinander bringst. Anders als bei der
Raucherentwöhnung, bei der die körperliche und geistige Gesundheit nur
allmählich wiederhergestellt wird, erzielst du bei der Pornoentwöhnung
vom ersten Tag an hervorragende Ergebnisse. Das \"kleine Monster\" zu
töten und die Wasserrutschen zu schließen, braucht ein bisschen Zeit,
aber die Wiederherstellung deines Belohnungskreislaufs ist bei Weitem
nicht so langsam wie die Rutsche in die Grube. Wenn du das Trauma der
Willenskraftmethode durchmachst, wird jeder Gewinn an Gesundheit oder
Energie durch die Depression, die du durchmachst, wieder zunichte
gemacht. Leider ist es nicht möglich, dass EasyPeasy dich in drei Wochen
sofort in deinen Geist versetzt, aber du kannst es! Du weißt instinktiv,
dass das, was dir gesagt wird, richtig ist, **du musst nur deine
Vorstellungskraft benutzen!**

# Finstere schwarze Schatten

Für Nutzer ist es sehr schwer zu glauben, dass die Selbstbefriedigung zu
Internetpornos tatsächlich diese unsicheren Gefühle auslöst, wenn du
spät abends noch aus bist oder nach einem anstrengenden Tag bei der
Arbeit. Nicht-Nutzer leiden nicht unter diesem Gefühl; Es sind die
Pornos, die es verursachen.

Eine weitere große Freude, wenn man mit Pornos aufhört, ist die
Befreiung von den finsteren schwarzen Schatten im Hinterkopf. Alle User
wissen, dass sie dumm sind, wenn sie sich vor den negativen Auswirkungen
der Pornografie verschließen. Die meiste Zeit unseres Lebens geschieht
das automatisch, aber die schwarzen Schatten lauern immer in unserem
Unterbewusstsein, direkt unter der Oberfläche. Einige der wunderbaren
Vorteile des Aufhörens sind uns bewusst, wie zum Beispiel die
Zeitverschwendung und die schiere Dummheit, mit einem zweidimensionalen
Bild Liebe zu machen.

Die letzten Kapitel haben sich mit den beträchtlichen Vorteilen eines
Nichtnutzers befasst, aber im Interesse der Fairness ist es notwendig,
eine ausgewogene Darstellung zu geben. Deshalb werden auf der nächsten
Seite die Vorteile eines Nutzers aufgelistet.

# Vorteile eines Porno-Nutzers
