# Warum ist es schwer aufzuhören?

Alle Nutzer haben das Gefühl, dass etwas Böses von ihnen Besitz
ergriffen hat. Am Anfang ist es eine einfache Frage der Einstellung:
*\"Ich werde aufhören, nur nicht heute\"*, aber irgendwann glauben wir,
dass wir nicht genug Willenskraft haben, um aufzuhören, oder dass Pornos
etwas an sich haben, das wir haben müssen, um das Leben zu genießen.
Pornosucht ist vergleichbar mit dem Weg aus einer rutschigen Grube: Wenn
du dich dem Gipfel näherst, siehst du die Sonne, aber du rutschst wieder
hinunter, wenn deine Stimmung sinkt. Schließlich öffnest du deinen
Browser und während du masturbierst, fühlst du dich schrecklich und
versuchst herauszufinden, warum du das tun musst.

Frag einen Nutzer: *\"Wenn du in die Zeit zurückgehen könntest, bevor du
süchtig wurdest, hättest du dann mit dem Wissen, das du jetzt hast,
angefangen, Pornos zu benutzen?\"*

*\"NIEMALS!\"* wäre die Antwort gewesen.

Frag einen eingefleischten Nutzer, der Internetpornos verteidigt und
nicht glaubt, dass sie das Gehirn schädigen oder die Dopaminrezeptoren
herunterregulieren: *\"Ermutigst du deine Kinder dazu, Pornos zu
benutzen?\"*

*\"Niemals!\"* ist die Antwort wieder.

Porno ist ein außergewöhnliches Rätsel. Wie schon gesagt, liegt das
Problem nicht darin zu erklären, warum es einfach ist, aufzuhören,
sondern warum es schwierig ist. Das eigentliche Problem ist, zu
erklären, warum jemand damit anfängt, *nachdem* er das Wissen über
neurologische Schäden gewonnen hat. Einer der Gründe, warum wir damit
anfangen, sind die vielen Millionen, die bereits damit angefangen haben,
und die sich wünschen, sie hätten gar nicht erst damit angefangen und
sagen, dass sie nicht ihr volles Potential ausgeschöpft haben. Wir
können nicht so recht glauben, dass sie es nicht genießen. Wir
assoziieren es mit Freiheit oder \"Sexualerziehung\" und arbeiten hart
daran, selbst süchtig zu werden. Wir verbringen dann den Rest unseres
Lebens damit, anderen zu sagen, dass sie es nicht tun sollen, und
versuchen, selbst davon loszukommen.

Außerdem verbringen wir einen großen Teil unserer Zeit damit, uns
hoffnungslos und unglücklich zu fühlen. Indem wir uns mit dem
Übernatürlichen \"erziehen\", bevorzugen und sehnen wir uns nach diesen
kalten Bildern, selbst wenn es warme, echte Bilder gibt! Durch das
ständige Auf und Ab des Dopamins, das durch PMO ausgelöst wird,
verurteilen wir uns selbst zu einem Leben voller Reizbarkeit, Wut,
Stress, Müdigkeit und sexueller Dysfunktion. Wenn wir Pornos
konsumieren, ohne die besten Seiten von Sex und Beziehung zu erfahren,
fühlen wir uns am Ende unglücklich und schuldig.

Wenn wir hier und auf anderen Seiten über die süchtig machenden und
zerstörerischen Fähigkeiten der Internetpornografie lesen, werden wir
noch nervöser und hoffnungsloser! Was ist das für ein Hobby, bei dem du
dir wünschst, du würdest es nicht tun, und wenn du es nicht tust, sehnst
du dich danach? Die Nutzer verachten sich jedes Mal, wenn sie über
Hypofrontalität und Desensibilisierung lesen, jedes Mal, wenn sie hinter
dem Rücken ihres vertrauensvollen Partners konsumieren, jedes Mal, wenn
sie sich nicht dazu durchringen können, nach einer Tagessitzung zu
trainieren. Ein ansonsten intelligenter und vernünftiger Mensch
verbringt seinen ganzen Tag mit Verachtung. Aber das Schlimmste ist, was
haben die Konsumenten davon, wenn sie das Leben mit diesen furchtbaren
schwarzen Schatten im Hinterkopf ertragen müssen? **Absolut nichts!**

Du denkst jetzt vielleicht: *\"Das ist ja schön und gut, aber wenn man
einmal süchtig nach diesen Dingen ist, ist es sehr schwer aufzuhören.\"*
Aber warum ist es so schwer? Manche sagen, es läge an den starken
Entzugserscheinungen, aber wie du noch lernen wirst, sind die
tatsächlichen Entzugserscheinungen so mild, dass du wissen solltest,
dass es PMOler gibt, die leben und sterben, ohne zu merken, dass sie
abhängig sind.

Manche sagen, dass Internetpornos kostenlos sind und die Menschheit
deshalb diese biologische Goldgrube für sich beanspruchen sollte, aber
das stimmt nicht - sie machen süchtig und wirken wie jede Droge. Frag
einen Nutzer, der schwört, dass er nur \"Erotika\" wie Playboy-Magazine
genießt, ob er schon einmal die Grenze zum \"unsicheren Porno\"
überschritten hat und dies unbewusst rationalisiert hat, anstatt gar
nichts zu benutzen.

Genuss hat auch nichts damit zu tun: Ich mag Flusskrebse, aber ich bin
nie an den Punkt gekommen, an dem ich jeden Tag Flusskrebse essen
musste. Bei anderen Dingen im Leben genießen wir sie, während wir sie
tun, aber wir sitzen nicht herum und fühlen uns als würde etwas Fehlen,
wenn wir es nicht tun.

Manche sagen:\
*\"Es ist lehrreich!\"* Und wann ist dein Abschluss? *\"Es ist sexuelle
Befriedigung!\"* Warum es also alleine tun, anstatt einen Partner zu
finden und es für ihn aufzusparen?\
*\"Es ist ein Gefühl der Befreiung!\"* Befreiung vom Stress des echten
Lebens? Pornos beseitigen nicht die Quelle des Stresses, aber sie
verstärken ihn.

Viele glauben, dass Pornos die Langeweile vertreiben, was ebenfalls ein
Trugschluss ist. Langeweile ist eine Geisteshaltung. Pornos gewöhnen
dich in kürzester Zeit an die Suche nach Neuem und führen dazu, dass du
dich immer mehr langweilst, bis du dich schließlich auf die wilde Jagd
nach dem richtigen Clip begibst und dich immer mehr darauf einstellst,
nach allem zu suchen, was neu ist, starke Emotionen hervorruft und
schließlich einen unerhörten Schockwert hat.

Manche sagen, sie tun es nur, weil ihre Freunde und alle, die sie
kennen, es auch tun. Du bist doch nicht so dumm, oder? Bete, dass deine
Freunde nicht anfangen, sich den Kopf abzuschneiden, um Kopfschmerzen zu
kurieren! Die meisten Nutzer, die darüber nachdenken, kommen zu dem
Schluss, dass es einfach eine Gewohnheit ist. Das ist zwar keine
wirkliche Erklärung, aber nachdem alle üblichen, rationalen Erklärungen
ausgeschlossen wurden, scheint es die einzige verbleibende
Entschuldigung zu sein. Leider ist sie genauso unlogisch. Jeden Tag in
unserem Leben ändern wir unsere Gewohnheiten, einige davon sind sehr
angenehm. Wir wurden einer Gehirnwäsche unterzogen und glauben, dass PMO
eine Gewohnheit ist und dass Gewohnheiten schwer zu durchbrechen sind.

Sind Gewohnheiten schwer zu brechen? Autofahrerinnen und Autofahrer in
den USA haben die Angewohnheit, auf der rechten Straßenseite zu fahren,
doch wenn sie nach Übersee reisen, brechen sie diese Gewohnheit ohne
großen Aufwand. Es ist eindeutig ein Trugschluss, dass Gewohnheiten
schwer zu brechen sind. Wir machen und brechen Gewohnheiten jeden Tag in
unserem Leben. Warum fällt es uns dann so schwer, mit einer Gewohnheit
zu brechen, die uns ein schlechtes Gewissen bereitet, wenn wir sie nicht
haben, und mit der wir uns schuldig fühlen, wenn wir sie haben, und die
wir am liebsten aufgeben würden, obwohl wir nur *aufhören müssten es* zu
tun?

Die Antwort ist, dass Porno keine Gewohnheit ist, sondern eine
**Sucht!** Deshalb scheint es auch so schwer zu sein, \"aufzuhören\".
Die meisten Nutzer verstehen nicht, was Sucht ist, und glauben, dass sie
durch Pornos echtes Vergnügen oder eine Krücke im Leben (z.B.
Stressbewältigung) bekommen. Sie glauben, dass sie ein echtes Opfer
bringen, wenn sie aufhören.

Die schöne Wahrheit ist, dass du, sobald du die wahre Natur der
Pornosucht und die Gründe, warum du sie benutzt, verstehst, ganz einfach
damit aufhören wirst. Innerhalb von drei Wochen wird das einzige Rätsel
sein, warum du es für nötig befunden hast, so lange Pornos zu benutzen,
und warum du andere Nutzer nicht davon überzeugen kannst, *wie schön es
ist, kein PMOer zu sein!*

## Die teuflische Falle

Internetpornos sind die raffinierteste, bösartigste Falle, die Mensch
und Natur gemeinsam entwickelt haben; es ist die einzige Falle in der
Natur, deren Aufstellung keine harte Arbeit erfordert. Manche von uns
werden sogar vor den Gefahren gewarnt, aber wir können nicht glauben,
dass sie keinen Spaß daran haben. Aber wie kommen wir überhaupt dazu, in
die Falle zu gehen? Normalerweise sind es kostenlose Proben von
Amateuren und Profis. So schnappt die Falle zu, dein erster \"Blick\"
hat Flecken und Löcher, und die meisten Vorschaubilder auf einer
Pornoseite sind amateurhafte und selbstgemachte Clips von unbekannten
Models. Wenn der erste Blick nur engelsgleiche Schönheiten und
professionelle Models zu sehen bekäme, würden die Alarmglocken läuten.

Aufgrund dieses Missverhältnisses in den Clips wird uns versichert, dass
wir nie süchtig werden, weil wir denken, dass wir jederzeit aufhören
können, wenn es uns nicht gefällt. Als intelligente Menschen würden wir
verstehen, warum die Hälfte der erwachsenen Bevölkerung systematisch
süchtig nach etwas ist, das ihr Potenzial, das zu tun, was sie sehen,
einschränkt. Die Neugierde bringt uns näher an die Türschwellen, aber
wir trauen uns nicht, auf die Vorschaubilder zu klicken, weil wir
befürchten, dass sie uns krank machen könnten. Wenn du versehentlich auf
eines klickst, wäre der einzige Wunsch, so schnell wie möglich von der
Seite wegzukommen.

Wir verbringen dann den Rest unseres Lebens damit, zu versuchen zu
verstehen, warum wir es tun, unseren Kindern zu sagen, dass sie nicht
damit anfangen sollen, und zuweilen versuchen wir auch, uns selbst zu
befreien. Die Falle ist so konstruiert, dass wir versuchen, nur aufgrund
eines \"Vorfalls\" aufzuhören, sei es sexuelle Leistung, der Verlust
einer Karriere oder einer Beziehung, Antriebslosigkeit oder einfach nur
das Gefühl, aussätzig zu sein. Sobald wir aufhören, haben wir aufgrund
von Entzugserscheinungen noch mehr Stress und die Methode, auf die wir
uns verlassen haben, um diesen Stress zu beseitigen, ist weg.

Nach ein paar Tagen der Qual kommen wir zu dem Entschluss, dass wir den
falschen Zeitpunkt zum Aufhören gewählt haben, und beschließen, auf
stressfreie Zeiten zu warten, die uns den Grund zum Aufhören nehmen.
Natürlich wird diese Zeit nie kommen, da wir innerlich glauben, dass
unser Leben immer stressiger wird. Wenn wir den Schutz unserer Eltern
verlassen, überschwemmen Stressfaktoren wie Jobs, Hausarbeit,
Hypotheken, Babys, größere Häuser und noch mehr Babys unser Leben. Das
ist eine Illusion, denn die Wahrheit ist, dass die stressigsten
Abschnitte im Leben eines jeden Lebewesens die frühe Kindheit und die
Jugend sind.

Wir neigen dazu, Verantwortung und Stress zu verwechseln. Das Leben
eines Drogenkonsumenten wird automatisch stressiger, denn Pornos
entspannen nicht und bauen keinen Stress ab, wie manche uns weismachen
wollen. Das Gegenteil ist der Fall: Je mehr du konsumierst, desto
stressiger wird dein Leben und schließlich wird das Fass zum Überlaufen
gebracht. Selbst wenn du dir die Sucht abgewöhnst (die meisten tun das
ein- oder mehrmals in ihrem Leben), kannst du ein glückliches Leben
führen und plötzlich wieder süchtig werden. Wenn wir in das
pornografische Labyrinth eintauchen, vernebelt sich unser Verstand und
wir verbringen den Rest unseres Lebens damit, zu versuchen, dem zu
entkommen, was vielen gelingt, nur um später wieder in die unheilvolle
Falle zu tappen.

Pornosucht ist ein komplexes und faszinierendes Rätsel, ähnlich wie ein
Rubik's Cube, das praktisch nicht zu lösen ist. Aber wenn du die Lösung
hast, ist es einfach und macht Spaß! EasyPeasy enthält die Lösung dieses
Rätsels und führt dich aus dem Labyrinth heraus, damit du nie wieder
hineingerätst. Alles, was du tun musst, ist den Anweisungen zu folgen.
Wenn du jedoch falsch abbiegst, ist der Rest der Anweisungen sinnlos.

Jeder kann es leicht finden, aufzuhören, aber zuerst müssen Fakten
geschaffen werden. Nein, keine Fakten, um dir Angst zu machen, es gibt
bereits mehr als genug Informationen. Wenn dich das aufhalten würde,
hättest du schon längst aufgehört. Aber warum fällt es uns so schwer,
aufzuhören? Um diese Frage zu beantworten, müssen wir den wahren Grund
kennen, warum wir immer noch Pornos konsumieren, und der lässt sich auf
zwei Faktoren reduzieren. Diese sind:

-   Natur und Internet Pornos.

-   Gehirnwäsche.

Pornokonsumenten sind intelligente, rationale Menschen. Sie wissen, dass
sie enorme Risiken für die Zukunft eingehen, also verbringen sie viel
Zeit damit, ihre \"Gewohnheit\" zu rationalisieren. Aber in ihrem Herzen
wissen Pornokonsumenten, dass sie dumm sind, denn sie wussten, dass sie
keine Notwendigkeit hatten, Pornos zu benutzen, bevor sie süchtig
wurden. Die meisten erinnern sich daran, dass ihr erster \"Blick\" eine
Mischung aus Abscheu und neuer Neugierde war. Dann spezialisierten sie
sich darauf, Seiten zu finden, zu filtern und zu bookmarken und
arbeiteten hart daran, süchtig zu werden.

Am ärgerlichsten ist das Gefühl, dass Nicht-Süchtige, meistens Frauen,
ältere Männer und Menschen, die in Ländern leben, in denen es keine
Hochgeschwindigkeits-Internetpornos gibt, nichts verpassen und die
Situation lächerlich finden. Nachdem wir diese Faktoren in den nächsten
Kapiteln beleuchtet haben, wirst auch du die bösartige Falle verstehen!
