# Gelegenheitsnutzer

Wenn du einen ständigen Juckreiz hast, neigst du natürlich dazu, ihn zu
kratzen. Da die Belohnungsschaltkreise des Gehirns zunehmend immun gegen
Dopamin und Opiate werden, besteht die natürliche Tendenz, zu edgen, zu
eskalieren, zu bingen (ein Film nach dem anderen gucken), nach Neuem zu
suchen, nach Schock zu suchen usw. Es gibt vier Hauptfaktoren, die
verhindern, dass die Nutzer bingen.

Zeit.

:   Die meisten können sich das nicht leisten.

Gesundheit

:   Um den Reiz zu lindern, müssen wir alles kostenlose Material
    konsumieren, das zur Verfügung steht, und noch einiges mehr. Die
    Fähigkeit, mit dieser Art von Binging umzugehen, variiert bei jedem
    Menschen zu verschiedenen Zeiten und in verschiedenen Situationen
    seines Lebens. Das wirkt wie eine automatische Limitierung.

Disziplin

:   Auferlegt von der Gesellschaft, der Arbeit, den Freunden und
    Verwandten oder vielleicht sogar vom Nutzer selbst als Ergebnis des
    natürlichen Tauziehens, das im Kopf jedes Nutzers stattfindet.

Vorstellungskraft

:   Mangelnde Vorstellungskraft reduziert den Schock, die Neuheit und
    andere Werte des Clips auf einer subjektiven Basis.

Es ist leicht, \"starke Nutzer\" für schwach zu halten, die nicht
verstehen können, warum andere ihren \"Konsum\" einschränken können.
Starke Nutzer sollten jedoch bedenken, dass die meisten
Gelegenheitsnutzer einfach nicht in der Lage sind, in Ketten zu schauen,
da sie dafür eine sehr starke Vorstellungskraft und Ausdauer brauchen,
um es zu schaffen. Einige der Einmal-die-Woche-Konsumenten, sind
körperlich nicht in der Lage, mehr zu tun, oder ihr Job, die
Gesellschaft oder ihr Hass auf die Sucht lassen es nicht zu, mehr zu
tun.

Es kann von Vorteil sein, ein paar Definitionen zu geben.

Der Nicht-Nutzer

:   Jemand, der nie in die Falle getappt ist, aber nicht selbstgefällig
    sein sollte. Er ist nur durch Glück oder die Gnade des Guten ein
    Nicht-Nutzer. Alle Nutzer waren davon überzeugt, dass sie nie
    süchtig werden würden, und einige Nicht-Nutzer versuchen es immer
    wieder mit einer gelegentlichen Sitzung.

Der Gelegenheitsnutzer

:   Es gibt zwei grundlegende Klassifizierungen von Gelegenheitsnutzern.

    1.  Der Nutzer, der in die Falle getappt ist, es aber nicht merkt -
        beneide solche Nutzer nicht. Sie probieren nur den Nektar an der
        Mündung der Kannenpflanze und werden höchstwahrscheinlich bald
        zu Starknutzer. Denke daran, so wie alle Alkoholiker als
        Gelegenheitstrinker angefangen haben, fangen auch alle
        Konsumenten als Gelegenheitsnutzer an.

    2.  Der Nutzer, der früher ein Starknutzer war und deshalb denkt,
        dass er nicht aufhören kann. Diese Konsumenten sind die
        traurigsten von allen und fallen in verschiedene Kategorien, von
        denen jede einen eigenen Kommentar benötigt.

Der Einmal-pro-Tag Nutzer

:   Wenn der Anspruch auf einen Orgasmus genossen wird, warum sollte man
    dann Internetpornos nur einmal täglich nutzen? Warum sollte man sich
    überhaupt die Mühe machen, wenn man es auch lassen kann? Vergiss
    nicht, dass die \"Gewohnheit\" in Wirklichkeit darin besteht, den
    Kopf gegen die Wand zu schlagen, damit es sich beim Aufhören
    entspannend anfühlt. Wer einmal am Tag nutzt, lindert seine
    Entzugserscheinungen für weniger als eine Stunde pro Tag. Auch wenn
    sie es nicht merken, verbringen sie den Rest des Tages damit, ihren
    Kopf gegen die Wand zu schlagen, und tun das für den Großteil ihres
    Lebens. Sie konsumieren einmal am Tag, weil sie nicht riskieren
    können, erwischt zu werden oder ihre neurologische Gesundheit zu
    gefährden. Es ist leicht, einen Starknutzer davon zu überzeugen,
    dass es ihm keinen Spaß macht, aber wesentlich schwieriger, einen
    Gelegenheitskonsumenten zu überzeugen. Jeder, der schon einmal
    versucht hat, seinen Konsum zu reduzieren, weiß, dass dies die
    schlimmste aller Folterungen ist und fast garantiert, dass du für
    den Rest deines Lebens süchtig bleibst.

Der abgelehnte Nutzer

:   Sie verlangen das Recht, jeden Tag einen Orgasmus zu haben, aber ihr
    Sexpartner ist nicht immer bereit, diese Bitte zu erfüllen. Anfangs
    nutzen sie Internetpornos, um diese Leere zu füllen, aber sobald sie
    die aufregende \"Wasserrutsche\" genommen haben, sind sie in einem
    Kreislauf aus Neuheit, Schock, übernormalen Bildern usw. gefangen.
    Eigentlich sind sie froh über die Ablehnung ihres Partners, denn das
    ist so etwas wie eine Ausrede. Wenn Internetpornos dir so viel
    geben, warum möchtest du dann überhaupt einen Partner haben? Lass
    sie stattdessen frei. Sie genießen nicht einmal die Sitzungen, wenn
    sie ihren Partner in ihren Gedanken \"tragen\" müssen. Irgendwann
    suchen sie nach ihrem Partner im wirklichen Leben, der ihnen eine
    Ausrede liefert, um in die Täler der dunklen Seite des Internets zu
    gehen.

Der Porn-Diät PMOer

:   Auch bekannt als: *\"Ich kann aufhören, wann immer ich will. Ich
    habe es schon tausende Male getan!\"*\
    Wenn sie glauben, dass eine Diät ihnen hilft, in Stimmung zu kommen,
    um sich einen Partner zu suchen, warum machen sie dann überhaupt
    eine Diät, die nur alle vier Tage stattfindet? Niemand kann die
    Zukunft vorhersagen. Was ist, wenn das zufällige Treffen eine Stunde
    nach der geplanten Sitzung stattfindet? Und wenn gelegentliches
    \"Reinigen der Rohre\" gut ist, um Spannungen abzubauen, warum dann
    nicht jeden Tag? Es ist erwiesen, dass Selbstbefriedigung nicht
    notwendig ist, um die Genitalien gesund zu halten, und
    Internetpornos sind überhaupt nicht notwendig. Selbst wenn das der
    Fall wäre, wird kein Anmach-Guru, der über die neurologischen
    Schäden gelesen hat, jemals empfehlen, Superstimulus-Pornos
    anzusehen. Die Wahrheit ist, dass sie immer noch süchtig sind. Auch
    wenn sie von der körperlichen Sucht befreit sind, bleibt ihnen das
    Hauptproblem der Gehirnwäsche. Sie hoffen jedes Mal, dass sie für
    immer damit aufhören können, tappen aber bald wieder in die gleiche
    Falle.

    Die meisten Nutzer sind neidisch auf diese Stopper und Starter und
    denken darüber nach, wie \"glücklich\" der Diätwillige ist, dass er
    seinen Konsum kontrollieren kann. Dabei übersehen sie jedoch, dass
    der Diätwillige seinen Konsum nicht unter Kontrolle hat und sich
    wünscht, er würde es nicht tun, wenn er konsumiert. Sie hören mühsam
    auf, fühlen sich dann entbehrungsreich und tappen wieder in die
    Falle und wünschen sich, sie hätten es nicht getan. Sie bekommen das
    Schlimmste aus beiden Welten. Wenn du darüber nachdenkst, ist das
    auch im Leben der Nutzer der Fall, wenn sie eine Sitzung haben
    dürfen und es als ihr Recht ansehen oder sich wünschen, sie hätten
    es nicht getan. Erst wenn man es ihnen vorenthält, wird es wertvoll.
    Das Syndrom der \"verbotenen Frucht\" ist eines der schrecklichen
    Dilemmas für Nutzer. Sie können nie gewinnen, weil sie einem Mythos,
    einer Illusion nachtrauern. Es gibt nur einen einzigen Weg, wie sie
    gewinnen können: indem sie aufhören, Trübsal zu blasen, indem sie
    mit Pornos aufhören!

Der \"I gucke nur statische Bilder und sichere (amateur) Pornos\" Nutzer

:   Ja, das macht am Anfang jeder, aber ist es nicht erstaunlich, wie
    der durchschnittliche Schockwert dieser Clips schnell ansteigt, und
    bevor wir uns versehen, fühlen wir uns als würden wir etwas
    vermissen (Toleranz)? Der Reiz des Neuen fehlt bei statischen
    Pornos, also zahlen wir die Zeche für eine Tasse Fett und fahren die
    Wasserrutsche hinunter in Richtung Groll und Schuld. Das Schlimmste,
    was du tun kannst, ist, die Bilder deines Partners (natürlich mit
    seiner Zustimmung) zur Selbstbefriedigung zu verwenden. Warum? Weil
    du damit dein Gehirn auf die Suche und Abwechslung verursachten
    Dopaminschübe neu kalibrierst, . Die Porno-Wasserrutschen in deinem
    Gehirn bauen DeltaFosB auf, so dass du Schwierigkeiten haben wirst,
    wenn du mit ihnen im echten Leben zusammen bist.

    Eine weitere Falle in dieser Kategorie sind \"Amateur\"- und
    \"selbstgemachte\" Pornos. Die meisten sind Fälschungen und du weißt
    das. Du wirst auch nicht beim ersten Bild aufhören, das dir ins Auge
    springt, sondern weiter suchen und suchen. Vergiss nicht, dass das
    Gehirn nicht nur den Orgasmus sucht, sondern auch die Neuheit der
    Jagd, die der Wasserrutsche ihren Nervenkitzel verleiht. Der
    Pornoinhalt ist nicht das Problem, egal ob Amateur oder Profi, es
    sind die Dopaminschübe im Gehirn, die zu Toleranz und Sättigung
    führen. Pornos zerstören die normale Gehirnfunktion, Masturbation
    verwirrt die Muskel-Gehirn-Reaktion. Der Orgasmus überflutet das
    Gehirn mit Opiaten, sodass der Weg beim nächsten Mal leichter zu
    beschreiten ist.

Der \"Ich habe aufgehört, aber ich schaue ab und zu\" Nutzer

:   In gewisser Weise sind die ab-und-zu Nutzer die erbärmlichsten von
    allen. Entweder gehen sie durch ihr Leben und glauben, dass sie
    beraubt werden, oder, was noch häufiger vorkommt, aus dem
    gelegentlichen Schauen werden zwei. Sie rutschen auf der schiefen
    Bahn nach unten und werden früher oder später wieder zu
    Starkkonsumenten. Sie sind wieder in die gleiche Falle getappt, in
    die sie schon einmal getappt sind.

Es gibt zwei weitere Kategorien von Gelegenheitsnutzern. Die erste ist
die, die zu Bildern oder Clips der neuesten Sexvideos von Prominenten
masturbiert, die in den Nachrichten auftauchen, oder zu etwas, das sie
von einer \"zufälligen\" Sichtung in der Schule oder auf der Arbeit
\"mit nach Hause genommen\" haben. Diese Menschen sind eigentlich nur
Nichtnutzer, aber sie haben das Gefühl, dass sie etwas verpassen. Sie
wollen Teil des Geschehens sein, und die meisten von uns fangen so an.
Wenn du das nächste Mal merkst, dass der Prominente deiner Fantasie nach
einer Weile nicht mehr so toll ist. Je \"unerreichbarer\" das Ziel
deiner Fantasie ist, desto frustrierender ist der Entzug des Orgasmus.

Die zweite Kategorie hat in letzter Zeit an Aufmerksamkeit gewonnen und
lässt sich am besten anhand eines Falles beschreiben, der online geteilt
wurde. Eine berufstätige Frau hatte viele Jahre lang Internetpornos
gelesen und nie mehr oder weniger als einmal pro Nacht benutzt. Sie war
im Übrigen eine sehr willensstarke Frau. Die meisten Nutzerinnen und
Nutzer würden sich fragen, warum sie überhaupt aufhören wollte, und
wiesen gerne darauf hin, dass in ihrem Fall keine Gefahr von PIED oder
PE bestand (was nicht stimmte). Sie benutzte nicht einmal statische
Bilder, denn die Geschichten waren viel zahmer als die, die sie selbst
täglich benutzen.

Sie machen den Fehler, anzunehmen, dass Gelegenheitsnutzer glücklicher
sind und mehr Kontrolle haben. Sie haben vielleicht mehr Kontrolle, sind
aber sicher nicht glücklich. Im Fall der Frau war sie weder mit ihrem
Partner noch mit echtem Sex zufrieden und sehr reizbar, wenn sie auf
ihre täglichen Belastungen reagierte. Ihre Liebsten konnten nicht
herausfinden, was sie bedrückte. Selbst wenn sie sich durch
Rationalisierung einredete, dass sie keine Angst vor ihrem Gebrauch
hatte, war sie immer noch nicht in der Lage, echte Beziehungen zu
genießen, die immer mit Höhen und Tiefen verbunden sind. Das
Belohnungszentrum ihres Gehirns ist nicht in der Lage, die normalen
De-Stressoren des Lebens zu nutzen, da es täglich mit Dopamin überflutet
wird. Die daraus resultierende Herunterregulierung der Rezeptoren in
ihrem Gehirn hat dazu geführt, dass sie unter den meisten Umständen
melancholisch ist. Wie die meisten hatte sie große Angst vor der dunklen
Seite des Pornos und der Behandlung von Frauen - bevor sie ihr erstes
Mal hatte. Schließlich fiel sie der Gehirnwäsche der Gesellschaft zum
Opfer und probierte ihre erste Seite aus. Anders als die meisten, die
kapitulieren und zu Kettennutzern werden, widerstand sie dem Abgleiten,
als sie die widerlichen Gewaltclips sah.

Das Einzige, was du an Pornos genießt, ist die Beendigung des
Verlangens, das zuvor begonnen hat, sei es das kaum wahrnehmbare
körperliche Verlangen oder die seelische Folter, den Juckreiz nicht
kratzen zu dürfen. Internetpornos sind selbst Gift, weshalb du die
Illusion, sie zu genießen, nur nach einer gewissen Zeit der Abstinenz
erträgst. Ähnlich wie bei Hunger oder Durst gilt: Je länger du es
erträgst, desto größer ist die Freude, wenn es endlich vorbei ist. Sie
machen den Fehler zu glauben, dass Pornos nur eine Gewohnheit sind,
denken sie: *\"Wenn ich es auf ein bestimmtes Maß beschränken kann oder
nur zu besonderen Anlässen, werden mein Gehirn und mein Körper es
akzeptieren. Dann kann ich den Konsum auf diesem Niveau halten oder
weiter reduzieren, wenn ich das möchte.* Mach dir klar, dass es die
\"Gewohnheit\" gar nicht gibt. Porno ist eine Drogensucht, bei der die
natürliche Tendenz darin besteht, die Entzugserscheinungen zu lindern,
nicht sie auszuhalten. Um den Konsum auf dem jetzigen Niveau zu halten,
müsstest du für den Rest deines Lebens ein enormes Maß an Disziplin und
Willenskraft aufbringen, denn wenn das Belohnungszentrum deines Gehirns
immun gegen Dopamin und Opiate wird, will es immer mehr und nicht immer
weniger.

Wenn Pornos nach und nach dein Nervensystem, deinen Mut, dein
Selbstvertrauen und deine Impulskontrolle zerstören, wirst du immer
weniger in der Lage sein, dem Verkürzen der Abstände zwischen den
einzelnen Sitzungen zu widerstehen. Deshalb können wir in den ersten
Tagen so leicht aufhören oder anfangen, wie wir wollen. Wenn wir ein
Anzeichen dafür bekommen, dass etwas nicht in Ordnung ist, hören wir
einfach auf. Beneide diese Frau nicht, denn wenn du nur einmal alle
vierundzwanzig Stunden einen Porno siehst, erscheint er dir als das
Kostbarste auf der Welt und macht Pornos zu einer \"verbotenen Frucht\".
Viele Jahre lang stand diese arme Frau im Zentrum eines Tauziehens.

Sie konnte nicht aufhören, Pornos zu konsumieren, hatte aber Angst
davor, es mit Streaming-Clips zu übertreiben. Dreiundzwanzig Stunden und
zehn Minuten lang musste sie an jedem dieser Tage gegen die Versuchung
und die fehlenden Gefühle gegenüber ihrem Freund ankämpfen. Es brauchte
enorme Willenskraft, um das zu tun, was sie tat, und am Ende brach sie
in Tränen aus. Solche Fälle sind selten, aber betrachte es logisch:
Entweder gibt es eine echte Krücke oder Freude an Pornos oder nicht.
Wenn es sie gibt, wer will dann eine Stunde, einen Tag oder eine Woche
warten? Warum solltest du in der Zwischenzeit auf das Vergnügen
verzichten müssen? Wenn es keine echten Hilfen oder Vergnügen gibt,
warum solltest du dann deinem Online-Harem einen Besuch abstatten?

Hier ist ein weiterer Fall eines Mannes, der einmal in vier Tagen nutzt
und sein Leben wie folgt beschreibt:\
*\"Ich bin vierzig Jahre alt, ich habe PIED mit echten Frauen und sogar
bei der Nutzung von Pornos, was meistens der Fall ist. Es ist schon eine
Weile her, dass ich eine volle Erektion hatte. Bevor ich mich auf die
Porno-Diät einließ, schlief ich nach einem Porno die ganze Nacht durch.
Jetzt wache ich jede Stunde in der Nacht auf und kann an nichts anderes
mehr denken. Selbst wenn ich schlafe, träume ich von meinen
Lieblingsclips. An den Tagen nach meiner geplanten Sitzung fühle ich
mich ziemlich niedergeschlagen, weil die Diät meine ganze Energie
aufbraucht. Meine SO (significant other, zu deutsch: Bessere \"Hälfte\"
oder Partner) würde mich allein lassen, weil ich so schlecht gelaunt
bin, und wenn sie nicht gehen kann, will sie mich nicht im Haus haben.
Ich gehe draußen joggen, aber mein Geist ist wie besessen davon. Am
geplanten Tag fange ich schon in der Nacht an zu planen und werde sehr
gereizt, wenn etwas gegen meine Pläne passiert. Ich ziehe mich aus
Gesprächen zurück und gebe bei der Arbeit und zu Hause nach (nur um es
später zu bereuen). Ich bin kein streitsüchtiger Typ, aber ich will
nicht, dass mich das Thema oder die Unterhaltung aufhält. Ich erinnere
mich an Zeiten, in denen ich dumme Streitereien mit meiner SO angefangen
habe. Ich warte auf zehn Uhr und wenn es so weit ist, zittern meine
Hände kontrolliert. Ich fange nicht gleich mit der Tat an, denn es sind
neue Videos hinzugekommen, also \"schaue ich mich um\". Mein Verstand
sagt mir, dass ich, nachdem ich vier Tage lang gehungert habe, einen
\"besonderen\" Clip verdient habe, der die Zeit der Suche wert sein
muss. Schließlich entscheide ich mich für einen oder zwei, aber ich
will, dass es länger hält, damit ich die nächsten vier Tage 'überleben'
kann, also nehme ich mir mehr Zeit, um die Tat zu vollenden.*\
Zusätzlich zu seinen anderen Problemen hat der arme Mann keine Ahnung,
dass er sich selbst mit Gift behandelt. Erst leidet er unter dem
\"Syndrom der verbotenen Früchte\" und dann zwingt er sein Gehirn,
Dopamin auszuschütten. Im Vergleich dazu sind seine Dopaminrezeptoren
nicht so stark geschädigt, aber er schmiert die Porno-Wasserrutschen,
sucht und sucht nach Aufregung, Neuheit, Abwechslung, Schock und Angst,
um die nächsten vier Tage zu überleben. Wahrscheinlich stellst du dir
diesen Mann als erbärmlichen Schwachkopf vor, aber das ist nicht so. Als
ehemaliger Sportler und ehemaliger Marineoffizier wollte er nicht
süchtig nach irgendetwas werden. Nach seiner Rückkehr aus dem Krieg
absolvierte er jedoch eine Ausbildung zum IT-Techniker in einem
Reha-Programm für Veteranen. Als er in das zivile Arbeitsleben eintrat,
war er ein gut bezahlter IT-Fachmann in einer Bank und bekam einen
Laptop, um seine Arbeit mit nach Hause zu nehmen. Es war das Jahr, in
dem berühmte Prominente ihre Pornovideos online \"leakten\" und es wurde
viel darüber gesprochen. Daraufhin wurde er süchtig und verbrachte den
Rest seines Lebens damit, viel Geld zu bezahlen und sich körperlich und
geistig zu ruinieren. Wenn er ein Tier wäre, hätte die Gesellschaft ihn
schon längst aus seinem Elend befreit, aber wir lassen es immer noch zu,
dass geistig und körperlich gesunde junge Teenager süchtig werden. Du
magst den Fall und die Notizen für übertrieben halten, aber dieser Fall
ist zwar extrem, aber bei weitem kein Einzelfall. Es gibt Zehntausende
von ähnlichen Geschichten. Kannst du dir sicher sein, dass viele seiner
Freunde und Bekannten ihn darum beneidet haben, dass er nur einmal in
seinem Leben abhängig war? Wenn du denkst, dass dir das nicht passieren
kann, **dann mach dir nichts vor.**

ES PASSIERT JETZT GERADE.

Wie andere Süchtige sind auch Pornonutzer notorische Lügner, sogar sich
selbst gegenüber. Das müssen sie auch. Die meisten Gelegenheitsnutzer
konsumieren viel öfter und bei viel mehr Gelegenheiten, als sie zugeben.
In vielen Gesprächen mit so genannten Zweimal-pro-Woche-Nutzern geben
sie zu, dass sie es mehr als drei oder vier Mal in der Woche getan
haben. Lies die Beiträge von Gelegenheitsnutzern auf reddit, NoFap und
in Reboot-Foren und du wirst feststellen, dass sie entweder die Tage
zählen oder darauf warten, zu versagen. Du brauchst Gelegenheitsnutzer
nicht zu beneiden, du brauchst auch keine zu benutzen, das Leben ist
unendlich viel süßer ohne sie. Lies das folgende Protokoll:

*\"Es begann mit einer einfachen Herausforderung, meinen Penis einen Tag
lang nicht zu berühren, und ich konnte es nicht. Ich denke nicht mehr an
Selbstbefriedigung, sie kommt mir nicht in den Sinn. Das ist möglich,
ich verspreche es dir. Der Reichtum, der auf diejenigen wartet, die dazu
in der Lage sind - er ist unglaublich.\"*

Teenager sind in der Regel schwieriger zu heilen, nicht weil es ihnen
schwerer fällt, aufzuhören, sondern weil sie nicht glauben, dass sie
süchtig sind oder sich im Anfangsstadium der Falle befinden und unter
der Illusion leiden, dass sie automatisch vor dem zweiten Stadium
aufgehört haben.

Eltern von Kindern, die Internetpornos verabscheuen, sollten sich nicht
in falscher Sicherheit wiegen. Alle Kinder verabscheuen die dunklen
Seiten von Pornos, bevor sie süchtig werden. Irgendwann hast auch du das
getan. Lass dich auch nicht von Panikmache täuschen, die Falle ist
dieselbe wie immer. Kinder wissen, dass Internetpornos einen
übernormalen Reiz darstellen, aber sie wissen auch, dass ein \"Besuch\"
oder \"Blick\" nicht ausreicht. Irgendwann werden sie vielleicht von
einem Partner, Mitschüler oder Arbeitskollegen beeinflusst.

Du denkst vielleicht, dass es nur einer Erziehung zur Plastizität des
Gehirns bedarf und dass Pornos (auch Masturbation) wie ein Virus in
ihrem Gehirn wirken, um sie davon zu überzeugen, dass sie niemals
süchtig werden können. Das Versagen der Gesellschaft, Jugendliche davor
zu bewahren, süchtig nach Internetpornos und anderen Drogen zu werden,
ist vielleicht die beunruhigendste der vielen Facetten der Sucht. Ich
bitte dich, in dieser Angelegenheit nicht selbstgefällig zu werden. Es
ist notwendig, Jugendliche zu schützen, da ihr Gehirn in ihrem Alter
noch sehr plastisch ist. Ein gutes Hilfsmittel ist das Buch
YourBrainOnPorn und die Aufklärung über die Neurowissenschaften. Selbst
wenn du den Verdacht hast, dass dein Teenager bereits süchtig sein
könnte, bietet das Buch eine hervorragende Anleitung, um zu verstehen,
wie man jemandem helfen kann, davon loszukommen.
