# Nur einmal kurz reingucken

Das ist das Verhängnis vieler, die die Willenskraftmethode anwenden. Sie
halten drei oder vier Tage durch und gönnen sich dann den einen oder
anderen Peek, um sich über Wasser zu halten. Sie sind sich nicht
bewusst, welch verheerende Auswirkungen das auf ihre Moral hat.

Für die meisten Nutzer war der erste Blick in den Harem der Tube-Site
nicht so gut wie der Sex mit einer echten Person. Die Clips, die sauber
sind, sind weit davon entfernt, ihrem Bewusstsein einen Schub zu geben.
Sie denken: *\"Gut, das war nicht ganz so erfreulich. Ich verliere die
Lust und stehe nicht so auf das schockierende Zeug.\"* In Wirklichkeit
ist das Gegenteil der Fall. Mach dir klar, dass der Spaß am Orgasmus
nicht der Grund war, warum du mit Pornos aufgehört hast. Wenn es den
Nutzern nur um den Orgasmus ginge, würden sie sich nie mehr als einen
Clip ansehen. Der einzige Grund, warum du Pornos brauchtest, war das
Füttern dieses kleinen Monsters. Stell dir vor, wie wertvoll dieser eine
Blick für dich gewesen sein muss, nachdem du vier Tage lang ausgehungert
warst. Dein Bewusstsein ist sich dessen nicht bewusst, aber den Fix, den
dein Körper erhalten hat, wird an dein Unterbewusstsein weitergegeben
und all deine gute Vorbereitung wird untergraben. Eine kleine Stimme in
deinem Hinterkopf sagt dir, dass sie trotz aller Logik wertvoll sind und
du noch eine haben willst.

Dieser kleine Blick hat zwei schädliche Auswirkungen:

1.  Es hält das kleine Monster in deinem Körper am Leben.

2.  Schlimmer noch, es hält das große Monster in deinem Kopf am Leben.
    Wenn du den 'letzten Blick' hattest, ist es einfacher, den nächsten
    zu haben.

Porno ist eine Mausefalle ohne Käse, nur mit Gift. Mit Willenskraft
musst du dich davon überzeugen, nicht nach dem Käse zu greifen, aber mit
EasyPeasy kannst du sehen, dass es Gift ist. Du musst sie nicht meiden,
du gehst einfach nicht hinein.

Und vor allem: Denk dran:

'Nur ein Blick' ist der Grund, warum Menschen überhaupt erst in die
Sucht geraten.
