image: rocker/verse

.bookdown:
  stage: deploy
  script:
    - tlmgr install amsmath
    - sh ./build.sh
    - mv _book public
  artifacts:
    paths:
      - public

pages:
  extends: .bookdown
  only:
    - master

