# Introduction

Ce manuel vous permettra d'arrêter de consommer de la pornographie immédiatement, sans douleur et de façon permanente, sans volonté ni sentiment de privation ou de sacrifice. Il ne vous imposera aucun jugement, aucune gêne ni aucune pression pour vous soumettre à des mesures douloureuses.
En fait, il n'est absolument pas nécessaire de réduire votre consommation pendant la lecture ; cela serait même préjudiciable.

Cela va peut-être à l'encontre de tout ce que l'on vous a dit, mais demandez-vous si ce que l'on vous a dit a fonctionné. Si c'était le cas, vous ne seriez pas en train de lire ce livre.

La dépendance à la pornographie se manifeste de diverses manières et a des effets sociétaux considérables. De nombreuses personnes utilisent la pornographie parce qu'Internet permet un accès instantané à des *stimuli supranormal*. Demandez-vous, est-ce que les questions suivantes s'appliquent à vous?

- Passez-vous beaucoup plus de temps à regarder du porno que vous ne le souhaitiez au départ ?

- Vos efforts pour arrêter ou limiter votre consommation de pornographie, sont-ils en vain ?

- Est-ce que le temps passé à regarder de la pornographie a-t-il interféré ou pris le pas sur des engagements personnels ou professionnels, des passe-temps ou des relations dans votre vie ?

- Faites-vous tout votre possible pour garder secrète votre consommation de pornographie (par exemple, en effaçant l'historique de votre navigateur, en mentant sur votre consommation de pornographie) ?

- La consommation de pornographie a-t-elle causé des problèmes importants dans vos relations intimes ?

- Connaissez-vous un cycle d'excitation et de plaisir avant et pendant la consommation de pornographie, suivi de sentiments de honte, de culpabilité et de remords après ?

- Passez-vous beaucoup de temps à penser à la pornographie, même lorsque vous ne la regardez pas ?

- La consommation de pornographie a-t-elle entraîné d'autres conséquences négatives dans votre vie personnelle ou professionnelle (par exemple, travail manqué, mauvais résultats, relations négligées, problèmes financiers) ?

Si vous êtes un utilisateur de porno qui en dépend pour se masturber ou avoir des rapports sexuels, la seule chose que vous devez faire est de continuer à lire ce livre.  
Si vous êtes ici pour un être cher ou un tiers, tout ce que vous avez à faire est de le persuader de lire ce livre.  
Si vous ne parvenez pas à presuader la personne, lisez-le vous-même. Comprendre la méthode permet de faire passer le message et d'empêcher vos enfants de commencer. Ne vous laissez pas tromper par le fait qu'ils n'y ont pas accès maintenant - tous y ont accès avant de devenir accros.


## Avertissement {-}
Vous avez peut-être une certaine appréhension à l'idée de lire ce livre. Peut-être que, comme beaucoup d'utilisateurs de pornographie, la simple pensée d'arrêter vous fait paniquer et que, bien que vous ayez l'intention d'arrêter un jour, ce n'est pas aujourd'hui.

Si vous vous attendez à ce que ce livre vous "effraie" pour vous inciter à arrêter de fumer en vous présentant les divers problèmes de santé auxquels les utilisateurs s'exposent, tels que les dysfonctionnements sexuels (y compris les dysfonctionnements érectiles induits par le porno), une exctation sexuelle aléatoire, la perte d'intérêt pour des partenaires sexuels réels, l'hypofrontalité cérébrale et la pensée aveuglante selon laquelle il s'agit d'une habitude sale et dégoûtante et que vous êtes une méduse stupide, veule et sans volonté, vous serez cruellement déçu. Ces tactiques ne m'ont jamais aidé à arrêter ma dépendance et si elles devaient vous aider, vous auriez déjà arrêté.

Les méthodes conventionnelles d'arrêt de la dependance préconisent l'utilisation de la volonté ou de méthodes de substitution telles que les régimes pornographiques (une fois tous les X jours) et la réduction de la consommation, qui sont tout aussi inefficaces car elles ne suppriment pas réellement les raisons de consommer du porno. En définitive, ce n'est pas en transformant quelque chose en fruit du pêcher que l'on traite la dépendance.

De nombreux sites décrivent en détail les effets sur le cerveau, étayés par des recherches évaluées par des pairs sur les neurotransmetteurs et la neuroplasticité. Bien que ces sites soient informatifs, beaucoup sont conscients des dangers du porno, mais choisissent de ne rien faire. Les utilisateurs, jeunes et moins jeunes, ont tendance à éviter ce type de contenu, sachant qu'un seul regard sur un site pornographique ne les tuera pas.

Cette méthode, appelée EasyPeasy, fonctionne différemment. Certaines des choses qui vont être dites peuvent être difficiles à croire, mais lorsque vous aurez terminé ce livre, vous ne ferez pas que les croire, vous vous demanderez comment on a pu vous laver le cerveau pour vous faire croire le contraire.

On croit souvent, à tort, que nous choisissons de regarder du porno. Les personnes dépendantes du porno (oui, dépendantes) ne choisissent pas plus de regarder du porno que les alcooliques ne choisissent de devenir alcooliques ou que les héroïnomanes ne choisissent de devenir héroïnomanes. Il est vrai que nous choisissons d'allumer l'ordinateur portable ou le smartphone, de lancer le navigateur et de visiter notre "harem en ligne" préféré. De temps en temps, je choisis d'aller au cinéma, mais je n'ai certainement pas choisi de passer toute ma vie dans une salle de cinéma. Au départ, la curiosité et la nature humaine m'y ont conduit, mais je n'aurais pas commencé si j'avais su que je deviendrais dépendant, provoquant le déclin de ma santé, de mon bonheur et de mes relations. *Si seulement j'avais entendu parler de dysfonctionnement sexuel lors de ma première visite sur ce site pornographique!*

Prenez un moment pour réfléchir, avez-vous déjà pris la décision "positive" que vous devez/avez besoin de porno pour vous masturber ? Ou que vous devriez/devez/avez besoin de fantasmes induits par le porno pour pimenter vos rapports sexuels avec votre partenaire ? Ou que, à certains moments de votre vie, vous ne pouviez pas profiter d'une bonne nuit de sommeil ou peut-être même passer une soirée après une dure journée de travail sans surfer sur du porno ? Ou que vous ne pouviez pas vous concentrer ou gérer votre stress sans cela ? À quel moment avez-vous décidé que vous aviez *besoin* de porno, que vous en aviez *besoin* en permanence dans votre vie, que vous vous sentiez en insécurité, voire en panique, sans porno, sans votre harem en ligne ?

Comme tous les autres utilisateurs de porno, vous avez été attiré dans le piège le plus sinistre et le plus subtil que l'homme et la nature aient jamais conçu ensemble. Aucune personne vivante, qu'elle soit elle-même utilisatrice ou non, n'aime l'idée que ses enfants utilisent du porno pour s'en sortir ou pour le plaisir. Cela signifie que tous les toxicomanes souhaitent n'avoir jamais commencé. Ce n'est pas surprenant : personne n'a besoin de porno pour profiter de la vie ou gérer le stress avant de devenir dépendant.

En même temps, tous les utilisateurs souhaitent continuer à utiliser. Après tout, personne ne nous oblige à lancer le mode incognito de notre navigateur. Qu'ils en comprennent ou non la raison, ce sont les utilisateurs qui décident de frapper aux portes de leurs *harems en ligne*.

S'il existait un bouton magique sur lequel l'utilisateur pourrait appuyer pour se réveiller le lendemain matin comme s'il n'avait jamais accédé à son premier site porno, les seuls accros demain seraient les jeunes qui "expérimentent" encore.

La seule chose qui nous empêche d'arrêter notre dépendance, c'est la **PEUR!** La peur causée par la croyance que nous devrons survivre à une période indéterminée de misère, de privation et d'envie insatisfaite pour nous libérer du porno. Ces croyances découlent de croyances irrationnelles, apprises ou acquises, telles que :

- La masturbation ou le sexe menant à l'orgasme est la *seule* et la *plus importante* chose dans la vie.

- Le porno est plus "sûr" que le sexe dans la vie réelle parce que le porno ne peut pas me rejeter.

- Le porno est éducatif et utile.

- Le droit à une expérience sexuelle "supérieure".

- Plus, c'est toujours mieux.

Ces croyances irrationnelles entraînent des conséquences irrationnelles lorsqu'elles sont mises en pratique, notamment :

- Adorer et être obsédé par la découverte d'un "10/10 parfait".

- Se percevoir comme un perdant si l'on manque de sexe, comme si c'était la chose la plus importante de l'expérience humaine.

- Attendre un 10 parfait.

- Juger et critiquer excessivement les partenaires potentiels.

- Se forcer à avoir des rapports sexuels, que vous en ayez envie ou non.

C'est la peur qu'une nuit pasée en solitude soit misérable, passée à lutter contre des pulsions incontrôlables. La peur que la nuit précédant les examens soit une nuit d'enfer sans porno. La peur de ne jamais pouvoir se concentrer, gérer le stress ou être aussi confiant sans notre petite béquille et de voir notre personnalité et notre caractère changer.

Mais surtout, nous avons peur que "drogué un jour, drogué toujours" : nous ne serons jamais complètement libérés, passant le reste de notre vie à avoir envie d'un orgasme occasionnel induit par le porno à des moments bizarres. Si, comme moi, vous avez déjà essayé toutes les méthodes conventionnelles pour arrêter de fumer et que vous êtes passé par la misère et la torture de la "méthode de la volonté", vous ne serez pas seulement affecté par cette peur, vous serez convaincu que vous ne pourrez jamais arrêter.

Si vous avez de l'appréhension, de la panique ou l'impression que le moment n'est pas venu pour arrêter votre dépendance, laissez-moi vous assurer que votre appréhension et votre panique ne sont pas soulagées par le porno - elles en sont la cause. Vous n'avez pas décidé de tomber dans le piège de la pornographie, mais comme tous les pièges, il est conçu pour que vous restiez piégé. Demandez-vous, lorsque vous avez regardé ces premières photos et vidéos pornographiques, si vous avez décidé de revenir les regarder aussi longtemps que vous vivrez. Alors, quand arrêteras-tu ? Demain ? L'année prochaine ? Arrête de te faire des illusions ! Le piège est conçu pour te retenir à vie. Sinon, pourquoi pensez-tu que tous les autres toxicomanes n'arrêtent pas avant que cela ne "tue" leur vie ?

J'ai parlé d'un bouton magique ; EasyPeasy fonctionne exactement comme ce bouton magique. Je tiens à préciser qu'EasyPeasy n'est pas magique, mais pour moi et pour d'autres qui ont trouvé qu'il était si facile et agréable d'arrêter la dépendance au porno, c'est ce qu'il semble être !

L'avertissement est le suivant :  
Il s'agit de la situation de la poule et de l'œuf : tous les toxicomanes veulent arrêter et tous les toxicomanes peuvent trouver facile et agréable d'arrêter. C'est seulement la **peur** qui empêche les utilisateurs d'essayer d'arrêter. Le gain le plus important est de se débarrasser de cette peur, mais vous ne serez pas libéré de cette peur tant que vous n'aurez pas terminé le livre. Au contraire, votre peur peut augmenter au fur et à mesure de votre lecture, ce qui peut vous empêcher de le terminer. 
Prenez ce commentaire d'une femme.

***"Je viens de terminer la lecture de EasyPeasy. Je sais que cela ne fait que quatre jours, mais je me sens tellement bien que je sais que je n'aurai plus jamais besoin de consommer du porno. J'ai commencé à lire votre livre il y a cinq mois, j'en étais à la moitié et j'ai paniqué. Je savais que si je continuais à lire, je devais m'arrêter. N'ai-je pas été stupide ?" ***

Vous n'avez pas décidé de tomber dans le piège, mais soyez clair dans votre esprit : vous n'y échapperez pas à moins de prendre la décision affirmative de le faire. Vous êtes peut-être déjà en train de tirer sur la laisse pour arrêter, ou vous appréhendez peut-être cette idée, mais dans tous les cas, gardez à l'esprit que **vous n'avez rien à perdre ! **VOUS N'AVEZ RIEN À PERDRE!**

Si, à la fin du livre, vous décidez que vous souhaitez continuer à utiliser le porno pour la masturbation ou le sexe, rien ne vous en empêche. Vous n'êtes même pas obligé de réduire ou d'arrêter votre consommation de porno pendant que vous lisez le livre, et n'oubliez pas qu'il n'y a pas de traitement de choc. Au contraire, je n'ai que de bonnes nouvelles pour vous. Pouvez-vous imaginer ce qu'a ressenti Andy Dufresne lorsqu'il s'est enfin échappé de la prison de Shawshank Redemption? C'est ce que j'ai ressenti lorsque je me suis échappé du piège de la pornographie, et c'est ce que ressentent les ex-utilisateurs qui ont utilisé EasyPeasy. À la fin du livre, c'est ce que vous ressentirez ! Allez-y !

## Enfin... {-}

Tout le monde peut trouver facile et agréable d'arrêter le porno, y compris vous ! Tout ce que vous avez à faire est de lire le reste de ce livre avec un esprit ouvert ; plus vous comprendrez, plus ce sera facile. Même si vous ne comprenez pas un mot, à condition de suivre les instructions, vous trouverez cela facile. Plus important encore, vous ne passerez pas votre vie à vous morfondre sur le porno ou à vous sentir privé, et à la fin du livre, le seul mystère sera de savoir pourquoi vous l'avez fait pendant si longtemps.

Avec EasyPeasy, il n'y a que deux raisons d'échouer.

**L'incapacité à suivre les instructions.**
Certains trouveront agaçant que le livre soit si dogmatique sur certaines recommandations, comme celle de ne pas essayer de réduire sa consommation ou d'utiliser des substituts. Je ne nie pas qu'il y a beaucoup de gens qui ont réussi à arrêter d'utiliser de telles ruses, mais ils ont réussi en dépit de celles-ci et non grâce à elles. Certaines personnes peuvent faire l'amour debout sur un hamac, mais ce n'est pas le moyen le plus facile. Les chiffres pour ouvrir la serrure de ce piège se trouvent dans ce livre, mais il faut les utiliser dans le bon ordre : aller d'un chapitre à l'autre et ne pas sauter de chapitres.

**Manque de compréhension.**
Ne prenez rien pour acquis, remettez en question non seulement ce que l'on vous dit, mais aussi vos propres opinions et ce que la société vous a dit sur le sexe, la pornographie sur Internet et la dépendance. Par exemple, ceux qui croient que ce n'est qu'une habitude, demandez-vous pourquoi d'autres habitudes - dont certaines sont agréables - sont faciles à abandonner, alors qu'une habitude qui procure une sensation horrible, coûte de l'énergie, du temps et de la virilité est si difficile à abandonner. Ceux qui croient que vous aimez le porno, demandez-vous pourquoi d'autres choses infiniment plus agréables sont à prendre ou à laisser. Pourquoi devez-vous *vous* avoir du porno, la panique s'installant si vous n'en avez pas ?

EasyPeasy est sur le point de vous donner la connaissance de la façon dont il est facile et agréable d'arrêter le porno. Comme beaucoup d'autres, l'un de mes plus grands triomphes dans la vie a été d'échapper au piège du porno. Il n'y a pas lieu de se sentir déprimé, au contraire, vous êtes sur le point d'accomplir quelque chose que tous les utilisateurs de la planète aimeraient réaliser : **LA LIBERTÉ!**

**ON RÉPÉTE, N'OUBLIEZ PAS, NE SAUTEZ PAS DE CHAPITRES.**

Quelques termes avant de commencer, **je vous en prie de vous en souvenir car ils seront utilisés très souvent par la suite** :  
***PMO*** : Le cycle du porno, de la masturbation et de l'orgasme. Ce terme est originaire de l'anglais, **Pornography, Masturbation and Orgamse**.
***Harem en ligne*** : Sites web hébergeant du porno sur Internet à haut débit.
