# La Méthode Facile

L'objectif de ce livre est de vous orienter vers un nouvel état d'esprit. Contrairement à la méthode habituelle d'arrêt - où vous commencez par avoir l'impression d'escalader le Mont Everest et passez les semaines suivantes à avoir des envies et à vous sentir privé - vous commencez tout de suite avec un sentiment d'allégresse, comme si vous étiez guéri d'une terrible maladie. À partir de ce moment-là, plus vous avancerez dans la vie, plus vous regarderez cette période et vous vous demanderez comment vous avez pu consommer du porno au départ. Vous regarderez les autres utilisateurs de porno avec pitié, plutôt qu'avec envie.

À condition que vous ne soyez pas quelqu'un qui n'est jamais devenu dépendant (en lisant pour votre conjoint) ou qui a arrêté (ou qui est dans les jours de jeûne d'un "régime porno"), il est essentiel de continuer à consommer jusqu'à ce que vous ayez complètement terminé le livre. Cela peut sembler une contradiction, et cette instruction de continuer à se masturber au porno suscite plus d'objections que toute autre, mais au fur et à mesure que vous lirez la suite, votre désir d'utiliser du porno diminuera progressivement. **Prenez cette instruction au sérieux : Tenter d'arrêter prématurément ne vous sera d'aucune utilité.**

Beaucoup ne terminent pas le livre parce qu'ils sentent qu'ils doivent renoncer à quelque chose, certains vont même jusqu'à ne lire délibérément qu'une ligne par jour afin de repousser l'événement maléfique. Voyez les choses ainsi : qu'avez-vous à perdre ? Si vous ne vous arrêtez pas à la fin du livre, vous ne serez pas plus mal que maintenant. Il s'agit par définition d'un pari de Pascal, c'est-à-dire un pari pris lorsque vous n'avez rien à perdre et de grandes chances de gains importants.

Par ailleurs, si vous n'avez pas regardé de porno depuis quelques jours ou quelques semaines, mais que vous n'êtes pas sûr d'être un utilisateur, un ex-utilisateur ou un non-utilisateur de porno, n'utilisez pas le porno pour vous masturber en lisant. En fait, vous êtes déjà un non-utilisateur, mais il faut laisser votre cerveau rattraper votre corps. À la fin du livre, vous serez un heureux non-utilisateur. EasyPeasy est tout le contraire de la méthode normale, qui consiste à énumérer les inconvénients considérables du porno et à dire :  
*"Si seulement je peux rester assez longtemps sans porno, le désir finira par disparaître et je pourrai à nouveau profiter de la vie, libéré de l'esclavage "*.  
C'est la façon logique de procéder, et des milliers de personnes arrêtent chaque jour en utilisant cette méthode. Cependant, il est très difficile de réussir pour les raisons suivantes :

**Arrêter le PMO n'est pas le vrai problème.**
Chaque fois que vous terminez votre session, vous avez cessé de l'utiliser. Vous avez peut-être de bonnes raisons, le premier jour de votre régime porno "une fois sur quatre", de dire "Je ne veux plus utiliser de porno, ni même me masturber "*. Tous les utilisateurs le font, et leurs raisons sont plus puissantes que vous ne pouvez l'imaginer. Le vrai problème, c'est le deuxième, le dixième ou le dix-millième jour où, dans un moment de faiblesse, vous aurez "juste un coup d'œil", vous en voudrez un autre et, soudain, vous serez à nouveau dépendant.

**La prise de conscience des risques pour la santé génère davantage de peur, ce qui rend l'arrêt plus difficile.**
Dites à un utilisateur que cela détruit sa virilité et la première chose qu'il fera sera de chercher quelque chose pour augmenter sa dopamine : une cigarette, de l'alcool ou même un navigateur pour chercher du porno.

**Toutes les raisons d'arrêter rendent en fait la chose plus difficile.**
Cela est dû à deux raisons. Premièrement, nous sommes continuellement obligés de renoncer à notre "petit ami" ou à un accessoire, un vice ou un plaisir (quelle que soit la façon dont l'utilisateur le perçoit). Deuxièmement, ils créent un "aveuglement". Nous ne nous masturbons pas pour les raisons que nous devrions arrêter. La vraie question est de savoir pourquoi nous voulons ou devons le faire.

Avec EasyPeasy, nous oublions (initialement) les raisons pour lesquelles nous aimerions arrêter, nous faisons face au problème du porno et nous nous posons les questions suivantes :

1.  Que fait le porno pour moi ?

2.  Est-ce que je l'apprécie vraiment ?

3.  Ai-je vraiment besoin de passer ma vie à saboter mon esprit et mon corps ?

La belle vérité est que *tout le porno* ne vous apporte absolument rien. Soyons clairs, ce n'est pas que les inconvénients d'être un consommateur l'emportent sur les avantages, c'est qu'il n'y a ***zéro*** avantages à regarder de la pornographie.

La plupart des utilisateurs trouvent nécessaire de rationaliser les raisons pour lesquelles ils utilisent du porno, mais les raisons qu'ils trouvent sont toutes des sophismes et des illusions.

Tout d'abord, nous allons supprimer ces sophismes et ces illusions. En fait, vous vous rendrez vite compte qu'il n'y a rien à abandonner. Non seulement cela, mais il y a des gains merveilleux et positifs à être un non-PMO (non utilisateur de la PMO), le bien-être et le bonheur n'étant que deux de ces gains. Une fois que les illusions selon lesquelles la vie ne sera jamais aussi agréable sans le porno auront disparu - en réalisant que non seulement la vie est tout aussi agréable sans lui, mais qu'elle l'est infiniment plus - et une fois que le sentiment d'être privé ou de manquer quelque chose aura été éradiqué, nous reviendrons sur l'augmentation du bien-être et du bonheur - et sur les dizaines d'autres raisons d'arrêter le porno. Ces prises de conscience deviendront des aides supplémentaires positives pour vous aider à réaliser ce que vous désirez vraiment : profiter de votre vie sans l'esclavage de la dépendance au porno !
