# Pourquoi Est-Il Difficile d'Arrêter ?

Tous les utilisateurs ont l'impression que quelque chose de maléfique les a possédés. Au début, il s'agit simplement de se dire "Je vais arrêter, mais pas aujourd'hui", mais on finit par croire qu'on n'a pas assez de volonté pour arrêter ou qu'il y a quelque chose d'inhérent au porno qu'il faut avoir pour profiter de la vie. La dépendance au porno peut être comparée au fait de se frayer un chemin hors d'une fosse glissante : lorsque vous vous approchez du sommet, vous voyez le soleil - mais vous vous retrouvez à redescendre lorsque votre humeur baisse. Finalement, vous ouvrez votre navigateur et, en vous masturbant, vous vous sentez mal et vous essayez de comprendre pourquoi vous devez le faire.

Demandez à un utilisateur : *"Si vous pouviez revenir au moment où vous êtes devenu accro, avec les connaissances que vous avez maintenant, auriez-vous commencé à utiliser du porno ?"*.

*"PAS QUESTION !"* serait la réponse.

Demandez à l'utilisateur confirmé, quelqu'un qui défend le porno sur Internet et ne croit pas qu'il cause des lésions au cerveau ou une régulation négative des récepteurs de dopamine : *"Encouragez-vous vos enfants à utiliser du porno ? "*

*"PAS QUESTION !"* est encore la réponse.

Le porno est une énigme extraordinaire. Comme dit précédemment, le problème n'est pas d'expliquer pourquoi il est facile d'arrêter, mais pourquoi c'est difficile. Le vrai problème est d'expliquer pourquoi quelqu'un s'y adonne *après* avoir compris les dommages neurologiques. Si nous nous y mettons, c'est en partie parce que des dizaines de millions de personnes s'y sont déjà mises, mais toutes ces personnes regrettent de ne pas avoir commencé et nous disent que c'est comme vivre en seconde vitesse. Nous n'arrivons pas à croire qu'ils n'en profitent pas. Nous l'associons à la liberté ou à une "éducation sexuelle" et nous travaillons dur pour devenir nous-mêmes accros. Nous passons ensuite le reste de notre vie à dire aux autres de ne pas le faire et à essayer de nous défaire de cette habitude.

Nous passons également une grande partie de notre temps à nous sentir désespérés et misérables. L'éducation auvec du surnaturel nous fait préférer et désirer ces images froides, même lorsque des versions chaudes et réelles sont disponibles ! En raison de la montée et de la descente constantes de dopamine induites par le PMO, nous nous condamnons à une vie d'irritabilité, de colère, de stress, de fatigue et de dysfonctionnement sexuel. En utilisant le porno, qui n'offre pas les meilleurs aspects du sexe et de la connexion, nous finissons par nous sentir malheureux et coupables.

En fait, la lecture des capacités addictives et destructrices de la pornographie sur Internet, ici et sur d'autres sites, nous rend encore plus nerveux et désespérés ! Quel est ce genre de passe-temps pour lequel, lorsque vous le pratiquez, vous souhaitez ne pas le faire, et lorsque vous ne le faites pas, vous en avez envie ? Les utilisateurs se méprisent chaque fois qu'ils lisent des articles sur l'hypofrontalité et la désensibilisation, chaque fois qu'ils consomment dans le dos de leur partenaire, brisant leur confiance, chaque fois qu'ils ne peuvent pas se résoudre à faire de l'exercice après une séance de jour. Un être humain, normalement intelligent et rationnel, passant ses journées dans le mépris. Mais le pire de tout, c'est ce que les utilisateurs gagnent à devoir supporter la vie avec ces horribles ombres noires au fond de leur esprit ? **Absolument rien!**

Vous vous dites peut-être : **"C'est très bien, je le sais, mais une fois qu'on est accro à ces choses, il est très difficile d'arrêter "** Mais pourquoi est-ce si difficile ? Certains disent que c'est à cause des puissants symptômes de sevrage, mais comme vous l'apprendrez bientôt, les symptômes de sevrage réels sont si légers que vous devriez connaître les PMOiens qui ont vécu et sont morts sans se rendre compte qu'ils étaient des toxicomanes.

Certains disent que le porno sur Internet est gratuit et que l'humanité devrait donc s'approprier cette cadeau biologique, mais c'est faux : il crée une dépendance et agit comme n'importe quelle drogue. Demandez à un utilisateur qui jure qu'il n'apprécie que les "érotiques" comme les magazines Playboy s'il a déjà franchi la limite du "porno dangereux" et, s'il est tout à fait honnête, il vous avouera les fois où il a inconsciemment rationalisé son acte, plutôt que de ne rien consommer du tout.

Le plaisir n'a rien à voir non plus : J'aime les écrevisses, mais je ne suis jamais arrivé au point où je devais en manger tous les jours. Pour les autres choses de la vie, nous en profitons pendant que nous les faisons, mais nous ne restons pas assis à nous sentir privés quand nous ne les faisons pas.

Certains disent :  
*"C'est éducatif !"* Alors, c'est quand que tu reçois ton diplôme ?  
*"C'est une satisfaction sexuelle !"* Alors pourquoi le faire seul au lieu de trouver un partenaire et de le garder pour ce partenaire?  
*"C'est un sentiment de libération !" Une libération du stress de la vie réelle ? Le porno ne supprime pas la source du stress, mais il l'augmente.

Beaucoup croient que le porno soulage l'ennui, ce qui est également une erreur. L'ennui est un état d'esprit. Le porno vous habitue à rechercher la nouveauté en un rien de temps, ce qui fait que vous vous ennuyez de plus en plus jusqu'à ce que vous vous lanciez dans une chasse effrénée pour trouver le bon clip, ce qui vous pousse à rechercher tout ce qui évoque la nouveauté, une émotion forte et, finalement, une valeur de choc scandaleuse.

Certains disent qu'ils ne le font que parce que leurs amis et tous ceux qu'ils connaissent le font. Si c'est le cas, priez pour que vos amis ne commencent pas à se couper la tête pour soigner un mal de tête ! La plupart des utilisateurs qui réfléchissent à la question en viennent à conclure qu'il s'agit simplement d'une habitude. Ce n'est pas vraiment une explication, mais après avoir écarté toutes les explications habituelles et rationnelles, cela semble être la seule excuse restante. Malheureusement, elle est tout aussi illogique. Chaque jour de notre vie, nous changeons nos habitudes, dont certaines sont très agréables. On nous a fait un lavage de cerveau pour nous faire croire que le PMO est une habitude et que les habitudes sont difficiles à briser.

Les habitudes sont-elles difficiles à briser ? En France, les conducteurs ont l'habitude de rouler à droite, mais lorsqu'ils voyagent à l'étranger, ils perdent cette habitude sans que cela ne leur pose le moindre problème. Il est clairement faux de dire que les habitudes sont difficiles à briser. Nous créons et détruisons des habitudes chaque jour de notre vie. Alors pourquoi avons-nous du mal à nous défaire d'une habitude qui nous prive quand nous ne l'avons pas, nous fait culpabiliser quand nous l'avons, une habitude dont nous aimerions nous défaire de toute façon, alors qu'il suffit de *cesser de la faire* ?

La réponse est que le porno n'est pas une habitude, **c'est une dépendance**. C'est pourquoi il semble si difficile d'y renoncer. La plupart des utilisateurs ne comprennent pas ce qu'est la dépendance et croient que le porno leur procure un plaisir authentique ou une béquille. Ils pensent qu'ils font un véritable sacrifice s'ils arrêtent.

La belle vérité, c'est qu'une fois que vous aurez compris la vraie nature de la dépendance au porno et les raisons pour lesquelles vous en consommez, vous cesserez de le faire, juste comme ça. En l'espace de trois semaines, le seul mystère sera de savoir pourquoi vous avez trouvé nécessaire d'utiliser du porno aussi longtemps et pourquoi vous n'arrivez pas à persuader les autres utilisateurs *de l'intérêt de ne pas être un PMOien!*.

## Le Piège Sinistre

Le porno sur Internet est le piège le plus subtil et le plus sinistre que l'homme et la nature aient pu concevoir ensemble ; c'est le seul piège dans la nature dont la mise en place ne nécessite pas un travail difficile. Certains d'entre nous sont même avertis des dangers, mais nous n'arrivons pas à croire qu'ils n'en profitent pas. Mais qu'est-ce qui nous y pousse en premier lieu ? Généralement, des échantillons gratuits offerts par des amateurs et des professionnels qui partagent. C'est ainsi que le piège se referme, votre premier "coup d'œil" est taché et troué, la plupart des vignettes sur une page porno étant des clips amateurs et artisanaux de modèles inconnus. Si le regard du premier spectateur n'était rempli que de beautés angéliques et de modèles professionnels, la sonnette d'alarme serait tirée.

En raison de ce décalage entre les clips, nos jeunes esprits sont rassurés et pensent que nous ne deviendrons jamais accros, que parce que nous ne les apprécions pas, nous pouvons arrêter quand nous le voulons. En tant qu'êtres humains intelligents, nous comprendrions alors pourquoi la moitié de la population adulte est systématiquement dépendante de quelque chose qui réduit son potentiel même à réaliser ce qu'elle regarde. La curiosité nous rapproche de leurs portes, mais sans oser cliquer sur certaines vignettes, de peur qu'elles ne vous rendent malade. Si vous avez accidentellement cliqué sur l'une d'elles, votre seul désir étant de vous éloigner de la page au plus vite.

Nous passons alors le reste de notre vie à essayer de comprendre pourquoi nous le faisons, à dire aux enfants de ne pas commencer, et à des moments bizarres à essayer de nous échapper nous-mêmes. Le piège est conçu de telle sorte que nous n'essayons d'arrêter qu'en raison d'un "incident", qu'il s'agisse d'une performance sexuelle, de la perte d'une carrière ou d'une relation, d'un manque de libido ou tout simplement du sentiment d'être un lépreux. Dès que nous arrêtons, le stress augmente en raison de la sensation de manque, alors que la méthode sur laquelle nous comptions pour éliminer ce stress n'est plus disponible.

Après quelques jours de torture, nous décidons que nous n'avons pas choisi le bon moment pour arrêter, et que nous attendrons des périodes sans stress, ce qui, en arrivant, éliminera la raison pour laquelle nous avons arrêté. Bien sûr, cette période n'arrivera jamais car nous pensons intérieurement que nos vies ont tendance à devenir de plus en plus stressantes. En quittant la protection de nos parents, les stress tels que le travail, le ménage, les hypothèques, les bébés, les maisons plus grandes et encore plus de bébés envahissent nos vies. C'est une illusion, la vérité étant que les périodes les plus stressantes de la vie de toute créature sont la petite enfance et l'adolescence.

Nous avons tendance à confondre responsabilité et stress. La vie d'un consommateur - comme celle d'un toxicomane - devient automatiquement plus stressante parce que le porno ne vous détend pas et ne soulage pas le stress, comme certains essaient de vous le faire croire. C'est plutôt l'inverse : vous devenez de plus en plus stressé à mesure que vous continuez à consommer, ce qui ne fait qu'ajouter de la paille sur le dos du chameau. Même les consommateurs qui se débarrassent de l'habitude (la plupart le font une ou plusieurs fois au cours de leur vie) peuvent mener une vie parfaitement heureuse et redevenir soudainement accros. En s'égarant dans le labyrinthe pornographique, notre esprit s'embrouille et nous passons le reste de notre vie à essayer de nous échapper. Beaucoup y parviennent, mais retombent dans le sinistre piège plus tard.

La dépendance au porno est une énigme complexe et fascinante, et un peu comme un Rubik's Cube, pratiquement impossible à résoudre. Mais si vous avez la solution, c'est simple et amusant ! EasyPeasy contient la solution à cette énigme, vous permettant de sortir du labyrinthe pour ne plus jamais y entrer. Tout ce que vous avez à faire est de suivre les instructions. Cependant, si vous prenez un mauvais virage, le reste des instructions est inutile.

Tout le monde peut s'arrêter facilement, mais nous devons d'abord établir les faits. Non, pas des faits destinés à vous effrayer, il y a déjà plus qu'assez d'informations disponibles. Si cela devait vous arrêter, vous vous seriez déjà arrêté. Mais pourquoi avons-nous du mal à nous arrêter ? Pour répondre à cette question, nous devons connaître la véritable raison pour laquelle nous continuons à consommer du porno, qui se résume à deux facteurs. Ce sont :

- La nature et le porno sur Internet.

- Le lavage de cerveau.

Les utilisateurs de porno sont des êtres humains intelligents et rationnels. Ils savent qu'ils prennent d'énormes risques pour l'avenir et passent beaucoup de temps à rationaliser leur "habitude". Mais les utilisateurs de porno savent au fond d'eux-mêmes qu'ils sont des idiots, car ils savent qu'ils n'avaient pas besoin de consommer du porno avant de devenir accros. La plupart se souviennent que leur premier "coup d'œil" était un mélange de dégoût et de curiosité nouvelle. Ils se spécialisent ensuite dans la localisation, le filtrage et la mise en signet de sites, travaillant dur pour devenir accros.

Le plus ennuyeux, c'est que les non-accros - la plupart des femmes, des hommes plus âgés et des personnes vivant dans des pays où le porno sur Internet à haut débit n'est pas disponible - ont l'impression de ne rien manquer et trouvent la situation ridicule. En démontant ces facteurs dans les chapitres suivants, vous comprendrez vous aussi le sinistre piège !