# A Quoi Je Renonce ?

**Absolument rien!** Il est difficile d'abandonner le porno à cause de la peur d'être privé de son plaisir ou de son accessoire. La peur que certaines situations agréables ne soient plus jamais tout à fait les mêmes. La peur de se retrouver incapable de faire face à des situations stressantes. En d'autres termes, ce sont les effets du lavage de cerveau qui nous font croire que le sexe -- et par extension l'orgasme -- est une nécessité pour tous les êtres humains. Plus loin encore, c'est la croyance qu'il y a quelque chose d'inhérent au porno sur Internet dont nous avons besoin, et que si nous arrêtons d'en consommer, nous nous en priverons et créerons un vide.

Que ce soit clair dans votre esprit : **Le porno ne comble pas un vide,** ***il en crée un!***

Notre corps est l'objet le plus sophistiqué de la planète. Que vous croyiez au dessein intelligent, à la sélection naturelle ou à une combinaison des deux, nos corps sont des milliers de fois plus efficaces que n'importe quelle création humaine ! Nous sommes incapables de créer la plus petite cellule vivante ou les miracles de la vue, de la reproduction et des divers systèmes interconnectés présents dans nos corps ou nos cerveaux. Si ce créateur ou ce processus nous avait destiné à gérer des stimuli supranormaux, nous aurions été dotés de systèmes de récompense différents. Nos corps sont dotés de dispositifs d'avertissement à sécurité intégrée et nous les ignorons à nos risques et périls.

### Il n'y a rien à abandonner

Une fois que vous aurez éliminé le petit monstre de votre corps et le lavage de cerveau (le grand monstre) de votre esprit, vous n'aurez plus envie de vous masturber souvent ni d'utiliser du porno sur Internet pour le faire. Il y a beaucoup de choses connues et inconnues lorsqu'il s'agit de la dépendance à la pornographie, de nombreux membres de la communauté médicale n'ayant aucun concept pour interroger ou déterminer si quelqu'un est dépendant de la pornographie. Un grand nombre de symptômes signalés sont étiquetés à tort sous d'autres causes. Ce n'est pas que les utilisateurs soient généralement des gens stupides, c'est simplement qu'ils sont malheureux sans porno. Pris entre le marteau et l'enclume, ils s'abstiennent et sont malheureux parce qu'ils ne peuvent pas utiliser de porno ou malheureux parce qu'ils se sentent coupables et commencent à se mépriser à cause de cela. Lorsqu'ils présentent des symptômes tels que des douleurs lombaires ou des dysfonctionnements sexuels, leur esprit est partagé entre l'acceptation de la responsabilité et le fait de détourner le regard.

Une autre analogie avec les fumeurs, nous avons tous vu des fumeurs qui trouvent des excuses pour s'éclipser et prendre une petite bouffée et nous voyons la véritable dépendance en action. Les toxicomanes ne le font pas pour le plaisir, mais parce qu'ils sont malheureux sans cela.

Pour beaucoup, leur première expérience sexuelle s'est soldée par un orgasme, si bien qu'ils ont acquis la conviction qu'ils ne peuvent pas apprécier le sexe sans orgasme. Pour les hommes, le porno est commercialisé comme une aide au sexe, parfois même comme une éducation à la confiance pendant l'acte. C'est n'importe quoi, le conditionnement d'un stimulus supranormal ne réussit qu'à le faire baisser.

Non seulement il n'y a rien à abandonner, mais des gains positifs massifs peuvent être obtenus. Lorsque les utilisateurs envisagent d'arrêter de fumer, ils ont tendance à se concentrer sur la santé et la virilité. Ce sont des raisons valables et importantes, mais je crois personnellement que les plus grands gains sont psychologiques :

- Le retour de votre confiance et de votre courage.

- La libération de l'esclavage.

- Ne plus avoir d'horribles démons au fond de votre esprit et ne plus vous mépriser.

## Le vide, le vide, le beau vide !

Imaginez que vous ayez un bouton de fièvre sur le visage, vous allez chez le pharmacien et il vous donne une pommade gratuite à essayer. Vous mettez la pommade et le bouton disparaît immédiatement. Une semaine plus tard, il réapparaît, alors vous retournez chez le pharmacien et lui demandez s'il a encore de la pommade. Le pharmacien vous dit *"Bien sûr ; gardez le tube, vous en aurez peut-être besoin plus tard "*.

Vous appliquez la pommade et hop, la plaie disparaît à nouveau. Mais chaque fois que la plaie revient, elle devient plus grande et plus douloureuse, avec un intervalle de plus en plus court. Finalement, la plaie recouvre tout votre visage, elle est atrocement douloureuse et revient toutes les demi-heures. Vous savez que la pommade va la faire disparaître temporairement, mais vous êtes très inquiet. La plaie finira-t-elle par s'étendre à tout votre corps ? L'intervalle va-t-il disparaître complètement ? Vous allez chez votre médecin, qui ne peut pas vous soigner, et vous essayez d'autres choses, mais rien ne vous aide, à part la pommade.

Vous êtes maintenant complètement dépendant de la pommade et vous ne sortez jamais sans vous assurer d'avoir un tube avec vous. Si vous allez à l'étranger, vous vous assurez d'emporter plusieurs tubes avec vous. En plus de vos inquiétudes pour votre santé, le pharmacien vous demande cent dollars par tube. Vous n'avez pas d'autre choix que de payer.

Vous tombez par hasard sur un article traitant de ce problème et découvrez que cela ne vous arrive pas qu'à vous, beaucoup de gens souffrent du même problème. En fait, la communauté médicale a découvert que la pommade ne guérit pas vraiment la plaie, mais qu'elle ne fait que la faire disparaître sous la surface de la peau. C'est la pommade qui a provoqué la croissance de la plaie. Pour vous en débarrasser, il vous suffit donc d'arrêter d'utiliser la pommade et la plaie disparaîtra en temps voulu.

Continuerez-vous à utiliser la pommade ? Faudrait-il de la volonté pour ne pas utiliser la pommade ? Si vous ne croyiez pas à l'article, il pourrait y avoir quelques jours d'appréhension, mais dès que vous réaliserez que la plaie commence à s'améliorer, le besoin ou l'envie d'utiliser la pommade disparaîtra. Seriez-vous malheureux ? Bien sûr que non ! Vous aviez un problème terrible que vous pensiez incurable, mais vous avez trouvé la solution. Même s'il fallait un an pour que la plaie disparaisse, vous penseriez chaque jour, à mesure que votre état s'améliorerait, à quel point vous vous sentiriez merveilleusement bien. C'est la magie de l'arrêt du porno.

La douleur n'est pas due aux douleurs corporelles, à l'absence de désir normal, à la baisse de l'excitation, à l'affaiblissement de la pénétration, au temps perdu à regarder des images bidimensionnelles, au sentiment de violation des droits, au mépris des personnes qui vous ont surpris ou, pire encore, au mépris de vous-même. Tout cela s'ajoute à la douleur.

La douleur nous fait fermer les yeux sur toutes ces choses, c'est ce sentiment de panique de vouloir une dose. Les non-consommateurs ne souffrent pas de ce sentiment. La pire chose dont nous souffrons est la peur, le plus grand gain étant de se débarrasser de cette peur. Elle est causée par votre première séance, renforcée et causée par chaque séance suivante.

Certains utilisateurs sont "heureux", aveuglés par leurs petits monstres rusés et vivent donc ce même cauchemar, avançant des arguments bidons pour tenter de justifier leur stupidité.

**C'est si bon d'être libre !**
