# Gagner le Temps Perdu

Habituellement, lorsque les utilisateurs essaient d'arrêter, les principales raisons invoquées sont la santé, la religion et la stigmatisation du partenaire. L'homme a lutté avec acharnement pour abolir l'esclavage dans de nombreuses régions du monde, mais l'utilisateur passe sa vie à souffrir d'un esclavage qu'il s'est lui-même imposé. Ils sont inconscients du fait que lorsqu'ils sont autorisés à utiliser du porno, ils souhaiteraient ne pas en utiliser. Le seul moment où le porno devient précieux est lorsque nous "essayons" de réduire notre consommation ou de nous abstenir, ou lorsque l'abstinence nous est imposée.

On ne répétera jamais assez que le lavage de cerveau rend difficile l'arrêt du porno. Plus on en dissipe avant de commencer, plus il vous sera facile d'atteindre votre objectif. Les utilisateurs confirmés, qui ne croient pas que le porno a un effet négatif sur leur santé (dysfonctionnement érectile induit par le porno, hypofrontalité, etc.) et qui ne se livrent pas à une lutte mentale sont généralement plus jeunes ou célibataires avec un partenaire sexuel occasionnel. Ainsi, la rétroaction interne est perdue en raison de la nature de leur jeunesse ou est trop peu fréquente pour être observée et enregistrée.

Un meilleur argument pour un jeune utilisateur est le temps passé, plutôt que de dire "*J'ai du mal à croire que tu ne t'inquiètes pas du temps que tu passes*". En général, leurs yeux s'illuminent, se sentant désavantagés s'ils sont attaqués pour des raisons de santé ou de stigmatisation sociale, mais pour le temps...  
> "*Oh, je peux me le permettre. C'est seulement x heures par semaine et je pense que ça vaut le coup, c'est mon seul vice de plaisir.*"
>
>"*J'ai toujours du mal à croire que tu ne sois pas inquiet. Supposons une moyenne d'une demi-heure par jour qui inclut le drainage physique des retraits de dopamine, tu passes environ une journée de travail complète tous les quinze jours. Je suis sûr que tu sera d'accord pour dire qu'une demi-heure par jour est une estimation très prudente. As-tu déjà pensé au temps que tu passes dans ta vie ? Que fais-tu pendant ce temps ? Tu développes de vraies relations ? Non, ta star du porno préférée n'a pas de sympathie pour toi, juste parce que tu as passé beaucoup de temps sur ses vidéos - tu gaspilles du temps ! En plus de cela, tu utilises ce temps pour ruiner ta santé physique, détruire tes nerfs et ta confiance en toi pour souffrir toute ta vie d'esclavage, de douleur, de mélancolie et de maussaderie. Cela doit sûrement t'inquiéter, non ?*"

Il est évident à ce stade - surtout avec les jeunes utilisateurs - qu'ils n'ont jamais considéré que c'était une dépendance à vie. De temps en temps, ils calculent le temps qu'ils perdent en une semaine et c'est assez alarmant. Très occasionnellement, et seulement lorsqu'ils pensent à arrêter, ils estiment ce qu'ils dépensent en un an, ce qui est effrayant - mais sur toute une vie, c'est impensable. Cependant, parce que nous sommes en train de nous disputer, l'utilisateur confirmé dira impulsivement : *"Je peux me le permettre, ce n'est que tant par semaine "*, se faisant passer pour un vendeur d'encyclopédies.

Refuseriez-vous une offre d'emploi qui vous paierait votre salaire annuel actuel et vous donnerait également un mois de congé chaque année ? N'importe quel utilisateur signerait en un clin d'œil et s'occuperait de trouver des offres de vacances dans des endroits exotiques. Trouver comment passer un mois complet sans travailler serait le plus gros problème à résoudre. Lors de chaque discussion avec un utilisateur confirmé (et n'oubliez pas qu'il ne s'agit pas de quelqu'un comme vous qui prévoit d'arrêter), personne n'a jamais accepté cette offre. Pourquoi pas ?

Souvent, à ce stade, un utilisateur confirmé dira : "*Écoutez, je ne suis pas vraiment préoccupé par l'aspect financier*". Si vous pensez de la sorte, demandez-vous pourquoi vous n'êtes pas inquiet. Pourquoi, dans d'autres aspects de votre vie, vous vous donnez beaucoup de mal pour économiser quelques dollars ici et là, mais vous en dépensez des milliers, tuant votre bonheur et accrochant la dépense ?

Toutes les autres décisions que vous prendrez dans votre vie seront le résultat d'un processus analytique consistant à peser les avantages et les inconvénients pour arriver à une décision rationnelle. Ce sera peut-être la mauvaise décision, mais ce sera le résultat d'une déduction rationnelle. Chaque fois qu'un utilisateur pèse le pour et le contre de l'utilisation du porno sur Internet, la réponse est une douzaine de fois, **"ARRÊTEZ D'UTILISER !** Par conséquent, tous les utilisateurs ne le font pas parce qu'ils le veulent ou le décident, mais parce qu'ils ne peuvent pas s'arrêter. Ils ***doivent*** utiliser du porno, et se font donc un lavage de cerveau, en gardant la tête dans le sable.

Les utilisateurs confirmés doivent garder à l'esprit que la situation ne fera qu'empirer de manière exponentielle, avec la publication de nouvelles études et l'augmentation du nombre de personnes parlant des effets néfastes du porno sur Internet. Aujourd'hui, ce sont des personnes non médicales qui discutent de ces effets, demain, ils seront sur la liste des tests de diagnostic de votre médecin. L'époque où l'utilisateur pouvait dissimuler ses "temps morts" derrière le stress du travail dans sa vie sexuelle est révolue ; votre partenaire va vous demander pourquoi vous êtes sur votre ordinateur portable tard le soir. Le pauvre utilisateur - qui se sent déjà malheureux - souhaite maintenant que le sol s'ouvre et l'avale.

Ce qui est étrange, c'est que de nombreuses personnes sont prêtes à payer cher des abonnements à des salles de sport et des entraîneurs personnels pour se muscler et avoir l'air sculpté, et que beaucoup, dans leur désespoir imaginaire (et réel), se tournent vers des traitements tels que l'augmentation de la testostérone, dont les effets secondaires sont douteux et dangereux. Pourtant, il y a beaucoup de personnes dans ce groupe qui bénéficieraient de l'arrêt d'une pratique détruisant systématiquement les systèmes de relaxation naturels de leur cerveau.

Ceci parce qu'elles pensent encore avec l'esprit de l'utilisateur qui a subi un lavage de cerveau. Essuyez le sable de vos yeux un instant. Le porno sur Internet est une réaction en chaîne et une chaîne pour la vie, et si vous ne brisez pas cette chaîne, vous resterez un utilisateur pour le reste de votre vie. Estimez combien de temps vous pensez passer sur le porno pour le reste de votre existence, évidemment la quantité variera d'une personne à l'autre, mais supposons que c'est un an et demi d'heures de travail. Imaginez qu'un chèque de la loterie correspondant à un an et demi de votre salaire se trouve demain sur votre tapis ? Vous danseriez de joie, alors commencez à danser ! Vous êtes sur le point de commencer à recevoir ces avantages !

Si vous pensez que c'est une façon délicate de voir les choses, vous vous faites encore des illusions. Calculez le temps que vous auriez gagné si vous n'aviez pas jeté votre premier coup d'œil dès le début.

Bientôt, vous prendrez la décision d'utiliser votre dernière session (pas encore, n'oubliez pas les instructions !), vous resterez un non-utilisateur en ne tombant pas à nouveau dans le piège. Tout ce que tu dois faire pour rester un non-utilisateur est de ne pas utiliser de porno et d'éviter de "jeter un coup d'œil". N'oubliez pas que si vous le faites, cela vous coûtera ce que vous avez estimé être votre gain salarial.

Si vous conseillez quelqu'un pour sa dépendance à la pornographie, dites-lui qu'il connaît quelqu'un qui a refusé une offre d'emploi lui permettant de toucher son salaire annuel actuel tout en bénéficiant d'un mois complet de congés payés. Lorsque vous lui demandez qui est cet idiot, dites-lui : "Vous !" C'est grossier, mais parfois vous devez faire passer le message d'une manière moins polie.