# La Santé

C'est dans ce domaine que le lavage de cerveau est le plus important, avec des utilisateurs - en particulier les jeunes et les célibataires - qui pensent être conscients des risques pour la santé mais ne le sont pas. Beaucoup se font des illusions en disant qu'ils sont prêts à en accepter les conséquences. Si votre routeur Internet était doté d'une fonction qui émettait une alarme avec un avertissement lorsque vous visitez un site pornographique, disant : "*Jusqu'à présent, vous vous en êtes tiré à bon compte, mais si vous restez une minute de plus, votre tête va exploser*". Seriez-vous resté ? Si vous doutez de la réponse, essayez de marcher jusqu'à une falaise, de vous tenir au bord, les yeux fermés, et d'imaginer que vous avez le choix entre arrêter le porno ou remonter les yeux bandés.

Il n'y a aucun doute sur le choix que vous feriez, mais en faisant l'autruche et en espérant que vous vous réveillerez un matin et que vous n'aurez plus envie de regarder du porno, vous ne faites rien. Les utilisateurs ne peuvent pas se permettre de penser aux risques pour la santé, sinon le plaisir illusoire de la dépendance disparaît. Cela explique pourquoi les traitements de choc sont si inefficaces dans les premiers stades de l'arrêt du tabac (ou dans notre cas, la pronographie), seuls les non-consommateurs peuvent se résoudre à lire des articles sur les changements destructeurs du cerveau.

Prenez cette conversation courante avec les utilisateurs, généralement les plus jeunes.

> **Moi:** "Pourquoi voulez-vous arrêter ?"
>
> **Utilisateur:** "*J'ai lu sur le blog d'un dragueur qu'il est bon d'arrêter pendant quatre jours pour s'amplifier.*"
>
> **Me:** "Tu n'es pas inquiet des risques pour la santé ?"
>
> **Utilisateur:** "*Non, je pourrais passer sous un bus demain.*"
>
> **Moi:** "Mais est-ce que vous passeriez délibérément sous un bus ?"
>
> **Utilisateur:** "*Bien sûr que non.*"  
>
> **Moi:** "Vous ne prenez pas la peine de regarder à gauche et à droite quand vous traversez la route ?"
>
> **Utilisateur:** "*Bien sûr que je le fais.*"

Exactement, ils se donnent beaucoup de mal pour ne pas passer sous un bus et il y a des milliers de chances contre une que ça arrive. Pourtant, l'utilisateur risque la quasi-certitude d'être handicapé par sa dépendance et semble complètement inconscient. La puissance du lavage de cerveau est telle que le porno sur Internet est un loup déguisé en mouton. N'est-il pas étrange que si nous avions l'impression qu'il y a le moindre défaut dans un avion, nous ne monterions pas dedans - même si les risques sont d'un parmi un million - alors que nous prenons plus d'une certitude sur quatre avec le porno et que nous n'en sommes apparemment pas conscients ? Qu'est-ce que l'utilisateur en retire ? **Absolument rien!**

Un autre mythe courant est celui de la dépression ou de la gêne. De nombreuses personnes plus jeunes ne s'inquiètent pas de leur santé parce qu'elles ne souffrent pas de dépression ou de mélancolie. La dépression ou le stress n'est pas la maladie, c'est un symptôme. Les personnes plus jeunes ne ressentent généralement pas l'irritabilité ou la dépression créée par la capacité naturelle de leur corps à produire plus de dopamine. Lorsqu'elles vieillissent ou que leur vie connaît de sérieux revers, leurs ressources déjà épuisées sont surmenées et elles présentent des symptômes complets. Lorsque les utilisateurs âgés se sentent stressés, déprimés ou irrités, c'est parce que les mécanismes de sécurité de la nature protègent le système nerveux d'un afflux excessif de dopamine en réduisant les récepteurs. L'utilisateur développe également d'autres changements neurologiques qui le maintiennent dans l'ornière.

Pensez-y de cette façon : si vous aviez une belle voiture et que vous la laissiez rouiller sans rien faire, ce serait plutôt stupide. Elle deviendrait rapidement un tas de rouille inamovible, incapable de vous transporter où que ce soit. Pourtant, ce ne serait pas la fin du monde car ce n'est qu'une question d'argent. Mais votre corps est le véhicule qui vous transporte dans la vie. Nous disons tous que notre santé est notre plus grand atout, demandez à n'importe quel millionnaire malade. La plupart d'entre nous peuvent se souvenir d'une maladie ou d'un accident dans leur vie où ils ont prié pour guérir. En consommant du porno, vous ne laissez pas seulement la rouille s'installer sans rien faire, vous détruisez systématiquement le véhicule qui vous permet de traverser toute votre vie.

Réveille-toi. Tu n'êtes pas obligé de faire ça, rappele-toi, ça ne fait *absolument rien pour toi*. 

Pour un instant, sortez votre tête du sable et demandez-vous si vous saviez avec certitude que votre prochaine séance déclencherait un processus qui vous rendrait totalement insensible à quelqu'un que vous aimez profondément, continueriez-vous à consommer ? En parlant aux personnes à qui cela arrive, elles ne s'attendaient certainement pas à ce que cela leur arrive non plus, et le pire n'est pas la maladie elle-même mais le fait de savoir qu'elles l'ont provoquée elles-mêmes. Essayez d'imaginer ce que ressentent les personnes qui ont "appuyé sur le bouton", car pour elles, le lavage de cerveau est terminé. Ils passent le reste de leur vie à se dire : "*Pourquoi me suis-je fait croire pendant si longtemps que j'avais besoin de me masturber sur du porno en ligne ? Si seulement j'avais la chance de revenir en arrière!*"

Arrêtez de vous faire des illusions, vous avez cette chance. C'est une réaction en chaîne, si vous vous engagez dans la prochaine séance de porno, cela vous mènera à la suivante, puis à la suivante. C'est déjà le cas pour vous. EasyPeasy ne promet aucun traitement de choc, donc si vous avez déjà décidé d'arrêter, ce qui suit ne sera pas choquant pour vous. Si ce n'est pas le cas, sautez le *reste de ce chapitre* et revenez-y une fois que vous aurez lu le reste du livre.

Des volumes et des volumes de recherche ont déjà été écrits sur les dommages que le porno sur Internet cause à notre vie sexuelle et à notre bien-être mental. Le problème est que jusqu'à ce qu'ils décident d'arrêter, ils ne veulent pas savoir. Les forums et les groupes d'entraide sont une perte de temps car le porno met des œillères. S'ils sont lus par inadvertance, la première chose qu'ils font est d'ouvrir leur site porno préféré. Les utilisateurs de porno ont tendance à considérer les risques liés au bonheur, au stress et au sexe comme des aléas, comme si on marchait sur une mine.

Mettez-vous le dans la tête, c'est déjà le cas. ***Chaque fois que vous ouvrez votre site porno, vous déclenchez un afflux de dopamine et les opioïdes se mettent au travail***. Les toboggans neuronaux sont graissés et le manège vous emmène en douceur vers les étapes suivantes, votre cerveau ayant déjà cédé au script. Le système nerveux est maintenant inondé de dopamine et, comme c'est la énième fois, les récepteurs de dopamine se referment et le petit monstre utilise cette légère baisse de plaisir par rapport à la dernière fois pour vous faire franchir la ligne rouge vers un porno ou un comportement plus choquant afin de libérer plus de dopamine. Plus de nouveauté, plus de dopamine et le petit monstre vous dit de continuer. Tant d'images et de vidéos en une seule séance déclenchent un stimulus supranormal, injectant davantage de substances chimiques dans le cerveau et vous poussant à continuer.

Pendant tout ce temps, vos récepteurs reçoivent des informations leur demandant de se fermer en réponse à l'inondation. L'orgasme ne fait qu'accroître cet effet et conduit au sevrage. Vous êtes dans le déni puisque le petit monstre a besoin de sa dose sans douleur ni inconfort réels. La menace d'une dysfonction érectile en terrifie plus d'un, c'est pourquoi ils la bloquent dans leur esprit et l'éclipsent par la peur d'arrêter. Ce n'est pas que la peur soit plus grande, mais arrêter aujourd'hui est immédiat. Pourquoi voir le côté négatif ? Peut-être que ça n'arrivera pas, étant donné que de toute façon, on aura forcément arrêté d'ici là.

Nous avons tendance à considérer le porno comme un bras de fer, d'un côté la peur : "*C'est malsain, dégoûtant et asservissant.*" De l'autre côté, les aspects positifs : "*C'est mon plaisir, mon ami, ma béquille.*" Il ne semble jamais nous venir à l'esprit que ce côté est aussi la peur ; ce n'est pas que nous aimons le porno, c'est que nous avons tendance à être malheureux sans lui. Les héroïnomanes privés d'héroïne connaissent la misère, mais imaginez la joie totale lorsqu'ils sont enfin autorisés à plonger une aiguille dans leur veine et à mettre fin à ce terrible besoin. Essayez d'imaginer comment quelqu'un pourrait croire qu'il éprouve du plaisir à planter une seringue hypodermique dans une veine. Les non-dépendants à l'héroïne ne souffrent pas de ce sentiment de panique et l'héroïne ne soulage pas ce sentiment, elle le provoque.

Les non-utilisateurs ne se sentent pas malheureux s'ils ne sont pas autorisés à utiliser du porno - seuls les utilisateurs souffrent de ce sentiment. La pornographie sur Internet ne soulage pas ce sentiment, elle le provoque. La peur des conséquences négatives n'aide pas les utilisateurs à abandonner, comparant ce sentiment à celui de marcher dans un champ de mines. Si vous vous en sortez, tant mieux, mais si vous n'avez pas de chance, vous avez marché sur une mine et en avez subi les conséquences. Si vous connaissiez les risques et étiez prêt à les prendre, en quoi cela concernait-il les autres ? Les toxicomanes dans cet état développent généralement les tactiques d'évitement suivantes.

***"Vous finirez par vieillir et perdre vos prouesses sexuelles de toute façon..."***  

Bien sûr que oui, mais les prouesses sexuelles ne sont pas le sujet, nous parlons ici d'esclavage. Même si c'est le cas, est-ce une raison logique pour s'abréger délibérément ?"

"La qualité de la vie est plus importante que le simple fait de vivre."  

Précisément ! Suggérez-vous que la qualité de vie d'un toxicomane est supérieure à celle d'une personne qui n'est pas toxicomane ? Croyez-vous vraiment que la qualité de vie d'un usager est meilleure que celle d'un non-usager ? Une vie passée à se cacher la tête dans le sable et à être malheureux ne semble pas être une vie agréable.

"Je suis célibataire et je ne prévois pas de me fixer dans le futur, alors pourquoi pas ?"

Même si c'était vrai, est-ce une raison logique pour jouer avec les mécanismes neurologiques de contrôle des impulsions ? Pouvez-vous concevoir que quelqu'un soit assez stupide pour se déshabiller dès qu'il est seul, même s'il est sûr de n'attendre personne ? **C'est ce que font effectivement les utilisateurs de porno!**

L'engorgement progressif de nos circuits de récompense par une stimulation excessive, qui les rend incapables de gérer le stress normal de la vie, n'aide pas à profiter de la vie avec enthousiasme et vigueur. Le porno et la masturbation ont remplacé l'appétit sexuel naturel, comme une barre de chocolat remplace la vraie nourriture. Il n'est pas surprenant que de nombreux médecins et psychologues établissent désormais un lien entre divers problèmes de santé mentale et des causes physiologiques. La communauté médicale traditionnelle a fait valoir qu'il n'a jamais été scientifiquement prouvé que le porno était la cause directe des problèmes signalés par les personnes qui s'avouent elles-mêmes, mais admettre son incapacité sexuelle en public est un événement qui déclenche tellement la honte que pourquoi quelqu'un le ferait-il s'il n'était pas vraiment inquiet - pour avoir trouvé la cause et l'éliminer de sa propre vie ?

EasyPeasy vous aidera à vous débarrasser du porno et à devenir un ex-usager heureux. Pas de porno, de masturbation assistée par le porno ou d'orgasmes inutiles. La seule aide sera le toucher, l'odeur et le parfum de votre partenaire. Comme le pain complet après un appétit bien développé, vous ne voudrez plus de l'huile de palme qui est le porno sur Internet. Les preuves sont tellement accablantes qu'elles n'ont pas besoin d'être prouvées ; lorsque je frappe mon pouce avec un marteau, cela fait mal, il n'est pas nécessaire de le prouver. Le stress lié à la consommation de pornographie sur Internet a des répercussions sur d'autres aspects de la vie des utilisateurs, les prédisposant à se tourner vers des drogues telles que les cigarettes et l'alcool pour faire face à la situation, voire, dans certains cas, à envisager le suicide.

Les utilisateurs se font également des illusions en pensant que les effets néfastes du porno sont exagérés. C'est l'inverse qui se produit, il ne fait aucun doute que le porno sur Internet est la principale cause de dysfonctionnement sexuel et de nombreux autres problèmes. Combien de divorces ont été causés par le porno ? Il n'existe pas de moyen fiable de le savoir, mais les recherches effectuées dans les communautés en ligne suggèrent que ce nombre augmente de façon exponentielle.

Il y a un épisode de *Friends* où les gars, qui recevaient continuellement du porno gratuit à la télévision, ont commencé à se demander pourquoi la livreuse de pizza ne demandait pas à voir leur "grande chambre". Quand on est dépendant, on projette invariablement des fantasmes pornographiques sur des femmes réelles. Imaginez ce qu'une exposition négligente ou même accidentelle au porno sur les côtés les plus sombres de l'internet pourrait faire à quelqu'un qui se trouve déjà à un point de basculement dans sa vie. Lutter contre ces pensées induites par le porno sera un véritable fardeau pour sa santé mentale.

Voici une autre expérience de pensée : supposons que quelqu'un vienne vous voir et vous dise qu'il ne souhaite pas nécessairement avoir un orgasme, mais qu'il veut absolument faire l'amour, même avec pénétration. Elle veut le faire aussi longtemps et aussi loin qu'il est possible de le faire sans orgasme - mais si cela arrive, c'est parfait. Je vous assure d'une nouvelle expérience sexuelle phénoménale, bien meilleure que toute autre, si vous recevez cette offre. Essayez-la.

Les effets du lavage de cerveau font que nous avons tendance à penser comme l'homme qui, après être tombé d'un immeuble de 100 étages, aurait dit en dépassant le cinquantième étage, "*Pour l'instant, tout va bien!*". Nous pensons que puisque nous nous en sommes tirés jusqu'ici, une séance de porno de plus ne fera pas la différence. Voyez les choses autrement, "l'habitude" est une chaîne continue à vie, chaque séance créant le besoin de la suivante. Lorsque vous commencez l'habitude, vous allumez une mèche. Le problème, c'est que *vous ne savez pas quelle est la longueur de la mèche.* Chaque fois que vous cédez à une séance de porno, vous vous rapprochez un peu plus de l'explosion de la bombe. **COMMENT SAUREZ-VOUS SI C'EST LA PROCHAINE FOIS?**

## Les Ombres Obscures Sinistres

Les utilisateurs ont beaucoup de mal à croire que la pornographie sur Internet est à l'origine de ce sentiment d'insécurité lorsqu'ils sortent tard le soir après une journée de conflit à la maison ou au travail. Les non-utilisateurs ne souffrent pas de ce sentiment, c'est le porno qui le provoque.

Une autre des grandes joies de l'arrêt du porno est la libération des sinistres ombres noires au fond de notre esprit. Tous les utilisateurs savent qu'ils sont idiots de fermer leur esprit aux effets néfastes de la pornographie. Pendant la majeure partie de notre vie, c'est automatique, mais les ombres noires sont toujours tapies dans notre subconscient, juste sous la surface. Plusieurs des merveilleux avantages de l'abandon de la pornographie sont conscients, comme la perte de temps et la stupidité pure et simple de faire l'amour à une image bidimensionnelle.

Les derniers chapitres ont traité des avantages considérables d'être un non-utilisateur, mais dans un souci d'équité, il est nécessaire de donner un compte rendu équilibré. C'est pourquoi la page suivante énumère les avantages d'être un utilisateur.

# Avantages d'être un Utilisateur de Porno
