# La Méthode de Volonté

C'est un fait accepté dans la société qu'il est très difficile d'arrêter le porno. Les livres et les forums qui vous conseillent sur la façon d'arrêter commencent généralement par vous dire à quel point c'est difficile. La vérité est que c'est ridiculement facile. Il est compréhensible de remettre en question cette affirmation, mais réfléchissez-y d'abord. Si votre objectif est de courir un kilomètre en quatre minutes, *c'est difficile* et vous devrez vous entraîner durement pendant des années, tout en étant peut-être physiquement incapable de le faire.

En revanche, tout ce que vous avez à faire pour arrêter le porno est de ne plus le regarder et/ou de ne plus vous masturber. Personne ne vous oblige à vous masturber (à part vous-même) et, contrairement à la nourriture ou à l'eau, vous n'en avez pas besoin pour survivre. Donc si vous voulez arrêter de le faire, pourquoi cela devrait-il être difficile ? En fait, ça ne l'est pas. Ce sont les utilisateurs qui se rendent la tâche difficile en faisant preuve de volonté ou en utilisant toute autre méthode qui leur donne l'impression de faire une sorte de sacrifice. Examinons ces méthodes.

Nous ne décidons pas de devenir des utilisateurs, nous nous contentons d'expérimenter des magazines ou des sites web pornographiques et, parce qu'ils sont affreux (soyons honnêtes), en dehors de notre clip désiré, nous sommes convaincus que nous pouvons arrêter quand nous le voulons. Au début, nous regardons ces premiers clips quand nous en avons envie et lors d'occasions spéciales. Avant de nous en rendre compte, non seulement nous visitons régulièrement ces sites et nous nous masturbons quand nous en avons envie, mais nous nous masturbons tous les jours devant ces sites. Le porno fait désormais partie de notre vie, ce qui nous oblige à disposer d'une connexion Internet partout où nous allons. Nous pensons alors que nous avons droit à l'amour, au sexe, à l'orgasme et aux propriétés antistress du porno. Il ne nous vient pas à l'esprit que les mêmes clips et acteurs ne nous procurent pas le même degré d'excitation et nous commençons à nous battre contre la ligne rouge pour éviter le "mauvais porno". En fait, la masturbation et le porno sur Internet n'améliorent pas notre vie sexuelle et ne réduisent pas le stress, mais les utilisateurs croient qu'ils ne peuvent pas profiter de la vie ou gérer le stress sans orgasme.

Il faut généralement beaucoup de temps pour se rendre compte que l'on est accro, car on souffre de l'illusion que les utilisateurs regardent du porno parce qu'ils y prennent plaisir - et non parce qu'ils en ont ***la nécessité***. Lorsque nous n'apprécions pas le porno, ce qui n'est jamais le cas à moins d'y ajouter de la nouveauté, un choc ou une escalade, nous avons l'illusion de pouvoir arrêter à tout moment. C'est un piège de confiance, "*je n'aime pas le porno, donc je peux arrêter quand je veux*". Seulement, vous ne semblez jamais "vouloir" arrêter.

En général, ce n'est que lorsque nous essayons réellement d'arrêter que nous nous rendons compte qu'il y a un problème. Les premières tentatives sont généralement précoces - déclenchées par la rencontre d'un partenaire et le fait de remarquer qu'il n'est pas "tout à fait suffisant" après les premiers rendez-vous. Une autre raison courante est la constatation des effets sur la santé présents dans la vie quotidienne.

Quelle que soit la raison, l'utilisateur attend toujours une situation stressante, qu'il s'agisse de santé ou de sexe. Dès qu'il s'arrête, le petit monstre commence à avoir faim. L'utilisateur veut alors quelque chose pour pomper sa dopamine, comme des cigarettes, de l'alcool, ou son favori - le porno sur Internet - avec son harem à portée de clic. La cachette à porno n'est plus à la cave, elle est virtuelle et accessible de partout. Si leur partenaire est là ou s'ils sont avec des amis, ils n'ont plus accès à leur harem virtuel, ce qui les plonge dans une détresse encore plus grande.

Si l'utilisateur est tombé sur du matériel scientifique ou des communautés en ligne, il va devoir se battre dans sa tête, résister aux tentations et se sentir privé. Leur moyen habituel d'évacuer le stress est désormais indisponible, subissant un triple coup dur. Après cette période de torture, le résultat probable est le compromis - "*je vais réduire ma consommation*" ou "*j'ai choisi le mauvais moment*" ou encore "*j'attendrai que le stress disparaisse de ma vie*". Cependant, une fois que le stress a disparu, il n'y a plus de raison d'arrêter et l'utilisateur ne décide pas d'arrêter à nouveau avant le prochain moment de stress.

Bien sûr, il n'y a jamais de bon moment car la vie de la plupart des gens devient plus stressante. Nous quittons la protection de nos parents, entrons dans le monde de l'installation d'un foyer, prenons des hypothèques, avons des enfants et avons des emplois plus responsables. Quoi qu'il en soit, la vie de l'usager ne peut pas devenir moins stressante, car le porno provoque en fait du stress. Plus l'utilisateur passe rapidement à l'étape de l'escalade, plus il est en détresse et plus la dépendance à l'illusion s'accroît.

En fait, c'est une illusion que la vie devient plus stressante et le porno - ou une béquille similaire - crée cette illusion. Nous reviendrons plus en détail sur ce sujet plus tard, mais après ces premiers échecs, l'utilisateur compte généralement sur la possibilité qu'un jour il se réveille et n'ait plus envie de se masturber ou de consommer du porno, etc. Cet espoir est généralement alimenté par des histoires entendues de la part d'autres ex-utilisateurs, "*Je n'étais pas sérieux jusqu'à ce que j'aie une pénétration qui s'estompe, puis je n'ai plus voulu utiliser de porno et j'ai arrêté de me masturber*".

Ne vous faites pas d'illusions, sondez ces rumeurs et vous découvrirez que ce n'est jamais aussi simple qu'il n'y paraît. Généralement, l'utilisateur s'était déjà préparé à arrêter et a simplement utilisé l'incident comme tremplin. Le plus souvent, les personnes qui arrêtent "comme ça" ont subi un choc, peut-être une découverte de leur partenaire, un incident d'accès à du porno qui ne correspond pas à leur orientation sexuelle normale ou une peur de dysfonctionnement sexuel. "*C'est juste le genre de personne que je suis.*" Arrêtez de vous faire des illusions. Cela n'arrivera pas si vous ne le faites pas.

Voyons plus en détail pourquoi la méthode de la volonté est si difficile. Pendant la majeure partie de notre vie, nous faisons l'autruche en nous disant : "*J'arrêterai demain*". Il arrive parfois que quelque chose déclenche une tentative d'arrêt. Il peut s'agir de problèmes de santé, de virilité ou d'une auto-analyse qui nous fait réaliser que nous n'aimons pas vraiment ça. Quelle que soit la raison, nous commençons à peser le pour et le contre du porno. Le sexe est divisé en deux catégories : tantrique (toucher, odeur, voix) et propagatif (orgasme) ; c'est l'une des principales clés de l'ouverture d'esprit, sans cette distinction importante, il y aura une confusion qui conduira à l'échec. Lors d'une évaluation rationnelle, nous découvrons ce que nous avons su toute notre vie, la conclusion est mille fois répétée : "***ARRÊTE DE REGARDER DU PORNO***".

Si vous deviez vous asseoir et donner des points aux avantages d'arrêter et les comparer aux avantages du porno, le total des points pour arrêter dépasserait de loin tous les "inconvénients". Si vous faites le pari de Pascal, en arrêtant votre dépendance, vous ne perdez presque rien, avec des chances élevées de gagner et des chances élevées de ne pas perdre. Bien que l'utilisateur sache qu'il sera mieux en tant que non-utilisateur, la conviction qu'il fait un sacrifice le fait réfléchir. Bien que ce soit une illusion, elle est puissante. Ils ne savent pas pourquoi, mais l'utilisateur a la conviction que dans les bons et les mauvais moments de la vie, les séances semblent l'aider. Avant même de commencer leur tentative, le lavage de cerveau sociétal, renforcé par le lavage de cerveau lié à leur propre dépendance, est ensuite combiné à un lavage de cerveau encore plus puissant sur la difficulté "d'abandonner".

On entend les histoires de ceux qui ont arrêté pendant plusieurs mois et qui ont toujours désespérément envie de fumer et les récits de ceux qui ont arrêté et qui passent le reste de leur vie à se lamenter sur le fait qu'ils aimeraient bien avoir une séance. Des récits d'utilisateurs qui ont arrêté pendant de nombreux mois ou années, qui mènent une vie heureuse et qui, après avoir jeté un coup d'œil au porno, sont soudain de nouveau accros. Ils en connaissent probablement plusieurs qui sont à un stade avancé de la maladie, qui se détruisent visiblement et ne profitent pas de la vie - et qui continuent pourtant à consommer. De plus, ils ont probablement vécu eux-mêmes une ou plusieurs de ces expériences.

Donc, au lieu de commencer par le sentiment "*Génial ! Vous avez entendu la nouvelle ? Je n'ai plus besoin de regarder du porno !*", ils commencent plutôt avec des sentiments de malheur et de morosité - comme s'ils essayaient d'escalader l'Everest - et ils déterminent faussement qu'une fois que le petit monstre a mis le grappin sur vous, vous êtes accroché pour la vie. De nombreux utilisateurs commencent leur tentative en s'excusant auprès de leur copine ou de leur épouse : "*Écoutez, j'essaie d'abandonner la pornographie. Je vais probablement être irritable pendant les deux prochaines semaines, essayez de me supporter.*" La plupart des tentatives sont vouées à l'échec avant même de commencer.

Supposons que l'utilisateur survive à quelques jours sans session, qu'il retrouve son excitation et commence à se remettre. Il n'a pas ouvert ses sites pornos préférés et est donc excité par des stimuli normaux qu'il avait auparavant ignorés. Les raisons pour lesquelles ils ont décidé d'arrêter disparaissent rapidement de leurs pensées, comme lorsqu'ils voient un mauvais accident de la route en conduisant. Cela vous ralentit pendant un moment, mais la prochaine fois que vous serez en retard à un rendez-vous, vous devrez appuyer sur l'accélérateur.

De l'autre côté de la guerre se trouve le petit monstre qui n'a toujours pas eu sa dose. Il n'y a pas de douleur physique - si vous aviez la même sensation à cause d'un rhume, vous ne vous arrêteriez pas de travailler ou ne seriez pas déprimé, vous en ririez. Tout ce que l'utilisateur sait, c'est qu'il veut rendre visite à son harem. Le petit monstre le sait et déclenche le grand monstre du lavage de cerveau, amenant la même personne qui, quelques heures ou jours plus tôt, listait toutes les raisons d'arrêter, à chercher désespérément une excuse pour recommencer. Ils commencent à dire des choses comme :

- "*La vie est trop courte, une bombe pourrait exploser, je pourrais passer sous un bus demain. Je l'ai laissé trop tard. Ils vous disent que tout vous rend dépendant de nos jours.*"

- "*J'ai choisi le mauvais moment.*"

- "*J'aurais dû attendre après Noël, après mes vacances/mes examens, après cet événement stressant de ma vie.*"

- "*Je n'arrive pas à me concentrer, je deviens irritable et de mauvaise humeur, je n'arrive même pas à faire mon travail correctement.*"

- "*Ma famille et mes amis ne m'aimeront plus. Soyons réalistes, pour le bien de tous, je dois recommencer à zéro. Je suis un accro du sexe confirmé et il n'y a aucune chance que je sois à nouveau heureux sans orgasme.*"

- "*Personne ne peut survivre sans sexe.*" (Lavage de cerveau par des personnes bien intentionnées qui ne tiennent pas compte de la distinction entre les parties tantriques et propagatives du sexe).

- "*Je savais que cela arriverait, mon cerveau est 'sensibilisé' par DeltaFosB en raison des changements affectés par les poussées de dopamine dues à mon utilisation excessive de porno dans le passé. La sensibilisation ne peut "jamais" être supprimée du cerveau.*"

À ce stade, l'utilisateur cède généralement. Il lance le navigateur et la schizophrénie augmente. D'un côté, il y a l'immense soulagement de mettre fin à l'envie, le petit monstre ayant enfin sa dose ; de l'autre, l'orgasme est terrible et l'utilisateur ne comprend pas pourquoi il le fait. C'est pourquoi l'utilisateur pense qu'il manque de volonté. En fait, ce n'est pas un manque de volonté, tout ce qu'il a fait, c'est changer d'avis et prendre une décision parfaitement rationnelle à la lumière des dernières informations.

"*A quoi bon être en bonne santé ou riche si vous êtes malheureux?*"

Absolument aucun ! Il vaut bien mieux avoir une vie agréable et courte qu'une vie misérable et longue. Heureusement, c'est faux pour le non-utilisateur, car la vie est infiniment plus agréable. La misère dont souffre l'utilisateur n'est pas due aux symptômes de sevrage - bien qu'elle soit initialement déclenchée par ceux-ci - la véritable agonie est le tiraillement de l'esprit causé par le doute et l'incertitude. Comme l'utilisateur a d'abord l'impression de faire un sacrifice, il commence ensuite à se sentir privé, ce qui est une forme de stress.

L'un de ces moments de stress est celui où le cerveau leur dit de "jeter un coup d'œil" ; ils veulent revenir en arrière dès qu'ils s'arrêtent. Mais comme ils se sont arrêtés, ils ne peuvent pas le faire, ce qui les rend encore plus déprimés et déclenche à nouveau l'alarme. Un autre facteur qui rend l'arrêt du tabac si difficile est le fait d'attendre que quelque chose se passe. Si votre objectif est de passer un examen de conduite, dès que vous aurez réussi l'examen, vous saurez si vous avez atteint votre objectif. Avec la méthode de la volonté, le récit interne est le suivant : "*Si je peux rester assez longtemps sans porno sur Internet, l'envie de le regarder finira par disparaître*". Vous pouvez voir cela en pratique dans les forums en ligne où les toxicomanes parlent de leurs séries ou de leurs jours d'abstinence.

Comme dit plus haut, l'agonie que subit l'utilisateur est mentale et causée par l'incertitude. Bien qu'il n'y ait pas de douleur physique, les effets sont néanmoins puissants. Désormais malheureux et peu sûr de lui, l'usager est loin d'oublier, désormais plein de doutes et de craintes.

- "*Combien de temps va durer l'envie de fumer?*"

- "*Est-ce que je serai à nouveau heureux un jour?*"

- "*Est-ce que j'aurai un jour envie de me lever le matin?*"

- Comment vais-je pouvoir gérer le stress à l'avenir ?

L'utilisateur attend que les choses s'améliorent, mais pendant qu'il se morfond, son "harem" devient de plus en plus précieux. En fait, il se passe quelque chose, mais inconsciemment, s'il peut survivre des semaines sans ouvrir son navigateur, l'envie de ce petit monstre disparaît. Cependant, comme nous l'avons déjà dit, les symptômes de sevrage de la dopamine et des opioïdes sont si légers que l'utilisateur n'en est même pas conscient. À ce moment-là, de nombreux usagers ont l'impression d'avoir "décroché" et prennent un verre pour le prouver, ce qui les renvoie au toboggan. Après avoir fourni de la dopamine au corps, une petite voix au fond de leur esprit leur dit "*Tu en veux une autre*". En fait, ils s'en étaient débarrassés, mais se sont de nouveau accrochés.

Enfant, vous regardiez des dessins animés et, selon les neurosciences, vous avez formé des voies neurales (DeltaFosB) pour eux. Pour décourager un enfant de regarder des dessins animés, il faut vérifier si ces voies existent toujours et interroger les adultes sur les raisons pour lesquelles ils n'aiment plus regarder leurs dessins animés préférés. D'une part, il existe de meilleurs divertissements et, d'autre part, les dessins animés ne sont plus aussi magiques. Avec la méthode de la volonté, vous refusez simplement le dessin animé à l'enfant, mais avec EasyPeasy, vous vous assurez également qu'il n'y voit aucun intérêt. Qu'est-ce qui est le mieux ?

En général, l'utilisateur ne se lance pas immédiatement dans une nouvelle session en pensant "*Je ne veux pas redevenir accro!*" et laisse passer une période de sécurité de quelques heures, jours ou même semaines. L'ex-consommateur peut alors se dire : "*Bien, je n'ai pas été accroché, je peux donc faire une autre session en toute sécurité*". Il est retombé dans le même piège que lorsqu'il a commencé et se trouve déjà sur la pente glissante.

Les utilisateurs qui réussissent en utilisant la méthode de la volonté ont tendance à trouver cela long et difficile car le problème principal est le lavage de cerveau. Longtemps après la disparition de la dépendance physique, l'usager continue à se morfondre. Finalement, après avoir survécu à cette longue torture, il commence à comprendre qu'il ne va pas céder, il arrête de se morfondre et accepte que la vie continue et est agréable sans porno. Il y a beaucoup plus d'échecs que de réussites, certains qui réussissent passent leur vie dans un état de vulnérabilité, avec une certaine dose de lavage de cerveau qui leur dit que le porno leur donne en fait un coup de fouet. Cela explique pourquoi de nombreux utilisateurs qui ont arrêté pendant de longues périodes finissent par recommencer plus tard.

De nombreux ex-utilisateurs s'offrent une séance occasionnelle pour se faire plaisir ou pour se convaincre de la force de leur maîtrise de soi. C'est exactement ce qu'ils font, mais dès que la séance se termine, la dopamine commence à disparaître et une petite voix au fond de leur esprit les pousse à en reprendre une autre. S'ils décident d'y participer, tout semble être sous contrôle, sans chocs, sans escalade ni recherche de nouveauté, alors ils disent : "*Merveilleux ! Même si je n'aime pas vraiment ça, je ne vais pas devenir accro. Après Noël / ces vacances / ce traumatisme, j'arrêterai.*" Ils sont loin de se douter que les toboggans aquatiques de leur cerveau ont été encore plus graissés.

Trop tard, ils sont déjà accrochés ! Le piège dont ils ont réussi à s'extirper a de nouveau fait sa victime.

Comme nous l'avons dit précédemment, le plaisir n'entre pas en ligne de compte. Il ne l'a jamais été ! Si nous regardions pour le plaisir, personne ne resterait sur les sites de télévision plus longtemps qu'il ne faut pour terminer l'acte. Quoi qu'il en soit, les souvenirs sont une meilleure façon de s'auto-plaire. Nous supposons que nous aimons le porno sur Internet uniquement parce que nous ne pouvons pas croire que nous serions assez stupides pour devenir dépendants si nous n'aimions pas ça. La plupart des utilisateurs n'ont aucune idée des stimuli supranormaux, de la recherche de la nouveauté ou du choc et, même après avoir lu des articles sur le sujet, ils ne croient pas que leur consommation soit motivée par le câblage du circuit de récompense évolutif. C'est pourquoi une grande partie du porno est subconsciente, si vous étiez conscient des changements neurologiques et si vous deviez justifier que cela vous coûte de l'argent dans le futur, même l'illusion du plaisir disparaîtrait.

Lorsque nous essayons de bloquer notre esprit sur le mauvais côté, nous nous sentons stupides. Si nous devions y faire face, ce serait intolérable ! Si vous observez un utilisateur en action, vous verrez qu'il n'est heureux que lorsqu'il n'est pas conscient de consommer. Une fois conscients, ils ont tendance à être mal à l'aise et à s'excuser. Le porno nourrit le petit monstre. Ainsi, une fois que vous l'aurez éliminé de votre corps en même temps que le lavage de cerveau (le grand monstre), vous n'aurez plus besoin ni envie de regarder !
