# Juste un Coup d'Oeil

"Juste un coup d'oeil" est un mythe que vous devez faire disparaître de votre esprit :

- C'est *juste un coup d'oeil* qui nous fait commencer en premier lieu.

- C'est *un seul coup d'œil* qui nous permet de surmonter une période difficile ou une occasion spéciale qui met en échec la plupart de nos tentatives d'arrêt.

- C'est *juste un coup d'oeil* qui, après avoir réussi à briser la dépendance, nous renvoie dans le piège. Parfois, c'est juste pour confirmer qu'ils n'ont plus besoin de porno et une visite au harem suffit.

Les effets secondaires du porno sont horribles et convainquent l'utilisateur qu'il ne redeviendra jamais accro - mais il l'est déjà. Le consommateur estime que quelque chose qui le rend si malheureux et coupable n'aurait pas dû l'inciter à le faire, mais il l'a fait.

C'est l'idée d'une "session spéciale" qui empêche souvent les utilisateurs d'arrêter, celle qui suit un long voyage en conférence, une dure journée de travail, une dispute avec les enfants ou un incident où votre partenaire vous rejette pour du sexe. Mettez-vous bien dans la tête qu'il n'y a pas de "seul coup d'œil". C'est une réaction en chaîne qui durera le reste de votre vie si vous ne la brisez pas. Le mythe de l'occasion unique et spéciale fait que les utilisateurs se morfondent après avoir arrêté. Prenez l'habitude de ne jamais voir la session "sans importance", c'est un fantasme. Chaque fois que vous pensez au porno, voyez une vie immonde passée derrière un écran pour le privilège de vous détruire mentalement et physiquement, une vie d'esclavage et de désespoir. Ce n'est pas un crime si vos érections ne sont pas fiables, mais c'en est un lorsque vous pourriez être plus heureux à long terme mais que vous choisissez de sacrifier cela pour un "plaisir" à court terme.

Ce n'est pas grave si nous ne pouvons pas toujours trouver "quelque chose à faire" pour combler le vide ; cela n'est pas possible de manière réaliste dans tous les cas et pour toute notre vie. Nous pouvons planifier la plupart d'entre elles, mais parfois, cela se produit tout simplement. Les bons et les mauvais moments arrivent aussi, indépendamment du porno. Mais mettez-vous bien ça dans la tête, le porno n'est pas le problème. Vous n'auriez jamais imaginé prendre du cyanure juste parce que vous aimez le goût des amandes, alors arrêtez de vous punir avec une session occasionnelle "sans gravité". Demandez à un usager qui a des problèmes : "*Si vous aviez la possibilité de revenir à l'époque où vous n'étiez pas accro, seriez-vous devenu un usager?*" La réponse est inévitablement "*C'est une blague!*". Pourtant, chaque utilisateur a ce choix tous les jours de sa vie, pourquoi n'optent-ils pas pour ce choix ? La réponse est la peur. La peur de ne pas pouvoir s'arrêter ou que la vie ne soit plus la même sans elle.

Arrêtez de vous faire des illusions ! Vous pouvez le faire, tout le monde le peut. C'est ridiculement facile, mais pour que ce soit le cas, il faut que certains principes fondamentaux soient clairs dans votre esprit.

1.  Il n'y a rien à abandonner, seulement de merveilleux gains positifs à réaliser.

2.  Ne vous convainquez jamais de l'existence d'une séance bizarre "sans importance" ou "juste un coup d'œil". Cela n'existe pas. Il n'y a qu'une vie de saleté et d'esclavage.

3.  Il n'y a rien de différent chez vous, tout utilisateur peut trouver facile d'arrêter.

De nombreux utilisateurs croient qu'ils sont des accros confirmés ou qu'ils ont une personnalité addictive. Cela se produit généralement à la suite de la lecture de quantités excessives de neurosciences choquantes. Cela n'existe pas, personne n'est né avec le besoin de se masturber devant des clips vidéo avant de devenir accro. C'est la drogue qui vous rend accro, pas la nature de votre caractère ou de votre personnalité. La nature du stimulus supernormal addictif vous fait croire que c'est le cas. Cependant, il est essentiel de supprimer cette croyance, car si vous croyez que vous êtes dépendant, vous le resterez, même lorsque le petit monstre dans votre corps sera mort depuis longtemps. Il est essentiel d'éliminer tout ce lavage de cerveau.