# Utilisateurs Occasionnels

Les gros utilisateurs ont tendance à envier l'utilisateur de porno occasionnel, nous avons tous rencontré ces personnages : "*Oh, je peux passer toute la semaine sans une session, ça ne me dérange pas vraiment.*" Nous aimerions être comme ça. C'est peut-être difficile à croire, mais aucun utilisateur n'aime être un utilisateur. N'oubliez jamais :  


| *Aucun utilisateur n'a jamais décidé d'en devenir un, qu'il soit occasionnel ou non, **par conséquent,***
| Tous les utilisateurs se sentent stupides, **par conséquent**.
| Tous les utilisateurs doivent se mentir à eux-mêmes et aux autres dans une vaine tentative de justifier leur stupidité.


Les fanatiques de golf se vantent de la fréquence à laquelle ils jouent et veulent jouer, alors pourquoi les utilisateurs se vantent-ils de la fréquence à laquelle ils se masturbent ? Si c'est là le véritable critère, alors l'accolade consiste sûrement à ne pas se masturber du tout, n'est-ce pas ?

Si quelqu'un vous disait : "*Je peux passer toute la semaine sans carottes et cela ne me dérange pas le moins du monde*", vous penseriez que vous parlez à un cinglé. Si j'aimais les carottes, pourquoi voudrais-je m'en passer toute la semaine ? Si je ne les appréciais pas, pourquoi aurais-je fait une telle déclaration ? Ainsi, lorsqu'un utilisateur fait un commentaire sur le fait de survivre une semaine sans session, il essaie de se convaincre -- et de vous convaincre -- qu'il n'a pas de problème. Mais il n'y aurait pas besoin de faire une déclaration s'il n'y avait pas de problème. Traduit, ce commentaire est "*J'ai réussi à survivre une semaine entière sans porno.*" Comme tous les utilisateurs, ils espèrent qu'après ça, ils pourront survivre le reste de leur vie. Ne pouvant survivre qu'une semaine, pouvez-vous imaginer à quel point la séance a dû être précieuse par la suite, après s'être senti privé pendant une semaine entière ?

C'est pourquoi les consommateurs occasionnels sont effectivement plus accrochés que les gros consommateurs, non seulement l'illusion du plaisir est plus grande, mais ils sont moins incités à arrêter parce qu'ils passent moins de temps et sont donc moins vulnérables aux risques pour la santé. De temps en temps, ils peuvent souffrir de dysfonctionnement sexuel, mais ils ne sont pas sûrs de ce qui l'a provoqué et le mettent donc sur le compte d'autres facteurs. N'oubliez pas que le seul plaisir que les consommateurs obtiennent est celui du cycle de recherche de dopamine et du soulagement de la sensation de manque, comme cela a déjà été expliqué. Le plaisir est une illusion, imaginez le petit monstre du porno comme une démangeaison presque imperceptible dont nous ne sommes pas conscients la plupart du temps.

Si vous avez une démangeaison permanente, la tendance naturelle est de la gratter. À mesure que les circuits de récompense deviennent de plus en plus insensibles à la dopamine et aux opioïdes, la tendance naturelle est à la surenchère, à l'escalade, à la frénésie, à la recherche de nouveauté, à la recherche de chocs, etc. Il existe quatre facteurs principaux qui empêchent les utilisateurs de regarder en chaîne.

**Temps.**
La plupart ne peuvent pas se permettre.

**Santé.**
Pour soulager la démangeaison, nous devons consommer tout le matériel gratuit qui est disponible et même plus. La capacité à faire face à ce type de consommation varie selon les individus, les moments et les situations de leur vie. Ceci agit comme une contrainte automatique.

**Discipline.**
Imposée par la société ou par le travail, les amis et les parents de l'utilisateur ; peut-être même par l'utilisateur lui-même en raison de la lutte naturelle qui se déroule dans l'esprit de chaque utilisateur.

**Imagination.**
Le manque d'imagination diminue le choc, la nouveauté et les autres valeurs du clip sur une base subjective.

Il est facile de considérer les utilisateurs occasionnels comme faibles, incapables de comprendre pourquoi d'autres sont capables de limiter leur consommation. Cependant, les gros utilisateurs doivent garder à l'esprit que la plupart des utilisateurs occasionnels sont tout simplement incapables de visionner des chaînes, ce qui nécessite une imagination et une endurance très fortes. Certains de ces utilisateurs occasionnels que les gros utilisateurs ont tendance à envier sont physiquement incapables de faire plus, ou parce que leur travail, la société, ou leur propre haine de devenir accro ne le leur permet pas.

Il peut être avantageux de donner quelques définitions.

**Le non-usager**

Une personne qui n'est jamais tombée dans le piège mais qui ne doit pas être complaisante. Ils ne sont non-usagers que par chance ou par la grâce du ciel. Tous les utilisateurs sont convaincus qu'ils ne deviendront jamais accros et certains non-utilisateurs continuent à essayer une session occasionnelle.

**L'utilisateur occasionnel**

Il existe deux classifications de base :

1.  L'utilisateur qui est tombé dans le piège sans s'en rendre compte - n'enviez pas ces utilisateurs. Ils ne font que goûter le nectar à l'embouchure de la sarracénie et, selon toute probabilité, ils deviendront bientôt de gros consommateurs. Rappelez-vous que, de même que tous les alcooliques ont commencé comme des buveurs occasionnels, de même tous les consommateurs commencent de façon occasionnelle.

2.  L'utilisateur qui était auparavant un gros consommateur et qui pense qu'il ne peut pas s'arrêter. Ces utilisateurs sont les plus tristes de tous et se répartissent en plusieurs catégories, chacune nécessitant un commentaire distinct.

**L'utilisateur d'une fois par jour**

S'ils apprécient leur droit à l'orgasme, pourquoi utiliser le porno sur Internet une seule fois par jour ? Si c'est à prendre ou à laisser, pourquoi se donner la peine de le faire ? N'oubliez pas que "l'habitude" consiste, en réalité, à se frapper la tête contre un mur pour se détendre en s'arrêtant. Le consommateur d'une fois par jour soulage ses douleurs de manque pendant moins d'une heure chaque jour. Bien qu'il ne soit pas conscient, il passe le reste de sa journée à se frapper la tête contre ce mur, ce qu'il fera pendant la majeure partie de sa vie. Ils ne consomment qu'une fois par jour parce qu'ils ne peuvent pas risquer de se faire prendre, ou d'altérer leur santé neurologique. Il est facile de convaincre un gros consommateur qu'il n'aime pas ça, mais beaucoup plus difficile de convaincre un consommateur occasionnel. Quiconque a déjà essayé de réduire sa consommation sait que c'est la pire des tortures et qu'il est presque garanti que vous resterez dépendant pour le reste de votre vie.

**L'utilisateur rejeté**

Ils réclament le droit d'avoir un orgasme tous les jours, mais leur partenaire sexuel n'est pas toujours heureux de répondre à cette demande. Au début, ils utilisent le porno sur Internet pour combler ce vide, mais après avoir pris le "toboggan" excitant, ils sont piégés dans un cycle de nouveauté, de choc, d'images anormales, etc. En fait, ils sont heureux du rejet de leur partenaire, car cela leur fournit une sorte d'excuse. Si le porno sur Internet vous apporte tant, pourquoi vous donner la peine d'avoir un partenaire ? Libérez-les plutôt. Ils ne profitent même pas des séances lorsqu'ils doivent "porter" leur partenaire dans leur esprit. À un moment donné, ils cherchent leur partenaire dans la vie réelle pour leur donner une excuse pour s'aventurer dans les vallées sombres d'Internet.

**L'utilisateur de Porn-Diet**

Aussi connu sous le nom de "*Je peux m'arrêter quand je veux. Je l'ai fait des milliers de fois!*"

S'ils pensent qu'un régime les aide à se mettre d'humeur à draguer, pourquoi suivent-ils le régime d'une fois tous les quatre jours ? Personne ne peut prédire l'avenir, et si le hasard de la rencontre se produisait une heure après la séance prévue ? De plus, si le fait de "nettoyer la plomberie" de temps en temps est bon pour soulager la tension, pourquoi ne pas le faire tous les jours ? Il a été prouvé que la masturbation n'est pas nécessaire pour garder les organes génitaux en bonne santé et que le porno sur Internet ne l'est pas du tout. Même si c'est le cas, aucun "gourou" de la drague qui a lu des articles sur les dommages neurologiques ne recommandera jamais de regarder du porno super stimulant. La vérité, c'est qu'ils sont toujours accrochés. Bien qu'ils soient débarrassés de la dépendance physique, ils restent confrontés au problème primaire du lavage de cerveau. Ils espèrent à chaque fois arrêter pour de bon, mais retombent rapidement dans le même piège.

En fait, la plupart des utilisateurs envient ces personnes qui arrêtent de fumer ou qui commencent à fumer et se disent qu'elles ont de la chance de pouvoir contrôler leur consommation. Cependant, ils oublient que les personnes au régime ne contrôlent pas leur consommation - lorsqu'ils consomment, ils souhaitent ne pas le faire. Ils se donnent la peine d'arrêter, puis commencent à se sentir privés et retombent dans le piège, regrettant de ne pas l'avoir fait. Ils obtiennent le pire des deux mondes. Si l'on y réfléchit, cela est vrai dans la vie des usagers lorsqu'ils sont autorisés à faire une séance : ils la prennent comme un droit ou souhaitent ne pas en faire. Ce n'est que lorsqu'ils en sont privés que le porno devient précieux. Le syndrome du "fruit défendu" est l'un des terribles dilemmes des utilisateurs. Ils ne peuvent jamais gagner car ils se morfondent pour un mythe, une illusion. Il n'y a qu'un seul moyen pour eux de gagner : arrêter de se morfondre en arrêtant le porno !

**L'utilisateur "Je ne regarde que du porno statique/amateur/fait maison".**

Oui, tout le monde fait cela au départ, mais n'est-il pas étonnant de constater que la valeur de choc moyenne de ces clips semble augmenter rapidement et qu'avant même de s'en rendre compte, on se sent privé (tolérance) ? La nouveauté manque avec le porno statique, alors nous payons le joueur de flûte pour une tasse de graisse et descendons le toboggan vers le ressentiment et la culpabilité. La pire chose que vous puissiez faire est d'utiliser les photos de votre partenaire (avec son accord, bien sûr) pour vous masturber. Pourquoi ? Parce que, ce faisant, vous reconnectez votre cerveau à la recherche, à la quête et aux bouffées de dopamine induites par la variété. Du point de vue chimique, les glissades d'eau du porno dans le cerveau sont des accumulations de DeltaFosB, de sorte que vous aurez des difficultés lorsque vous serez avec eux en temps réel.

Un autre piège de cette catégorie est le porno "amateur" et "fait maison". La plupart sont des faux et vous le savez, et vous n'allez pas non plus vous arrêter au tout premier qui vous saute aux yeux, mais continuer à chercher et à chercher. N'oubliez pas que ce n'est pas seulement l'orgasme que le cerveau recherche, mais la nouveauté de la chasse qui donne le frisson au toboggan aquatique. Le contenu pornographique n'est pas le problème - qu'il soit amateur ou professionnel - ce sont les bouffées de dopamine dans le cerveau qui provoquent l'accumulation de la tolérance et de la satiété. Le porno détruit le fonctionnement normal du cerveau, la masturbation brouille la réponse muscle-cerveau ; l'orgasme inonde le cerveau d'opioïdes et rend le chemin plus facile à suivre la prochaine fois.

**L'utilisateur "J'ai arrêté mais je jette un coup d'oeil de temps en temps"**.

D'une certaine manière, les utilisateurs de "peeking" sont les plus pathétiques de tous. Soit ils passent leur vie à croire qu'ils sont privés, soit, le plus souvent, le coup d'œil occasionnel en devient deux. Ils glissent sur la pente glissante et, tôt ou tard, redeviennent de gros consommateurs. Ils sont à nouveau tombés dans le même piège que celui dans lequel ils sont tombés en premier lieu.

Il existe deux autres catégories d'utilisateurs occasionnels. La première est celle des personnes qui se masturbent sur des images ou des clips des dernières vidéos sexuelles de célébrités qui font la une des journaux, ou sur quelque chose qu'elles ont "ramené à la maison" après l'avoir regardé "accidentellement" à l'école ou au travail. Ces personnes ne sont en fait que des non-utilisateurs, mais elles ont le sentiment de manquer quelque chose. Ils veulent faire partie de l'action, et la plupart d'entre nous ont commencé de cette façon. La prochaine fois, remarquez qu'après un certain temps, la célébrité de votre fantasme ne vous plaît plus. Plus la cible de votre fantasme est "inaccessible", plus le retrait de l'orgasme est frustrant.

La deuxième catégorie a récemment fait l'objet d'une attention accrue, le meilleur moyen de la décrire étant de présenter un cas partagé en ligne.

Une femme professionnelle lisait des histoires pornographiques sur Internet depuis de nombreuses années et n'avait jamais consommé plus ou moins qu'une fois par nuit. Par ailleurs, c'était une femme très volontaire. La plupart des utilisateurs se demanderaient pourquoi elle voulait arrêter en premier lieu - en soulignant volontiers qu'il n'y avait aucun risque de PIED, ou d'EP dans son cas (faux). Elle n'utilisait même pas d'images statiques, les histoires étant bien plus douces que le matériel qu'ils utilisent eux-mêmes au quotidien.

Ils font l'erreur de supposer que les utilisateurs occasionnels sont plus heureux et ont plus de contrôle. Ils ont peut-être plus de contrôle, mais ils ne sont certainement pas heureux. Dans le cas de cette femme, elle n'était pas satisfaite de son partenaire ni du sexe réel, et était très irritable lorsqu'elle répondait à son stress et à ses contraintes quotidiennes. Ses proches étaient incapables de comprendre ce qui la tracassait. Même si elle se convainquait de ne pas avoir peur de son usage par la rationalisation, elle se trouvait toujours incapable d'apprécier les vraies relations qui comportent invariablement des hauts et des bas. Le centre de récompense de son cerveau était incapable d'utiliser les déstressants normaux présents dans la vie en raison de l'inondation quotidienne de dopamine. La régulation négative subséquente des récepteurs cérébraux l'a rendue mélancolique dans la plupart des circonstances. Comme la plupart des gens, elle avait une grande peur du côté sombre de la pornographie et du traitement des femmes - avant sa première fois. Finalement, elle a été victime du lavage de cerveau de la société et a essayé son premier site. Contrairement à la plupart de ceux qui capitulent et deviennent des utilisateurs à la chaîne, elle a résisté à la tentation de voir des clips violents.

Tout ce que vous appréciez dans le porno, c'est de mettre fin à l'envie qui a commencé avant, qu'il s'agisse de l'envie physique presque imperceptible, ou de la torture mentale de ne pas être autorisé à gratter la démangeaison. Le porno sur Internet est en soi un poison, c'est pourquoi vous ne souffrez de l'illusion d'en profiter qu'après des périodes d'abstinence. Comme pour la faim ou la soif, plus vous souffrez longtemps, plus le plaisir est grand lorsque vous êtes enfin soulagé. Faisant l'erreur de croire que le porno n'est qu'une habitude, ils pensent : "*Si je peux le maintenir à un certain niveau ou seulement dans des occasions spéciales, mon cerveau et mon corps l'accepteront. Ensuite, je peux continuer à en consommer à ce niveau ou le réduire davantage si je le souhaite.*"

Que ce soit clair dans votre esprit, "l'habitude" n'existe pas. Le porno est une dépendance à une drogue, la tendance naturelle étant de soulager les symptômes de manque, et non de les supporter. Pour le maintenir au niveau où vous êtes actuellement, il vous faudrait faire preuve d'une discipline et d'une volonté extraordinaires pour le reste de votre vie ; à mesure que le centre de récompense de votre cerveau s'immunise contre la dopamine et les opioïdes, il en veut de plus en plus, et non de moins en moins.

À mesure que le porno commence à détruire progressivement votre système nerveux, votre courage, votre confiance et le contrôle de vos impulsions, vous devenez de plus en plus incapable de résister à la réduction de l'intervalle entre chaque session. C'est pourquoi, dans les premiers jours, nous pouvons prendre ou laisser. Si l'on sent que quelque chose ne va pas, mentalement ou physiquement, on arrête tout simplement. N'enviez pas cette femme, lorsque vous ne regardez qu'une fois toutes les vingt-quatre heures, cela semble être la chose la plus précieuse sur terre, faisant du porno un "fruit défendu". Pendant de nombreuses années, cette pauvre femme a été au centre d'une lutte acharnée.

Incapable d'arrêter de consommer, mais effrayée à l'idée de passer aux clips en streaming. Pendant vingt-trois heures et dix minutes de chacun de ces jours, elle a dû lutter contre la tentation et le manque de sentiments envers son petit ami. Il lui a fallu beaucoup de volonté pour faire ce qu'elle a fait, ce qui l'a finalement conduite aux larmes. De tels cas sont rares, mais il faut voir les choses logiquement : Soit il y a une véritable béquille ou un véritable plaisir dans le porno, soit il n'y en a pas. Si c'est le cas, qui veut attendre une heure, un jour ou même une semaine ? Pourquoi devriez-vous être privé de la béquille ou du plaisir pendant ce temps ? S'il n'y a pas de véritable béquille ou de plaisir, pourquoi se donner la peine de rendre visite à son harem en ligne ?

Voici un autre cas d'un homme qui vit une fois par jour, décrivant sa vie comme suit :

> *J'ai quarante ans, j'ai souffert de dysfonctionnement érectile induit par le porno (PIED) avec de vraies femmes et même en utilisant du porno, ce qui est la plupart du temps. Cela fait longtemps que je n'ai pas eu d'érection complète. Avant de me mettre au régime porno une fois sur quatre, j'avais l'habitude de dormir profondément toute la nuit après ma séance. Maintenant, je me réveille toutes les heures de la nuit et je ne pense qu'à ça. Même endormi, je rêve de mes clips préférés. Les jours qui suivent ma séance programmée, je me sens plutôt déprimée, le régime me prenant toute mon énergie. Mon épouse me laisse seule car je suis de mauvaise humeur et si elle ne peut pas partir, elle ne veut pas de moi à la maison. Je vais faire du jogging dehors mais mon esprit est obsédé par ça.*
>
> *Le jour prévu, je commence à planifier plus tôt dans la nuit, devenant très irrité si quelque chose se produit contre mes plans. Je me retire des conversations et je cède (pour ensuite le regretter) au travail et à la maison. Je ne suis pas du genre à discuter, mais je ne veux pas que le sujet ou la conversation me retienne. Je me souviens de moments où je me disputais bêtement avec mon conjoint. J'attends dix heures et quand elles arrivent, mes mains tremblent de façon incontrôlable. Je ne commence pas l'acte tout de suite - car il y a de nouvelles vidéos qui ont été ajoutées - et je " magasine ". Mon esprit me dit que, puisque je me suis affamé pendant quatre jours, je mérite un clip "spécial" qui doit valoir le temps passé à chercher. Finalement, je me contente d'un ou deux clips, mais je veux qu'ils durent pour pouvoir 'survivre' pendant les quatre jours suivants, alors je prends plus de temps pour terminer l'acte.* 

En plus de ses autres problèmes, ce pauvre homme ne sait pas qu'il s'empoisonne. D'abord, il souffre du "syndrome du fruit défendu", puis il force son cerveau à absorber de la dopamine. Comparativement, ses récepteurs de dopamine ne sont pas aussi coupés, mais il graisse les glissières d'eau du porno, cherchant, cherchant la tension, la nouveauté, la variété, le choc et l'anxiété afin de survivre les quatre prochains jours. Vous imaginez probablement cet homme comme un imbécile pathétique, mais ce n'est pas le cas. En tant qu'ancien athlète devenu ex-sergent des Marines, il ne voulait pas devenir dépendant de quoi que ce soit. Cependant, à son retour de la guerre, il a suivi une formation de technicien informatique dans le cadre d'un programme de réadaptation pour anciens combattants. 

Lorsqu'il est entré dans la vie active, il était un informaticien bien payé dans une banque, et on lui a donné un ordinateur portable à emporter chez lui. C'est l'année où des personnalités célèbres ont "divulgué" leurs vidéos pornographiques en ligne, ce qui a fait couler beaucoup d'encre. Il est alors devenu accro, passant le reste de sa vie à payer le prix fort et à se ruiner physiquement et mentalement. S'il s'agissait d'un animal, la société l'aurait depuis longtemps mis hors d'état de nuire, mais nous permettons encore à de jeunes adolescents mentalement et physiquement sains de devenir accros. Vous pouvez penser que ce cas et ces notes sont exagérés, mais ce cas -- bien qu'extrême -- est loin d'être unique. Il y a des dizaines de milliers d'histoires similaires. Pouvez-vous être sûrs que beaucoup de ses amis et connaissances l'enviaient parce qu'il n'en prenait qu'une fois sur quatre ? Si vous pensez que cela ne peut pas vous arriver, **arrêtez de vous faire des illusions.** **C'EST DÉJÀ LE CAS.**

Comme les autres toxicomanes, les utilisateurs de pornographie sont des menteurs notoires, même envers eux-mêmes. Ils sont obligés de l'être. La plupart des utilisateurs occasionnels s'y adonnent bien plus souvent et à bien plus d'occasions qu'ils ne veulent bien l'admettre. De nombreuses conversations avec des utilisateurs dits " deux fois par semaine " admettent qu'ils l'ont fait plus de trois ou quatre fois cette semaine-là. Lisez les histoires des utilisateurs occasionnels sur reddit, NoFap et les forums de Reboot (redémarrage de l'esprit par l'arrêt de la PMO), et vous verrez qu'ils comptent les jours ou attendent d'échouer. Vous n'avez pas besoin d'envier les utilisateurs occasionnels, vous n'avez pas besoin de consommer non plus, la vie est infiniment plus douce sans cela. Prenez le journal suivant :

"*Cela a commencé par un simple défi de ne pas toucher mon **engin** pendant une journée et d'en être incapable. Je ne pense plus à la masturbation, elle ne me traverse plus l'esprit. C'est possible, je vous le promets. Les richesses qui attendent ceux qui en sont capables - elles sont incroyables.*"

Les adolescents sont généralement plus difficiles à guérir, non pas parce qu'ils ont plus de mal à s'arrêter, mais parce qu'ils ne croient pas être accrochés ou sont au stade initial du piège. Ils souffrent généralement de l'illusion qu'ils auront automatiquement arrêté avant la deuxième étape.

Les parents d'enfants qui détestent la pornographie sur Internet ne doivent pas avoir un faux sentiment de sécurité. Tous les enfants détestent les côtés sombres du porno avant de devenir accros. À un moment donné, vous l'avez fait aussi. Ne vous laissez pas non plus berner par les campagnes d'avertissement, le piège est le même qu'avant. Les enfants savent que le porno sur Internet est un stimulus supranormal, mais ils savent aussi qu'une seule "visite" ou un seul "coup d'œil" ne suffira pas. À un moment donné, ils peuvent être influencés par un partenaire, un camarade de classe ou un collègue de travail.

Ne soyez pas complaisant à cet égard. L'incapacité de la société à empêcher les adolescents de devenir dépendants de la pornographie sur Internet et d'autres drogues est peut-être la facette la plus inquiétante de cette dépendance. Le cerveau des adolescents est beaucoup plus plastique, et il est nécessaire de les éduquer et de les protéger. Si vous ne savez pas par où commencer, vous pouvez consulter le livre [YourBrainOnPorn](https://www.yourbrainonporn.com/) (malheureusement qu'en anglais pour le coup) pour vous informer sur la neuroscience. Même si vous soupçonnez votre adolescent d'être déjà accro, ce livre fournit des éléments de compréhension fondamentaux pour aider quelqu'un à s'échapper. Sinon, recommandez ce livre !