# L'utilisateur de YouTube / Twitch / Instagram

Cet utilisateur devrait être regroupé avec les utilisateurs occasionnels, mais ses effets sont si insidieux qu'il mérite un chapitre à part. Il conduit à l'effondrement du contrôle de soi, provoquant presque une rupture pour un utilisateur du forum NoFap :

> La tentative avait été déclenchée par l'inquiétude de ma femme concernant mes érections peu fiables et mon manque d'intérêt. Je lui avais dit que ce n'était pas elle, juste la pression du travail. Elle m'a répondu : "Je sais que tu as déjà géré la pression du travail, mais comment te sentirais-tu si tu étais à ma place et que tu devais regarder quelqu'un que tu aimes se détruire systématiquement ?" C'était un argument que je trouvais irrésistible, d'où la tentative d'arrêt. Elle sait que je ne la trompe pas, mais c'est en quelque sorte pire que ça. La tentative s'est terminée au bout de trois semaines, avec pour point culminant une discussion animée avec un vieil ami. Ce n'est que des années plus tard que j'ai compris que mon esprit sournois avait délibérément déclenché la dispute. Je me suis senti exaspéré à juste titre à l'époque, mais je ne crois pas que ce soit une coïncidence, car je ne m'étais jamais disputé avec cet ami avant, et je ne l'ai jamais fait depuis. C'était clairement le petit monstre au travail.
>
> Quoi qu'il en soit, j'avais mon excuse. J'avais désespérément besoin de me défouler et peu importe comment. Ma femme n'étant pas d'humeur, j'ai eu le sentiment d'y avoir droit, et je me suis convaincu que ce n'était pas grave si je me "restreignais" en évitant les sites pornographiques et en restant de ce côté de la "ligne rouge" en ne regardant que des vidéos YouTube. Mais ma femme a fini par se raviser au fil de la nuit et a voulu faire l'amour, mais j'étais fatigué et sans ma "puissance", alors j'ai inventé un mal de tête. Je ne pouvais pas supporter de penser à la déception que cela allait causer à ma femme. Puis je suis progressivement revenu à mes anciennes habitudes, YouTube devenant ma nouvelle destination de harem. Je me souviens avoir été plutôt satisfait à l'époque, pensant que cela réduisait au moins ma consommation. Finalement, elle m'a accusé de continuer à l'ignorer au lit. Je ne l'avais pas réalisé, mais elle a décrit les fois où j'avais provoqué une dispute et quitté la maison en trombe. D'autres fois, j'ai pris deux heures pour acheter un article mineur et simulé des entorses. J'ai trouvé de piètres excuses pour éviter de la courtiser, alors quand j'ai un harem en ligne fiable, c'est encore plus difficile.

Le pire dans le cas de l'utilisateur de YouTube, c'est que cela renforce l'idée fausse qu'il est privé. Simultanément, cela entraîne une perte importante d'estime de soi ; une personne autrement honnête peut se forcer à tromper l'être aimé. Cela vous est probablement arrivé, ou vous arrive encore, sous une forme ou une autre.

Les problèmes rencontrés sur les sites Web tels que Twitch, Instagram, TikTok, Twitter (et la plupart des médias sociaux) sont principalement motivés par la supplémentation. Poussés par des envies de nouveauté et de dopamine, ils se font croire qu'ils sont sur un site sûr. Rappelez-vous : le plaisir est de chercher, pas de tuer, et le petit monstre ne se soucie pas de savoir d'où vient sa dose. Pour l'utilisateur, le contenu "doux" reçu dans ses différents flux en ligne lui procure un soulagement fugace de la sensation de manque, le gardant accroché et attendant sa prochaine session.

Le modèle de l'image/vidéo est en effet beau, et si vous l'aviez à vos côtés en ce moment, il pourrait sûrement vous donner du plaisir, mais cette image ne peut pas... Elle n'est tout simplement pas réelle. Votre cerveau est trompé comme un taureau qui se heurte à une cape rouge, et ne comprend pas ensuite pourquoi il l'a fait. On pourrait penser qu'il suffit alors de regarder ces images sans se masturber. Mais rappelez-vous que votre cerveau est accroché à la nouveauté sans limite, et que le petit monstre ne se soucie pas de savoir d'où vient sa dose. C'est le même piège.

Vous avez peut-être regardé la série télévisée Columbo, le thème de chaque épisode est similaire. Le méchant, généralement un homme d'affaires riche et respecté, a commis ce qu'il est convaincu être le meurtre parfait et sa confiance dans le fait que son crime ne sera pas détecté est renforcée lorsqu'il découvre que le détective Columbo, à l'allure plutôt miteuse et peu impressionnante, est chargé de l'affaire.

Columbo a la fâcheuse habitude de fermer la porte à la fin de son interrogatoire, après avoir assuré au suspect qu'il n'a rien à craindre. Mais juste avant que l'air satisfait n'ait disparu du visage du meurtrier, Columbo réapparaît et dit : "*Juste un petit point, monsieur, que vous pourrez sûrement expliquer...*". Le suspect bafouille, et à partir de ce moment-là, il sait que Columbo va progressivement l'épuiser. Quelle que soit l'atrocité du crime, à partir de ce moment-là, la sympathie va au meurtrier.

Ces crises sont similaires, la tension de ne pas être autorisé à franchir la ligne rouge pour avoir le plaisir pornographique qu'ils "méritent", puis de se demander où est le plaisir après avoir terminé l'acte. La peur de franchir la ligne, de perdre le contrôle et de retourner au lit, pour être ensuite traqué par la peur que votre partenaire veuille du sexe. Les vidéos YouTube "sûres" ne vous satisfont plus à cause de la désensibilisation, du manque de nouveauté et de la certitude que, tôt ou tard, vous vous rendrez dans votre harem en ligne préféré. L'humiliation et la honte finales étant alors lorsque cette certitude devient un fait, suivies par le retour immédiat au visionnage à la chaîne.

**OH, LES JOIS D'ÊTRE UN PMOien (utilisateur de la PMO, cf. l'introduction tout en bas)!**
