# Une Habitude Sociale ?

La santé de l'esprit et du corps sont les principales raisons pour lesquelles nous *devrions* vouloir arrêter - mais elles l'ont toujours été. Nous n'avons pas vraiment besoin de recherches scientifiques et de connaissances en neurosciences pour nous dire que le porno crée une dépendance et peut potentiellement briser nos vies. Notre corps est l'objet le plus sophistiqué de la planète, et tout utilisateur sait dès la première séance que le stimulus peut être excessif et devenir un poison.

La seule raison pour laquelle nous nous adonnons au porno est le chevauchement de ce cycle avec notre programmation évolutive. Le porno sur Internet est très disponible, gratuit et en continu 24h/24. Le porno était autrefois considéré comme inoffensif, mais c'était à l'époque où les images étaient statiques et où les vidéos nécessitaient de se rendre au magasin local pour acheter une cassette VHS.

Aujourd'hui, il est généralement considéré - même par les utilisateurs eux-mêmes - que le porno est un stimulus supranormal et qu'il crée une dépendance. Autrefois, l'homme fort n'admettait pas qu'il se masturbait, le terme "branleur" étant péjoratif. Dans chaque pub, club ou bar, la majorité des hommes étaient fiers de vouloir ramener une femme chez eux et d'avoir de vrais rapports sexuels. Aujourd'hui, la position est complètement inversée pour l'accro au porno sur Internet, l'homme d'aujourd'hui réalise qu'il commence à sentir qu'il n'a pas besoin d'une femme. Se regroupant en ligne, il discute de ses expériences, élabore des stratégies et explore les options. L'homme fort d'aujourd'hui ne veut pas dépendre des drogues. Grâce à la révolution sociale, tous les utilisateurs réfléchissent sérieusement à l'arrêt du porno et de la masturbation sur Internet. Les utilisateurs d'aujourd'hui considèrent le porno comme une activité inutile et nuisible.

La tendance la plus significative observée sur les forums est l'accent mis de plus en plus sur les aspects antisociaux du porno. L'époque où un homme se vantait d'avoir du sexe et des orgasmes tous les jours est lentement remplacée par la prise de conscience de l'esclavage du monstre porno.

La seule raison pour laquelle les gens continuent après avoir été éduqués est qu'ils n'ont pas réussi à arrêter ou qu'ils ont trop peur d'essayer. Il existe un large spectre d'intérêt pour le sujet, certains s'abstenant de porno, de masturbation et d'orgasme - avec ou sans partenaire. Les pratiques qui séparent les parties tantriques et propagatives du sexe, comme la rétention du sperme et le Karezza, sont discutées et adoptées en masse. De nombreux échecs mentionnés ci-dessus sont en réalité des chutes, ce qui profite quelque peu aux personnes qui les pratiquent. Une fois que vous aurez entamé la voie du " pas de PMO ", vous trouverez la meilleure solution qui s'applique à votre vie. Nous vous encourageons à élaborer votre propre plan sur les orgasmes après avoir compris et pratiqué la séparation sexuelle. Quel que soit votre parcours, vous verrez l'intérêt de limiter le nombre de fois où vous inondez votre cerveau de substances chimiques par l'orgasme, et de ne plus jamais considérer le porno, le sexe et l'orgasme comme un plaisir ou une béquille pour votre moi émotionnel.

Plusieurs communautés en ligne populaires, fondées par des non-utilisateurs, se consacrent à l'abandon non seulement du porno mais aussi de la masturbation. Ces sites sont en fin de compte bénéfiques à ceux qui s'échappent, mais la plupart des notes leur indiquent d'essayer la volonté. La conséquence de l'obsession des stries et autres mesures est l'apitoiement sur soi et le manque d'exaltation. Une grande partie du lavage de cerveau est bien vivante. Finalement, quelqu'un finit par craquer et un effet domino se produit, les autres utilisateurs découvrant qu'ils ne sont pas les seuls. Cependant, leurs efforts ne sont pas vains, ils avancent, bien qu'avec beaucoup d'auto-torture car ils ferment leurs navigateurs mais pas le désir et le besoin. EasyPeasy fonctionne à l'inverse, en éteignant d'abord le besoin et le désir avant d'éteindre le navigateur. Chaque jour, de plus en plus d'utilisateurs quittent le navire en perdition et ceux qui y restent sont terrifiés à l'idée d'être les derniers.

**NE LAISSE PAS ÇA DEVENIR TOI!**