# Le Timing

En dehors du fait évident que cela ne vous fait aucun bien et que c'est le bon moment pour arrêter, le moment est important. La société traite avec désinvolture la pornographie sur Internet comme une habitude légèrement déplaisante qui ne nuit pas à votre santé. C'est faux. C'est une toxicomanie, une maladie et un destructeur de relations dans la société. La pire chose qui puisse arriver dans la vie de la plupart des utilisateurs est de devenir accro à cette terrible dépendance. S'ils restent accrochés, des choses horribles se produisent. Le choix du moment est donc important pour se donner le droit à une bonne cure.

Tout d'abord, identifiez les moments ou les occasions où le porno semble être important pour vous. Si vous êtes un homme d'affaires qui l'utilise pour l'illusion de soulager le stress, choisissez une période relativement calme ou des vacances. Si vous utilisez le porno principalement pendant des périodes ennuyeuses ou relaxantes, le contraire s'applique. Quoi qu'il en soit, prenez votre tentative au sérieux et faites-en la chose la plus importante de votre vie.

Prévoyez une période de trois semaines et essayez d'anticiper tout événement qui pourrait conduire à l'échec. Des événements tels que des voyages en conférence, l'absence de votre partenaire, etc. ne doivent pas vous décourager, à condition que vous les prévoyiez à l'avance et que vous n'ayez pas l'impression de vous priver. N'essayez pas de réduire votre consommation dans l'intervalle, car cela ne ferait que créer l'illusion qu'il est agréable de se priver. En fait, il est utile de se forcer à regarder et à avoir autant de séances de porno que possible. Lors de la dernière séance et de la dernière fois, soyez conscient de la déception due à la satiété, des attentes non satisfaites, de toute douleur corporelle, des effets de manque, de l'irritation et de la mélancolie. Pensez à combien ce sera merveilleux lorsque vous vous permettrez d'arrêter de le faire.

**QUOI QUE VOUS FASSIEZ, NE TOMBEZ PAS DANS LE PIÈGE DE VOUS DIRE "PAS MAINTENANT, PLUS TARD" ET DE NE PLUS Y PENSER. ÉTABLISSEZ VOTRE EMPLOI DU TEMPS MAINTENANT ET ATTENDEZ-LE AVEC IMPATIENCE.**

Rappelez-vous, *vous n'abandonnez rien*. Au contraire, vous êtes sur le point de recevoir des gains positifs merveilleux.

Pendant des années, le corps médical a considéré le porno comme inoffensif, sans connaître la différence entre le porno statique apprivoisé d'antan et la dernière expérience de réalité virtuelle en streaming. Le problème est que, bien que chaque utilisateur consomme du porno sur Internet uniquement pour soulager le besoin de dopamine qu'il provoque, ce n'est pas la dépendance à la substance chimique qui accroche l'utilisateur, mais l'auto-lavage du cerveau résultant de la dépendance. Une personne intelligente se laissera prendre à un tour de passe-passe, mais seul un imbécile continuerait à s'y laisser prendre après s'être rendu compte de la supercherie. Heureusement, la plupart des utilisateurs ne sont pas des idiots ; ils pensent seulement l'être. Chaque utilisateur a son propre lavage de cerveau. C'est pourquoi il semble y avoir une telle diversité dans les types de toxicomanes, ce qui ne fait qu'aggraver les mystères.

Si l'intérêt du livre original était d'arrêter la nicotine (l'une des drogues les plus rapides et les plus addictives connues de l'homme), vous serez agréablement surpris de constater que la philosophie proposée dans le livre original est toujours valable lorsqu'elle est adaptée à d'autres dépendances. Les connaissances accumulées et le défi que Carr et moi-même relevons consistent à communiquer ces connaissances à chaque utilisateur individuel. Le fait que je sache que chaque utilisateur peut non seulement trouver qu'il est facile d'arrêter, mais qu'il peut même apprécier le processus, n'est pas seulement inutile, mais aussi extrêmement frustrant, à moins que l'utilisateur puisse s'en rendre compte. Dans son livre original, Allen Carr explique son conseil controversé :

>"De nombreuses personnes m'ont dit : *'Vous dites : "Continuez à fumer jusqu'à ce que vous ayez terminé le livre" Cela a tendance à faire que le fumeur mette du temps à lire le livre ou ne le termine tout simplement pas. Point final. Par conséquent, vous devriez changer la consigne.'* Cela semble logique, mais je sais que si la consigne était : *'Arrêtez immédiatement'*, certains fumeurs ne commenceraient même pas à lire le livre. Un fumeur m'a consulté dans les premiers jours. Il m'a dit : *'Je n'aime vraiment pas avoir à demander votre aide, je sais que j'ai une forte volonté. Dans tous les autres domaines de ma vie, je suis maître de la situation. Pourquoi tous les autres fumeurs arrêtent-ils de fumer en faisant appel à leur propre volonté, alors que je dois venir vous voir ? Il a poursuivi en disant : "Je pense que je pourrais le faire tout seul, si je pouvais fumer pendant que je le faisais"*.

La croyance sociétale veut qu'il soit incroyablement difficile d'arrêter de fumer, alors de quoi un fumeur a-t-il besoin quand quelque chose est difficile ? Notre petit ami, notre béquille. S'échapper du tabac semble être un double coup dur, non seulement il y a une tâche difficile à accomplir -- ce qui est déjà assez difficile -- mais la béquille sur laquelle nous comptons normalement pour de telles occasions n'est pas disponible. La véritable beauté de cette méthode réside peut-être dans le fait qu'il n'est pas nécessaire d'abandonner pendant le processus, mais plutôt de se débarrasser de toutes les peurs et de toutes les doutes au départ, de sorte qu'à la fin de la dernière session, vous êtes déjà en train de profiter de la liberté.

C'est pourquoi ce hackbook conservera les mêmes conseils. On aura beau dire que ce sera facile et agréable, il y aura une grande majorité qui ne pourra pas l'accepter à cause du lavage de cerveau personnel sur la difficulté d'arrêter de fumer.

Le timing est le seul chapitre qui m'amène à remettre sérieusement en question le conseil original d'Allen. Avant tout, si les déclencheurs sont le stress du bureau, il faut choisir un jour férié pour faire une tentative et vice versa. Ce n'est pas le moyen le plus facile, mais plutôt de choisir ce que vous considérez comme le moment le plus *difficile*. Qu'il s'agisse du stress, des obligations sociales, de la concentration ou de l'ennui, une fois que vous avez prouvé que vous supportez et appréciez la vie dans les pires situations, toutes les autres sont agréables. Mais si c'était le conseil, feriez-vous même la tentative ?

Voici une analogie : ma sœur et moi avons l'intention de nager ensemble. Nous arrivons à la piscine en même temps, mais nous finissons rarement par nager ensemble. La raison en est qu'elle s'immerge un orteil et qu'une demi-heure plus tard, elle nage réellement. C'est une torture lente, je sais d'avance qu'à un moment ou à un autre, même si l'eau est froide, je devrai la braver. Alors j'ai appris à le faire de la manière la plus facile : Plonger directement dedans. Maintenant, imaginez que je sois en mesure d'insister sur le fait que si elle ne plonge pas directement dans l'eau, elle ne sait pas nager. Si c'était le cas, elle ne nagerait pas du tout. Voyez-vous le problème ?

D'après les réactions, de nombreux utilisateurs ont utilisé le conseil de chronométrage original pour retarder ce qu'ils pensaient être le "mauvais jour". J'ai ensuite pensé utiliser une technique similaire à celle du chapitre sur les "avantages du porno", quelque chose comme : "Le timing est très important et dans le chapitre suivant, vous serez conseillé sur le meilleur moment pour faire la tentative" et sur la page suivante, il y a juste un énorme "MAINTENANT !" C'est en fait le meilleur conseil, mais le suivriez-vous ? L'aspect le plus subtil du piège est peut-être le fait que lorsque nous avons un véritable stress dans notre vie, ce n'est pas le bon moment pour arrêter, mais que dans les moments sans stress, nous n'avons aucune envie de mettre fin à la torture. Posez-vous les questions suivantes :

1.  Lorsque vous vous êtes mis au porno pour la première fois, avez-vous vraiment décidé que vous en seriez dépendant pour le reste de votre vie sans jamais pouvoir vous arrêter ? ***Bien sûr que non!***

2.  Allez-vous continuer le reste de votre vie sans jamais pouvoir vous arrêter ? ***Bien sûr que non !***

Alors, quand allez-vous arrêter ? Demain ? L'année prochaine ? L'année suivante ? N'est-ce pas la question que vous vous posez depuis que vous avez réalisé que vous étiez accro ? Espérez-vous qu'un matin vous vous réveillerez et que vous n'aurez plus envie de regarder la télévision ? Arrêtez de vous faire des illusions, avec n'importe quelle dépendance, vous devenez progressivement plus accro, pas moins. Allez-vous attendre jusqu'à ce que vous ayez vraiment commencé à sentir que sortir du lit est plus difficile que de se masturber ? Ce serait un peu inutile.

Le véritable piège est la croyance que ce n'est pas le bon moment - ce sera toujours plus facile demain. Nous croyons que nous menons des vies stressantes, mais en réalité, ce n'est pas le cas. La plupart des stress réels ont été éliminés de nos vies. En sortant de chez vous, vous ne vivez pas dans la crainte d'être attaqué par des animaux sauvages, la plupart ne se demandent pas d'où viendra leur prochain repas, ni si un toit sera au-dessus de leur tête ce soir. Pensez à la vie d'un animal sauvage, chaque fois qu'un lapin sort de son terrier, il est confronté au Vietnam pour toute sa vie. Mais le lapin le supporte, il a de l'adrénaline et d'autres hormones, et nous aussi. La vérité est que les périodes les plus stressantes de la vie de toute créature sont la petite enfance et l'adolescence. Mais trois milliards d'années de sélection naturelle nous ont équipés pour faire face au stress, et beaucoup de ceux qui ont eu une enfance difficile mènent une vie normale.

C'est un cliché de dire : "Si vous n'avez pas la santé, vous n'avez rien", mais c'est absolument vrai. Lorsque vous vous sentez physiquement et mentalement fort, vous pouvez profiter des hauts et gérer les bas. Beaucoup confondent responsabilité et stress, mais la responsabilité ne devient stressante que lorsque nous ne nous sentons pas assez forts pour la gérer. Ce qui détruit le plus, ce n'est pas le stress, le travail ou la vieillesse, mais les béquilles illusoires vers lesquelles ils se tournent.

Voyez les choses ainsi : vous avez déjà décidé de ne pas rester dans le piège pour le reste de votre vie. Par conséquent, à un moment ou à un autre, que ce soit facile ou difficile, tu devras passer par le processus de libération. Le porno n'est pas une habitude ou un plaisir, c'est une toxicomanie et une maladie. Nous avons établi que, loin d'être plus facile demain, la situation va empirer progressivement. Le moment de s'en débarrasser est **maintenant** - ou aussi près de maintenant que vous pouvez le faire. Pensez à la rapidité avec laquelle chaque semaine de notre vie passe, c'est tout ce qu'il faut. Pensez à quel point il sera agréable de profiter du reste de votre vie sans que des ombres toujours plus grandes ne planent sur vous. Si vous suivez toutes les instructions, vous n'aurez même pas à attendre cinq jours ou trois semaines. Non seulement vous trouverez qu'il est facile d'arrêter le porno, mais **vous y prendrez plaisir!**