# Est-ce que le Plaisir me Manquera ?

**NON!** Une fois que le petit monstre pornographique sera mort, que votre corps cessera de réclamer de la dopamine et que les glissades d'eau pornographiques dans votre cerveau commenceront rapidement à s'estomper en raison du manque de "graissage", tout lavage de cerveau restant disparaîtra. Non seulement vous serez mieux équipé physiquement et mentalement pour faire face au stress et aux contraintes de la vie, mais vous profiterez pleinement des bons moments.

Il n'y a qu'un seul danger, celui de l'influence de ceux qui utilisent encore le sexe comme béquille et comme plaisir. L'expression *"l'herbe de l'autre est toujours plus verte"* est courante dans de nombreux aspects de notre vie et facilement compréhensible. Pourquoi, dans le cas de la pornographie - dont les inconvénients sont si énormes par rapport aux "avantages" illusoires - l'ex-utilisateur a-t-il tendance à envier ceux qui ont besoin du sexe et de la pornographie comme béquille ?

Avec tous les lavages de cerveau subis pendant l'enfance, il est tout à fait compréhensible que nous soyons tombés dans le piège. Comment se fait-il alors que, après avoir réalisé que le porno est un jeu de dupes et avoir réussi à s'en débarrasser, nous retombions directement dans le même piège ? C'est l'influence du lavage de cerveau de la société qui associe le porno au sexe, présenté comme normal. L'ex-utilisateur a un pincement au cœur ! Le sentiment de vide d'insécurité lié au fait qu'il est célibataire (ce qui n'est pas un crime de toute façon) provoque un sentiment d'anxiété, et le pousse à faire du toboggan. Il s'agit en effet d'une curieuse anomalie, en particulier si l'on tient compte de cette observation : non seulement tous les non-usagers du monde sont heureux de l'être, mais tous les usagers du monde, même avec leur esprit déformé, dépendant et lavé au cerveau, souffrant de l'illusion du plaisir ou de la relaxation, souhaiteraient ne jamais être devenus accros en premier lieu. Alors, pourquoi certains ex-usagers envient-ils ?

1.  Un seul coup d'oeil. Rappelez-vous que cela n'existe pas. Arrêtez de voir l'occasion isolée et commencez à regarder du point de vue de l'utilisateur de porno. Vous les enviez peut-être, mais eux ne s'approuvent pas et vous envient. Si seulement vous pouviez en quelque sorte observer cliniquement un autre utilisateur, car il peut être le coup de pouce le plus puissant de tous pour vous aider à vous en sortir. Remarquez la rapidité avec laquelle ils ouvrent de nombreux onglets et fenêtres de navigateur ? Il avance rapidement vers les sections importantes, se lasse vite des clips et passe en revue toute la gamme des genres produisant de la nouveauté, du choc, de l'anxiété, etc. Remarquez en particulier que l'acte semble être automatique. Rappelez-vous : ils n'y prennent pas plaisir, c'est qu'ils ne peuvent pas s'amuser sans cela. Le lendemain matin, en se réveillant avec une volonté affaiblie, une énergie perdue et des yeux éteints, ils devront continuer à s'étouffer à la première apparition de stress et de tension. Ils s'exposent à une vie entière de saleté, de mauvaise santé mentale et de confiance en soi ternie - une vie entière à se détruire avec des ombres noires au fond de leur esprit. Pour atteindre quel but ? L'illusion que vous obtenez ce que vous "méritez" et un plaisir maudit ?

2.  La deuxième raison pour laquelle certains ex-utilisateurs ont des frissons est que l'utilisateur de porno fait quelque chose - comme s'auto-plaire - et que le non-utilisateur ne le fait pas, et a donc tendance à se sentir privé. Mettez-vous bien dans la tête que ce n'est pas le non-utilisateur qui est privé, mais le pauvre dépendant qui est privé de :

    - Santé

    - Energie

    - Confiance

    - Paix de l'esprit

    - Courage

    - Tranquillité

    - Liberté

    - Respect de soi

    Perdez l'habitude d'envier les utilisateurs de porno et commencez à les voir comme les créatures misérables et pathétiques qu'ils sont vraiment. Je le sais, j'étais autrefois l'un des pires. C'est pour cela que vous lisez ce livre et non ceux qui ne peuvent pas faire face à la réalité et continuent à se faire des illusions.

Vous n'envieriez pas un héroïnomane, et comme toute toxicomanie, la vôtre ne s'améliorera pas. Si vous n'appréciez pas d'être un consommateur aujourd'hui, vous l'apprécierez encore moins demain. N'enviez pas les autres usagers, ayez pitié d'eux. Croyez-moi : ***Ils ont besoin de votre pitié !***
