# Puisse-je Compartimentaliser ?

Ce mythe est principalement répandu par les utilisateurs qui tentent d'arrêter avec la méthode de la volonté, qui font de la gymnastique mentale et commencent une routine Jekyll et Hyde : "*Le porno est pour mon alter ego et la vraie vie sentimentale est pour mon côté relationnel.*" Rien n'est plus éloigné de la vérité : les glissades d'eau du porno, le DeltaFosB et les changements neurologiques vont envahir la romance de la vraie vie, la rendant moins désirable. M. Hyde va définitivement passer outre les instructions du Dr. Jekyll.

Si vous utilisez du porno sur Internet, vous vous entraînez au rôle de voyeur, ou vous avez besoin de la possibilité de cliquer sur quelque chose de plus excitant à la moindre baisse du niveau de dopamine. Ou encore, à la recherche continuelle de la "bonne" scène pour un effet maximal. En outre, il se peut que vous vous masturbiez dans une position voûtée ou que vous regardiez votre smartphone au lit la nuit, et que vous finissiez par désirer ces signaux plus que les stimuli de la vie réelle. Le sexe va à l'encontre de presque tous les aspects du harem en ligne et n'a donc aucune chance lorsqu'on le compare. Les souvenirs créés lorsque l'on est jeune sont puissants et durables. Il faut donc plus de temps pour décomposer ces toboggans pornographiques et en reconnecter ou en créer de nouveaux. Mais cela ne veut pas dire que c'est plus difficile.

Chaque fois que vous montez sur le "toboggan à eau pornographique", vous le graissez, vous gardez les nerfs frais et prêts à tirer. Lorsque vous vous garez à côté d'un fast-food, l'odeur de la friteuse vous parvient aux narines et la vente est déjà faite. De même, les toboggans aquatiques pornographiques dans votre cerveau sont prêts à vous aspirer et sont ouverts 24h/24. Chaque indice ou déclencheur allume votre circuit de récompense avec la promesse de sexe - mais ce n'est pas du sexe. Néanmoins, les cellules nerveuses solidifient ces associations avec l'excitation sexuelle en faisant pousser de nouvelles branches pour renforcer les connexions. Plus vous utilisez le porno, plus les connexions nerveuses se renforcent. Au bout du compte, il se peut que vous ayez *besoin* d'être un voyeur, que vous ayez besoin de cliquer sur des contenus toujours plus nombreux et nouveaux, que vous ayez besoin de porno pour vous endormir ou que vous ayez besoin de rechercher la fin parfaite pour faire le travail.

Comme pour toute substance ou drogue comportementale, le corps développe une immunité et la drogue cesse de soulager complètement les symptômes de manque. Dès que l'utilisateur de porno termine une session, il en veut une autre et rapidement, la faim permanente restant insatisfaite. Le penchant naturel étant l'escalade pour obtenir le rush de dopamine. Cependant, la plupart des utilisateurs en sont empêchés pour l'une ou l'autre des raisons suivantes, voire les deux.

**L'argent:** Ils ne peuvent pas se permettre de s'abonner à des sites pornographiques payants.

**La santé:** le corps ne peut pas tout supporter, que ce soit les montées de dopamine ou les orgasmes. De plus, les orgasmes déclenchent des substances chimiques afin de réduire la poussée de dopamine. Il le faut, c'est comme ça que le corps fonctionne.

Une fois que le petit monstre a quitté votre corps, l'horrible sentiment d'insécurité prend fin. Votre confiance revient, ainsi qu'un merveilleux sentiment de respect de soi, obtenant l'assurance de prendre votre vie en main et l'utilisant comme tremplin pour s'attaquer à d'autres problèmes. C'est l'un des nombreux avantages de se libérer de toute dépendance.

Le mythe du cloisonnement est l'un des nombreux tours que le petit monstre joue à votre esprit. Ces tours rendent plus difficile l'arrêt - en raison de l'impossible satisfaction de la faim permanente - ce qui pousse de nombreux utilisateurs à se tourner vers la cigarette, l'alcool ou même des drogues plus dures pour combler le vide.

Les humains sont des animaux d'évaluation, tant pour eux-mêmes que pour les autres. Regarder du porno avec votre partenaire est insatisfaisant, car vous évaluez tous deux la performance de l'autre par rapport au récit. Voulez-vous avoir Brad Pitt dans votre chambre, même s'il est sur un poster ? Aucune personne ne peut rivaliser avec un harem où chaque "expérience" est jouée, scénarisée, dirigée par des professionnels et immédiatement disponible 24h/24.