# Évitez les Faux Incentives

De nombreux utilisateurs de la méthode de la volonté tentent d'accroître leur motivation en construisant de fausses incitations. Il en existe de nombreux exemples, l'un d'entre eux étant de se récompenser par des cadeaux après avoir évité de regarder du porno pendant un mois. Cette approche semble logique et sensée, mais elle est en fait fausse, car tout utilisateur qui se respecte préfère continuer à regarder du porno tous les jours plutôt que de se récompenser avec un cadeau qu'il s'est lui-même offert. Cela génère des doutes dans l'esprit de l'utilisateur, car non seulement il devra s'abstenir pendant *trente jours*, mais il n'est même pas sûr de *jouir* des jours sans porno. Leur seul plaisir ou leur seule béquille leur a été enlevé ! Tout cela ne fait qu'augmenter l'importance du sacrifice que l'utilisateur a l'impression de faire, qui devient de plus en plus précieux dans son esprit.

Voici d'autres exemples :

- J'arrêterai pour que ça me force à avoir une vie sociale et plus de sexe réel.

- J'arrêterai pour qu'une énergie magique m'aide à surpasser mes concurrents et à obtenir le partenaire que je recherche.

- J'arrêterai pour m'engager à ne pas gaspiller mon énergie et mon enthousiasme avec le porno afin de développer la faim en moi.

Ces affirmations sont vraies, peuvent être efficaces, et vous pourriez finir par obtenir ce que vous voulez - mais réfléchissez-y une seconde. Si vous obtenez ce que vous voulez, une fois la nouveauté passée, vous vous sentirez privé ; si vous ne l'avez pas obtenu, vous vous sentirez malheureux. Dans un cas comme dans l'autre, vous retomberez tôt ou tard dans le même piège.

Le fait de lier l'arrêt du PMO à une fausse incitation ne fait qu'accroître le doute, car si vous n'obtenez pas votre incitation (et même si vous l'obtenez), vous commencerez à avoir des pensées douteuses telles que *"L'arrêt du tabac va-t-il réellement améliorer ma vie ? Si j'arrête et que je n'obtiens pas ce que je veux, ai-je utilisé la méthode correctement ?"* De telles pensées augmentent le sentiment de sacrifice et créent donc des pangs.

Un autre exemple typique sont les pactes en ligne ou sur les forums, ceux-ci ont l'avantage d'éliminer la tentation pendant certaines périodes. Cependant, ils échouent généralement pour les raisons suivantes :

1.  L'incentive est faux, pourquoi voudriez-vous vous arrêter juste parce que d'autres personnes le font ? Tout ce que cela permet, c'est de générer une pression supplémentaire et d'augmenter le sentiment de sacrifice. C'est très bien si tous les utilisateurs veulent sincèrement arrêter à un moment donné - mais vous ne pouvez pas les forcer à arrêter, même si tous le veulent secrètement. Jusqu'à ce qu'ils soient prêts à le faire, un pacte crée une pression supplémentaire, qui ne fait qu'augmenter leur désir de regarder. Ils deviennent ainsi des téléspectateurs secrets, ce qui accroît encore le sentiment de dépendance.

2.  La dépendance à l'égard de l'autre L'utilisation de la méthode de la volonté engendre le sentiment de subir une période de pénitence, pendant laquelle ils attendent que l'envie disparaisse. S'ils cèdent, il y a un sentiment d'échec. Lorsqu'on utilise la méthode de la volonté, l'un des participants au moins va forcément abandonner, fournissant ainsi aux autres participants l'excuse qu'ils attendaient. Ce n'est pas leur faute, ils auraient tenu bon mais "Yannick" les a laissés tomber. La vérité est que la plupart d'entre eux ont déjà triché.

3.  Partager le mérite est l'inverse de la dépendance. Arrêter de consommer du porno procure un merveilleux sentiment d'accomplissement et, si vous le faites seul, les félicitations que vous recevez de vos amis et de vos copains en ligne peuvent vous donner un formidable coup de fouet les premiers jours. Cependant, lorsque tout le monde le fait en même temps, le crédit doit être partagé et le coup de pouce est donc réduit.

4.  Un autre exemple classique est la promesse du gourou. Arrêter vous rendra heureux car vous n'êtes plus engagé dans la lutte acharnée, votre cerveau commence à se recâbler et à retrouver le contrôle de ses impulsions. Cependant, vous devez garder à l'esprit que cela ne fera pas de vous un dieu du sexe ni ne vous fera gagner au loto. Personne, sauf vous, ne se soucie le moins du monde que vous arrêtiez le porno. Vous n'êtes pas une personne faible si vous consommez du porno trois fois par jour et que vous souffrez de PIED, ni une personne forte si vous êtes dépendant et que vous n'en souffrez pas.

Arrêtez de vous faire des illusions. Si l'offre d'emploi de dix mois de travail pour douze mois de salaire par an, ou les risques de réduire la capacité de votre cerveau à faire face au stress et aux tensions quotidiennes, ou de vous mettre en danger d'avoir une érection fiable, ou la torture mentale et physique et l'esclavage à vie ne les ont pas arrêtés, les quelques incitations bidons ci-dessus ne feront pas la moindre différence, ne réussissant qu'à faire paraître le sacrifice pire. Concentrez-vous plutôt sur l'autre côté :

\"Qu'est-ce que ça m'apporte ? Pourquoi ai-je besoin de regarder du porno ?\"

Continuez à regarder l'autre côté de la lutte acharnée et demandez-vous ce que le porno vous apporte. *ABSOLUMENT RIEN.* Pourquoi ai-je besoin de le faire ? *TU N'EN AS PAS BESOIN !,TU NE FAIS QUE TE PUNIR.* C'est un pari de Pascal : vous n'avez presque rien à perdre (excitation déclinante), des chances de faire de gros bénéfices (excitation complète et fiable, bien-être mental et bonheur) et aucune chance de perdre gros.

Pourquoi ne pas déclarer ensuite votre abandon à vos amis et à votre famille ? Cela fera de vous un ex-dépendant ou un ex-usager fier, et non un non-usager heureux et exalté. Cela pourrait effrayer un peu votre partenaire, qui pourrait y voir un stratagème pour avoir plus de sexe, d'une manière un peu new-age. Il peut aussi avoir peur que vous vous transformiez en machine à sexe, c'est difficile à expliquer, à moins qu'il ne soit ouvert d'esprit.

Toute tentative d'amener les autres à vous aider à arrêter de fumer donne plus de pouvoir au petit monstre. Le chasser de votre esprit et l'ignorer totalement a pour effet d'essayer de *ne pas* y penser. Au lieu de cela, soyez attentif, dès que vous repérez les pensées, les indices (seul à la maison) ou les pensées distraites, dites-vous simplement : *"Super, je ne suis plus esclave du porno. Je suis libre et heureux de connaître les différences dans le sexe !"* Cela coupera l'oxygène à la pensée et l'empêchera de brûler vers les pulsions et les envies. À cet égard, la pratique de la méditation de pleine conscience peut être utile pour aider à la dépersonnalisation des pensées.