# Le Moyen Facile d'Arrêter

Ce chapitre contient des instructions concernant le moyen facile d'arrêter le porno. À condition de suivre les instructions, vous constaterez que l'arrêt va de relativement facile à agréable ! À condition que vous suiviez les instructions ci-dessous, il est ridiculement facile d'arrêter le porno, tout ce que vous avez à faire est deux choses.

1.  Prendre la décision de ne plus jamais regarder de porno.

2.  Ne vous morfondez pas. Réjouissez-vous.

Vous vous demandez probablement : "*Pourquoi avoir besoin du reste du livre ? Pourquoi n'avez-vous pas pu le dire dès le départ ?"*  Eh bien, la réponse est que vous auriez fini par vous morfondre et, par conséquent, par changer votre décision. Vous l'avez probablement déjà fait de nombreuses fois.

Comme déjà dit, le porno est un piège subtil et sinistre. Le principal problème de l'arrêt n'est pas la dépendance à la dopamine - qui est certes un problème, mais pas le principal - c'est le lavage de cerveau. Il est donc nécessaire de détruire d'abord tous les mythes et les illusions. Comprenez votre ennemi, connaissez ses tactiques et vous le vaincrez facilement. Après avoir passé une grande partie de ma vie à souffrir d'une dépression noire en essayant d'arrêter le porno, lorsque j'ai finalement réussi à m'échapper, je suis passé directement à zéro sans un seul mauvais moment. C'était agréable même pendant la période de sevrage et je n'ai jamais eu la moindre douleur depuis. Au contraire, c'est l'une des plus belles choses qui me soit arrivée dans la vie.

Ma dernière tentative a été différente. Comme tous les usagers d'aujourd'hui, le problème avait été sérieusement réfléchi dans mon esprit. Jusqu'alors, après un échec, j'avais l'habitude de me consoler en me disant que ce serait plus facile la prochaine fois. Il ne m'était jamais venu à l'esprit que je devrais continuer ainsi pour le reste de ma vie, cette pensée m'a rempli d'horreur et j'ai commencé à réfléchir très profondément à ce sujet.

Plutôt que de lancer inconsciemment le navigateur, j'ai analysé mes sentiments et confirmé ce que je savais déjà. Je n'aimais pas le porno et je le trouvais sale et dégoûtant. J'ai commencé à regarder des non-utilisateurs vivant dans d'autres parties du monde, ou des personnes plus âgées qui n'avaient jamais connu les sites porno. Jusque-là, j'avais toujours considéré les non-utilisateurs comme des personnes insipides, peu sociables et pointilleuses. Cependant, en les examinant lorsqu'ils apparaissaient, ils semblaient être - au mieux - plus forts et plus détendus. Ils semblaient être capables de faire face au stress et aux contraintes de la vie et semblaient apprécier les fonctions sociales plus que les utilisateurs de porno. Ils avaient certainement plus d'éclat et d'entrain que les utilisateurs pornos.

J'ai commencé à parler à des ex-utilisateurs. Jusque-là, j'avais toujours considéré qu'ils avaient été contraints d'abandonner pour des raisons de santé ou de religion et qu'ils aspiraient toujours secrètement à une visite au harem. Quelques-uns m'ont dit : *"On a parfois des frissons, mais ils sont si rares qu'ils ne valent pas la peine de s'en préoccuper. "* La plupart m'ont répondu : *"Ça te manque ? C'est une blague ! La vie ne s'est jamais sentie aussi bien !"* Même si les échecs étaient des chutes pour eux, ils ne se condamnaient pas et les acceptaient sans condition. Comme un entraîneur qui accepte une erreur d'un joueur en or. Parler avec des ex-usagers a détruit un autre mythe que j'avais toujours eu dans mon esprit, à savoir qu'il y avait une faiblesse inhérente en moi, jusqu'à ce que je me rende compte que tout le monde passe par ce cauchemar privé.

En gros, je me suis dit : "Des tas de gens arrêtent maintenant et mènent des vies parfaitement heureuses, je n'avais pas besoin de le faire avant de commencer et je me souviens avoir dû travailler dur pour m'habituer à cette saleté. Quoi qu'il en soit, je n'aimais pas le porno, je détestais tout ce rituel répugnant et je ne voulais pas passer le reste de ma vie en esclave de cette dépendance dégoûtante. Je me suis alors dit ceci :

*"Que vous le vouliez ou non, vous avez terminé votre dernière séance. "*

J'ai su, dès ce moment-là, que je n'aurais plus jamais de séance. Je ne m'attendais pas à ce que ce soit facile, au contraire. J'étais persuadée que je m'étais engagée à vivre des mois de dépression noire et à passer le reste de ma vie à ressentir des douleurs occasionnelles. Au lieu de cela, ce fut un bonheur absolu dès le début.

Il m'a fallu beaucoup de temps pour comprendre pourquoi cela avait été si facile et pourquoi je n'avais pas souffert de ces terrifiants symptômes de manque. La raison en est qu'ils n'existent pas, c'est le doute et l'incertitude qui créent ces symptômes. La belle vérité, ***c'est qu'il est facile d'arrêter la pornographie***, c'est seulement l'indécision et la morosité qui rendent les choses difficiles. Même lorsqu'ils sont dépendants, les utilisateurs peuvent se passer de porno pendant des périodes relativement longues à certains moments. Ce n'est que lorsque vous le voulez, mais que vous ne pouvez pas l'avoir, que vous souffrez.

Par conséquent, la clé pour rendre l'arrêt facile est de le rendre certain et définitif. Ne pas espérer, mais *savoir* que vous avez arrêté, avoir pris la décision. Ne jamais douter ou remettre en question, au contraire, toujours se réjouir ! Si vous pouvez être certain dès le départ, ce sera facile. Mais comment en être certain dès le départ ? C'est pourquoi le reste du livre est nécessaire. Il y a certains points essentiels qui doivent être clairs dans votre esprit avant de commencer :

1.  Réalisez que vous pouvez y arriver. Il n'y a rien de différent en vous et la seule personne qui peut vous faire regarder est vous-même. Pas cette star, qui n'a jamais pensé, dans ses rêves les plus fous, à se faire utiliser pour réduire sa virilité.

2.  Il n'y a absolument rien à abandonner. Au contraire, il y a d'énormes gains positifs à faire. Non seulement vous serez en meilleure santé et plus riche, mais vous profiterez davantage des bons moments et serez moins malheureux pendant les mauvais.

3.  Il n'y a rien de tel qu'un coup d'œil ou une visite. La pornographie est une dépendance à la drogue et une réaction en chaîne. En vous plaignant d'une visite occasionnelle, vous ne ferez que vous punir inutilement.

4.  Ne considérez pas la pornographie comme une habitude "les garçons seront des garçons" qui pourrait vous blesser, mais comme une toxicomanie. Admettez que, que vous le vouliez ou non, **vous avez la maladie** et qu'elle ne disparaîtra pas parce que vous vous enfouissez la tête dans le sable. Rappelez-vous que, comme toutes les maladies invalidantes, non seulement elle dure toute la vie, mais elle s'aggrave de façon exponentielle. Le moment le plus facile pour la guérir est maintenant.

5.  Séparez la maladie - la dépendance neurologique - de l'état d'esprit d'être un consommateur ou non. Tous les consommateurs, s'ils avaient l'occasion de revenir en arrière, avant de devenir dépendants, sauteraient sur l'occasion. Vous avez cette possibilité aujourd'hui ! N'y pensez même pas comme à un "abandon".

En prenant la décision finale de faire votre dernière visite, vous serez déjà un non-utilisateur. Un utilisateur est l'un de ces pauvres malheureux qui traversent la vie en se détruisant avec du porno. Un non-utilisateur est quelqu'un qui ne le fait pas. Une fois que tu as pris cette décision finale, tu as déjà atteint ton objectif. Réjouissez-vous de ce fait, ne restez pas à vous morfondre en attendant que la dépendance chimique disparaisse. Sortez et profitez de la vie immédiatement. La vie est merveilleuse même lorsque vous êtes dépendant et chaque jour sera bien meilleur lorsque vous ne le serez plus.

La clé pour faciliter l'arrêt du porno est d'être certain de réussir à s'abstenir complètement pendant la période de sevrage (trois semaines maximum). Si vous êtes dans le bon état d'esprit, vous trouverez cela ridiculement facile.

À ce stade, si vous avez ouvert votre esprit comme demandé au début, vous avez déjà décidé de vous échapper. Vous devriez maintenant éprouver des sentiments d'excitation, comme un chien qui tend sa laisse, impatient de descendre les toboggans aquatiques pornographiques DeltaFosB. Si vous avez un sentiment de malheur, c'est pour l'une des raisons suivantes :

1.  Quelque chose n'a pas pris forme dans votre esprit. Relisez les cinq points ci-dessus et demandez-vous si vous les croyez vrais. Si vous doutez d'un point, relisez les sections appropriées du livre.

2.  Vous avez peur de l'échec lui-même. Ne vous inquiétez pas, continuez à lire et vous réussirez. Tout le commerce du porno sur Internet est un tour de passe-passe d'une ampleur gigantesque. Les personnes intelligentes se laissent prendre au piège de la confiance, mais seul un imbécile, une fois qu'il a découvert le piège, continue à se faire des illusions.

3.  Vous êtes d'accord avec tout mais vous êtes toujours malheureux. Ne le soyez pas ! Ouvrez les yeux, il se passe quelque chose de merveilleux. Vous êtes sur le point de vous échapper de la prison, il est essentiel de commencer avec le bon état d'esprit : *"C'est merveilleux que je sois un non-usager !"*

Tout ce qu'il faut faire maintenant, c'est vous maintenir dans cet état d'esprit pendant la période de sevrage, et les prochains chapitres traitent de points spécifiques pour vous permettre de le faire. Après la période de sevrage, vous n'aurez plus besoin de penser de cette façon, vous le penserez automatiquement, le seul mystère dans votre vie étant de savoir pourquoi vous ne l'avez pas vu avant. Toutefois, deux avertissements importants.

- Retardez votre projet de faire votre dernière visite jusqu'à ce que vous ayez terminé le livre.

- Une période de retrait pouvant aller jusqu'à trois semaines a été mentionnée à de nombreuses reprises, ce qui peut être source de malentendus. Premièrement, vous pouvez inconsciemment penser que vous devez souffrir pendant trois semaines. Ce n'est pas le cas. Deuxièmement, évitez le piège qui consiste à penser : "Je dois m'abstenir pendant trois semaines et tout ira bien". Rien de magique ne se produira au bout de trois semaines, vous ne vous sentirez pas soudainement comme un non-consommateur, car les consommateurs ne se sentent pas vraiment différents. Si vous vous morfondez à propos de l'arrêt pendant les trois semaines, il est fort probable que vous vous morfondrez encore après ces trois semaines. En résumé, si vous pouvez commencer dès maintenant en disant *"Je ne vais plus jamais consommer, n'est-ce pas merveilleux ? "*, après trois semaines, toute tentation disparaîtra. Alors que si vous dites, *"Si seulement je pouvais survivre à ces trois semaines sans porno "*, vous mourrez d'envie d'une visite au harem après ces trois semaines.

Pensez-y de cette façon : votre cerveau veut maintenir le status quo, l'ordre établi, donc si vous êtes convaincu que vous perdez quelque chose de bon en arrêtant la dépendance au porno, vous vous sentirez évidemment horrible. Il est impossible de vous forcer à vous sentir d'une certaine façon si votre cerveau n'y croit pas. C'est pourquoi il est important de se donner la peine de supprimer l'illusion que la pornographie vous apporte quelque chose. C'est ainsi que vous saurez que vous ne sacrifiez rien.

Les dysfonctionnements sexuels ont beaucoup à voir avec votre cerveau et votre état d'esprit. Le porno sur Internet reconnecte le circuit de récompense de votre cerveau et donne à votre esprit un état d'esprit de "doute". Ce doute sur soi entraînera sans aucun doute un dysfonctionnement sexuel. Avoir tout le désir dans la partie supérieure, mais supporter l'absence d'excitation dans la partie inférieure est la pire chose qui puisse arriver à votre état d'esprit. La libido allant de pair avec la romance est l'élixir de jeunesse que vous pouvez avoir jusqu'à votre mort. Vous gardez les probabilités élevées en arrêtant  le porno, mais ce n'est pas le seul ou le principal gain. C'est votre libération de l'esclavage !