# La Période de Sevrage

Jusqu'à trois semaines après votre dernière séance, vous pouvez être soumis à une période de sevrage. Il s'agit de deux facteurs distincts, mais séparés :

1.  La sensation de manque de dopamine. Une sensation de vide, d'insécurité, semblable à la faim, identifiée comme une fringale ou un sentiment de " quelque chose que je dois faire ".

2.  Les déclencheurs psychologiques de certains stimuli externes tels que les publicités, la navigation en ligne, les conversations téléphoniques, etc.

Si l'on ne parvient pas à comprendre et à différencier ces deux facteurs distincts, il est difficile de réussir en utilisant la méthode de la volonté, et c'est la raison pour laquelle beaucoup de ceux qui y parviennent finissent par retomber dans le piège. Bien que le manque de dopamine ne provoque pas de douleur physique, il ne faut pas sous-estimer sa puissance. Nous parlons de "douleurs de la faim" lorsque nous nous privons de nourriture pendant une journée ; il peut y avoir des gargouillements d'estomac, mais il n'y a pas de douleur physique. Malgré tout, la faim est une force puissante et nous sommes susceptibles de devenir très irritables lorsque nous sommes privés de nourriture. C'est comme lorsque notre corps a besoin d'une poussée de dopamine, à la différence qu'il a besoin de nourriture et non de poison. Avec un bon état d'esprit, la sensation de manque est facilement surmontée et disparaît très rapidement.

Après quelques jours d'abstinence par la méthode de la volonté, le besoin de bouffées de dopamine disparaît rapidement. C'est le deuxième facteur - le lavage de cerveau - qui pose problème. L'usager a pris l'habitude de soulager sa sensation de manque à certains moments et à certaines occasions, ce qui provoque une association d'idées (*"J'ai la gaule, je dois regarder du porno "* ou "*Je suis au lit avec mon ordinateur portable et je dois faire une séance pour me sentir heureux*"). L'effet est mieux illustré par un exemple : Vous avez une voiture et le clignotant est à gauche, mais sur votre prochaine, il est à droite. Vous savez qu'il est à gauche, mais pendant quelques semaines, vous allumez les essuie-glaces lorsque vous voulez indiquer.

S'arrêter est similaire, pendant les premiers jours, le mécanisme de déclenchement fonctionnera à certains moments. Vous penserez à l'envie d'une séance, c'est pourquoi il est essentiel de contrer le lavage de cerveau dès le départ et de faire disparaître rapidement ces indices et ces déclencheurs. Avec la méthode de la volonté, parce que l'utilisateur croit qu'il fait un sacrifice, il se morfond et attend que les envies s'en aillent ; loin de supprimer ces mécanismes de déclenchement, il les augmente au contraire. De même, dans le cadre de la méthode du gourou, l'utilisateur commence à se demander quand il va devenir un Dieu et exige même qu'il n'ait pas ces pensées, ce qui ouvre la voie au dégoût de soi et à l'échec.

Un déclencheur commun est le temps passé seul, en particulier lors d'événements sociaux avec des amis. L'ex-consommateur qui utilise d'autres méthodes pour arrêterle porno est déjà malheureux parce qu'il se sent privé de sa béquille ou de son plaisir habituel. Ses amis sont avec leur partenaire et agissent de manière intime. L'utilisateur est soit célibataire, soit n'obtient rien de son partenaire, et ne profite plus de ce qui devrait être une occasion sociale agréable. Les toboggans cérébraux existants les conduisent vers le porno, ce qui est plus facile que d'essayer de courtiser son partenaire.

Comme ils associent le droit au sexe à leur bien-être, ils subissent maintenant un triple coup et le lavage de cerveau est en fait accru. S'ils sont résolus et peuvent tenir assez longtemps, ils finissent par accepter leur sort et reprendre le cours de leur vie. Cependant, une partie du lavage de cerveau demeure, le deuxième aspect le plus pathétique étant que l'utilisateur a arrêté la PMO mais, même après plusieurs années, il a toujours envie d'une "dernière visite au harem" à certaines occasions. Ils se languissent d'une illusion qui n'existe que dans leur esprit et se torturent inutilement.

Même sous EasyPeasy, la réaction aux déclencheurs est la défaillance la plus courante. L'ex-utilisateur a tendance à considérer le porno sur Internet comme une sorte de placebo ou de pilule de sucre. Il se dit : "*Je sais que le porno ne m'apporte rien, mais si je pense qu'il m'apporte quelque chose, alors, à certaines occasions, il me sera utile*. Une pilule de sucre, bien que n'apportant aucune aide physique réelle, peut être une aide psychologique puissante pour soulager des symptômes authentiques et est donc bénéfique. Le porno sur Internet et la masturbation habituelle ne sont cependant pas des pilules de sucre. Pourquoi ? Le porno crée les symptômes qu'il soulage et cesse de les soulager complètement.

Vous aurez peut-être plus de facilité à comprendre l'effet si vous le comparez à celui d'un non-consommateur ou d'un consommateur qui a réussi à arrêter pendant plusieurs années. Prenons le cas d'un utilisateur qui perd son partenaire. Il est assez courant, dans ces moments-là, de dire, avec les meilleures intentions du monde : "*Faites une visite au harem, ça vous aidera à vous calmer.*" Si l'offre est acceptée, elle n'aura pas d'effet calmant car il n'y a pas de dépendance à la dopamine et donc pas de sensation de manque. Au mieux, cela ne fera que lui donner un coup de fouet psychologique momentané.

Même après la fin de la séance, la tragédie initiale est là. En fait, elle s'accentuera parce que la personne souffre maintenant d'une sensation de manque, le choix étant de l'endurer ou de se soulager en refaisant des glissades d'eau pour recommencer la chaîne de la misère. Tout ce que le porno a apporté, c'est un stimulant psychologique éphémère, le même que celui que l'on aurait pu obtenir avec un livre ou un bon film, même mauvais. De nombreux non-utilisateurs et ex-utilisateurs sont redevenus dépendants à la suite de telles occasions. Que ce soit bien clair dans votre esprit : Vous n'avez pas besoin de la poussée de dopamine et vous vous torturez davantage en continuant à la considérer comme une sorte d'accessoire ou de stimulant. Il n'est pas nécessaire d'être malheureux.

Les orgasmes ne permettent pas d'établir de bonnes relations ; la plupart du temps, ils les ruinent. Rappelez-vous également qu'il n'est pas tout à fait vrai que ceux qui font des démonstrations d'affection en public apprécient chaque occasion. L'intimité est mieux appréciée en privé, où les partenaires peuvent répondre sans gêne. Il n'est pas nécessaire d'être accro à la dopamine induite par l'orgasme. Si cela se produit comme un résultat naturel d'une série d'événements de la vie, c'est bien, mais profitez de l'occasion et de la vie sans cela.

Après avoir abandonné le concept du porno en tant que plaisir en soi, de nombreux utilisateurs pensent "*Si seulement il y avait du porno propre sur Internet*". Le porno soft propre existe, et tous ceux qui s'y essaient découvrent rapidement que c'est une perte de temps. Mettez au clair dans votre esprit que la seule raison pour laquelle vous avez utilisé du porno est le besoin de dopamine. Une fois débarrassé de ce besoin de dopamine, vous n'aurez plus besoin de visiter votre harem en ligne.

Que les frissons soient dus à de véritables symptômes de sevrage de la dopamine ou à des mécanismes de déclenchement ou de repérage, acceptez-les. La douleur physique est inexistante et avec le bon état d'esprit, ce ne sera pas un problème. Ne vous inquiétez pas du manque, la sensation elle-même n'est pas mauvaise. C'est l'association avec le désir et le sentiment de refus qui est le problème. Au lieu de vous morfondre sur ça, reconnaissez-le : "*Je sais ce que c'est, c'est la sensation de manque du porno. C'est ce dont souffrent les utilisateurs toute leur vie et qui les rend dépendants. Les non-utilisateurs ne souffrent pas de ces douleurs, c'est un autre des nombreux maux de cette dépendance au mensonge. N'est-ce pas merveilleux que je purge ce mal de mon cerveau !"*

En d'autres termes, pendant les trois prochaines semaines, vous subirez un léger traumatisme dans votre corps, mais pendant ces semaines et pour le reste de votre vie, quelque chose de merveilleux se produira. Vous vous débarrasserez d'une terrible maladie, dont les avantages dépasseront de loin le léger traumatisme, et vous apprécierez les symptômes de sevrage. Elles deviendront des moments de plaisir, comme un jeu passionnant pour affamer le ver des cassettes pornographiques qui vit dans votre estomac. Vous devez l'affamer pendant trois semaines tout en essayant de vous inciter à vous mettre au lit pour le maintenir en vie.

Parfois, il essaiera de te rendre malheureux. Parfois, tu seras pris au dépourvu. Vous recevrez une URL pornographique ou tomberez sur quelque chose en ligne et oublierez que vous avez arrêté, un léger sentiment de privation lorsque vous vous en souviendrez. Préparez-vous à ces astuces à l'avance et, quelle que soit la tentation, mettez-vous dans la tête qu'elle n'est là qu'à cause du monstre qui est dans votre corps et que chaque fois que vous résistez à la tentation, vous avez porté un nouveau coup moral dans la bataille.

Quoi que vous fassiez, n'essayez pas d'oublier le porno. C'est l'une des choses qui causent aux PMOiens utilisant la méthode de la volonté des heures de dépression. Ils essaient de passer à travers chaque jour en espérant qu'ils finiront par l'oublier. C'est comme ne pas pouvoir dormir : plus on s'inquiète, plus c'est difficile. Quoi qu'il en soit, vous ne pourrez pas l'oublier. Pendant les premiers jours, le "petit monstre" vous le rappellera sans cesse et vous ne pourrez pas l'éviter. Tant qu'il y aura des ordinateurs portables, des smartphones et des magazines autour de vous, vous aurez des rappels constants.

Le fait est que vous n'avez pas besoin d'oublier, il ne se passe rien de mal. En fait, il se passe quelque chose de merveilleux et d'admirable, et même si vous y pensez des milliers de fois par jour, **savez chaque instant, rappelez-vous combien il est merveilleux d'être à nouveau libre. Rappelez-vous la joie pure de ne plus avoir à vous torturer.** Comme nous l'avons dit précédemment, vous constaterez que les douleurs deviennent des moments de plaisir et vous serez surpris de la rapidité avec laquelle vous oublierez le porno.

Quoi que vous fassiez, *ne doutez pas de votre décision*. Si vous commencez à douter, vous commencerez à vous morfondre, et cela ne fera qu'empirer. Au lieu de cela, utilise ce moment de déprime et transforme-le en un coup de pouce. Si la cause est la dépression, rappelez-vous que le porno en est la *cause*. Si un ami vous transmet une URL, soyez fier de dire : "*Je suis heureux de dire que je n'ai plus besoin de ça*". Cela les blessera, mais lorsqu'ils verront que cela ne vous dérange plus, ils seront à moitié prêts à vous rejoindre.

**Rappelez-vous : vous avez des raisons incroyablement puissantes d'arrêter en premier lieu.** Rappelez-vous les coûts et demandez-vous si vous voulez vraiment risquer le mauvais fonctionnement de votre corps, de votre esprit, et le simple fait que vous vivrez sous un charme pour le reste de votre vie. Soyez attentif aux efforts du petit monstre pour minimiser les risques et surtout, rappelez-vous que la sensation n'est que temporaire, et que chaque instant est un instant de plus vers votre objectif.

Certains utilisateurs craignent de devoir passer le reste de leur vie à inverser les "déclencheurs automatiques". En d'autres termes, ils croient qu'ils devront passer leur vie à se convaincre qu'ils n'ont pas besoin de porno en recourant à la psychologie. Ce n'est pas le cas, rappelez-vous que l'optimiste voit la bouteille à moitié pleine et que le pessimiste la voit à moitié vide. Dans le cas de la pornographie, la bouteille est vide et l'utilisateur la voit pleine. Il n'y a aucun avantage à consommer du porno sur Internet. C'est l'utilisateur qui a subi un lavage de cerveau lui faisant croire qu'il y en a. Une fois que tu auras commencé à te dire que tu n'as pas besoin ou envie de porno, en très peu de temps tu n'auras même plus besoin de le dire, car tu verras toi-même la belle vérité. C'est la dernière chose que tu dois faire ; assure-toi que ce n'est pas la dernière chose que tu fais.