# Juste un Coup d'Oeil, bis

C'est la perte de nombreux utilisateurs de la méthode de la volonté. Ils passent trois ou quatre jours sans se priver d'un petit coup d'œil pour tenir le coup. Ils ne se rendent pas compte de l'effet dévastateur que cela a sur leur moral.

Pour la plupart des utilisateurs, leur premier coup d'œil sur le site porno avec leur harem en ligne n'a pas été aussi bon que le sexe avec une personne réelle. Les clips qui sont propres sont rares, ce qui donne un coup de fouet à leur esprit conscient. Ils se disent : "*Bien, ce n'était pas si agréable que ça. Je perds l'envie et je ne suis pas tellement intéressé par les trucs choquants.*" En fait, c'est l'inverse qui se produit. Mettez-vous bien dans la tête que le plaisir de l'orgasme n'était pas la raison pour laquelle vous avez arrêté le porno. Si les utilisateurs n'étaient là que pour l'orgasme, ils ne regarderaient jamais plus d'un clip. La seule raison pour laquelle vous aviez besoin du porno était de nourrir ce petit monstre. Imaginez, après avoir été affamé pendant quatre jours, combien ce seul coup d'oeil a dû être précieux pour lui. Votre esprit conscient n'est pas au courant, mais le fix que votre corps a reçu est communiqué à votre subconscient, et toute votre préparation solide sera mise à mal. Il y aura une petite voix au fond de votre esprit qui dira qu'en dépit de toute logique, les séances sont précieuses et que vous en voulez une autre.

Ce petit coup d'œil a deux effets néfastes :

1.  Il maintient le petit monstre en vie dans votre corps.

2.  Pire encore, il maintient le gros monstre en vie dans votre esprit. Si tu as eu le "dernier coup d'œil", il sera plus facile d'avoir le suivant.

Le porno est un piège à souris sans fromage, seulement du poison. En utilisant la volonté, vous devez vous convaincre de ne pas attraper le fromage, mais EasyPeasy vous permet de voir que c'est du poison. Vous n'avez pas besoin de l'éviter, il suffit de ne pas y aller.

Surtout, rappelez-vous :

*C'est en jetant un seul coup d'oeil que les gens deviennent dépendants au départ.*