# Sera-t-il plus Difficile pour Moi ?

Il existe une infinité de combinaisons de facteurs qui déterminent la facilité avec laquelle chaque utilisateur peut arrêter le porno. Pour commencer, chacun d'entre nous a son propre caractère, sa carrière, ses circonstances personnelles, son timing, son métabolisme, etc. Certaines professions peuvent rendre l'abandon plus difficile que d'autres, mais si le lavage de cerveau est supprimé, il n'en est pas forcément ainsi. Prenons les quelques exemples suivants.

Il arrive que les membres de la profession médicale aient des difficultés. Nous pensons que cela devrait être plus facile pour les médecins parce qu'ils sont plus conscients des effets, mais bien que cela fournisse des raisons plus fortes d'arrêter, cela ne le rend pas plus facile à accomplir. Les raisons sont les suivantes :

1.  La conscience constante des risques pour la santé crée la peur, l'une des conditions nécessaires pour soulager les symptômes de sevrage.

2.  Le travail d'un médecin est extrêmement stressant et il n'est généralement pas en mesure d'évacuer le stress supplémentaire de l'état de manque tout en travaillant.

3.  Ils subissent le stress supplémentaire de la culpabilité, car ils estiment qu'ils devraient montrer l'exemple au reste de la population. Cela leur met davantage de pression et augmente le sentiment de privation.

Après une dure journée de travail, lorsque leur stress est momentanément soulagé par la pornographie, cette séance est incorrectement associée au soulagement ressenti. À cause de cette association d'idées erronée, le porno s'attribue tout le mérite de la situation, devenant soudainement très précieux lorsqu'on arrête le porno et qu'on passe par les affres du sevrage. Il s'agit d'une forme de consommation occasionnelle qui s'applique à toute situation où l'utilisateur est contraint de s'abstenir pendant de longues périodes. Dans le cadre de la méthode de la volonté, l'utilisateur est malheureux parce qu'il est privé et ne profite pas de la fatigue et du sommeil qui viennent après une séance. Son sentiment de perte est fortement accru. Toutefois, si l'on parvient d'abord à supprimer le lavage de cerveau et la morosité liés au porno, il est possible de profiter de la pause et du sommeil, même si le corps a besoin des transmetteurs d'amines - sérotonine, norépinéphrine et dopamine.

Une autre situation difficile est l'ennui, en particulier lorsqu'il est associé à des périodes de stress. Les exemples typiques sont les étudiants et les parents célibataires, le travail étant à la fois stressant et monotone. Lors d'une tentative d'arrêt par la méthode de la volonté, la personne seule a de longues périodes pendant lesquelles elle se morfond sur sa "perte", ce qui augmente les sentiments de dépression. Là encore, cela peut être facilement surmonté si votre état d'esprit est correct. Ne vous inquiétez pas du fait que l'on vous rappelle sans cesse que vous avez arrêté le porno. Profitez de ces moments pour vous réjouir du fait que vous vous êtes débarrassé de ce monstre maléfique.

Si vous avez un état d'esprit positif, ces douleurs se transformeront en moments de plaisir. N'oubliez pas que tout utilisateur, quels que soit son âge, son sexe, son intelligence ou sa profession, peut trouver facile et agréable d'arrêter, à condition **de suivre toutes les instructions**.

## Principales raisons de l'échec

Il y a deux raisons principales à l'échec. La première est l'influence d'un stimulus externe : une publicité, un article de presse en ligne, la navigation sur Internet, etc. Ils se retrouvent dans un moment de faiblesse, ou même deviennent jaloux lorsqu'ils voient de l'intimité dans des scénarios sociaux. Ce sujet a déjà été longuement discuté. Profitez de ce moment pour vous rappeler qu'il n'y a pas de visite ou de coup d'œil unique. Réjouissez-vous d'avoir brisé la chaîne de l'esclavage mental. Rappelez-vous que l'utilisateur vous envie et que vous devriez avoir pitié de lui, car il en a besoin.

L'autre raison est de passer une mauvaise journée. Mettez-vous bien dans la tête avant de commencer que, que vous soyez un consommateur ou non, vous aurez de bons et de mauvais jours. Il pleut aussi bien pour le pape que pour le meurtrier. La vie est relative et vous ne pouvez pas avoir des hauts sans des bas. Le problème avec la méthode de la volonté, c'est que dès que le consommateur a une mauvaise journée, il commence à se morfondre pour une visite au "harem", ce qui aggrave encore le problème. Le non-utilisateur est mieux équipé pour gérer le stress et les tensions, non seulement physiquement mais aussi mentalement. Si vous passez une mauvaise journée pendant la période de sevrage, prenez le problème à bras le corps ; rappelez-vous que les mauvais jours existaient lorsque vous étiez dépendant, sinon vous n'auriez pas décidé d'arrêter. Au lieu de vous morfondre, reconnaissez-les plutôt : *"D'accord, aujourd'hui n'est pas très bon, mais le porno n'y changera rien. Demain sera meilleur et au moins j'ai un bonus merveilleux, je me suis débarrassé de cette affreuse dépendance "*.

Lorsque vous êtes un utilisateur de porno, vous devez bloquer votre esprit aux aspects négatifs du porno. Les utilisateurs n'ont jamais de brouillard cérébral, ils sont juste "un peu déprimés". Lorsque tu as les inévitables problèmes de la vie et que tu as envie de porno, es-tu heureux et joyeux ? Bien sûr que non. Une fois que vous avez arrêté, la tendance est de mettre tout ce qui ne va pas sur le compte du fait que vous avez arrêté.

Si le travail vous stresse, vous vous dites : "*Dans des moments pareils, j'aurais fait une séance*". C'est vrai, mais ce qu'on oublie surtout, c'est que le porno n'a pas résolu le problème, et que vous ne faites que vous punir en vous morfondant pour des béquilles illusoires. Vous créez une situation impossible, malheureux parce que vous ne pouvez pas vous masturber devant du porno, mais vous serez encore plus malheureux si vous le faites. *Vous savez que vous avez pris la bonne décision en l'arrêtant, alors pourquoi vous punir en doutant de votre décision?*

N'oubliez pas qu'une approche mentale positive est essentielle - toujours.
