# Les Substituts

Parmi les exemples de substituts, citons le fait de se limiter aux magazines pornographiques, aux images statiques sur Internet, aux régimes pornographiques, etc. **N'UTILISEZ AUCUN D'EUX.** Ils rendent la chose plus difficile, pas plus facile. Si vous avez une frousse et que vous utilisez un substitut, cela ne fera que prolonger la frousse, la rendant plus difficile. Ce que vous dites vraiment, c'est que vous avez besoin du porno pour combler le vide. Ce sera comme céder à un pirate de l'air ou à une crise de colère d'un enfant, ce qui ne fera qu'entretenir la sensation et prolonger la torture. De toute façon, les substituts ne soulageront pas l'envie, ils ne féront qu'éloigner la faim. Votre besoin est un besoin d'acides aminés dans le cerveau, et tout ce que cela fera, c'est vous faire penser au porno. Rappelez-vous ces points :

1.  Il n'y a pas de substitut au porno.

2.  Tu n'as pas besoin de porno. Ce n'est pas de la nourriture, c'est du poison. Quand les douleurs arrivent, rappelle-toi que ce sont les consommateurs qui souffrent des douleurs de manque, pas les non-utilisateurs. Vois-les pour ce qu'ils sont, un autre mal de la drogue. Voyez-les comme la mort d'un monstre.

3.  Le porno sur Internet crée le vide ; il ne le remplit pas. Plus vite vous apprendrez à votre cerveau que vous n'avez pas besoin de regarder, plus vite vous serez libre. En particulier, évitez tout ce qui ressemble à du porno, comme les magazines pour hommes, les films, les romans d'amour et les publicités. Il ne s'agit pas d'être fermé d'esprit, il est normal de parler de romance et de sexe, mais pas de porno. Il y a toujours moyen de trouver quand et où faire de la discrimination. Il est vrai qu'une petite proportion d'utilisateurs qui tentent d'arrêter de consommer du porno softcore ou des régimes pornographiques y parviennent (de leur propre point de vue) et attribuent leur succès à cette consommation. Cependant, ils cessent de fumer *malgré* leur consommation et non à cause d'elle. Il est regrettable que beaucoup recommandent encore ces mesures.

Ce n'est pas surprenant car si vous ne comprenez pas pleinement le piège de la pornographie, un régime ou un substitut doux semble très logique. Il repose sur la conviction que lorsque vous tentez d'arrêter la pornographie, vous avez deux ennemis puissants à vaincre :

- Rompre avec l'habitude.

- Survivre aux terribles douleurs physiques du sevrage.

Si vous avez deux ennemis puissants à vaincre, il est raisonnable de ne pas les combattre simultanément mais un par un. La théorie veut donc que lorsque vous arrêtez de consommer du porno, vous réduisiez votre consommation à une fois par semaine ou vous utilisiez du porno sans danger. Puis, une fois l'habitude perdue, réduisez progressivement l'offre, en vous attaquant ainsi à chaque ennemi séparément.

Cela semble logique mais repose sur des informations erronées. Le porno n'est pas une habitude, mais une dépendance à la dopamine, et la douleur physique réelle du sevrage est presque imperceptible. Ce que vous essayez de faire en arrêtant de fumer, c'est de tuer les monstres dans votre corps et votre cerveau le plus rapidement possible. Les techniques de substitution ne font que prolonger la vie du petit monstre, ce qui prolonge le lavage de cerveau. EasyPeasy vous permet d'arrêter immédiatement, en tuant le lavage de cerveau avant votre dernière session. Le petit monstre sera bientôt mort, et même s'il est en train de mourir, il ne sera pas plus un problème qu'il ne l'était lorsque vous étiez utilisateur.

Réfléchissez, comment pouvez-vous guérir la dépendance à une drogue en recommandant cette même drogue ? Il existe de nombreuses histoires en ligne sur des personnes qui ont cessé de consommer du porno pur et dur sur Internet, mais qui sont accrochées à des alternatives "sûres", après s'être laissées convaincre par les justifications de leur petit monstre. Ne vous laissez pas tromper par le fait que le porno sans danger n'est pas affreux - tout comme le premier clip à haute vitesse. Tous les substituts ont exactement les mêmes effets que n'importe quel porno. Certains se mettent même à manger, mais bien que le sentiment de vide que procure l'envie d'une séance soit indiscernable de la faim de nourriture, l'un ne satisfait pas l'autre. En fait, s'il y a quelque chose qui est conçu pour vous donner envie de porno, c'est bien de vous gaver de nourriture. Comme nous l'avons expliqué précédemment, les régimes porno et le porno sans danger ne feront que vous placer au milieu de la lutte acharnée, la résistance à la tentation étant si ennuyeuse que vous vous sentirez soulagé de visiter votre harem en ligne préféré.

Le principal mal des substituts est de prolonger le vrai problème, le lavage de cerveau. Avez-vous besoin d'un substitut pour la grippe lorsqu'elle sera terminée ? Bien sûr que non. En disant que vous avez besoin d'un substitut pour le porno, vous dites en réalité que vous faites un sacrifice. La dépression associée à la méthode de la volonté est causée par le fait que l'utilisateur croit qu'il fait un sacrifice. Tout ce que vous ferez, c'est de substituer un problème à un autre. Il n'y a aucun plaisir à se gaver de nourriture, de cigarettes ou d'alcool. Vous ne ferez que grossir, vous serez malheureux et en un rien de temps, vous serez de retour à la drogue.

Les utilisateurs occasionnels ont du mal à se défaire de l'idée qu'ils sont privés de leur petite récompense, comme ceux qui n'ont pas le droit d'aller en ligne pendant une période donnée, lors d'un voyage, d'un événement familial, etc. Certains disent : "*Je ne saurais pas comment me détendre si ce n'était pas pour le porno*". Cela prouve bien que, souvent, la pause est prise non pas parce que l'utilisateur en a besoin ou même envie, mais parce que le dépendant -- ce qu'il est -- a désespérément besoin de gratter la démangeaison.

N'oubliez pas que les séances de porno n'ont jamais été de véritables récompenses. Elles équivalaient à porter des chaussures serrées pour avoir le plaisir de les enlever. Donc, si vous sentez que vous avez besoin d'une petite récompense, laissez cela être votre substitut ; pendant que vous travaillez, portez des chaussures ou des sous-vêtements d'une taille trop petite, et ne vous autorisez pas à les enlever avant votre pause, puis vivez le merveilleux moment de relaxation et de satisfaction lorsqu'ils sont enlevés. Vous pensez peut-être que ce serait plutôt stupide. Vous avez tout à fait raison. Il peut être difficile de visualiser en restant dans le piège, mais c'est ce que font les utilisateurs. Il est également difficile d'imaginer que vous n'aurez bientôt plus besoin de cette petite "récompense" et que vous regarderez bientôt vos amis qui sont encore dans le piège avec une véritable pitié et que vous vous demanderez pourquoi ils n'en voient pas l'utilité.

Cependant, si vous continuez à vous faire croire que la visite du harem en ligne était une véritable récompense, ou que vous avez besoin d'un substitut, vous vous sentirez privé et malheureux. Il y a de fortes chances que vous finissiez par retomber dans le piège dégoûtant. Si vous avez besoin d'une véritable pause, comme c'est le cas des femmes au foyer, des enseignants, des médecins et d'autres travailleurs, vous en profiterez bientôt encore plus, car vous n'aurez pas à vous rendre dépendant. N'oubliez pas que vous n'avez pas besoin d'un substitut. Les frissons sont un besoin de dopamine et disparaîtront bientôt. Laissez-vous guider par ce principe pendant les prochains jours et profitez de l'occasion pour débarrasser votre corps et votre esprit de l'esclavage et de la dépendance.