# Comment Éviter les Situations de Tentation

Jusqu'à présent, les conseils ont été directs et vous ont demandé de les considérer comme des instructions plutôt que des suggestions. Ces conseils sont fondés sur des raisons solides et pratiques, et ces raisons ont été étayées par des milliers d'études de cas. Quant à la question de savoir s'il faut ou non essayer d'éviter la tentation, ce n'est pas le cas. Chaque utilisateur devra décider pour lui-même. Cependant, deux suggestions utiles peuvent être faites pour vous aider dans ce processus. C'est la crainte d'une future crise de manque qui nous pousse à utiliser du porno pour le reste de notre vie, et cette crainte se compose de deux phases distinctes.

**Première phase - "*Comment puis-je survivre sans porno?*"**

Cette peur est le sentiment de panique que ressent l'utilisateur lorsqu'il est célibataire ou qu'il a un partenaire asexué, peu intéressé ou indisponible. Cette peur n'est pas causée par le manque mais par la peur psychologique de la dépendance, de l'incapacité à survivre sans sexe et sans orgasme. Elle atteint son paroxysme lorsque vous êtes sur le point d'arrêter le porno, lorsque la sensation de manque est au plus bas. C'est la peur de l'inconnu, le genre de peur qu'ont les gens lorsqu'ils apprennent à plonger.

Le plongeoir est haut d'un demi-mètre mais semble être haut de quatre. L'eau est profonde de quatre mètres mais semble être d'un demi-mètre. Il faut du courage pour se lancer, convaincu que l'on va se casser la tête. Le lancement est la partie la plus difficile, si vous trouvez le courage de le faire, le reste est facile ! Cela explique pourquoi de nombreux usagers au caractère bien trempé n'ont jamais essayé d'arrêter, ou ne peuvent survivre que quelques jours lorsqu'ils le font. En fait, il y a des utilisateurs qui suivent un régime porno et qui, lorsqu'ils décident d'arrêter, s'adonnent à la frénésie et passent à des clips plus violents plus rapidement que s'ils n'avaient pas décidé d'arrêter. Cette décision provoque la panique, ce qui est stressant et déclenche l'envie de faire un tour au harem. Mais maintenant, vous ne pouvez plus en avoir, ce qui entraîne des pensées de privation et un stress accru.

Le déclencheur s'active rapidement lorsque la mèche saute et que vous lancez le navigateur. Ne vous inquiétez pas, la panique est juste psychologique. C'est la peur dont vous êtes dépendant. La belle vérité est que vous ne l'êtes pas, même si vous êtes encore dépendant. Ne paniquez pas et lancez-vous.

**Phase deux - Peur à plus long terme**

La deuxième phase est à long terme et implique la peur que certaines situations ne soient pas agréables à l'avenir ou que vous ne puissiez pas faire face à un traumatisme sans porno. Ne vous inquiétez pas, si vous pouvez vous lancer, vous constaterez que c'est le contraire qui se produit. L'évitement de la tentation elle-même se divise en deux catégories.

1.  "*Je vais m'inscrire à un régime porno d'une fois tous les quatre jours. Je me sentirai plus en confiance en sachant que je peux aller en ligne si cela devient difficile. Si j'échoue, ce n'est pas grave, j'ajouterai simplement des jours supplémentaires à mon prochain cycle.*"

    Le taux d'échec des personnes qui procèdent ainsi est **beaucoup plus élevé** que celui des personnes qui abandonnent purement et simplement. Cela est principalement dû au fait que si vous passez un mauvais moment pendant la période de sevrage, il est facile de sauter sur le navigateur et de visiter le harem avec les excuses ci-dessus. Si vous avez l'indignité d'enfreindre clairement vos propres règles comme une vitre brisée, vous êtes plus susceptible de surmonter la tentation. De toute façon, la douleur serait probablement déjà passée si vous l'aviez retardée. Cependant, la principale raison du taux d'échec élevé dans ces cas est que l'utilisateur ne s'est pas senti complètement déterminé à arrêter dès le départ. Rappelez-vous que les deux éléments essentiels pour réussir sont :

    - La certitude.

    - "N'est-ce pas merveilleux que je n'aie plus besoin de porno ?"

    Dans les deux cas, pourquoi diable avez-vous besoin d'une séance ? Si vous avez toujours besoin de visiter votre harem, relisez d'abord le livre. Il y a quelque chose qui ne colle pas. Prenez le temps de tuer le gros monstre de lavage de cerveau dans votre esprit.

2.  "*Dois-je éviter les situations stressantes ou sociales pendant la période de sevrage ?*"

    Dans le cas de situations stressantes, oui. Il ne sert à rien de vous mettre une pression excessive. Dans le cas d'événements sociaux, comme les bars ou les clubs, le conseil est inverse. Sortez et amusez-vous tout de suite, vous n'avez pas besoin de sexe ou du côté propagatif du sexe, même si vous êtes dépendant du porno. Sortez et réjouissez-vous du fait que vous n'avez pas besoin de sexe ou du côté propagatif du sexe, cela vous prouvera rapidement la belle vérité que la vie est tellement meilleure sans ces pressions. Pensez simplement à combien elle sera meilleure lorsque le petit monstre vous aura quitté, ainsi que ces pensées de besoin.