# Le Moment de la Révélation

Généralement, dans les trois semaines qui suivent l'évasion, les ex-usagers vivent le moment de la révélation. Le ciel semble s'éclaircir et c'est le moment où le lavage de cerveau prend complètement fin. Au lieu de vous dire que vous n'avez pas besoin de regarder du porno, vous réalisez soudain que le dernier fil est rompu et que vous pouvez profiter du reste de votre vie sans plus jamais en avoir besoin. C'est également à partir de ce moment que l'on commence généralement à considérer les utilisateurs comme des objets de pitié.

Les personnes qui arrêtent le porno en utilisant la méthode de la volonté ne connaissent normalement pas ce moment car, bien qu'ils soient heureux d'être des ex-consommateurs, ils continuent à avancer dans la vie en croyant qu'ils font un sacrifice. Plus vous étiez dépendant, plus ce moment est merveilleux et il dure toute la vie. Bien qu'il existe de nombreuses joies dans la vie, il est impossible de retrouver le sentiment réel de les vivre. La joie de ne plus avoir à regarder du porno est différente. Si vous vous sentez déprimé et que vous avez besoin d'un coup de pouce, rappelez-vous à quel point il est agréable de ne plus être accroché à cette horrible dépendance. Beaucoup considèrent cette expérience comme l'un des plus grands événements de leur vie. Dans la plupart des cas, le moment de la révélation n'a pas lieu après trois semaines, mais après quelques jours.

Dans mon propre cas, cela s'est produit avant de terminer ma dernière visite au harem. Je suis sûr que beaucoup de lecteurs ici, avant même d'avoir atteint la fin des chapitres, diraient quelque chose comme "*Vous n'avez pas besoin de dire un autre mot. Je vois tout ça si clairement que je sais que je n'aurai plus jamais besoin de porno.*" D'après les commentaires reçus, cela arrive fréquemment. Idéalement, si vous suivez toutes les instructions et comprenez parfaitement la psychologie, cela devrait vous arriver immédiatement.

Bien qu'il soit indiqué qu'il faut environ cinq jours pour que le manque physique perceptible disparaisse, et environ trois semaines pour qu'un ex-utilisateur se libère complètement, de telles directives peuvent causer deux problèmes. Le premier est que la suggestion est implantée dans l'esprit des gens qu'ils devront souffrir pendant cinq jours à trois semaines. Le second est que l'ex-usager a tendance à penser : "*Si je peux survivre pendant cinq jours ou trois semaines, je peux m'attendre à un véritable coup de pouce à la fin de cette période.*"

Cependant, il se peut qu'ils aient cinq jours agréables ou trois semaines agréables suivis de jours désastreux qui frappent tout le monde, qui n'ont rien à voir avec la dépendance mais sont causés par d'autres facteurs dans nos vies. Alors notre ex-usager qui attend le moment de la révélation vit plutôt une dépression. Cela peut détruire sa confiance en lui. De même, s'il n'y avait pas de directives, l'ex-usager pourrait passer le reste de sa vie à attendre que rien ne se passe. C'est ce qui arrive à la grande majorité de ceux qui cessent d'utiliser la méthode de la volonté.

On s'interroge souvent sur la signification des cinq jours et des trois semaines. S'agit-il de périodes tirées au sort ? Non, bien qu'il ne s'agisse pas de dates précises, elles reflètent une accumulation de réactions au fil des ans. Environ cinq jours après l'arrêt, l'ex-consommateur cesse d'avoir la dépendance comme occupation principale de son esprit. La plupart des ex-consommateurs vivent une révélation autour de cette période, généralement dans des situations stressantes ou sociales qui, à un moment donné, ne pouvaient pas être supportées ou appréciées sans la visite d'un harem. Vous réalisez soudain que non seulement vous en profitez ou vous y faites face, mais que l'idée du porno ne vous a jamais effleuré. À partir de ce moment-là, tout va généralement bien. C'est là que tu sais que tu es libre.

D'après mon expérience et celle de beaucoup d'autres personnes qui ont essayé d'arrêter en utilisant la méthode de la volonté, c'est aux alentours de trois semaines que la plupart des tentatives sérieuses d'arrêt échouent. Ce qui se passe généralement, c'est qu'après environ trois semaines, vous sentez que vous avez perdu le désir de regarder du porno. Vous avez besoin de vous le prouver, alors vous sautez sur le navigateur pour visiter votre harem. Ça fait bizarre de prouver que tu as arrêté. Mais dans le processus, tu as graissé le toboggan DeltaFosB grâce à la poussée de dopamine fraîche, ce dont ton corps a eu besoin au cours des trois dernières semaines. Dès que vous avez terminé l'acte, la dopamine commence à quitter votre corps. Une petite voix réapparaît : "*Tu n'as pas réussi, tu en veux une autre.*"

Vous ne vous précipitez pas tout de suite parce que vous ne voulez pas être à nouveau accroché, ce qui vous permet de laisser passer une période de sécurité. Lors de la prochaine tentation, vous pourrez vous dire : "*Bien, je n'ai pas été accroché à nouveau, donc il n'y a pas de mal à en avoir un autre.*" Vous êtes déjà sur la pente glissante. La clé du problème n'est pas d'attendre le moment de la révélation, mais de réaliser qu'une fois que vous fermez le navigateur, c'est terminé. Vous avez coupé l'approvisionnement en oxygène de votre petit monstre. Aucune force sur terre ne peut vous empêcher d'être libre, *à moins que vous ne vous morfondiez sur votre sort ou que vous n'attendiez la révélation.* Allez profiter de la vie, faites-y face dès le début. Le moment sera bientôt venu.