# La Visite Finale

Après avoir décidé du moment, vous êtes maintenant prêt à rendre visite à votre harem une dernière fois. Avant de le faire, vérifiez les deux points essentiels.

1.  Etes-vous certain de réussir ?

2.  Avez-vous un sentiment de malheur ou d'excitation à l'idée que vous êtes sur le point de réaliser quelque chose de merveilleux ?

Si vous avez des doutes, relisez d'abord le livre. N'oubliez pas que vous n'avez jamais décidé de tomber dans le piège du porno, mais que ce piège est conçu pour vous asservir à vie. Pour en sortir, vous devez prendre la décision positive que vous êtes sur le point de vous arrêter et de faire votre dernière visite.

N'oubliez pas que si vous avez lu ce livre jusqu'à présent, c'est parce que vous aimeriez vraiment vous échapper. Prenez donc cette décision positive maintenant, en faisant le vœu solennel que lorsque vous fermerez la fenêtre de votre navigateur privé, que ce soit facile ou difficile, vous ne visiterez plus jamais votre harem. Vous craignez peut-être d'avoir fait ce vœu plusieurs fois par le passé et d'échouer encore, ou de devoir subir un traumatisme terrible. N'ayez crainte, la pire chose qui puisse vous arriver est d'échouer. Vous n'avez donc ***absolument rien*** à perdre et tant à gagner.

Mais ne pensez même plus à l'échec, la belle vérité est qu'il n'est pas seulement ridiculement facile d'arrêter le porno, vous pouvez même apprécier le processus. Cette fois, vous allez utiliser EasyPeasy ! Tout ce que vous avez à faire est de suivre les instructions simples qui vont vous être données.

1.  Faites le vœu solennel maintenant et pensez-y.

2.  Parcourez consciemment les images et les clips de votre site de tubes préféré, en regardant les tentatives désespérées des administrateurs du site, des acteurs et même des amateurs pour amplifier le choc, la nouveauté et la nature supernormale de leurs produits et demandez-vous où est le plaisir.

3.  Lorsque vous fermez enfin le navigateur, ne le faites pas avec un sentiment de "*je ne dois plus jamais visiter un autre harem en ligne*" ou "*je ne suis pas autorisé à en visiter un autre*" mais plutôt avec un sentiment de liberté, comme "*n'est-ce pas génial ? Je suis libre ! Je ne suis plus l'esclave du porno ! Je n'aurai plus jamais à visiter ces sites répugnants dans ma vie.*"

4.  Sachez que pendant quelques jours, il y aura un petit saboteur de porno dans votre estomac. Il se peut que vous ne soyez conscient que de la sensation de vouloir une séance. Le petit monstre du porno a été désigné comme le léger besoin physique de dopamine. À proprement parler, c'est inexact, et il est important de comprendre pourquoi. Comme il faut jusqu'à trois semaines pour que ce petit monstre meure, les ex-utilisateurs croient qu'il continuera à avoir envie après la dernière visite au harem en ligne et qu'ils doivent donc faire preuve de volonté pour résister à la tentation pendant cette période. Ce n'est pas le cas, le corps n'a pas envie de dopamine déclenchée par le porno, seul le cerveau en a envie.

Si vous ressentez l'envie de jeter un coup d'œil au cours des prochains jours, votre cerveau a un choix simple à faire. Il peut soit interpréter ce sentiment pour ce qu'il est en réalité - un sentiment d'insécurité vide déclenché par la première visite d'un site pornographique en ligne et perpétué par chacune des visites suivantes, et se dire **"YIPPEE ! JE SUIS UN NON-UTILISATEUR !"**

Ou, tu peux commencer à avoir envie de porno et souffrir pour le reste de ta vie. Réfléchissez un instant, ne serait-ce pas une chose incroyablement stupide à faire ? Dire "*Je ne veux plus jamais regarder de porno*", puis passer le reste de sa vie à dire "*J'aimerais bien y aller*" ? C'est ce que font ceux qui utilisent la méthode de la volonté, et il n'est pas étonnant qu'ils se sentent si malheureux. Ils passent le reste de leur vie à se morfondre pour quelque chose qu'ils espèrent désespérément ne jamais avoir. Pas étonnant que si peu réussissent et que les rares qui y parviennent ne se sentent jamais complètement libres.

> Obtenez cette image mentale clairement dans votre esprit, car elle peut être très utile pour surmonter le pouvoir des stimuli externes de vous perturber. Imaginez-vous assis tranquillement, laissant le téléphone sonner, ignorant son signal, insensible à son ordre. Bien que vous en soyez conscient, vous n'y faites plus attention et n'y obéissez plus. De même, fixez clairement dans votre esprit le fait que le signal extérieur en lui-même n'a aucun pouvoir sur vous, aucun pouvoir de vous émouvoir. Dans le passé, vous lui avez obéi, vous y avez répondu, par pure habitude. Vous pouvez, si vous le souhaitez, prendre la nouvelle habitude de ne pas y répondre.
>
> Remarquez également que votre non-réponse ne consiste pas à faire quelque chose, à faire un effort, à résister ou à lutter, mais à ne rien faire - à vous détendre. La sonnerie du téléphone est une analogie symbolique de tous les autres stimuli extérieurs que vous avez l'habitude de contrôler et que vous choisissez maintenant de modifier intentionnellement.
>
> --- Maxwell Maltz, "The New Psycho Cybernetics" Ch 12. 

C'est seulement le fait de douter et d'attendre qui rend difficile l'abandon, ***donc ne doutez jamais de votre décision*** car vous savez que c'est la bonne. Si vous commencez à en douter, vous vous mettez dans une situation sans issue. Misérable en ayant envie d'une visite mais incapable d'en avoir une. Quel que soit le système que vous utilisez, qu'essayez-vous d'atteindre en arrêtant le porno ? Ne plus jamais en regarder ? Non ! De nombreux ex-utilisateurs y parviennent mais passent le reste de leur vie à se sentir privés.

Quelle est la différence entre les utilisateurs et les non-utilisateurs ? Les non-utilisateurs n'ont ni besoin, ni envie de regarder du porno, ils n'ont pas de besoin et n'ont pas besoin de faire preuve de volonté pour ne pas en regarder. C'est ce que vous essayez de faire et vous avez tout à fait le pouvoir de le faire. Vous n'avez pas besoin d'attendre pour ne plus avoir envie de porno ou pour devenir un non-utilisateur, c'est terminé au moment où vous fermez la dernière fenêtre du navigateur, coupant ainsi l'approvisionnement en dopamine : **VOUS ÊTES DÉJÀ UN HEUREUX NON-UTILISATEUR!**

Vous resterez un heureux non-utilisateur à condition que :

1.  Vous ne doutez jamais de votre décision.

2.  Vous n'attendez pas de devenir un non-usager. Si vous le faites, vous ne ferez qu'attendre que rien ne se passe et vous créerez une phobie.

3.  Vous n'essayez pas de *ne pas* penser à la pornographie ou d'attendre le "moment de la révélation" pour créer une phobie.

4.  Vous n'utilisez pas de substituts.

5.  Vous voyez tous les autres utilisateurs tels qu'ils sont réellement et vous les plaignez plutôt que de les envier.

Qu'il s'agisse de bons ou de mauvais jours, ne changez pas votre vie simplement parce que vous avez arrêté le porno. Si vous le faites, vous ferez un véritable sacrifice alors que ce n'est pas nécessaire. Rappelez-vous, vous n'avez pas renoncé à vivre. Vous n'avez renoncé à rien. Au contraire, vous avez guéri d'une terrible maladie et vous vous êtes échappé d'une prison insidieuse. Au fur et à mesure que les jours passent et que votre santé -- tant physique que mentale -- s'améliore, les hauts sembleront plus élevés et les bas moins bas que lorsque vous étiez consommateur. Chaque fois que vous penserez au porno au cours des prochains jours ou pour le reste de votre vie, pensez :

***"YIPPEE ! JE SUIS UN NON-UTILISATEUR !" ***

## Un Dernier Avertissement

Aucun utilisateur, s'il avait la possibilité de revenir au moment où il est devenu accro avec les connaissances qu'il a maintenant, ne choisirait de commencer. Des dizaines de milliers de personnes qui réussissent à se débarrasser de l'habitude pendant de nombreuses années mènent des vies parfaitement heureuses, pour finalement se faire piéger à nouveau. J'espère que ce livre vous aidera à trouver qu'il est relativement facile d'arrêter. Mais attention, les utilisateurs qui trouvent qu'il est facile d'arrêter trouvent qu'il est tout aussi facile de recommencer, **ne tombez pas dans ce piège**.

Quelle que soit la durée de votre arrêt ou votre certitude de ne jamais redevenir accro, faites-vous une règle à vie de ne pas regarder de porno pour quelque raison que ce soit. Résistez aux allusions et aux sous-entendus des médias, et rappelez-vous qu'ils mettent en avant leur image "d'ouverture" en introduisant le porno dans le grand public ; sans savoir que le porno, le porno sur Internet et la masturbation compulsive tuent les relations et le sentiment de bien-être personnel d'un très grand nombre d'hommes et de centaines de femmes.

N'oubliez pas que le premier coup d'œil ou la première visite ne vous fera rien. Vous n'aurez aucune sensation de manque à soulager et vous vous sentirez très mal. Ce qu'elle fera, c'est vous faire ressentir le plaisir de la montée de dopamine dans votre esprit et votre cerveau, et une petite voix au fond de votre esprit vous dira que vous en voulez une autre. Vous aurez alors le choix d'être malheureux pendant un certain temps, ou de recommencer toute la chaîne sale.