# Le Feedback

La guerre n'est pas contre les utilisateurs, mais contre le piège de l'industrie pornographique, et elle est menée pour la simple raison que j'y prends plaisir. Chaque fois que j'entends parler d'un utilisateur qui s'échappe de la prison, j'éprouve un sentiment d'immense plaisir. Mais ce plaisir n'a pas été sans une frustration considérable, principalement causée par deux catégories d'utilisateurs de porno. Malgré l'avertissement du chapitre précédent, je suis continuellement surpris par le nombre de ceux qui trouvent qu'il est facile d'arrêter, mais qui retombent ensuite dans le panneau et constatent qu'ils n'y arrivent pas la fois suivante.

C'est comme trouver quelqu'un dans un marécage jusqu'au cou et sur le point de couler. Vous l'aidez à s'en sortir et il vous en est reconnaissant, mais six mois plus tard, il replonge directement dans le marécage. Les utilisateurs qui trouvent qu'il est facile d'arrêter et de recommencer posent un problème particulier, cependant lorsque vous vous libérez ***S'IL VOUS PLAÎT, S'IL VOUS PLAÎT, NE FAITES PAS LA MÊME ERREUR.*** Ils pensent que ces personnes recommencent parce qu'elles sont toujours accrochées et que la dopamine leur manque. En fait, ils trouvent l'arrêt si facile qu'ils perdent leur peur du porno. Ils se disent : "*Je peux avoir une session bizarre, et même si je redeviens accro, il me sera facile d'arrêter.*"

J'ai bien peur que ça ne fonctionne pas comme ça, il est facile d'arrêter le porno mais impossible de contrôler la dépendance. La seule chose essentielle pour arrêter le porno est de ne pas l'utiliser.

L'autre catégorie d'utilisateurs frustrés est celle des personnes trop effrayées pour tenter d'arrêter, ou qui, lorsqu'elles le font, trouvent que c'est un grand combat. Les principales difficultés semblent être les suivantes.

**La peur de l'échec**.

:   Il n'y a pas de honte à échouer, mais ne pas essayer est tout simplement stupide. Voyez les choses ainsi : vous ne vous cachez de rien. La pire chose qui puisse arriver est que vous échouiez, auquel cas vous n'êtes pas plus mal en point que maintenant. Pensez simplement à quel point il serait merveilleux de réussir. Si vous n'essayez pas, vous avez déjà garanti l'échec.

**La peur de la douleur et d'être malheureux.**

:   Ne vous en faites pas, pensez simplement : quelle chose affreuse pourrait vous arriver si vous ne regardiez plus jamais de porno ? Absolument rien. Des choses terribles *arriveront* si vous le faites, relisez les notes sur le pari de Pascal. Dans tous les cas, la panique est causée par la dopamine et disparaîtra bientôt. Le plus grand gain est de se débarrasser de cette peur. Croyez-vous vraiment que les utilisateurs sont prêts à avoir des pénétrations qui s'estompent, des performances sexuelles peu fiables ou le plaisir illusoire qu'ils tirent du porno ? Si vous vous sentez paniqué, la respiration profonde vous aidera. Si vous êtes avec d'autres personnes et qu'elles vous dépriment, fuyez-les et allez au garage, dans un bureau vide ou ailleurs.


    Si vous avez envie de pleurer, n'ayez pas honte. Pleurer est un moyen naturel d'évacuer les tensions. Personne n'a jamais pleuré sans se sentir mieux après. L'une des choses horribles que nous faisons aux jeunes hommes est de les conditionner à ne pas pleurer. Vous pouvez les voir essayer de retenir leurs larmes, mais regardez leur mâchoire se contracter. Nous nous apprenons à ne pas montrer nos émotions, mais nous ne sommes pas censés les refouler à l'intérieur. Criez, hurlez ou piquez une colère. Frappez quelque chose. Considérez votre lutte comme un match de boxe que vous ne pouvez pas perdre. Personne ne peut arrêter le temps, chaque instant qui passe voit mourir le petit monstre qui est en vous. Appréciez votre victoire inévitable.

**Ne pas suivre les instructions.**

: Incroyablement, certains utilisateurs disent que la méthode n'a pas fonctionné pour eux. Ils décrivent alors comment ils ont ignoré non seulement une instruction mais pratiquement toutes les instructions. Pour plus de clarté, nous les résumons sous forme de liste de contrôle à la fin de ce chapitre.

**Mauvaise compréhension des instructions.**

:   Les principaux problèmes semblent être les suivants :

    "*Je n'arrête pas de penser au porno.*"

    :   Bien sûr, vous ne pouvez pas et si vous essayez, vous créerez une phobie, devenant ainsi misérable. C'est comme essayer de s'endormir le soir ; plus vous essayez, plus cela devient difficile. Peu importe que tu penses au porno pendant quatre-vingt-dix pour cent de ta vie, c'est ce que tu penses qui est important. Si vous pensez "*Oh, j'adore regarder du porno*" ou "*Quand serai-je libre?*", vous serez malheureux. Si vous pensez plutôt "*YIPPEE ! Je suis libre!*" vous serez heureux.

    "*Quand le petit monstre du porno va-t-il mourir?*"

    :   La bouffée de dopamine quitte votre corps très rapidement, mais il est impossible de dire quand votre corps cessera de souffrir de la légère sensation physique de manque de dopamine. Ce sentiment de vide et d'insécurité est identique à la faim, à la dépression ou au stress normaux. Tout ce que fait le porno, c'est d'en augmenter le niveau. C'est pourquoi les utilisateurs qui cessent d'utiliser la méthode de la volonté ne sont jamais tout à fait sûrs de s'en être débarrassés, même après que leur corps a cessé de souffrir du manque de dopamine. S'ils souffrent d'une faim ou d'un stress normal, leur cerveau leur dit encore qu'il s'agit d'une raison valable pour réclamer leur session de droit. L'idée est que vous n'avez pas besoin d'attendre que l'envie du porno disparaisse, elle est si légère que nous ne nous en rendons même pas compte, nous la connaissons seulement comme une sensation de désir. Quand vous sortez de chez le dentiste, attendez-vous que votre mâchoire cesse de vous faire mal ? Bien sûr que non, vous continuez à vivre. Même si vous avez toujours mal à la mâchoire, vous êtes ravi.

        N'attendez pas que les retraits s'arrêtent car vous créerez le doute en vous demandant constamment "*Combien de temps cela va-t-il prendre ? Suis-je vraiment libre si je ne me sens pas différent ?". La peur est la sensation réelle, donc attendre que la vie s'améliore après avoir arrêté le porno créera le doute. Le sevrage est imperceptible, sauf si vous le craignez, et les améliorations exponentielles de la neurologie sont lentes, donc si vous attendez de vous sentir différent, vous aurez l'impression que rien ne se passe, ce qui créera le doute.

    *"Le 'moment de la révélation' n'est pas encore arrivé. "*

    :   Si vous l'attendez, vous ne faites que provoquer une autre phobie. Une fois, j'ai arrêté pendant trois semaines avec la méthode de la volonté. En discutant avec un vieil ami, il m'a demandé comment je m'en sortais.
        "*J'ai survécu à trois semaines*", ai-je répondu.
        Il m'a demandé : "*Qu'est-ce que tu veux dire, tu as survécu à trois semaines*".
        J'ai précisé : "*J'ai tenu trois semaines sans porno.*"
        Il a dit : "*Qu'est-ce que tu vas faire ? Survivre le reste de ta vie ? Qu'est-ce que tu attends, tu l'as fait. Tu es un non-usager.*"

        J'ai pensé, "*Il a tout à fait raison, qu'est-ce que j'attends?*" Malheureusement, en raison d'un manque de compréhension du piège, j'y suis vite retourné, mais le point a été noté. Vous devenez un non-utilisateur lorsque vous fermez votre navigateur. L'important est d'être un non-utilisateur heureux dès le départ.

    "*Je suis toujours en manque de porno.*"

    :   Alors tu es très stupide. Comment pouvez-vous prétendre que vous voulez être un non-utilisateur et ensuite dire que vous voulez du porno ? C'est une contradiction. Si tu dis que tu veux du porno, tu dis que tu veux être un utilisateur. Les non-utilisateurs ne veulent pas visiter les sites à tube dégoûtants. Tu sais déjà ce que tu veux être, alors arrête de te punir.

    "*J'ai choisi de ne pas vivre.*"

    :   Pourquoi ? Tout ce que vous avez à faire est d'arrêter de vous tuer et de commencer à vous énergiser à la place. Vous n'avez pas besoin d'arrêter de vivre le moins du monde. C'est aussi simple que ça, pendant les deux prochains jours, vous aurez un léger traumatisme dans votre vie. Votre corps subira l'aggravation presque imperceptible du retrait des demandes et des revendications pour une poussée de dopamine. Maintenant, gardez ceci à l'esprit : vous n'êtes pas plus mal en point que vous ne l'étiez. C'est ce que vous avez subi pendant toute votre vie, chaque fois que vous étiez endormi, à l'église, au supermarché ou à la bibliothèque. Cela ne semblait pas vous déranger lorsque vous étiez consommateur et si vous n'arrêtez pas, vous continuerez à souffrir de cette détresse pour le reste de votre vie.

        Le porno et ses orgasmes ne créent pas d'occasions, ils vous en privent. Même si votre corps est toujours en manque de dopamine, les repas et les occasions sociales sont merveillesues. La vie est merveilleuse, allez aux événements sociaux, même s'il y a des danseuses nues. Rappelez-vous que ce n'est pas vous qui êtes privé, ce sont eux. Chacun d'entre eux aimerait être à votre place, si seulement ils savaient. Profitez d'être la prima donna et le centre d'attention. Arrêter le porno est un merveilleux sujet de conversation, en prenant un plaisir secret qu'ils ne peuvent pas avoir. Vos amis et vos pairs seront surpris de voir que vous, autrefois timide et à l'air fatigué, êtes maintenant heureux et joyeux. Vous profiterez de la vie dès le début, il n'y a pas besoin d'envier les dragueurs dans les soirées, ils vous envieront - si seulement ils savaient.
    
    "*Je suis misérable et irritable.*"

    :   Il s'agit d'un non-respect des instructions. Trouvez laquelle. Certaines personnes comprennent et croient tout ce qui est écrit, mais commencent tout de même par éprouver un sentiment de malheur, comme si quelque chose de terrible était en train de se produire. Vous ne faites pas seulement ce que vous aimeriez faire, mais aussi ce que tous les utilisateurs de la planète aimeraient faire. Avec n'importe quelle méthode d'arrêt, l'ex-utilisateur essaie d'atteindre un certain état d'esprit, de sorte que chaque pensée liée à la pornographie est ponctuée de "*YIPPEE ! JE SUIS LIBRE!*" Si tel est votre objectif, pourquoi attendre ? Commencez dans cet état d'esprit et ne le perdez jamais, il n'y a pas d'alternative.

    "*J'ai eu une bonne semaine / un bon mois / six mois mais je suis de retour dans le piège.*"

    :   Rappelez-vous, la peur est la piqûre elle-même. Céder à une sensation génère plus de peur, alimentant le petit monstre affaibli et réussissant à effrayer le non-utilisateur en lui faisant croire qu'il est accroché pour la vie. En réalité, leur conceptualisation du lavage de cerveau n'a pas changé, mais ils ont donné de la dopamine au processus de pensée. Il s'agit par définition d'une chute en avant, mais d'un manquement aux instructions. Comprenez laquelle ci-dessous et réjouissez-vous.

## La Liste de Contrôle

Si vous suivez ces instructions, vous ne pouvez pas échouer :

1.  Faites le vœu solennel de ne jamais, au grand jamais, aller sur Internet pour visiter votre harem *OU* vous contenter d'images statiques *OU* faire la paix avec les graphiques érotiques *OU* tout ce qui contient des stimuli supranormaux, et tenez-vous-en à votre vœu.

2.  Mettez cela au clair dans votre esprit : Il n'y a absolument rien à abandonner. Cela ne signifie pas que vous serez mieux en tant que non-PMOien (vous le savez depuis le début), ni que, bien qu'il n'y ait aucune raison rationnelle de faire de la PMO, vous en retirez un certain plaisir ou une béquille, car autrement vous ne le feriez pas. Ce que l'on veut dire, c'est qu'il n'y a ***pas de véritable plaisir ou de béquille dans le fait de s'adonner à la PMO.*** Ce n'est qu'une illusion, comme se taper la tête contre un mur pour avoir du plaisir quand on s'arrête.

3.  Il n'y a rien de tel qu'un PMOien confirmé. Tu es juste l'un des centaines de millions de personnes qui sont tombées dans ce piège subtil. Comme les millions d'autres ex-PMOiens qui pensaient ne pas pouvoir s'échapper, tu t'es échappé.

4.  Si, à n'importe quel moment de votre vie, vous deviez peser le pour et le contre de la PMO, la conclusion dominante serait toujours "*Arrête de le faire. Tu es un idiot!*" Rien ne changera jamais cela. Il en a toujours été ainsi et il en sera toujours ainsi. Après avoir pris ce que vous savez être la bonne décision, ne vous torturez jamais en doutant. Le pari de Pascal s'applique parfaitement au PMO, avec aucune chance de perte, de fortes chances de gains et de fortes chances d'éviter les pertes.

5.  N'essayez pas de ne pas penser au porno, ou de vous inquiéter du fait que vous y pensez constamment. Chaque fois que vous y pensez, que ce soit aujourd'hui, demain ou pour le reste de votre vie, pensez **"YIPPEE ! Je me suis libéré de ça !"**.

6.  **N'utilisez pas** de substitut sous quelque forme que ce soit. **Ne vous défiez pas** en gardant votre ordinateur portable à côté de vous pendant que vous dormez. **Ne pas** éviter les pièces de théâtre, les films ou les magazines. **Ne modifiez pas votre mode de vie** de quelque manière que ce soit, uniquement parce que vous avez arrêté. Si vous suivez les instructions ci-dessus, vous connaîtrez bientôt le "moment de la révélation" :

7.  N'attendez pas que le "moment de la révélation" arrive. Continuez simplement votre vie, en profitant des hauts et en faisant face aux bas. Vous verrez qu'en un rien de temps, le moment arrivera.