# De l'Aide à ceux qui Coulent Encore

Les utilisateurs de porno paniquent aujourd'hui, sentant des changements dans la façon dont le porno sur Internet est perçu par les hommes et les femmes. La nature addictive du porno sur Internet est de plus en plus souvent étudiée, car elle est désormais considérée, à juste titre, comme différente de la pornographie traditionnelle. La facilité et la disponibilité de la pornographie sur Internet inquiètent même les partisans de la pornographie. Ils ont également le sentiment que leur croisade pour la liberté d'expression et de pensée est détournée par divers éléments. Le Far West de l'Internet non surveillé rend presque impossible l'application de restrictions d'âge aux stimuli supranormaux. Il est regrettable que cela ne prenne pas fin de sitôt, mais des centaines de milliers d'utilisateurs arrêtent, la plupart des accros étant conscients des études montrant des similitudes entre le porno et la toxicomanie. Chaque fois qu'un utilisateur quitte le navire en perdition, ceux qui y restent se sentent de plus en plus malheureux.

Chaque utilisateur sait instinctivement qu'il est ridicule de s'auto-saboter et de passer du temps devant des pixels en deux dimensions, ce qui a pour effet de sursaturer son cerveau et, ce faisant, de développer des voies neuronales qui garantissent de mauvaises performances sexuelles. Si vous ne pensez toujours pas que c'est ridicule, essayez de parler à un magazine porno qui se trouve au centre de votre ville et demandez-vous quelle est la différence. Une seule. Vous ne pouvez pas obtenir le plaisir de la chaleur et de l'intimité de cette façon. Si vous pouvez arrêter d'acheter de l'alcool et des cigarettes chaque fois que vous faites vos courses, vous pouvez certainement arrêter de visiter votre harem en ligne. Les utilisateurs ne trouvent pas de raisons rationnelles pour regarder du porno, mais ils ne se sentent pas aussi stupides si d'autres personnes le font aussi.

Les utilisateurs mentent ouvertement sur leurs habitudes, non seulement aux chercheurs et à leur entourage, mais aussi à eux-mêmes. Ils sont obligés de le faire, le lavage de cerveau est essentiel s'ils veulent conserver une certaine estime d'eux-mêmes. Ils ressentent le besoin de justifier leur "habitude" non seulement à eux-mêmes mais aussi aux non-utilisateurs. Ils font sans cesse la publicité des avantages illusoires du porno par des moyens plus subtils.

Si un utilisateur arrête en utilisant la méthode de la volonté, il se sent toujours privé et a tendance à se plaindre. Cela ne fait que confirmer aux autres utilisateurs qu'ils ont raison de continuer à consommer. Si l'ex-consommateur réussit à se débarrasser de son habitude, il est alors reconnaissant de ne plus avoir à s'auto-saboter ou à gaspiller son énergie dans la vie et n'a pas besoin de se justifier. N'oubliez pas que c'est la peur qui fait que l'utilisateur fait l'autruche et ne remet en question son comportement que lorsqu'il arrête. Aidez l'utilisateur en éliminant ces peurs. Dites-lui combien il est merveilleux de ne pas avoir à vivre dans une prison, combien il est agréable de se réveiller le matin en pleine forme au lieu de manquer d'énergie et de se détester, combien il est merveilleux d'être libéré de l'esclavage, de pouvoir profiter pleinement de sa vie et d'être débarrassé de ces ombres noires. Ou mieux encore, faites-leur lire ce livre.

Il est essentiel de ne pas déprécier un utilisateur marié en indiquant qu'il ruine délibérément sa relation ou qu'il est en quelque sorte infidèle ou impur. On croit souvent à tort que l'ex-usager est le pire à cet égard. Cette conception a une certaine substance, mais elle est généralement due à la méthode d'arrêt par la volonté. En effet, l'ex-consommateur, bien qu'il se soit débarrassé de l'habitude, conserve une partie du lavage de cerveau et croit toujours qu'il a fait un sacrifice. Il se sent vulnérable et son mécanisme de défense naturel consiste à attaquer l'utilisateur de porno.

Cela peut renforcer l'ego de l'ex-utilisateur, mais cela n'aide en rien l'utilisateur. Tout ce que cela fait, c'est de le mettre au pied du mur, de le rendre encore plus malheureux et, par conséquent, d'accroître son besoin de pornographie. Bien que le changement d'attitude du corps médical à l'égard de la pornographie sur Internet soit la principale raison pour laquelle de nombreux utilisateurs arrêtent le porno, cela ne facilite pas leur démarche. En fait, cela rend les choses beaucoup plus difficiles. La plupart des utilisateurs pensent aujourd'hui qu'ils arrêtent principalement pour des raisons de santé. Ce n'est pas tout à fait vrai.

Bien que le risque énorme pour la santé soit évidemment la raison principale de l'arrêt, les utilisateurs sabotent leur virilité depuis des années et cela n'a pas fait la moindre différence. La principale raison pour laquelle les utilisateurs arrêtent est que la société commence à voir le porno démasqué pour ce qu'il est : La toxicomanie. Les attitudes de la société changent lentement - de nombreux partenaires poseraient maintenant des questions si vous êtes sur votre ordinateur portable au milieu de la nuit.

L'interdiction totale du porno dans certains pays ou l'indisponibilité d'Internet sont des exemples classiques du dilemme de l'utilisateur voyageur. En général, ils se disent que cela les aidera à réduire leur consommation. Le résultat est qu'au lieu d'une ou deux par jour, qu'ils n'auraient pas appréciées, ils s'abstiennent pendant une semaine entière. Pendant cette période d'abstinence forcée, non seulement ils sont mentalement privés en attendant leur récompense, mais leur corps est également en manque. Oh, comme cette visite du harem en ligne est précieuse lorsqu'elle est finalement autorisée.

Les abstinences forcées ne réduisent pas réellement la consommation, car l'utilisateur se fait encore plus plaisir lorsqu'il est enfin autorisé à être seul. Tout ce que cela fait, c'est d'ancrer dans l'esprit de l'utilisateur la valeur du porno sur Internet et sa dépendance à son égard. L'aspect le plus insidieux de cette abstinence forcée est son effet sur les adolescents. Nous permettons aux pirates de la "liberté d'expression", les producteurs de pornographie, de cibler les adolescents malchanceux pour les rendre accros dès le départ. Puis, à la période probablement la plus stressante de leur vie, alors qu'ils ont besoin de porno par-dessus tout, nous les faisons chanter pour qu'ils abandonnent en raison du mal qu'ils se font.

Beaucoup n'y parviennent pas et sont obligés, sans que ce soit leur faute, de souffrir d'un complexe de culpabilité pour le reste de leur vie. Beaucoup réussissent et sont heureux de le faire, en se disant : " Bien. Puis viennent la douleur et la peur de trouver du travail et d'autres luttes d'adultes, suivies par le plus grand "high" de leur vie - trouver un emploi. La douleur et la peur sont terminées, maintenant qu'ils se sentent en sécurité, le vieux mécanisme de déclenchement se remet en marche. Une partie du lavage de cerveau étant toujours là et avant que l'odeur du nouvel ordinateur portable de travail ne disparaisse, l'utilisateur est au seuil de son harem en ligne préféré. L'exaltation de l'occasion bloque les mauvais sentiments de son esprit, il n'a pas l'intention de redevenir accro, mais un seul coup d'oeil ne peut pas faire de mal... Trop tard ! Ils sont déjà accrochés à nouveau.

Le vieux besoin du petit monstre recommencera et même s'ils ne redeviennent pas immédiatement dépendants, la dépression post-high les rattrapera probablement. Il est étrange que, bien que les héroïnomanes soient des criminels au regard de la loi, la réaction de la société soit d'aider ces personnes. Adoptons la même attitude à l'égard du pauvre utilisateur de pornographie. Ils ne le font pas parce qu'ils le veulent, mais parce qu'ils pensent qu'ils doivent le faire. Contrairement à l'héroïnomane, ils doivent généralement subir des années et des années de torture mentale et physique. On dit toujours qu'une mort rapide est préférable à une mort lente, alors n'enviez pas le pauvre consommateur de porno. ***Ils méritent votre pitié.***