# Conseils aux Non-utilisateurs

## Aidez vos amis utilisateurs de pornographie à lire ce livre.

Tout d'abord, étudiez le contenu de ce livre et essayez de vous mettre à la place de l'utilisateur. Ne les forcez pas à lire ce livre en leur disant qu'ils sont en train de ruiner leur santé ou de jouer avec le feu. Ils le savent mieux que vous. Les utilisateurs ne continuent pas à regarder du porno parce qu'ils y prennent plaisir ou parce qu'ils en ont envie, ils ne le disent à eux-mêmes et aux autres que pour conserver leur amour-propre. Ils le font parce qu'ils sont dépendants du porno, parce qu'ils pensent que cela les détend, leur donne du courage ou de la confiance (plaisir ou béquille) et parce qu'ils ont le sentiment que la vie ne sera jamais agréable sans "sexe" - du moins leur version du sexe. Si vous essayez de forcer un utilisateur à arrêter, il se sentira comme un animal piégé et voudra encore plus son harem. Cela peut le transformer en utilisateur secret et le porno deviendra encore plus précieux dans son esprit.

Concentrez-vous plutôt sur l'autre côté de la médaille. Mettez-le en compagnie d'ex-usagers (blogs, forums, YBOP, NoFap, etc.). Faites en sorte qu'ils racontent à l'utilisateur comment eux aussi pensaient être accrochés pour la vie et combien la vie est meilleure en tant que non-utilisateur. Une fois que vous leur aurez fait croire qu'ils peuvent arrêter, leur esprit commencera à s'ouvrir. Commencez alors à expliquer l'illusion créée par les symptômes de sevrage. Non seulement les "poussées de dopamine" ne les stimulent pas, mais elles détruisent leur confiance et les rendent irritables et fatigués.

Ils devraient maintenant être prêts à lire ce livre eux-mêmes, s'attendant à lire des pages et des pages d'histoires sur l'excitation peu fiable, les pénétrations qui s'estompent, le PIED, l'EP, etc. Expliquez-leur que cette approche est complètement différente et que les références à la maladie ne représentent qu'une infime partie du matériel.

En bref, ne laissez pas ce sujet mourir dans l'obscurité. Dites-le à vos amis, mais ne soyez pas bizarre. Si vous essayez de "gagner" la conversation ou d'avoir un débat, vous ne réussirez qu'à les aliéner et à accroître leur peur.

## Devrais-je le dire à ma moitié ?

Devrais-je parler de mon habitude à ma femme, ma petite amie ou mon partenaire ? L'intention étant de vous aider à arrêter à finir votre dépendance. Il y a plusieurs facteurs en jeu ici.

Si vous n'avez pas réussi à arrêter le porno en utilisant la méthode de la volonté et que vous en avez déjà parlé à votre partenaire, parlez-lui de votre nouvelle approche et permettez-lui de s'instruire en lisant le livre. Il pourra vous aider et vous motiver pendant la période de sevrage et sera un point d'appui lorsque le petit monstre tentera de vous faire trébucher.

Si vous venez seulement de prendre conscience de l'existence du piège de la pornographie et que vous n'avez jamais essayé d'arrêter le porno, utilisez d'abord EasyPeasy vous-même. Comme expliqué précédemment, cette expérience devrait être agréable. Toutefois, si vous éprouvez des difficultés, demandez leur aide. Soyez ouvert et vulnérable avec votre partenaire et votre relation s'en trouvera renforcée.

Si vous aimez vous évader et que l'indécision ne vous rend pas la tâche difficile, il n'y a pas vraiment de raison de le faire savoir à votre partenaire. Si ce n'était pas un problème dans le passé, laissez-le mourir. Cependant, préparez-vous à ce que votre partenaire se demande pourquoi vous avez l'air, vous vous sentez et êtes plus performant !

## Mon partenaire arrête la pornographie

La pornographie est un destructeur pervers des relations et si l'arrêt peut se faire instantanément, la guérison prend du temps. De nombreux utilisateurs, en raison de croyances irrationnelles nées de leur dépendance, déversent leur colère sur leurs partenaires et leurs proches. Ces comportements se manifestent par le gaslighting, le mensonge et les comportements manipulateurs. Ce n'est pas le cas de tous les usagers, mais c'est de plus en plus fréquent aux stades avancés de la maladie. Bien que ces comportements puissent s'être manifestés à partir de la dépendance sous-jacente à la pornographie, il est important de vous informer sur ces comportements et, s'ils sont reconnus, d'envisager de consulter un thérapeute spécialisé dans les dépendances sexuelles.

Si votre partenaire est en période de sevrage, partez du principe qu'il souffre, qu'il le fasse ou non. N'essayez pas de la minimiser en lui disant que c'est facile d'arrêter, qu'il peut le faire lui-même. Au contraire, continuez à lui dire à quel point vous êtes fier de lui, à quel point il a meilleure mine, à quel point il est plus agréable d'être avec lui et à quel point il est plus facile en général. Il est particulièrement important de continuer à le faire, lorsqu'un utilisateur fait une tentative d'arrêt, l'euphorie de la tentative et les éloges qu'il reçoit de ses pairs peuvent l'aider. Cependant, ils ont tendance à oublier rapidement, alors continuez à les féliciter.

Comme ils ne parlent pas de pornographie, vous pouvez penser qu'ils ont oublié et ne veulent pas que vous leur rappeliez. C'est généralement tout le contraire avec la méthode de la volonté, car l'ex-usager a tendance à n'être obsédé que par cela. N'ayez donc pas peur d'aborder le sujet et de continuer à le féliciter, il vous le dira s'il ne veut pas qu'on le lui rappelle.

Faites tout votre possible pour le soulager des pressions pendant la période de sevrage, en pensant à des moyens de rendre sa vie intéressante et agréable. Cette période peut également être éprouvante pour les non-consommateurs qui n'ont jamais connu la dépendance. Si l'un des membres d'un groupe est irritable, cela peut provoquer un malaise général. Si l'ex-usager se sent irritable, il se peut qu'il s'en prenne à vous, mais ne ripostez pas, car c'est à ce moment-là qu'il a le plus besoin de vos éloges et de votre sympathie. Si vous vous sentez vous-même irritable, ce qui est compréhensible, essayez de ne pas le montrer.

L'une des astuces d'un toxicomane qui essaie d'arrêter le porno avec l'aide de la méthode de la volonté est de piquer des crises de colère, en espérant que son partenaire ou ses amis diront "*Je ne supporte pas de te voir souffrir comme ça. Pour l'amour du ciel, prends ton poison*". L'utilisateur n'a donc pas à perdre la face, il n'abandonne pas, il a reçu des instructions. Si l'ex-usager utilise ce stratagème, ne l'encouragez en aucun cas à rechuter. Dites plutôt : "*Si c'est ce que le porno te fait, Dieu merci, tu seras bientôt libre. C'est merveilleux que tu aies eu le courage d'abandonner.*"

N'oubliez pas qu'il y a deux parties qui guérissent dans le cadre du processus de rétablissement. Lorsque votre partenaire abandonne le porno, il est important que vous disposiez de votre propre réseau de soutien, de vos propres routines de soins et de vos propres limites. Ce processus ne se fait pas du jour au lendemain et nécessite confiance, communication et responsabilité. La tenue d'un journal, le développement de vos propres passions et, surtout, la thérapie, vous aideront dans ce processus.

## Dérapage (rechute)

L'existence de cette section devrait servir d'avertissement à ceux qui quittent le piège. Personnellement, je n'ai jamais rechuté, mais j'utiliserai des expériences tirées d'entretiens avec des membres de la communauté et des outils de la thérapie cognitivo-comportementale pour illustrer mon propos.

Tout d'abord, appeler cela une rechute est contre-productif. Tout ce qui s'est passé, c'est que vous avez dérapé et nourri le petit monstre, qui à son tour a déclenché le grand monstre du lavage de cerveau. Les utilisateurs qui glissent (ce qui, par définition, est une chute en avant) engendrent généralement toute une série de croyances irrationnelles :

  - "*Je ne serai jamais libre*" - **Catastrophisation**
  - "*Je devrais / dois faire de l'exercice, étudier et être fructueux chaque jour de ma vie*" (alias - **musterbating**)
  - "*Aujourd'hui, j'ai fait de la MOP, à quoi bon lire tous les livres et les forums...". Mon but était de ne même pas faire de M, mais je suis là - un échec - en train de rechuter.*" - **Peu de tolérance à la frustration**
  - "*Mes amis / lecteurs de forums / d'autres ne font pas de PMO pendant (n) jours, mais moi je n'y arrive pas donc je suis un cas désespéré. Je me sentais bien hier car j'ai bien étudié et j'ai été fructueux, mais aujourd'hui je n'ai pas... Je suis en train de dégringoler.*" - **Evaluation entre soi et les autres**
  - "Je ne devrais pas avoir de pensées sexuelles" - Lui-même, ses parents ou la société dans son ensemble ont installé des **croyances rigides** par rapport au sexe. Demandez-vous si l'autoflagellation vous aide à atteindre vos objectifs et, dans l'affirmative, si vous appréciez le voyage ?

Les facteurs qui aboutissent au lavage de cerveau de chaque utilisateur sont apparemment infinis. Vous vous connaissez mieux que quiconque, il s'agit manifestement d'un manquement aux instructions. Vous avez vu de la valeur dans la pornographie, mais comment ?

Ce que l'on oublie souvent, c'est qu'il faut du temps pour inverser le lavage de cerveau. Cela ne rend pas les choses plus difficiles, mais presque toutes les industries utilisent le sexe, et contrer activement le lavage de cerveau est un processus conscient (du moins au début), donc cela peut prendre du temps pour solidifier pleinement les leçons qu'il contient. Par conséquent, plusieurs lectures sont recommandées (vous pouvez sauter les chapitres qui vous posent problème) et cela ne devrait pas vous prendre longtemps.

Une expérience étonnamment commune aux utilisateurs religieux qui quittent le piège est de vouloir que cela fasse un peu mal, comme une forme d'expiation. Ils trouvent qu'il est si facile d'arrêter, puis se sentent coupables de se sentir ainsi. Mais pourquoi s'auto-saboter et rendre les choses difficiles ? Le petit monstre est très sournois à cet égard.

Dissociez-vous du petit monstre, il a été ajouté par l'industrie pornographique il y a longtemps. Imaginez une brute qui fait une crise de colère dans la cour de récréation. Que dites-vous à une brute ? Si tu cèdes, tu ne fais que les renforcer. Certains qui abandonnent finissent par nourrir la brute, et augmentent ainsi leur lavage de cerveau, mais leur conceptualisation du piège n'a pas changé. Reprenez-vous, déterminez où vous avez fait fausse route et profitez de la liberté !

Vous n'êtes pas votre besoin. La méditation de pleine conscience consiste à observer la pensée, ce qui permet de tirer des leçons fondamentales sur la nature de l'esprit. Il est fortement recommandé de méditer en général, et c'est également tout à fait compatible avec la pratique religieuse. Vous ne pouvez pas vous battre avec vous-même, ni avec le petit monstre. Vous devez vous aimer inconditionnellement, vous et le processus.

Mais éliminez l'échec de votre esprit. Voici une section de "*Méditations d'un accro au porno*" par Gulliaco (dont le lien se trouve dans la section des ressources à la fin du livre)

> Puisque regarder du porno ne vous offre aucun avantage, que c'est quelque chose qui ne fait que vous blesser, et qu'il est extrêmement ridicule de vouloir faire quelque chose comme ça, je le compare à boire de l'eau de Javel. Voilà :
>
> **Le dur voyage pour ne pas boire d'eau de javel.**
>
> Bonjour ! Nous sommes NoBleach et nous organisons des défis de reboot dans lesquels les participants ("Bleachstronauts") s'abstiennent de boire de l'eau de Javel pendant un certain temps. Que votre objectif soit de participer occasionnellement à un défi mensuel pour tester votre maîtrise de soi, ou que la consommation excessive d'eau de Javel soit devenue un problème dans votre vie et que vous souhaitiez arrêter pour une plus longue période, vous trouverez ici une communauté de soutien et de nombreuses ressources.
>
> - "*Je me permets parfois de boire un ou deux verres d'eau de Javel. Je sais que le "une goutte" est un mensonge, mais je ne pense pas qu'un seul verre fera mal. On ne peut pas détruire toutes les heures que j'ai passées sans le faire.*"
> - "*Je n'ai pas de problème pour arrêter de boire de l'eau de Javel, mais parfois je vais dans la rue, et je vois quelqu'un qui boit de l'eau, vous savez, dans un verre, et j'imagine que le verre contient de l'eau de Javel. J'ai alors une envie pressante et, après avoir débattu avec moi-même pour savoir si je devais le faire ou non, je cède finalement le soir et je bois un verre.*"
> - "*Écoutez, mon problème est que parfois, quand je suis seule dans ma cuisine, je commence à voir les verres, parfois je me tente en ouvrant le récipient où je garde l'eau de Javel, parfois je la sens et... Eh bien, je me retrouve au point de départ. J'ai tellement envie d'arrêter ça, mais je ne suis pas sûre d'être capable d'arrêter.
capable d'arrêter.*"
> - "*Arrêter de boire de la Javel est impossible, je veux dire, j'ai toujours une bouche, tu sais ? Comment je suis censé arrêter si j'ai toujours une gorge qui me rappelle que je peux avaler de l'eau de javel?*"
> - "*Oh mec, ça se passait tellement bien, 19 jours entiers sans le faire. L'important c'est d'apprendre de l'échec ! Maintenant je sais ce qu'il faut éviter de faire : regarder les produits de nettoyage au supermarché. Je vais essayer de tenir jusqu'à un mois ! Je vais remettre mon compteur à zéro. Souhaitez-moi bonne chance !*"
> Si tu as une envie pressante, calme-toi mec ! Rappelle-toi ce que dit le hackbook :
>
> "*Il est difficile de renoncer à l'alcool par crainte d'être privé de son plaisir ou de son accessoire. La peur que certaines situations agréables ne soient plus jamais tout à fait les mêmes. La peur d'être incapable de faire face à des situations stressantes. En d'autres termes, ce sont les effets du lavage de cerveau qui nous font croire qu'acheter de l'eau de Javel, et par extension en boire, est une nécessité pour tous les êtres humains. Plus loin encore, c'est la croyance qu'il y a quelque chose d'inhérent à l'eau de Javel abordable dont nous avons besoin, et que si nous arrêtons d'en consommer, nous nous priverons et créerons un vide. Que ce soit clair dans votre esprit : L'eau de Javel ne comble pas un vide, elle en crée un !*"
> 
> Et je dis :
> "*Supposez que vous soyez obligé de regarder un verre plein d'eau de Javel pendant cinq minutes. Essayez de vous souvenir d'une de ces marques ou odeurs que vous aimiez tant. Peut-être est-elle accompagnée d'un son, ou bien vous ne vous souvenez que de certains détails. L'eau de Javel est là et vous ne pouvez pas fermer les yeux ou tourner la tête, car cette eau de Javel est dans votre esprit, c'est un souvenir enregistré en vous*.
>
> *Sentez-vous des envies ? Ressentez-vous quelque chose dans votre langue ou un changement dans votre respiration ? Quels sont vos sentiments par rapport à ce dont vous vous souvenez ? Identifiez-les, l'eau de Javel veut les brouiller, les rendre confus et vous faire prêter attention uniquement à ce qui veut vous attraper.*"
>
> Avec ce qui précède, je n'essaie pas de rejeter vos sentiments, et encore moins de dire quelque chose comme "haha me smart you dumb", mais de vous donner une perspective afin que vous réalisiez combien il est ridiculement facile (et le sera toujours) de surmonter cette dépendance.
> Regarder du porno n'est pas comme un interrupteur marche/arrêt où vous dites "*oh bien, je suis dans une situation X, alors je vais regarder du porno*". Fantasmes ! Des mensonges ! Combien de fois vous autorisez-vous à boire un verre d'eau de Javel ? Jamais ? Pourquoi ? Parce que c'est une chose horrible, voilà pourquoi ! Comment es-tu supposé échapper à ta dépendance si tu ne réalises pas
si tu ne réalises pas que l'OMM est une chose horrible à s'infliger ?

## Qu'en est-il de la MO (masturbation, orgasme) ?

Les gens se branlent depuis des lustres sans problème. Pour être clair, le porno est le problème.

Ceci étant dit, vous pouvez devenir accro à la masturbation pour les mêmes raisons que le porno, comme la mentalité du "besoin d'avoir un orgasme", l'escalade mentale, le fait de forcer le corps à avoir des rapports sexuels et la simple recherche hendonique du plaisir.

Il est très probable que le porno et la masturbation se soient profondément entremêlés dans votre esprit. De nombreux utilisateurs constatent qu'ils finissent par rechuter à force de se masturber sur des fantasmes induits par le porno. À mesure que votre cerveau se recompose, ce lavage de cerveau finit par s'estomper, mais il est préférable de faire une pause pendant un certain temps. Vous devriez également rechercher du sexe réel afin d'accélérer ce processus.

Ce n'est pas une instruction, mais évaluez-la. Les avantages rapportés de la rétention de sperme sont nombreux - augmentation de la concentration et de l'énergie, suppression du "brouillard cérébral" et augmentation de la confiance en soi, ainsi qu'un grand nombre d'autres avantages. D'après mon expérience personnelle, il y a une nette différence, et tout dépend de la façon dont vous transmutez cette énergie accrue.

En spéculant, et sans connaissance scientifique stricte, les avantages pourraient se résumer à deux facteurs différents.

- Après l'orgasme, le cerveau libère de la prolactine, qui inhibe la libération de dopamine.

- Priver votre cerveau de bouffées de dopamine permet une plus grande absorption par le simple fait de vivre.

- Le sperme est réabsorbé par la circulation sanguine après ~78 jours, et constitue l'un des meilleurs nutriments que votre corps puisse recevoir.

- Transmuter l'énergie sexuelle en habitudes productives apporte avec elle une couche supplémentaire de productivité.

Vous pouvez également souhaiter avoir des rapports sexuels sans orgasme, ce qui, comme nous l'avons mentionné précédemment, est une expérience sexuelle merveilleuse. Vous pouvez renforcer votre capacité à le faire en pratiquant les exercices de Kegel. D'après mon expérience personnelle, la façon la plus simple et la plus efficace de cibler ce muscle est d'arrêter d'uriner à mi-course. La séparation de la partie tantrique et de la partie propagative du sexe est l'un des nombreux avantages de l'évasion du piège de la PMO (et mes partenaires l'ont également apprécié !).

Mais toute cette partie est plus une suggestion personelle de ma part, le Hackauteur Anonyme.

## Déviations par rapport aux conseils standards

Cette section est nouvelle et est écrite avec une certaine appréhension, mais elle doit tout de même être mentionnée.

Certaines personnes utilisant EasyPeasy trouvent que leur désir de regarder du porno devient si réduit qu'elles ne peuvent pas se résoudre à faire une dernière séance. **C'est très bien**, mais ne sous-estimez pas le pouvoir d'en avoir une. Naviguer consciemment et solidifier à quel point vous détestez le PMO peut être vraiment puissant. Personnellement, j'ai trouvé cela très utile et j'étais heureux de m'en laver les mains ; sincèrement soulagé de ne plus jamais avoir à le faire. Cependant, votre expérience peut varier.

Si vous vous êtes déjà libéré du piège depuis un certain temps et que vous venez d'éliminer le lavage de cerveau, il n'est pas nécessaire de nourrir le petit monstre, car il ne ferait que vous harceler. Profitez plutôt de la liberté !

## Aidez-nous à mettre fin à ce scandale

La pornographie sur Internet est l'un des dangers d'une société libre, s'appuyant sur les efforts bien intentionnés des libertés individuelles. La base même de la civilisation - la raison pour laquelle l'espèce humaine a tant progressé - est certainement que nous sommes capables de communiquer nos connaissances et nos expériences, non seulement entre nous mais aussi aux générations futures. Même les animaux trouvent nécessaire d'avertir leur progéniture des pièges de la vie.

Les producteurs de porno ne le font pas de bonne foi, croyant sincèrement aider l'humanité, d'autant plus que la dépendance au porno sur Internet est largement étudiée. Peut-être qu'à ses débuts, les gens croyaient sincèrement que le porno éduquait les gens à l'intimité, mais les autorités savent que c'est une erreur. Aucun site de pornographie ne prétend véritablement éduquer. Les seules revendications portent sur le choc, la nouveauté et les qualités progressives de leurs produits.

L'hypocrisie pure et simple est incroyable. En tant que société, nous nous crispons sur le harcèlement scolaire et l'objectivation du corps humain. Comparés au porno sur Internet, ces problèmes ne sont que des boutons. Le nombre de personnes dépendantes atteint de nouveaux sommets chaque année, passant du temps de qualité avec des pixels imaginaires et illusoires au détriment de leur santé, de leur virilité, de leur énergie et de leur temps. De loin le plus grand tueur dans les relations, des centaines de milliers de vies sont ruinées chaque année parce qu'ils sont devenus accros. Les producteurs de pornographie sur Internet ne font pas de publicité dans les publications grand public - ils n'en ont pas besoin, nos pulsions biologiques nous conduisent au seuil de leurs harems bien remplis, distribuant des échantillons gratuits comme le dealer local. Aujourd'hui, les sites pornographiques ne stockent pas tant leurs produits qu'ils n'encouragent les visiteurs à publier du contenu.

Il est intelligent que les sociétés pornographiques affichent des avertissements 18+ pour dissuader les utilisateurs mineurs, alors que certaines ne prennent même pas la peine de le faire. La pornographie sur Internet touche tout le monde, à tout âge. "*Nous vous avons averti du danger, c'est votre choix*", telle est leur attitude. Prennent-ils des mesures pour vérifier l'âge ? Non, cela découragerait leurs clients. Bien sûr, si la vérification de l'âge est légiférée, ils trouveront simplement un autre pays pour opérer. Ou bien paieront-ils une "élite" pour écrire sur la façon dont la prohibition a entraîné la contrebande d'alcool et la création de la mafia ? On oublie commodément de se demander pourquoi l'abrogation de la prohibition n'a pas permis de réduire le nombre de victimes de l'alcool et pourquoi les forces de l'ordre n'ont pas réussi à contrôler le développement de la mafia.

Nous pouvons aborder cette question différemment en éduquant la jeune génération. S'ils peuvent éviter les cigarettes et l'alcool en faisant leurs courses, ils peuvent faire de même avec la pornographie sur Internet. Nous assistons déjà à des changements sociétaux tels que les mèmes "No Nut November" et "Coomer" qui deviennent courants. L'utilisateur n'a pas plus le choix que l'héroïnomane. Les utilisateurs ne décident pas de devenir dépendants, ils sont attirés dans un piège subtil. S'ils avaient le choix, les seuls consommateurs demain matin seraient des adolescents qui débutent, croyant pouvoir arrêter à tout moment s'ils le veulent.

Pourquoi ces normes factices ? Pourquoi les héroïnomanes sont-ils considérés comme des criminels, alors qu'ils peuvent s'enregistrer comme toxicomanes et obtenir de la méthadone et un traitement médical approprié pour les aider à s'en sortir ? Essayez de vous enregistrer en tant que dépendant du porno, si vous allez voir votre médecin pour qu'il vous aide, il vous dira soit : "*Arrêtez de le faire autant, essayez la modération*", ce qui, vous le savez déjà, ne marchera pas, ou bien il vous prescrira des médicaments pour traiter votre "dépression". Le pire est le conseil d'aller chercher de vrais partenaires, sérieusement ? Connaissent-ils des utilisateurs qui trouvent le porno meilleur et le font dans le dos de leur partenaire ? Certaines personnes ne comprennent tout simplement pas.

Les campagnes de peur n'aident pas les utilisateurs à arrêter, elles rendent les choses plus difficiles. Elles ne font qu'effrayer les utilisateurs, ce qui les incite à regarder encore plus. Elles empêchent également les adolescents de devenir accros. Les adolescents savent que le porno tue leur libido, mais ils savent aussi qu'un seul coup d'œil ne suffira pas. Comme la dépendance est très répandue, tôt ou tard, l'adolescent - soit par pression sociale, soit par curiosité - essaiera une seule visite. Et comme le porno gratuit propose des clips horribles, il est probable qu'ils deviennent accros.

Pourquoi laissons-nous ce scandale perdurer ? Pourquoi les gouvernements ne lancent-ils pas de véritables campagnes ? Pourquoi ne nous dit-on pas que le porno sur Internet est une drogue et un poison mortel, qu'il ne vous détend pas et ne vous donne pas confiance en vous, mais détruit vos nerfs, et qu'il suffit d'un seul coup d'œil pour devenir accro ? Pourquoi ne peuvent-ils pas faire respecter la vérification de l'âge en demandant des cartes de crédit enregistrées, peut-être avec une tierce partie ? Mindgeek, propriétaire de la plupart des grands sites pornographiques, tente d'escroquer les gouvernements pour qu'ils utilisent leur propre solution de vérification de l'âge - ne les laissez pas faire ! La machine à remonter le temps de H. G. Well décrit un incident dans un futur lointain où un homme tombe dans une rivière. Ses compagnons se contentent de rester assis sur la berge comme du bétail, inconscients des cris de désespoir. Inhumain et inquiétant, à l'image de l'apathie générale de la société face à la crise du porno.

Il y a un vent de changement de la société. Une boule de neige a commencé à dévaler la pente et nous espérons que ce livre contribuera à la transformer en avalanche. Vous aussi pouvez aider en diffusant le message.

À ce titre, je vous demande -- si vous voyez quelqu'un qui a du mal à utiliser la volonté, ou qui tente d'arrêter la pornographie, de bien vouloir l'orienter vers cette méthode. Cependant, la véritable tâche à accomplir est de changer le discours sur le porno en général. Prenez l'habitude, si vous voyez en ligne, ou même si vous faites l'expérience de la normalisation du porno, de chercher à éduquer et à libérer ces personnes de manière *respectueuse*.

Il se peut que vous receviez une réaction négative, mais parfois un commentaire suffit. Comme beaucoup l'ont fait avant vous, vous pouvez vous attendre à recevoir des messages de personnes reconnaissantes qui vous remercient pour leur liberté.

## Dernier avertissement

Vous pouvez maintenant profiter du reste de votre vie en tant que non-utilisateur heureux. Pour vous en assurer, vous devez suivre ces simples instructions.

1.  Conservez la page suivante dans vos signets et consultez-la autant que vous le souhaitez.

2.  Si jamais vous commencez à envier un autre utilisateur, rendez-vous compte qu'il vous enviera. Ce n'est pas vous qui êtes privé. C'est eux qui le sont.

3.  Souvenez-vous que vous n'aimiez pas être un utilisateur. C'est pourquoi vous avez arrêté. Vous aimez être un non-utilisateur.

4.  Rappelez-vous qu'il n'y a pas qu'un seul coup d'œil.

5.  Ne doutez jamais de votre décision de ne plus jamais regarder de porno. Vous savez que c'est la bonne.

6.  Si vous avez des difficultés, trouvez et contactez un thérapeute qui s'y connaît en matière de pornographie sur Internet. Vous pouvez en trouver des listes en ligne.