# Les Instructions

1.  Suivez toutes les instructions.

2.  Gardez l'esprit ouvert.

3.  Commencez par un sentiment d'exaltation.

4.  Ignorez tous les conseils et toutes les influences qui vont à l'encontre de EasyPeasy.

5.  Résistez à toute promesse de solution temporaire.

6.  Soyez clair dans votre esprit : Le porno ne procure aucun plaisir véritable ni aucune béquille et vous ne faites pas de sacrifice. Il n'y a rien à abandonner et aucune raison de se sentir privé.

7.  N'attendez pas pour arrêter, faites-le maintenant !

8.  Prenez la décision de ne plus jamais regarder de porno et ne la remettez jamais en question.

9.  Rappelez-vous qu'il n'y a pas qu'un seul coup d'œil.

10. Ne plus jamais regarder de porno.

## Les Affirmations

- Je suis libre de l'esclavage du porno.

- Il est facile d'ignorer mes pensées sur le porno.

- Bye bye les pensées, bye bye les envies. Adieu mes envies.

- Je concentre mon subconscient pour vaincre la dépendance au porno.

- Le porno me vole mon temps, mon énergie et ma vitalité.

- Vaincre le porno devient exponentiellement plus facile jour après jour et dans tous les aspects.

- J'apprécie et je valorise mon style de vie sans porno, fort, heureux, léger et facile.

- Si je regarde en arrière et que je pense à mes progrès, cela me procure une grande joie et une grande fierté de moi-même.

- Chaque fois que je vois d'autres utilisateurs de porno, je suis encore plus motivé pour me voir briser cette chaîne.

- Toute cette énergie refoulée est en train de guérir mon corps et mon esprit. Je peux alors faire un travail plus productif et plus stimulant pour atteindre mes valeurs et mes objectifs.

- Mon cerveau se remet en forme et s'exerce en ne faisant pas ce que je faisais auparavant.

- Maintenant, toute cette volonté refoulée est utilisée pour gérer le stress léger et les tensions de la vie.

- Super, je suis libre et je ne suis plus un esclave !