# La fin du livre
Me voilà, le Hackauteur Anonyme. 
Tout d'abord je vous remercie de tenir avec moi et avoir lu ce livre, c'est un livre assez dense niveau information et assez repepitif par moments, mais il vaut tellement la peine.

Normalement, j'allais faire comme avant et traduire cette partie du livre, mais sur un deuxième abord je l'ai trouvé un peu chargée pour un utilisateur vu que Fraser Patterson (un superbe tipeu) partage ses idées (dont cenrtaines, je ne suis pas en accord) et les ressources sont trop visées envers des anglophones.

Mais l'exprit de ce chapitre mérite une réecriture pour un public moins Anglo-Américain et plus Français, ce qui sera fait prochainnement (juré, promis).

## Comment puis-je aider EasyPeasy?

Tout d'abord, partage, partage, partage. L'addcition au contenu pornographique est tellement normalisé dans notre société que ce bouqin risque de faire plus de bien que de mal.

Puis bien sur, vous pouvez forker et demander une requête de fusion, en corrigeant les erreurs commises.

Aussi, pour ceux qui voudraient plus de contact, voici mon tag discord: asmy#8865 et mon corriel [ici](lioasmy@gmail.com)

