# Bevezető

Ezen hack-könyv segítségével azonnal, fájdalommentesen, és végleg felhagyhatsz a pornográfia használatával. A könyv nem ítélkezik, nem aláz meg, és nem kényszerít arra hogy fájdalmas lépéseket hozz.

Valójában, amíg olvasod, egyáltalán nem szükséges csökkentened a használatot. Sőt, így tenni kifejezetten káros lehet.

Lehet, hogy ez mindennel szembemegy, amit eddig hittél, de kérdezd meg magadtól, hogy az eddigi módszerek működtek-e. Ha működtek volna, most nem olvasnád ezt a könyvet.

A pornófüggőség számos módon manifesztálódik sok emberben, és ennek a hatásai a társadalomban is megérződnek. Sokan azért használják, mert az internetnek köszönhetően azonnal hozzá tudnak férni ezekhez a szupernormális (vagyis a normálisnál erősebb) stimulánsokhoz. Gondold át, hogy a következő állítások igazak-e rád.

-   Az eredetileg tervezettnél sokkal több időt töltesz pornónézéssel?

-   Sikertelenül próbálod  pornónézést abbahagyni vagy mérsékelni?

-   A pornónézés fontosabb lett, mint a szakmai vagy személyes ügyeid, a hobbijaid, a kapcsolatiad?

-   Minden követ megmozgatsz, hogy a pornófogyasztásod titokban maradjon (pl: kitörlöd az előzményeidet, hazudsz a használatodról)?

-   A pornónézés gondokat okozott az intim kapcsolataidban?

-   A pornóhasználat előtt izgalamat, utána pedig megbánást érzel?

-   Sokat gondolkozol a pornográfián, akkor is ha éppen nem nézed?

-   A pornográfia egyéb gondokat okozott a szakmai, vagy személyes életedben (pl: félbehagyott munka, gyenge teljesítmény, elhanyagolt kapcsolatok, pénzügyi nehézségek)?

Ha te egy olyan pornóhasználó vagy, aki az önkielégítés vagy a szex miatt függött rá, olvass tovább. Ha egy szerettedért aggódsz, győzd meg az illetőt hogy olvassa el ezt a könyvet.  Ha nem tudod meggyőzni, hogy olvassa el, olvasd el te magad, mert haérted a módszert, könnyebben el tudod az üzenetet juttatni az érintetthez, ezáltal megelőzheted hogy a gyerekeid elkezdjék. Ne tévesszen meg az, hogy most még nem férnek hozzá -- idővel hozzá fognak. 

## Figyelmezetés {-}

Előfordulhat, hogy ez a könyv téged nyugtalanít. Előfordulhat, hogy oly sok pornóhasználóhoz hasonlóan a pornóval való felhagyás gondolata is pánikkal tölt el, és bár szeretnél egy nap felhagyni vele, az a nap sosem ma van.

Ha arra számítasz, hogy a könyv majd addig ijesztget mindenféle egészségügyi kockázatokkal, mint például szexuális zavarokkal (többek között pornó okozta merevedési zavarral), megbízhatatlan felizgulással, azzal hogy a valódi szexpartnerek nem fognak érdekelni, agyi hipofrontalitással[^4], vagy azzal a váddal, hogy ez egy mocskos, visszataszító szokás, és te egy gyenge, gerinctelen kis hernyó vagy, csalódni fogsz. Az ilyesféle taktikák sosem segítettek, és ha segítettek volna, már felhagytál volna a használattal.

Az leszokáshoz való szokásos praktikák az akaraterőt, helyettesítési módszereket, például pornó-diétát (csak meghatározott időközönként használsz)  vagy a fogyasztás csökkentését írják elő. Ezek a módszerek hatástalanok, mert nem szüntetik meg az okokat amiért az ember pornót néz. Végül pedig, ha a függőség tárgyát egy tiltott gyümölccsé tesszük, azzal a függőség nem orvosolható. 

Számos oldal részletekbe menően beszámol az agyat érő hatásokról, szakmailag elbírált kutatásokat idézve a neurotranszmitterekről, és a neuroplaszticitásról. Ezek az oldalak tényleg informatívak, és sokan tisztában vannak a pornó veszélyeivel, mégse tesznek semmit. A használók többnyire elkerülik ezeket az oldalakat, abban bízva, hogy egy látogatás egy pornóoldalra nem fogja őket megölni.

Ezen módszer, amire a Járható Útként fogunk hivatkozni, máshogy működik. Olyan dolgok is el fognak hangzani, amiket nehéz lesz elhinni, de mire elolvasod majd a könyvet, nemcsak hogy el fogod ezeket a dolgot már hinni, hanem csodálkozni fogsz, hogy hogyan moshatták át az agyad olyannyira, hogy bármi mást higgy. 

Van egy olyan tévképzet, hogy mi döntünk úgy hogy pornót nézünk. A pornófüggők (igen, függők) is csak annyira döntenek úgy hogy pornót néznek, mint amennyire az alkoholisták döntenek úgy hogy alkoholisták lesznek, vagy annyira, mint amennyire a heroinisták döntenek úgy, hogy heroinisták lesznek. Tegyük hozzá, hogy az egyszer igaz, hogy mi döntünk úgy hogy bekapcsoljuk a laptopunkat vagy telefonunkat,  majd elindítjuk a böngészőt azért hogy meglátogassuk az online háremünket. Néha úgy döntök, hogy elmegyek a moziba (*ez a könyv még a járvány előtt íródott - a fordító*), de semmiképpen sem döntöttem úgy, hogy az egész életemet a moziban fogom tölteni. Eredetileg a kíváncsiság és az emberi természet vitt oda, de nem kezdtem volna bele, ha tudtam volna hogy függő leszek, ami pedig az egészségem, a boldogságom, és a kapcsolataim rovására fog menni. *“Bár hallottam volna a szexuális zavarokról, mielőtt még felkerestem volna az első pornóoldalt!”*

Egy pillanat erejéig, gondolj bele, hoztál-e már olyan “pozitív” döntést, hogy pornóra van szükséged az önkielégítéshez, vagy hogy szükséged van rá egyáltalán? Vagy hogy pornó-szerű fantáziákkal kell megfűszerezned a szext a pároddal? Vagy hogy nem tudtál pornónézés nélkül aludni? Vagy hogy nem tudtál nélküle koncentrálni, vagy a stresszt kezelni? Mikor jutottál arra pontra, amikor úgy döntöttél hogy neked igenis szükséged van a pornóra, hogy neked mindig is szükséged lesz a pornóra, és félelem tört rád, az online háremed nélkül.

Minden használóhoz hasonlóan téged is becsaltak az ember vagy a természet által valaha is felállított legalattomosabb, és legnehezebben észrevehető csapdába. Nincs a Föld színén olyan ember, használó vagy sem, aki békét lelne abban a tudatban hogy a gyermeke pornót használ azért, hogy megbirkózzon az élettel, vagy csak az “élvezetért”. Ebből kifolyólag, az összes függő azt kívánja, bár el se kezdte volna. Ez aligha meglepő: senkinek sincs szüksége a pornóra azért hogy a stresszt legyűrje vagy hogy az életet élvezze, mielőtt ráfüggne.

Egyúttal az összes használó tovább szeretné használni. Végülis, senki sem kényszerít, hogy elindítsuk a böngésző inkognitó módját. Akár értik az okát, akár nem, egyedül a használók azok, akik úgy döntenek, hogy az online háremük kapuin dörömbölnek.

Ha létezne egy olyan varázsgomb, amit a használó megnyomva, a következő reggel úgy ébredne fel, mintha sosem nézett volna fel az első pornó-oldalára, holnapra már csak a még mindig 'kísérletező' fiatalok lennének függők. 

A  szabadulás egyetlen akadálya a **FÉLELEM!** A félelmet az okozza hogy azt hisszük a szabadulásunkért cserébe egy meghatározatlan ideig  szenvedünk kell a pornó megvonása, és a kielégítetlen sóvárgás miatt. Ezek a tévképzetek több okból eredeztethetők, valamelyiket tanuljuk, valamelyik meg ránk ragad. Ilyenekre gondolok:

-   Az orgazmushoz vezető szex vagy önkielégítés az **egyetlen** és **legfontosabb** dolog az életben

-   A pornó “biztonságosabb” a valódi szexnél, mert a pornó nem utasíthat vissza

-   A pornó hasznos, és nevelő hatású

-   Az ember jogosult a szexuális élményekre

-   Minél több, annál jobb

Ezek a tévképzetek ésszerűtlen dolgokat eredményeznek, ha ezek alapján cselekszel, például:

-   Ha egy “tökéletes 10/10-et” találsz, a rögeszméddé válik.

-   Lúzernek érzed magad, ha nem jön össze a szex, mintha ez lenne a legfontosabb dolog az életben.

-   “Egy tökéletes 10/10-est” követelsz.

-   A potenciális partnereiddel túlságosan ítélkező és kritikus vagy.

-   Szexre kényszeríted magad, ha akarod, ha nem.

Félsz attól, hogy egy egyedül töltött éjszaka kibírhatatlan lesz, mert kontrollálhatatlan impulzusokkal kell harcolni. Félsz attól, hogy pornó nélkül a vizsgák előtti éjszaka maga lesz a pokol. Félünk attól, hogy a támaszunk nélkül nem fogunk tudni koncentrálni, a stresszel bírni, vagy hogy odalesz az önbizalmunk. 

De legfőképp, félünk attól, hogy *“aki függő, az is marad”*: attól hogy soha nem leszünk teljesen szabadok, és ebben a tudatban az töltjük az életünk hátralévő részét, a pornó-kiváltotta orgazmusért sóvárogva, mindenféle szokatlan időpontokban. Ha hozzám hasonlóan már az összes hagyományos módszert kipróbáltad, és átmentél az “akaraterő-módszer” okozta szenvedésen, akkor nem csak félni fogsz, hanem meg leszel róla győződve, hogy soha nem fogod tudni abbahagyni.

Ha aggodalmaskodsz, vagy pánikolsz, vagy úgy érzed, hogy az idő nem alkalmas arra, hogy felhagyj a használattal, hadd biztosítsalak arról, hogy az aggodalmadon a pornó nem fog segíteni -- lévén hogy az okozza. Nem te akartál beleesni a csapdába, de a csapda úgy van megtervezve, hogy ne tudj belőle kimászni. Kérdezd meg magadtól, hogy amikor először néztél pornográf képeket, vagy videókat, úgy döntöttél, hogy egész életedben vissza-vissza fogsz hozzájuk térni? Szóval, mikor fogod abbahagyni? Holnap? Jövőre? Ne szórakozz magaddal! A csapdát úgy tervezték, hogy egy életre benne maradj. Mi másért gondolod hát, hogy a többi függő nem hagyja abba, még mielőtt tönkreteszi az életét?

Említettem egy “varázsgombot”; a Járható Út egy varázsgombként működik. Azonban, hadd tisztázzak valamit: a Járható Út nem varázslat, de számomra és azok számára akik könnyűnek, és élvezetesnek találták a szabadulást, annak tűnik!

A figyelmeztetés így szól:
Ez egy tyúk és tojás szituáció: minden függő fel akar hagyni a használattal, és minden függő könnyűnek és élvezetesnek találhatja. Egyedül a **félelem** gátolja meg a használókat abban, hogy megpróbáljanak leállni. Az egyik legnagyobb nyereség az, hogy megszabadul az ember a félelemtől, de addig nem szabadulsz meg attól félemtől, amíg be nem fejezted a könyvet. Sőt, lehet hogy a félelmed nőni fog, ahogy haladsz a könyvben, és ez meggátolhat abban, hogy befejezd. Példának okáért, olvasd el ezt a kommentet egy hölgytől:

***“Nemrég olvastam ki a Járható Utat. Tudom hogy csak négy napja, de remekül érzem magam, tudom hogy soha többé nem lesz szükségem PMO-ra. A könyvedet 5 hónapja kezdtem el először olvasni, eljutottam a feléig, majd pánikba estem. Tudtam, hogy ha tovább olvasok, abba kell majd hagynom. Hülye voltam, nemde?”***

Nem te akartál a csapdába beleesni, de azt tartsd észben, hogy nem is fogsz belőle kijutni, hacsaknem döntesz úgy. Lehet hogy már a láncot rángatod, hogy végre abbahagyd, vagy lehet aggodalmas vagy már a gondolatától is, de mindenesetre emlékezz, **CSAK A LÁNCAIDAT VESZÍTHETED!**

Ha a könyv végén úgy döntesz, hogy tovább folytatod a pornóhasználatot, önkielégítésre, vagy szexre, semmi sem fog benne megakadályozni. Amíg olvasol, nem is kell csökkentened, vagy megszüntetned a használatot, és emlékezz, ez nem sokkterápia. Épp ellenkezőleg, kizárólag jó hírekkel szolgálhatok. El tudod képzelni, hogy A remény rabjaiban, hogy érezte magát Andy Dufresne, amikor végül kiszökött a börtönből? Én is úgy magam, amikor végül kimásztam a pornó csapdájából, és így éreznek az ex-használók, kik a Járható Út segítségével szabadultak ki, és a könyv végére, te is így fog érezni! Hajrá!

## Végül... {-}

Mindenki, és ebbe te is beletartozol, könnyen és élvezetesen felhagyhat a pornóhasználattal! Ehhez nincs más dolgod, csak el kell olvasnod a könyv hátralévő részét, lehetőleg nyitott hozzáállással; minél többet értesz meg belőle, annál könnyebb lesz. Ha követed az utasításokat, még akkor is sikerrel fogsz járni, ha még egy szót sem értesz belőle. Ami még fontosabb, nem fogsz a pornó után sírni, nem lesz hiányérzeted, és a könyv végére az lesz előtted az egyetlen rejtély, hogy miért néztél pornót ilyen sokáig.

A Járható Úttal két oka szokott lenni a sikertelenségnek.

**Az instrukciók véghez nem vitele.**
Lesznek olyanok, akik szerint zavaró, hogy a könyv ilyen dogmatikus néhány instrukcióval kapcsolatban, például hogy ne csökkentsd a használatod, vagy ne használj helyettesítseket.  Semmiképpen sem tagadom, hogy vannak olyanok, akik ilyen okosságok használata mellett sikerrel leszoktak, de ők a trükkök *ellenére*, és nem miattuk szoktak le. Néhány ember tud egy függőágyon állva szeretkezni, de az messze nem a legkézenfekvőbb. A csapdát záró számzárás lakat számai ebben a könyvben vannak, de a megfelelő sorrendben kell bevinni őket: fejezetről fejezetre haladva, és egyetlen egy fejezetet sem átugorva. 

**A könyv meg nem értése.**
Ne vegyél semmit sem magától értetődőnek, ne csak azt kérdőjelezd meg, amit hallasz, hanem a saját nézeteidet, és azt amit a társadalom mond  a szexről, az internetes pornóról, és a függőségről. Például azok, akik szerint ez csak egy szokás, kérdezzék meg maguktól, hogy miért van az, hogy a többi szokást, melyek közül valamelyik élvezetes, miért könnyű abbahagyni, és miért nehéz abbahagyni egy olyan szokást, ami mindig borzalmas érzés, sok energiába, pénzbe, és az életkedvedbe kerül. Azok, akik azt hiszik, hogy élvezik a pornóhasználatot, kérdezzék meg maguktól, hogy az olyan dolgok, amik sokkalta élvezetesebbek, miért olyan könnyű elhanyagolni? Miért kell neked pornót használnod, és pánikba esni, ha éppen nem lehet?

A Járható Út segítségével meg fogod tudni, hogy milyen egyszerű, és milyen élvezetes felhagyni a pornó használattal. Sokakhoz hasonlóan,  az egyik legdiadalmasabb pillanat az volt az életemben, amikor kiszabadultam a pornó csapdájából. Nem kell búsulni, épp ellenkezőleg, valami olyasmit készülsz elérni, amit a bolygó összes használója szeretne elérni: **A SZABADSÁGOT!**

**EMLÉKEZZ, NE UGORJ ÁT EGY FEJEZETET SE.**

Néhány hasznos kifejezés, mielőtt nekivágsz:
***PMO***: A pornó-maszturbálás-orgazmus ciklusa 
***Online hárem***:  Nagy sebességű internetes pornót tartalmazó oldalak
***Leállás, abbahagyás, felhagyás, leszokás***: Szövegkörnyezettől függően találhatóak itt meg, de mind ugyanazt jelentik: nem PMO-zol többet.

[^4]: Dióhéjban ez azt jelenti hogy nem jut elég vér az agy prefrontális kérgébe. Mindez még rövidebben azt jelenti hogy hülye leszel.
