# A Könnyű Módszer

A könyv célja az, hogy egy új hozzáállást honosítson meg a fejekben. A lelláshoz használt hagyományos módszerekkel szemben- ahol olyan érzés nekivágni, mintha a Csomolungmát másznád meg - és aztán az elkövetkező hetekben a használó sóvárog a pornó után, és hiányérzettel küzd, itt egyből örülhetsz, mintha valami szörnyű kórból gyógyultál volna meg. Onnantól kezdve, ahogy haladsz az életben, egyre többet fogsz erre az időszakrra visszatekinteni, és csodálkozni fogsz, hogy egyáltalán pornót használtál. A többi pornóhasználóra szánalommal, és nem irigykedve fogsz tekinteni.

Feltéve, hogy te nem olyasvalaki vagy, aki soha nem volt függő (egy szeretted miatt olvasod el), vagy már korábban felhagytál a használattal (vagy a “pornó-diéta” tartózkodási napjaiban vagy), fontos, hogy tovább használd a pornót, amíg teljesen be nem fejezted a könyvet. Ez ellentmondásnak tűnhet, és ez az az utasítás, hogy folytasd a pornóra önkielégítést, minden másnál több ellenkezést von maga után, de ahogy haladsz a könyvben, a vágyad a pornó iránt fokozatosan csökkenni fog. **Vedd ezt  az insrtukciót komolyan. Nem fog jót tenni, ha korán abbahagyod.**

Sokan be sem fejezik a könyvet, mert úgy érzik, hogy valami fel kell adniuk, olyanok is vannak, akik naponta szándékosan csak egy sort olvasnak el, hogy eltolják az “eseményt”. Nézd így, mi veszteni valód van? Ha a könyv végén nem állsz le, ugyanott vagy mint most. A helyzet, ami előállt, teljesen megfelel Pascal fogadásának, egy olyan fogadásnak amiben nem veszíthetsz semmit, és jó eséllyel nyerhetsz hatalmasat.

Ha történetesen egy pár napja nem néztél pornót, de nem vagy benne biztos, hogy használó, volt használó, vagy nem-használó vagy, ne használj pornót önkielégítéshez, míg olvasol. Sőt, ez esetben te már nem-használó vagy, de kell egy kis idő, míg az agyad a testedhez hozzáigazodik. A könyv végére egy boldog nem-használó leszel. A Járható Út a komplett ellentéte a normális módszernek, ahol az ember felsorolja a pornó jelentős hátrányait, majd így szól: 

*“Ha kibírnám pornó nélkül elég ideig, idővel nem vágynék rá többet, és ismét élvezhetem majd az életet, szabadon”* Ez egy teljesen logikus hozzáállás, és naponta ezrek állnak le ily módon. Azonban, nagyon nehéz így sikerrel járni a következő okokból:

**Nem a PMO abbahagyása a valódi gond.**
Mindig, amikor végzel egy alkalommal, abbahagytad a használatot. Erős okaid lehetnek arra, hogy a négynaponta-egyszer rendszerű pornódiétád első napján azt mondd: *“Nem akarok többet pornót nézni, vagy akár maszturbálni sem”*. Minden felhasználó akar, és az okaik sokkal erősebbek, mintsem el tudnád képzelni. Az igazi gond a második, tizedik, vagy tízezredik nap, amikor vetsz 1egyetlen árva pillantást', szeretnél még egyet, és hirtelen újra függő vagy.

**Az egészségügyi kockázatokkal tisztában levés félelmet generál, ezáltal nehezebb lesz leállni.** 
Mondd azt egy használónak, hogy a pornó a potenciája kárára megy, és az első dolga az lesz, hogy keres egy másik dopamin forrást: cigarettát,  alkoholt, vagy akár pornót.

**Az okok a leállásra valójában nehezebbé teszik.**
Ez két dolog miatt van így. Egy, folyamatosan arra vagyunk kényszerítve, hogy feladjuk 'kis cimboránkat', vagy támaszunkat, bűnünket, vagy örömünket (ahogy a használó felfogja).  Nem azokért az okokért maszturbálunk, amiért abba kéne hagynunk. A valódi kérdés az, hogy miért akarjuk, vagy kell csinálni?

A Járható Úttal (eleinte) megfeledkezünk azokról az okokról, amiért abba szeretnénk hagyni, szembenézünk a pornó problémájával, és feltesszük magunknak a következő kérdéseket: 

1.    Miben segít a pornó?

2.    Élvezem-e én egyáltalán?

3.    Az életemet tényleg a testemet és az elmémet szabotálva kell leélnem?

A gyönyörű igazság az, hogy a pornó az **égvilágon semmiben sem** segít. Hadd tisztázzam, nem az a helyzet,  hogy annak ha pornóhasználó vagy több a hátránya, mint az előnye, hanem az hogy **semmi** előnye nincs az internetes pornó nézésének. 

Sok használó racionalizálni kívánja a pornóhasznalatát, de az érveik mind tévképzetek és illúziók. 

Először is, meg fogunk szabadulni ezektől a tévképzetektől és illúzióktól. Sőt, hamarosan rá fogsz jönni, hogy csodálatos, pozitív dolgokat nyerhetsz, ha megszabadulsz a PMO-tól, úgy hogy a jólét, és a boldogság csak kettő közülük. Amint eltávolítjuk az illúziókat,  hogy az élet soha többé nem élvezetes pornó nélkül, rá fogsz jönni hogy az élet nemcsak ugyanannyira élvezetes nélküle, hanem  milliószor élvezetesebb, és amikor eltűnik a megfosztottság érzése, ismét bele fogsz gondolni a jólétbe, a boldogságba -- és a tucatnyi többi okba, hogy felhagyj a pornóval. Ezek segíteni fognak abban, hogy elérd azt amit igazán szeretnél:  a pornófüggőség rabigája nélkül élvezni az életet!
