# Miért nehéz leállni?

Minden használó úgy érzi, hogy valami ördöngös dolog szállta meg őt. Az elején még csak az megy hogy *“abbahagyom, de nem ma”*, de idővel oda jutunk, hogy azt gondoljuk nincs elég akaraterőnk ahhoz hogy leálljunk, vagy hogy van valami a pornóban, amivel muszáj rendelkeznünk, azért hogy élvezni tudjuk az életet. A pornófüggőség ahhoz hasonlítható, amikor egy csúszós gödörből akarsz kimászni: ahogy közeledsz a tetejéhez, látod a napfényt- de egyből lecsúszol, amikor a hangulatod nem olyan jó. Idő kérdése hogy megnyisd a böngészőt, és önkielégítés közben borzalmasan érzed magad, és megpróbálsz rájönni, hogy miért is  kell ezt csinálnod.

Kérdezz meg egy használót: *“Ha visszamehetnél az időben azelőttre, hogy ráfüggtél, úgy hogy tudod azt, amit most tudsz, elkezdtél volna pornót használni?”*

*“SEMMIKÉPP SEM!”*-válaszolna a használó. 

Kérdezz meg egy megrögzött használót, olyasvalakit aki megvédi az internetes pornót, és nem hiszi hogy káros az agynak, és nem hisz a dopamin receptorok leépülésében: *“Bátorítanád a gyerekeid arra hogy pornót nézzenek?”*

**“SEMMIKÉPP SEM!”**-szólna ismét a válasz

A pornó egy rendkívüli rejtély. Mint ahogy azt már feljebb elhangzott, nem azt nehéz elmagyarázni, hogy miért könnyű leállni, hanem azt hogy miért nehéz. Részben azért kezdjük el, mert már több tízmillió ember ráfügött, de mindnyájan azt kívánják, bár el ne kezdték volna, és azt mondják, hogy olyan, mintha csak második sebességen lenne a képletes sebváltó. És még így se bírjuk teljesen elhinni hogy nem élvezik. A pornót a szexuális felvilágosítással asszociáljuk, és keményen dolgozunk azért, hogy magunk is függők legyünk, aztán az egész életünket azzal töltjük, hogy másoknak mondjuk, hogy ne csinálják, és aztán próbálunk róla leszokni.

Időnk jelentős részét pedig kesergéssel, és nyomorgással töltjük. Amikor 'szupernormálissal' oktatjuk magunkat, az agy ezeket az élettelen képeket fogja preferálni, még akkor is, ha valódi partnerek is elérhetőek! A PMO által előidézett dopamin hullámok által egy életnyi ingerlékenységre, haragra, stresszre, levertségre, és szexuális zavarokra ítéljük magunkat. Pornót használva, lévén hiányoznak belőle a szex, és a kapcsolatok legjobb részei, nyomorultul, és bűntudattal telve érezzük magunkat.

Sőt, az internetes pornó addiktív és pusztító hatásairól való olvasás, mind itt, és máshol, idegessé, és reménytelenné tesz. Miféle hobbi az, amit ha éppen csinálsz, azt kívánod bár ne tennéd, és ha nem teszed, sóvárogsz utána? A használók utálják magukat, mindig amikor a hipofrontalitásról és a hatás elvesztéséről olvasnak, mindig amikor a partnerük háta mögött használják, mindig amikor nem képesek edzeni az egész napos használat után. Egy egyénként okos és racionális ember az egész napját megvetésben tengeti. De ami a legrosszabb, mit kapnak a használók azért, hogy elviselik az életet ezekkel a szörnyű, fekete árnyékokkal az elméjükben? **Semmit az égvilágon!**

Lehet hogy azt gondolod *“Ez így rendben van, tisztában vagyok vele, de amint ráfüggtél az ilyesmi dolgokra, nagyon nehéz leszokni.”* De miért nehéz? Valakik szerint az erős elvonási tünetek miatt van ez, de ahogy meg fogod tudni, az elvonási tünetek olyan haloványak, hogy vannak olyan PMO-zók, kik anélkül éltek és haltak, hogy valaha rájöttek volna, hogy ők drogfüggők.

Valakik szerint pedig az internetes pornó ingyen van, és így az emberiségnek ki kéne használnia ezt a biológiai aranybányát, de tévednek -- a pornó függőséget okoz, és úgy csinál, mint bármilyen más drog. Kérdezz meg egy használót aki esküszik hogy csak az erotikus magazinokat, mint például a Playboyt élvezi, hogy átlépte-e már vonalat a “biztonságtalan pornó” irányába, és ha teljesen őszinte, nem győzné számolni, hogy hányszor racionalizálta már magában, amikor használta.

Az élvezet sem játszik semmilyen szerepet. Szeretek rákot enni, de sohasem jutottam el arra a pontra hogy minden nap rákot kellett ennem. A többi dolgot az életben élvezzük, amikor csináljuk, de nem ülünk hiányérzettől gyötörve, amikor éppen nem.

Néhányan azt mondják:
*"Oktató jellegű"*" Mikor fogsz belőle vizsgázni?
*“Szexuális kielégülést okoz”* Miért egyedül csinálod, és miért nem egy partnerrel együtt?
*“Felszabadító érzés”* Megszabadít a világ okozta stessztől? A pornó nem szünteti meg a stressz forrását, hanem csak hozzáad.

Sokan úgy hiszik, hogy a pornó megszünteti az unalmat, ami szintén nem igaz. Az unalom egy elmeállapot. A pornó arra ösztönöz, hogy mindig keresd az új tartalmat, ami miatt egyre inkább unatkozni fogsz, amíg nem kezdesz el egy új, megfelelő videót keresni, ami miatt  az agyad egyre jobban arra lesz programozva, hogy újdonságok, erős érzelmek, és idővel sokkoló dolgok után nézzen.

Néhányan azt mondják, hogy csak azért csinálják, mert a barátaik, és az összes ember akit ismernek, szintén csinálja. Ha ez így van, imádkozz, hogy a barátaid nem kezdik el levágni a fejüket fejfájás ellen. A legtöbb felhasználó, ha belegondol, arra a következtetésre jut, hogy ez csak egy szokás. Ez nem magyarázat, de mivel már az összes ésszerű magyarázatot elvetették, úgy tűnik ez az egyetlen megmaradt magyarázat. Sajnos ez is ugyanannyira logikátlan. Az életünk minden napján változtatjuk a szokásainkat, és valamelyik szokásaink igen élvezetesek. Az agymosás terméke, ha azt hisszük, hogy a PMO egy szokás, és hogy a szokásokat nehéz megtörni.

Nehéz lenne megtörni a szokásokat? A kontinensen az a szokás, hogy az autók az út jobb oldalán mennek, de ha egy autós átmegy Nagy-Britanniába, különösebb problémák nélül megtörik ezt a szokást. Az hogy a szokásokat nehéz megtörni, egyértelműen egy tévedés. Életünk  minden napján bevezetünk új szokásokat, és félbehagyunk régieket. Tehát, miért találjuk nehéznek, hogy megtörjünk egy szokást, ami miatt megvonást érzünk, ha éppen nem csináljuk, bűntudatunk van, ha csináljuk, egy olyan szokást amit egyébként is szeretnénk megtörni, miközben ahhoz hogy megtörjük, az egyetlen dolgunk az, hogy ne csináljuk?

A válasz az, hogy a pornó nem egy szokás, hanem **függőség!** Ezért tűnik úgy hogy nehéz “feladni”. A legtöbb használó nem érti a függőséget, és azt hiszi, hogy a pornó valódi örömöt, vagy támaszt ad neki. Azt hiszi, egy komoly áldozatot hoznak, ha felhagynak vele.

A gyönyörű igazság az, hogy amint megérted a függőség természetét, és hogy miért használod, abba fogod hagyni, csak úgy. Három héten belül, az egyetlen rejtély az lesz, hogy miért érezted szükségesnek a pornóhasználatot ilyen sokáig, és hogy miért nem tudod meggyőzni a többi használót, hogy miért *olyan jó nem PMO-zni!*

## Az alattomos csapda

Az internetes pornó a az ember vagy a természet által valaha is felállított legalattomosabb, és legnehezebben észrevehető csapda; ez az egyetlen csapda a természetben, aminek a felállítása nem igényel kemény munkát. Vannak olyanok, akik tisztában vannak a veszélyekkel, de nem bírjuk elhinni, hogy nem élvezik. De mi az, ami miatt elkezdjük? Tipikusan, ingyenes minták amatőröktől, és profiktól, akik megosztják a tartalmat. Így nyílik ki a csapda, az első 'pillantásod' messze nem tökéletes, hiszen bármilyen pornóoldalon a nyitóképek általában amatőr kinézetűek, és ismeretlen modelleket szerepeltetnek. Ha az új használó csak angyali szépségeket, és profi modelleket látna, egyből szólna a riasztó.

A videókban lévő eltérés miatt, a fiatal elméink megbizonyosodnak affelől, hogy sohasem lesznek függők, azt gondolva, hogy mivel nem élvezzük, bármikor abbahagyhatjuk. Intelligens emberi lényekként megértenénk, hogy a felnőtt népesség fele miért függ rá egy olyan dologra, ami aláássa az arra való képességüket, amit éppen néznek. A kíváncsiság közelebb visz a pornó küszöbéhez, de nem merünk rákattintani egyes nyitóképekre, attól félve, hogy megbetegít. Ha véletlenül rákattintasz egyre, csak arra vágynál, hogy minél messzebb kerülj attól az oldaltól.

Ezután egész életünkben azt próbáljuk megérteni, hogy miért csináljuk, mondjuk a gyerekeknek, hogy el ne kezdjék, és néha magunk is megpróbálunk kiszabadulni. A csapdát úgy tervezték, hogy csak egy 'incidens' után próbáljunk megállni, legyen az szexuális teljesítménybeli, egy karrier, vagy egy párkapcsolat félbetörése, az ösztön meggyengülése, vagy csak az hogy hullaként érzed magad. Amint leállunk, az elvonási kattogás miatt a stressz csak növekszik a használt módszerrel.

Pár napnyi kínzás után úgy határozunk, nem a jó időt választottunk arra hogy leálljunk, úgy döntve, hogy várunk egy stressz nélküli időszakra, ami ha eljön, megszünteti az okainkat, amiért leálltunk volna. Az az idő sohasem fog eljönni, mert belül úgy hisszük, hogy az élet csak egyre stresszesebb lesz. A szüleink védelmét elhagyva, különböző stresszel járó dolgokkal fogunk találkozni, például munka, az otthonunk megteremtése, jelzálog, gyerekek, nagyobb ház, több gyerek. Ez egy illúzió, az igazság az, hogy bármely lény életének legstresszesebb időszaka mindig a kora gyermekkor és a serdülőkor.

Hajlamosak vagyunk a stresszt és a felelősséget összekeverni. Egy használó élete -- csakúgy mint egy drogfüggőé -- automatikusan több stresszel jár, mert a pornó nem nyugtat meg, és nem oldja a stresszt, ahogy néhányan próbálják elhitetni. Épp ellenkezőleg, ahogy használod, a stressz csak nőni fog, és több vízcsepp fog cseppeni a már majdnem teli pohárba. Még azok a használók is, akik megszabadulnak a szokástól (a legtöbben életük során egyszer vagy többször megteszik), teljesen boldog életet tudnak élni, de egyszercsak újra függők lesznek. Besétálva a pornó útvesztőjébe az elméink elhomályosodnak, és az életünk hátralévő részében szabadulni próbálunk. Néhányan sikerrel járnak, aztán később ismét foglyul ejti őket a csapda.

A pornófüggőség egy összetett, és lenyűgöző kirakós, és a Rubik kockához hasonlóan, tulajdonképpen lehetetlen kirakni. De ha megvan a megoldás, egyszerű és mókás lesz! A Járható Út tartalmazza a kirakós megoldását, melynek segítségével kijuthatsz az útvesztőből, és soha többé nem sétálsz bele. Nincs más dolgod, mint követni az utasításokat. Azonban, ha rossz irányba fordulsz, a többi utasítás elveszti az értelmét. 

Bárki könnyűnek találhatja a leállást, de előbb pár tényt meg kell állapítani. Nem, nem olyan tényeket, amivel ijesztgetnek, már elég információ lelhető fel. Ha ezek miatt leállnál, már megtetted volna. De miért érezzük nehéznek a leállást? Ahhoz hogy ezt megválaszoljuk, tudnunk kell, hogy miért használunk továbbra is pornót, ami két okra vezethető vissza, amelyek:

-   A természet és az internetes pornó

-   Agymosás

A pornóhasználók intelligens, és ésszerű emberek. Tudják, hogy hatalmas kockázatot vállalnak a jövőre nézve, ezért sok időt töltenek azzal, hogy a 'szokásukat' ésszerűsítik. Azonban a szívük mélyén a pornóhasználók tudják hogy hülyék, tudják hogy nem volt szükségük pornóra, mielőtt ráfüggtek volna. Emlékeznek, hogy az első 'pillantásuk' az undor és a kíváncsiság keveréke volt. Ezután meg az oldalak megtalálásában, kiszűrésében, és  könyvjelzőzésére szakosodnak, nagy energiákat fektetve bele, hogy függők legyenek.

Ami a legidegesítőbb, hogy van egy érzés, hogy a nem-függők -- a legtöbb nő, az idősebb férfiak, és nagysebességű internettel nem rendelkező országokban élők -- nem maradnak le semmiről, és hogy a helyzet szinte komikus. Ezeket a tényezőket lebontva a következő fejezetekben, te is meg fogod érteni az alattomos csapdát!

