# Mit adok fel?

**Semmit az égvilágon!** A pornót nehéz feladni, mert attól félünk, megfosztjuk magunkat az örömünktől vagy a támaszunktól. Attól félünk, hogy bizonyos helyzetek soha nem lesznek utána ugyanolyanok. Félünk, hogy nem fogjuk tudni kezelni a stresszes helyzeteket. Máshogy fogalmazva, ezek az agymosás hatásai, amik azt hitetik el velünk, hogy a szex --és ezt továbbgondolva az orgazmus-- kötelező mindenkinek. Sőt, még azt is, hogy a pornóban van valami benne rejlő dolog, ami kell nekünk, és hogy amikor leállunk a használattal, ezt megtagadjuk magunktól, és egy űrt képzünk. 

Vésd szilárdan az eszedbe: **a pornó nem betölti, hanem** ***létrehozza*** **az űrt!**

Az emberi test a legbonyolultabb dolog a Földön. Akár a tudatos tervezésben, akár a természetes kiválasztódásban, vagy a kettő kombinációjában hiszel, a testünk ezerszer hatékonyabb bármilyen gépnél. Nem tudjuk megteremteni a legkisebb élő sejtet, vagy a látás csodáit, a szaporodási, és mindenféle összekapcsolt rendszereket az agyunkban és a  testünkben. Ha a Teremtő, vagy a folyamat azt akarta volna hogy kezelni tudjuk a szupernormális stimulánsokat, másféle jutalmazó rendszert adott volna. A testünk biztonságos figyelmeztető rendszerekkel van ellátva, és a saját kárunkra hagyjuk őket figyelmen kívül. 

## Nincs mit feladni

Amint kipurgáltad a kicsi szörnyt a testedből, és az agymosást (a nagy szörnyet) az elmédből, se nem akarsz majd rendszeresen önkielégíteni, se nem akarsz hozzá majd internetes pornót használni. Sok dolgot tudunk a pornófüggőségről, és sokat nem, és sok orvos nem tud embereket pornófüggőnek besorolni, vagy kikérdezni valakit, hogy az-e. Sok jelentett tünetet tévesen másnak tulajdonítanak. Nem arról van szó, hogy a használók hülyék lennének, csupán arról, hogy pornó nélkül meg vannak lőve. Csúnya helyzetbe kerültek, mert vagy tartózkodnak és nyomorultul érzik magukat, mert nem használhatnak pornót, vagy bűntudatuk van, emiatt saját magukat utálják meg, és aztán ezért érzik nyomorultul magukat. Amikor tüneteik lesznek,  például alsóháti fájdalom vagy szexuális zavarok, kettészakad az elméjük, aközött hogy elfogadják a felelősséget, vagy hogy más irányba nézzenek.

Egy másik dohányos analógia következik, mindenki látott már dohányosokat, akik előállnak valamilyen kifogással, hogy nagy cselesen elszívjanak egy cigit, és ilyenkor látjuk a valódi függőséget akcióban. A függők ezt nem azért csinálják, mert élvezik, hanem mert enélkül nyomorultul érzik magukat. 

Sokak első szexuális élménye orgazmusban ért véget, ezért az ragadt meg bennük, hogy a szexet anélkül nem is élvezhetik. A férfiaknak a pornót a szexhez való segítségként reklámozzák, sőt néha még a szex közbeni magabiztosságot segítő oktatatásként is. Ez hülyeség, a hozzászoktatás a szupernormális stimulánsokhoz kizárólag a magabiztosság rombolásában segít. 

Nemcsak hogy nincs mit feladni, de hatalmasakat lehet nyerni. Amikor a használók a pornó abbahagyásán gondolkoznak, hajlamosak az egészségre, és a férfiasságra koncentrálni. Ezek érvényes és fontos indokok, de személy szerint azt hiszem, hogy a legnagyobb jutalmak pszichológiaiak:

-   Az önbizalmad és a bátorságod visszatér.

-   Felszabadulsz a rabságból.

-   Az elmédből eltűnnek a borzalmas árnyékok, és nem utálod magad többé.

## Mily’ gyönyörű az űr!

Képzeld el, hogy van egy kiütés az arcodon, ezért elmész a gyógyszertárba, ahol kipróbálásra ingyen adnak egy kenőcsöt. Applikálod a kenőcsöt, és a kiütés azonnal eltűnik. Rá egy héttel újra előjön a kiütés, ezért visszamész a gyógyszertárba, és megkérdezed, van-e még a kenőcsből. A patikus azt mondja, hogy *“Persze; tartsa meg a tubust, lehet még kelleni fog.”*

Bekened az érintett területet, és nézzenek oda, eltűnt a kiütés! De mindig amikor a kiütés visszatér, nagyobb és fájdalmasabb lesz, és a visszatérések között idő meg egyre rövidebb. Idővel a kiütés elfedi az egész arcodat, közben kibirhatatlanul fájdalmas, és fél óránként visszatér. Tudod hogy a kenőcs átmenetileg eltávolítja, de nagyon aggódsz. Át fog terjedni a kiütés az egész testedre? El fog tűnni a visszatérések közötti idő? Elmész a háziorvoshoz, de nem tudja meggyógyítani, tehát kipróbálsz egyéb dolgokat is, de a kenőcsön kívül semmi sem segít.

Eddigre már teljesen a kenőcstől függesz, sehova sem mész, anélkül hogy nem bizonyosodnál meg róla, hogy van nálad egy tubus. Ha külföldre mész, több tubust is viszel. Az egészségügyi aggodalmakon felül, a tubus darabja húszezer forintba kerül. Nincs mese, fizetned kell.

Egy napon egy cikkbe botlasz, ahol ezt vitatják meg, és ott kiderül, hogy ez nem csak veled történik, sokan mások is ugyanettől a problémától szenvednek. Sőt, az orvosok rájöttek, hogy a kenőcs igazából nem gyógyítja a kiütést, hanem csak a bőr felszíne alá viszi. A kenőcs miatt nőtt meg a kiütés, tehát nincs más dolgod, csak hagyd abba a kenegetést, és a kiütés hamarosan el fog tűnni. Tovább használnád a kenőcsöt? Akaraterő kellene ahhoz, hogy ne használd? Ha nem hittél a cikknek, egy pár napig még aggodalmaskodnál, de amint rájössz, hogy a kiütés elkezdett gyógyulni, többé nem kellene, és nem is akarnád a kenőcsöt használni. Nyomorultul éreznéd magad? Persze hogy nem! Volt egy komoly panaszod, amiről azt hitted, hogy gyógyíthatatlan, de megtaláltad rá a gyógyírt. Ha a kiütésnek egy évébe telt volna eltűnnie, minden egyes nap ahogy egyre javult, azon gondolkodnál, hogy milyen csodálatosan érzed magad. Ez a pornóról való leszokás varázsa. 

A kiütés nem a fájdalom, a rendes vágyakozás hiánya, a gyengülő felizgulás, az egyre gyengébb penetráció, a kétdimenziós képekre elpazarolt idő, a pornóra való vélt jogosultságod esetleges megsértésének az érzése, azon emberek utálata akik esetleg tetten értek, vagy még rosszabb, saját magad utálata. Ezek a kiütésen felül vannak meg. 

A kiütés miatt a homokba dugjuk a fejünket ezekkel kapcsolatban, a kiütés annak az érzése hogy pornót akarsz. A nem-használók nem szenvednek ettől az érzéstől. A legrosszabb amitől szenvedünk, az a félelem, tehát a legjobb dolog amit nyerhetünk, az a szabadulás a félelemtől. A félelmet a legelső használat okozza, és a többi mind megerősíti.

Néhány használó ‘boldog’, mert  megvakította a kicsi szörny, tehát ugyanezen a rémálmon megy keresztül, átlátszó érvekkel megpróbálva igazolni a hülyeségét.

*Olyan jó szabadnak lenni!*
