# Időszerzés

Amikor a használók le akarnak szokni a pornóról, a fő okuk az egészségük, és a társuk stigmája szokott lenni. Része ennek a szörnyű drog által előidézett agymosásnak a rabszolgaság, az emberek keményen küzdöttek sok helyen a rabszolgaság eltörléséért -- a használó mégis önmagát rabigába hajtva szenved egy életen át. Nincsenek annak tudatában, hogy amikor tudnak pornót használni, azt kívánják, bárcsak nem-használók lennének. A pornó egyedül akkor válik értékessé, amikor vissza akarunk venni a használatból, vagy tartózkodni, vagy amikor kényszerből tartózkodunk.

Nem lehet elég gyakran elismételni, hogy mivel az agymosás miatt nehezebb leállni a pornóval, ezért minél több hazugságot cáfolunk meg, mielőtt elkezdenénk, annál könnyebb lesz elérned a célodat. A megrögzött használók, akik szerint a pornó nincs rossz hatással az egészségükre (pornó okozta merevedési zavar, hipofrontalitás, stb), és akiknek nincs kötélhúzás az agyában, általában fiatalabbak, vagy egyedülállóak, alkalmi szexpartnerekkel. Ezért a belső visszajelzés elveszik a fiatalságuk természete miatt, vagy csak túl ritka ahhoz, hogy meg tudják figyelni és észrevenni. 

Egy még jobb érv a fiatal használónak a pornóval töltött idő, tehát azt mondod hogy *“nem hiszem el, hogy mennyi időt töltesz ezzel”*. A szemeik ilyenkor felélénkülnek, és hátrányban érzik magukat, ha egészséggel, vagy a társadalmi stigmával támadják őket, na de ha az idővel…
*“Ó hát van rá időm, csak heti x óra, meg szerintem megéri, ez az egyetlen bűnös élvezetem”*

*“Továbbra sem hiszem el, hogy nem aggódsz. Tételezzük fel egy fél órás napi átlagot, ami tartalmazza a dopamin elvonási tüneteket is, egy teljes munkanapnyi időt töltesz el két hetente. Bizonyosan egyetértenél, hogy a napi fél óra egy nagyon szerény becslés. Belegondoltál már hogy mennyi időt fogsz egész életedben ezzel tölteni? És mit csinálsz az alatt az idő alatt? Valódi kapcsolatokat építesz? Nem, a kedvenc pornósztárod nem szimpatizál veled, csak azért mert olyan sok időt töltesz a videóin - az ablakon dobod ki az időt! Nemcsak ez, hanem ez idő alatt az egészségedet teszed tönkre, elpusztítod a nyugalmad, és az önbizalmad, csak azért hogy egy életen át szenvedhess a rabságtól, fájdalomtól, melankóliától és nyűgösségtől. Ez biztosan aggodalommal tölt el, nemdebár?*

Eddigre már jól látszik -- főleg a fiatalabb használóknál -- hogy sosem egy életen át tartó függőségként tekintettek a pornóra. Időnként kigondolják hogy mennyi időt pazarolnak el egy hét alatt, és már az az idő is rendkívül aggasztó. Igen ritkán, és csak akkor ha le terveznek állni, becsülik csak fel, hogy mennyi időt töltenek el egy évben - de hogy egy élet alatt mennyit, az elgondolhatatlan. Azonban, mivel egy vita közben vagyunk, a használó csuklóból azt fogja mondani hogy *“belefér, csak ennyi idő hetente”*, saját magán eljátszva a klasszikus marketingfogást. 

Elutasítanál-e egy állásajánlatot ami a jelenlegi fizetésedet adja, és közben van egy egybefüggő hónapnyi szabadságod minden évben? Mindegyik használó gondolkodás nélkül aláírná, és neki is látna nyaralásokat nézni egzotikus helyekre. A legnagyobb probléma az lenne, hogy kitalálja, hogy tölti el azt a szabad hónapot. A megrögzött használókkal (ne feledd, az nem egy olyasvalaki mint te, aki le tervez állni) folytatott beszélgetések során senki sem fogadta el ezt az ajánlatot. Miért? A megrögzött használó ilyenkor gyakran azt mondja hogy *“Nézd, engem a pénz nem nagyon izgat.”* Ha ilyesmi módon gondolkodsz, tedd fel magadnak a kérdést, hogy miért nem. Az élet többi részén miért töröd magad hogy megspórolj pár száz forintot, és közben miért dobsz ki több tízezret, az árral nem törődve, azért hogy boldogtalan légy?

Az összes többi döntésed az életben mind egy analitikus folyamat eredménye, ami során átgondolod az előnyöket és a hátrányokat, hogy egy ésszerű döntést tudj hozni. Lehet hogy végül rossz döntésnek bizonyul, de racionális következtetések eredményeképpen hoztad meg. Ha bármilyen felhasználó bármikor átgondolja az internetes pornóhasználat előnyeit és hátrányait, az eredmény századjára is az hogy: **“HAGYD ABBA! EGY BALEK VAGY!”** Ebből kifolyólag minden használó csak azért használja, mert nem bírja abbahagyni, és nem azért mert szeretné, vagy mert úgy döntött. **Muszáj** pornót használnia, ezért átmossa a saját agyát, közben a fejét a homokba dugva.

A megrögzött használók ne feledjék, hogy a helyzet csak egyre inkább romlani fog, mert egyre több tanulmány készül el, és egyre több ember beszél az internetes pornó káros hatásairól. Ma az átlagemberek beszélnek a hatásairól, holnap már az orvosi diagnosztikai tesztek listáján lesz. Elmúltak már azok a napok, amikor a használó elpalástolhatta a szexuális alulteljesítést a munkahelyi stresszel, a partnered meg fogja már kérdezni hogy miért nézed késő este a laptopodat. A szegény használó --aki már eleve rosszul érzi magát-- most már azt kívánja, bárcsak elnyelné a Föld.

Az a furcsa, hogy sok ember hajlandó komoly összegeket kifizetni edzőtermi bérletért, meg személyes edzőért hogy izmot szedjen fel, és kigyúrt legyen és sokak a képzelt (és valós) elkeseredésükben a tesztoszteronszintjüket gyanús és veszélyes mellékhatásokkal járó (mód)szerekkel próbálják növelni. És ebben a csoportban sokan vannak, akik jól járnának ha leállnának az agyuk nyugalmi rendszereit elpusztító tevékenységgel.

Ez  azért van, mert még mindig a használó agymosott elméjével gondolkodnak. Egy pillanatra dörzsöld ki a homokot a szemedből. Az internetes pornó egy láncreakció és a lánc egy életen át tart, és hacsaknem töröd meg a láncot, egész életedben használó fogsz maradni. Becsüld fel, hogy szerinted mennyi időt fogsz a pornóval tölteni életed hátralévő részében, és a mennyiség mindenkinél más lesz, de most számoljunk azzal, hogy másfél évnyi munkaóra. Képzeld el, hogy egy másfél évnyi fizetésedet tartalmazó lottószelvény heverne holnap az ajtód előtt! Ez esetben táncra perdülnél az örömtől, tehát neki is kezdhetsz! Hamarosan megkapod ezeket a jutalmakat!

Ha azt hiszed hogy ez a dolgok csűrés-csavarása, akkor továbbra is szórakozol magaddal. Számold ki, mennyi időt spóroltál meg volna, ha rá sem pillantottál volna valaha pornóra. 

Hamarosan meg fogod hozni a döntést, hogy sort kerítesz az utolsó használatra (Még ne, emlékezz az utasításokra!), és nem-használó maradsz, mert többé nem esel bele a csapdába. Ahhoz hogy nem-használó maradj, nincs más dolgod, mint hogy ne használj pornót, és hogy kerüld az ‘egyetlen kis pillantást’. Emlékezz, ha mégis megteszed, az a becsült fizetésedbe fog kerülni. 

Ha valakinek a pornófüggőségén segítesz, mondd el neki, hogy ismersz valakit, aki elutasított egy állásajánlatot, ami az éves fizetését fizette, egy hónapnyi fizetett szabadsággal. Ha megkérdezi, hogy ki volt az a kretén, mondd neki hogy ***“Te!”***. Ez igen udvariatlan, de néha bunkónak kell lenni, hogy átjöjjön az üzenet.
