# Egészség

Ez az a terület, ahol az agymosás a legerősebb a használóknál - különösen a fiatal és egyedülálló használóknál- akik azt hiszik hogy tisztában vannak az egészségügyi kockázatokkal, de nincsenek. Sokan azzal hülyítik magukat, hogy azt mondják, hogy készen állnak elfogadni a következményeket. Ha a routereden lenne egy olyan funkció, ami egy riasztó hangjelzést ad le, ha rámész egy pornóoldalra, azt mondva *“Eddig megúsztad, de ha még egy percig maradsz, felrobban a fejed.”* Maradnál? Ha kételkedsz a válaszban, próbálj egy szikla szélére állni csukott szemmel, és képzeld el hogy választanod kell, hogy vagy leállsz a pornóval, vagy bekötött szemmel tovább haladsz.

Nincs kétség afelől, hogy mit választanál, de azzal hogy a fejed a homokba dugod, és hogy reménykedsz hogy egy reggel majd úgy ébredsz fel, hogy többet nem akarsz pornót nézni nem érsz el semmit. A használók nem engedhetik meg maguknak,hogy belegondoljanak az egészségügyi kockázatokba, mert ha megteszik a függőségük képzelt élvezete odalesz. Ez megmagyarázza hogy a sokkterápia miért olyan hatástalan a szabadulás elején, csak a nem-használók azok, akik ráveszik magukat, hogy a pusztító agyi változásokról olvassanak. 
Vedd például ezt a beszélgetést, általában fiatalabb használókkal.

> **Én:** “Miért akarsz leállni?”
>
>**Használó:** *“Egy csajozóművész blogján olvastam hogy érdemes négy napig leállni, hogy felpörgessem magam”*
>
>**Én:** “Az egészségügyi kockázatok nem aggasztanak?
>
>**Használó:** *“Nem, lehet hogy holnap elüt a busz”*
>
>**Én:** “De szándékosan nem ugranál a busz elé?”
>
>*Használó:** *“Persze hogy nem”*
>
>**Én:** “Nem nézel körbe, amikor átkelsz az úton?”
>
>**Használó:** *“Persze hogy körbenézek”*

Pontosan, a használó nagyon vigyáz nehogy elüsse őt a busz, pedig annak az esélye hogy elüti, egy a több ezerhez. Mindeközben egészen biztos hogy meg fogja nyomorítani a függősége, de ennek nincs tudatában. Ilyen erős az agymosás, az internetes pornó báránybőrbe bújt farkas. Nem-e különös, hogy nem szállnánk fel egy repülőre, ha úgy érezzük, hogy valami hiba van benne - még akkor is ha csak egy a millióhoz a baleset esélye- mégis vállaljuk az egy a négyhez kockázatot a pornóval, úgy hogy észre se vesszük? És mit kap ebből a használó? **Semmit az égvilágon!**

Egy másik gyakori mítosz a depresszió, vagy a nyűgösség. Sok fiatal nem aggódik az egészsége miatt, mert nem szenvednek a depressziótól vagy a melankóliától. A depresszió vagy stressz nem a betegség, hanem a tünet. A fiatalok többnyire nem érzik az ingerlékenységet vagy depressziót, mert a testük több dopamint tud termelni. Ahogy öregszenek, vagy ahogy kudarcokba botlanak, akkor a már kimerült erőforrásaik elfogynak, és teljes súlyossággal tapasztalják meg a tüneteket. Amikor az idősebb használók érzik magukat stresszesen, borúsan vagy nyűgösen, az azért van mert a természet hibamentes mechanizmusai úgy védik meg az idegrendszert a dopamin-ártól, hogy megnyirbálják a receptorokat. A használó idegrendszere más módokon is átalakul, hogy nehogy kizökkenjenek a kerékvágásból.

Képzeld el így, ha lenne egy jó kocsid, és hagynád elrozsdásodni, anélkül hogy bármit is tennél ellene, az elég nagy hülyeség lenne. Az autó gyorsan egy megmozdíthatatlan halom rozsda lenne, ami nem tudna sehová sem elvinni. Azonban ez nem lenne a világ vége, ugyanis pénzért helyrehozható. De a tested az a jármű, ami végigvisz az életen. Mindenki azt mondja, hogy az egészség a legnagyobb kincs, kérdezd meg bármelyik beteg milliomost. Többségünk vissza tud tekinteni egy betegségre, vagy egy balesetre, amikor imádkozott hogy meggyógyuljon. Azáltal hogy pornót használsz, nem csak hogy hagyod az autód elrozsdásodni, hanem szisztematikusan elpusztítod azt a járművet, ami végighordoz az életen.

Nyisd ki a szemed. Ne felejtsd, nem kell ezt csinálnod, *nem ad semmit.* Egy pillanatra húzd ki a fejed a homokból, és tedd fel magadnak a kérdést, hogy ha biztosra tudnád, hogy a következő használat elindít egy folyamatot, aminek következtében teljesen elhidegülnél egy olyan személytől akit nagyon szeretsz, tovább használnád a pornót? Olyanokkal beszélve akikkel ez megtörténik, ők semmiképp sem számítottak arra hogy ez lesz, és a legrosszabb dolog nem maga a betegség, hanem a tudata, hogy ők hozták magukra. Próbáld hogy hogy érzik magukat azok, akik ‘megnyomták a gombot’, számukra az agymosás véget ért. Az életük hátralévő részében pedig végig azt gondolják *“Miért hülyítettem magam ilyen sokáig azzal hogy internetes pornóra kell önkielégítenem? Bárcsak visszamehetnék az időben”*

Ne hülyítsd magad, visszamehetsz az időben. A pornó egy láncreakció, ha használod, az újabb és újabb használathoz fog vezetni. Már repülsz vissza. A Járható Út nem ígér semmiféle sokkterápiát, tehát ha már eldöntötted hogy le fogsz állni, a következő rész nem lesz sokkoló. Amennyiben még nem, ugord át *a fejezet hátralévő részét*, és akkor olvasd el, ha a könyv többi részét már elolvastad.

Kutatások sorát írták már az internetes pornó szexuális életre és mentális egészségre gyakorolt káros hatásairól. A baj az, hogy a használó nem akar erről tudni, amíg el nem döntötte, hogy leáll. A fórumok meg a mentorálási csoportok mind az ember idejét pazarolják, mert a pornó megvakítja az embert. Ha véletlenül olvas bele ilyenekbe, az első dolga az lesz, hogy megnyissa a kedvenc pornóoldalát. A pornóhasználók hajlamosak úgy gondolni, hogy a boldogság, a stressz, meg a szexuális veszélyek teljesen váratlanul és véletlenszerűen jönnek, mint a taposóaknára lépés.

Vésd a fejedbe, a folyamat már elkezdődött. ***Minden egyes alkalommal*** amikor megnyitod a pornóoldalt, dopamin árt idézel elő, és így az opioidok működésbe lépnek. Az idegi vízicsúszdák be vannak zsírozva, és ahogy csúszol le a csúszdán, az agyad a forgatókönyv alapján cselekszik. Az idegrendszert elárasztotta a dopamin, és mivel ez már a nagyon sokadik alkalom, a dopamin receptorok lezárulnak, és a kicsi szörny kihasználja hogy ez már nem olyan élvezetes mint az előző alkalom, hogy még tovább menj a vörös vonalon, a még sokkolóbb pornó irányába, hogy több dopamin szabaduljon fel. Több újdonság, több dopamin, és a kicsi szörny sürget hogy haladj tovább. A sok kép és videó egy használat során szupernormális stimulánsként hat, ami több vegyi anyagot fecskendez az agyba, és arra ösztökél hogy folytasd.

A receptorok pedig az ár hatására lekapcsolnak. Az orgazmus csak erősíti ezt a hatást, és elvonáshoz vezet. Te meg tagadásban vagy, mert a kicsi szörny pornót követel, fájdalom vagy kényelmetlenség nélkül. A merevedési zavarral való fenyegetés sokakat megrémiszt, és ez az ami miatt kizárják az elméjükből, és felülírják a leállástól való félelemmel. A félelem nem nagyobb, de ha ma állnak le vele, az azonnali. Miért is nézik a rossz oldalát? Lehet nem fog megtörténni, addigra már úgyis leálltak vele.

A pornóra hajlamosak vagyunk kötélhúzásként tekinteni, melynek az egyik oldalán a félelem van: *“A pornó egészségtelen, mocskos és a szolgájává tesz.”* A másik oldalon a pozitívumok: *“Ez az én örömöm, a barátom, a támaszom.”*. Az sose tűnik nekünk fel, hogy ezen az oldalon is a félelem van; a pornót nem élvezzük, hanem nélküle nyomorultak vagyunk. A herointól megfosztott heroinisták teljesen maguk alatt vannak, de képzeld csak el a színtiszta örömüket, amikor végre tűt szúrhatnak a vénájukba, végetvetve a sóvárgásnak. Próbáld meg elképzelni, hogy hogyan hiheti azt bárki is, hogy örömét leli egy tű vénába szúrásában. A nem heroinfüggők nem érzik ezt a pánikot, mert a heroin nem enyhíti, hanem okozza ezt az érzést.

A nem-használók nem érzik magukat nyomorultul, ha nem használhatnak pornót -egyedül a használók szenvednek ettől. Az internetes pornó nem enyhíti, hanem okozza ezt az érzést. A negatív következményektől való félelem nem segít a használóknak felhagyni a pornóval, hanem olyan érzés lesz tőle, mintha egy aknamezőn mennének át. Ha megúszod, rendben van, de ha nincs szerencséd, aknára lépsz, és szembenézel a következményekkel. Ha tisztában voltál a kockázatokkal, és fel voltál rájuk készülve, akkor annak mi köze volt bárkihez? 
A függők ilyen állapotban a következő kitérési taktikákkal hozamodnak elő.

***“Meg fogsz öregedni, és akkor úgyis elveszíted a potenciádat...”***

Nyilván meg fogsz, de nem a potencia a lényeg - itt rabszolgaságról van szó. Vagy még hogyha ez is lenne a helyzet, jó ok ez arra hogy megkárosítsd magad?

***“Az életminőség fontosabb mint csak hogy életben legyen az ember.”***

Pontosan! Azt mondod, hogy a függőnek jobb az életminősége, mint a nem függőnek? Tényleg azt hiszed, hogy a használó életminősége jobb, mint a nem-használóé? Egy olyan élet, amiben a fejed homokba dugid, miközben teljesen nyomorult vagy, nem hangzik túl kellemesnek.

***“Egyedülálló vagyok, és nem tervezek megkomolyodni, tehát miért is ne?”***

Még ha ez igaz is volna, de ez egy logikus ok hogy a neurológiai impulzus-kontrollal szórakozz? El tudsz képzelni egy embert aki olyan hülye, hogy mindig levetkőzik, ha egyedül van a házában, attól függetlenül, hogy mennyire biztosak benne, hogy nem jön senki? **A pornóhasználók lényegében ezt csinálják!**

Az élet élvezésében nem segít hogy úgy megbabrálod a jutalmazó központot, hogy nem tudja a stresszt kezelni. A valódi szexuális étvágyat helyettesítette a pornó és az önkielégítés, mint ahogy a tábla csoki helyettesíti a valódi ételt. Nem túl meglepő módon, sok orvos és pszichológus sok mentális egészségi problémát már a fiziológiai okokhoz kötik. A fősodorbeli orvosi közösség kitalálta, hogy tudományosan nem bizonyított, hogy a pornó lenne a páciensek által jelentett problémák közvetlen oka, de ugye az ember saját szexuális gondjait nyilvánosan beismerni eléggé megalázó dolog, miért is tenné ezt bárki, hacsaknem aggódik nagyon - és ha megtalálta már a problémát és kiküszöbölte.

A Járható Út segít megszabadulni a pornótól, és segít hogy egy boldog volt használó légy. Se pornó, sem pornóval segített önkielégtés, se felesleges orgazmusod. Az egyetlen segítség a társad tapintása és illata lesz. Mint a teljes kiőrlésű kenyér az éhes hasra, többé nem kívánod majd az internetes pornó fruktózos -kukoricaszirupos ipari kenyerét. Az egész olyan nyilvánvaló, hogy nem kell bizonyíték; ha ráütök az ujjamra kalapáccsal, akkor az fáj, nem kell külön bebizonyítani. Az internetes pornó által okozott stressz átfolyik a használó életének többi részébe, és ez sokakat fogékonnyá tesz a drogokra, például a cigarettára, vagy az alkoholra, azért hogy meg tudjon birkózni a helyzettel, és néhány esetben a használó az öngyilkosságot fontolgatja miatta.

A használók abban a tévképzetben is szenvednek, hogy a pornó káros hatásai felül vannak becsülve. Ennek az ellenkezője igaz, kétségtelen hogy az internetes pornó a szexuális zavarok és sok más egyéb probléma elsődleges oka. Hány válást idézett a pornó elő? Nincsen erre vonatkozó megbízható forrás, de az online közösségekben való keresés azt sugallja, hogy a ezeknek a száma exponenciálisan nő.

Van egy rész a *Jóbarátokban*, ahol a fiúk, akik folyamatos ingyen pornót kapnak a tévén, azon csodálkoznak, hogy a pizzafutárlány miért nem akarta megnézni a ‘szép nagy hálószobájukat’. Amikor függő vagy, a pornós fantáziáid elkerülhetetlenül a valódi nőkre vetíted ki. Képzeld el, hogy mit tesz az internet sötét sikátoraiban található pornóra való óvatlan vagy véletlen kitettség egy olyan emberrel, aki az életének egy fordulópontján van. A harc ezek ellen a gondolatok ellen komoly megterhelést jelent a mentális egészségére.

Itt egy másik gondolatkísérlet, mondjuk valaki odajön hozzád, és azt mondja, hogy nem feltétlenül akar orgazmust, de nagyon is szeretne szeretkezni, akár penetratív módon is. Addig akarja csinálni, amíg bírod orgazmus nélkül - de ha mégis lesz, nem baj. Garantálom hogy egy rendkívüli, új szexuális élményben lesz részed, ami sokkal jobb mint bármi más, ha valaha megkapod ezt az ajánlatot. Próbáld ki.

Az agymosás hatásai miatt úgy gondolkodunk, mint az ember aki miután leesett egy száz emeletes épület tetejéről, és azt mondta: *“Eddig minden rendben!”*, ahogy elsüvített az ötvenedik emelet mellett.  Azt hisszük, hogy eddig megúsztuk, tehát még egy használat nem számít semmit. Próbáld meg máshogy nézni, a ‘szokás’ egy életen át tartó lánc, amiben minden egyes használat szükséget teremt a következőre. Amikor elkezded a szokást, egy kanócot gyújtasz meg. A baj csak az, hogy *nem tudod, milyen hosszú a kanóc*. Minden alkalommal, amikor beadod a derekad, és használod, egy lépéssel közelebb vagy ahhoz hogy a bomba felrobbanjon. **HONNAN TUDOD, HOGY NEM A KÖVETKEZŐTŐL ROBBAN FEL?**

## Sötét hátsó árnyékok

A használók nehezen hiszik el, hogy a munkában vagy otthon töltött nehéz nap utáni kimozdulás során a bizonytalan érzéseket az internetes pornó okozza. A nem-használók nem szenvednek ettől az érzéstől, mert azt a pornó okozza.

Egy másik nagy öröm, amiben részed lesz ha leszoksz a pornóról, az az hogy megszabadulsz az elmédben lévő sötét árnyékoktól. Az összes használó tudja hogy bolond, mert kizárja az elméjéből a pornó káros hatásait. Az életünk nagy részében ez automatikusan folyik, de a sötét árnyékok mindig ott settenkednek a tudatalattiban, épp hogy a  felszín alatt. A pornóról való leszokásnak több előnye is tudatos, például hogy mekkora hülyeség és időpazarlás egy két dimenziós képpel szeretkezni.

A legutóbbi fejezetek a nem-használó-lét számottevő előnyeivel foglalkoztak, de a méltányosság jegyében szükséges kiegyensúlyozott módon beszámolni. Ezért a következő fejezetben a pornóhasználatból származó előnyök olvashatóak.

# A pornóhasználat előnyei
