# Az akaraterő-módszer

Az egy elfogadott tény, hogy a pornóhasználattal nehéz leállni. A leállással foglalkozó könyvek és fórumok többnyire azzal kezdik, hogy elmondják, mennyire nehéz. Pedig igazából nevetségesen könnyű. Érthető, ha megkérdőjelezed ezt az állítást, de előbb gondolj bele. Ha az a célod, hogy egy kilométert lefuss hat perc alatt, *az* bonyolult, és éveken át kell keményen edzened, és még úgy sem biztos hogy képes leszel rá.

Azonban, ha a pornóval akarsz leállni nincs más dolgod, csak az hogy ne nézz pornót és/vagy ne maszturbálj. Senki sem kényszerít az önkielégítésre, és nem is szükséges a túléléshez, nem úgy mint az élelem vagy a víz. Tehát ha le akarsz vele állni, akkor az miért lenne nehéz?  Igazából nem is nehéz. A használók nehezítik meg maguknak az akaraterő vagy bármilyen más módszer használata által, ami miatt úgy érzik hogy valamilyen áldozatot hoznak.  Vizsgáljuk meg ezeket a módszereket.

Nem döntünk úgy hogy használók akarunk lenni, csupán kísérletezünk a pornó magazinokkal vagy weboldalakkal, és mivel borzalmasak (igen, borzalmasak), a vágyott videót leszámítva, meg vagyunk róla győződve hogy bármikor leállhatunk. Eleinte akkor nézzük azt a pár videót amikor szeretnénk, meg különleges alkalmakkor. Mielőtt ráesznélnénk, nem csak hogy rendszeresen látogatjuk meg az oldalakat, és végzünk rájuk önkielégítést  amikor szeretnénk -- hanem napi rendszerességel csináljuk. A pornó a mindennapi életünk része lett, és így tesz róla, hogy bárhová megyünk, internetkapcsolat kelljen. Ezután azt hisszük, hogy jogosultak vagyunk a szerelemre, a szexre, az orgazmusra, és a pornó stressz-enyhítő hatásaira. Az hogy ugyanaz a videó és ugyanazok a színészek nem biztosítják már ugyanazt az izgalmat, elkerüli a figyelmünket, és elkezdünk a vörös vonal ellen harcolni, hogy elkerüljük a ‘rossz pornót’. Az önkielégítés és a pornó igazából se nem javítja a szexuális életünket, se nem enyhíti a stresszt, a használók csupán azt hiszik hogy orgazmus nélkül nem tudják élvezni az életet vagy a stresszt kezelni.

Többnyire sok idő szokott lenni, mire rájövünk hogy függők vagyunk, azért mert abban az illúzióban szenvedünk, hogy a használók azért néznek pornót, mert élvezik -- és nem azért mert **szükségük van rá**. Amikor nem ‘élvezzük’ a pornót, amit egyébként soha nem teszünk, hacsaknem van benne újdonság, sokk, vagy eszkaláció, abban az illúzióban vagyunk, hogy bármikor leállhatunk. Ez egy csapda, *“Nem élvezem a pornót, tehát leállhatok bármikor amikor akarok”.* Csakhogy sosem ‘akarsz’ leállni.

Többnyire csak akkor akarunk leállni, amikor már észrevettük, hogy baj van, az első próbálkozások általában hamar jönnek - miután találkozunk egy lehetséges társsal, és észrevesszük, hogy ő nem ‘elegendő’ az első randevúk után. Másik gyakori ok, hogy észrevesszük az egészségügyi hatásokat a mindennapi életünkben.

Mindegy mi az oka, a használó kivár egy stresszes alkalmat, legyen az egészséggel, vagy szexxel kapcsolatos. Amint leáll a használó, a kicsi szörny megéhezik. A használó ekkor akar valamit, amivel a dopamin szintjét növelheti, például cigarettát, alkoholt, vagy a kedvencét- internetes pornót- mert a háreme továbbra is csak kattintásnyira van. A pornó már nem a pincében van tárolva, hanem virtuálisan, és bárhonnan hozzáférhető. Ha a társa vele van, vagy a barátaival találkozik éppen, a használó nem tud hozzáférni a virtuális háremjéhez, ami miatt a használó még lehangoltabb lesz.

Ha a használó ezzel foglalkozó tudományos írásokat vagy online közösségeket talál, kötélhúzás lesz a fejében, mert próbál ellenállni a kísértéseknek, és közben megfosztva is érzi magát. Mivel a szokásos stresszoldási módszere most már elérhetetlen, így ez még súlyosabban érinti. A valószínű eredménye ennek a kínzással felérő időszaknak a kompromisszum -  *“Majd visszafogom magam”* vagy *“Rossz időt választottam”* esetleg *“Megvárom  amíg a stressz eltűnik az életemből”*. Azonban, ha eltűnik a stressz, akkor már nincs oka abbahagyni, és a használó nem akar majd a következő stresszes időszakig leállni.

Természetesen sosincs megfelelő idő erre, mert a legtöbb ember élete fokozatosan válik egyre stresszesebbé. Elhagyjuk a szüleink védelmét, és belépünk az önálló életbe ahol házat veszünk jelzálogra, gyerekeket nevelünk fel, és felelősségteljesebb munkákat végzünk. Ennek ellenére a használó élete nem lesz kevésbé stresszes, mert igazából a pornó okozza a stresszt. Minél gyorsabban kerül át használó az eszkalációs fázisba, annál lehangoltabb lesz, és annál inkább függeni fog az illúziótól. 

Az hogy az élet egyre stresszesebb lesz, az egy illúzió, és a pornó -vagy más hasonló dolog- kreálja ezt az illúziót. Ez később részletesebben ki lesz fejtve, de ezen kezdeti kudarcok után a használó többnyire arra a lehetőségre hagyatkozik, hogy egy nap majd fel fog kelni, és többet majd nem akar önkielégíteni, pornót nézni, stb. Ezt a reményt többnyire volt használóktól hallott történetek táplálják: *“Nem gondoltam az egészet komolyan, amíg nem lett merevedési zavarom, aztán pedig már nem akartam többet pornót nézni és maszturbálni.”*

Ne áltasd magad, nézz utána ezeknek a pletykáknak, és rá fogsz jönni hogy a helyzet sosem olyan egyszerű mint amilyennek tűnik. A használó többnyire már készült arra hogy leálljon, és az incidenst csak ugródeszkának használta. Akik “csak a úgy hirtelen” leálltak, őket többnyire valamilyen sokkhatás érte; lehet hogy a társuk érte őket tetten, azon vették észre magukat hogy olyan pornót néznek, ami kívül esik a szexuális orientációjukon, vagy megtapasztalták a szexuális zavart saját magukon, és ettől ijedtek meg. *“Én már csak egy ilyen ember vagyok”*. Ne áltasd magad. Nem fogsz tudni leszokni, csak ha teszel is érte.

Vizsgáljuk meg tüzetesen hogy miért olyan nehéz az akaraterő-módszer. Életünk nagy részében a fejet homokba dugós *“Holnap majd leállok”* megközelítéssel élünk. Néha valami miatt hirtelen le akarunk állni. Lehet ez aggodalom az egészség, virilitás miatt,  vagy az hogy egy pillanatra magnkba néztünk, és rájöttünk hogy igazából nem lelünk a pornóban örömöt. Bármi is az okunk, elkezdjük a pornó előnyeit és hátrányait összehasonlítani. A szex két részre bomlik, az egyik a tantrikus (tapintás, illat, hang), a másik meg a szaporodási (orgazmus); ez az egyik kulcsa annak hogy az elménk felnyíljon ez ügyben, és enélkül a fontos megkülönböztetés nélkül zavar lesz a fejben, ami bukáshoz vezet. Racionális vizsgálódás után rájövünk arra, amit mindig is tudtunk, és a konklúzió ezredjére is az lesz hogy ***“NE NÉZZ PORNÓT!”***

Ha leülnél és összeírnád a leállás előnyeit, és összehasonlítanád a pornó előnyeivel, a leállás előnyei felülmúlnák a “hátrányokat”. Ha a Pascal féle fogadást alkalmazod, látod hogy nem veszíthetsz semmit, nagy eséllyel nyersz, és még nagyobb eséllyel *nem* veszítesz. Bár a használó tudja hogy jobb lenne neki ha nem nézne pornót, de azt hiszi hogy áldozatot hoz, és ezzel csúnyán átveri magát. Ez egy illúzió, de egy erős illúzió. Nem tudja miért, de a használó azt hiszi, hogy a jobb meg rossz napokon a pornó segíteni látszik. Mielőtt még egyáltalán nekikezdenene a szabadulási kísérletnek, a társadalmi agymosást megerősíti a függőségéből eredő agymosás, és ez összeadódik azzal az agymosással hogy milyen nehéz ‘feladni’.

Hallani történeteket olyanokról akik már több hónapja leálltak, és mégis elkeseredetten sóvárognak, és beszámolókat mogorva használókról, akik bár leálltak, de egész életükben arról panaszkodnak, hogy nagyon szeretnének pornót nézni. Vannak mendemondák olyan használókról akik több hónapra vagy évre leálltak, boldogan élik az életüket, de ‘rákukkantanak egyet’ és hirtelen újra függők lettek. A használó valószínűleg több embert is ismer, aki a betegség előrehaladott stádiumában van, és jól láthatóan pusztítja magát, és nem élvezi az életet - és mégis tovább használja. Ezenfelül, lehet hogy a használó maga is szenvedett ezektől a helyzetektől.

Tehát ahelyett hogy azzal indítanának hogy *“Remek! Hallottad a jó hírt? Nem kell többé pornót néznem”*, csak siránkoznak -- mintha a Csomolungmát akarnák megmászni- és tévesen megállapítják hogy amint a kicsi szörny belédszállt, egy életre ott marad. Sok használó azzal kezdi a kísérletet, hogy bocsánatot kér a barátnőjétől vagy feleségétől hogy *“Nézd, most épp próbálom feladni a pornót. Egy pár hétig eléggé ingerlékeny leszek, próbálj meg elviselni.”* A legtöbb kísérlet már azelőtt kudarcra van ítélve, mielőtt elkezdődne.

Tételezzük fel, hogy a használó túlél pár napot használat nélkül, elkezd visszatérni a rendes izgalmi állapota, és rálépett a gyógyulás útjára. Nem nyitotta meg a kedvenc pornóoldalát, és ebből kifolyólag újra a normális stimulánsok izgatják fel, amik eddig nem érdekelték. Az okok amiért az elején leállt, tempósan hagyják el az agyát, mint például ha vezetés közben egy balesetet látna. Egy darabig lelassít, de azért beletaposol a gázba ha legközelebb késésben vagy.

A kötélhúzás másik oldalán a kicsi szörny van, ami még mindig nem kapta meg az adagját. De fizikai fájdalom nincs - ha ugyanezt éreznéd megfázás miatt, továbbra is bemennél dolgozni, nem lennél depressziós tőle, nevetnél csak az egészen. A használó csak annyit tud, hogy meg akarja látogatni a háremét. A kicsi szörny ezt tudja, és beindítja a nagy agymosó szörnyet, ami miatt ugyanaz a személy aki pár órával vagy nappal korábban még sorolta az okokat hogy leálljon, most elkeseredetten keres akármilyen okot hogy újra csinálhassa. Ilyesmi dolgokat kezd el mondani:

-   *“Az élet túl rövid, lehet hogy holnap  felrobban egy bomba, vagy elüt a busz. Már lekéstem erről. Mostanában mindenre rámondják hogy függőséget okoz.”*

-   *“Rossz időt választottam”*

-   *“Kellett volna várnom karácsonyig, a nyaralásig, a vizsgákig, eddig a stresszes eseményig.”*

-   *“Nem tudok koncentrálni, kezdek ingerlékeny és nyűgös lenni, még a munkámat sem tudom jól végezni”*

-   *“A családom és a barátaim nem fognak szeretni. Lássuk be, újra el kell kezdenem a többiek miatt. Megrögzött szexfüggő vagyok, és orgazmus nélkül sosem leszek boldog.”*

-   *“Szex nélkül senki sem tud túlélni”* (Olyan jóindulatú emberek általi agymosás, akik nem különböztetik meg a szex tantrikus és szaporodási részét)

-   *“Tudtam hogy ez be fog következni, az agyamat ‘szenzitizálta’ a DeltaFosB a dopamin rohamok miatti változások miatt, amit meg a korábbi pornóhasználatom okozott. A szenzitizáció pedig nem távolítható el az agyból.”*

Eddigre a használó többnyire feladja. Bekapcsolja a böngészőt, a skizofrénia növekszik. Az egyik oldalon ott van a hatalmas megkönnyebbülés, ahogy a sóvárgás véget ér, és a kicsi szörny megkapja az adagját; a másik oldalon pedig ugye az orgazmus borzalmas, és a használó nem érti, hogy miért csinálja. A használó ezért hiszi hogy nincs akaratereje. Ez valójában nem az akaraterő hiánya, a használó csak annyit tett, hogy meggondolta magát, és hozott egy teljesen ésszerű döntést a legutóbbi információk alapján.

*“Mi értelme van annak hogy egészséges vagy gazdag vagy, ha közben nyomorultul érzed magad?”*

Semmi! Sokkal jobb egy rövid, de örömteli élet, mint egy hosszú, de nyomorult élet. Szerencsére ez nem igaz a nem-használóra, mert az ő élete milliószor örömtelibb. Amitől a használó szenved, az nem az elvonási kattogás -- bár eleinte az indítja el -- hanem a valódi agónia az a kötélhúzás az agyban, amit a kétely és a bizonytalanság okoz. Mivel a használó az áldozathozatal érzésével kezd, ezért megfosztottnak érzi magát, ami a stressz egy formája.

Az egyik ilyen stresszes érzés az, amikor az agya azt mondja a használónak hogy ‘kukkantson bele’; amint leáll, egyből vissza akar fordulni. De mivel már leállt, nem teheti, ettől még levetertebb lesz, és ez újra beindítja a folyamatot. Egy másik tényező ami miatt nehéz leállni, az az amikor vár arra hogy valami történjen. Ha az a célod, hogy átmenj a forgalmi vizsgán, amint átmentél, bizonyos hogy elérted-e a célodat. Az akaraterő-módszerrel az a belső narratíva, hogy *“Ha elég sokáig nem nézek pornót, akkor a késztetés a nézésére meg fog szűnni.”* Ezt láthatod a gyakorlatban is, amikor a függők a 'szériájukról' beszélnek, vagyis arról hogy hány napig tartózkodtak.

Mint ahogy azt már feljebb el lett mondva, az agónia amin a használó keresztülmegy mentális, és a bizonytalanság okozza. Bár nincsen fizikai fájdalom, a hatásai továbbra is erősek. A használó most már nyomorultul és bizonytalanul érzi magát, így nem hogy felejtene, hanem tele van kételyekkel és félelemmel.

-   *“Meddig fog tartani a sóvárgás?”*

-   *"Boldog leszek-e valaha?"*

-   *"Fel akarok-e majd reggel kelni?"*

-   *“A jövőben hogyan fogok a stresszel elbánni?”*

A használó arra vár hogy a dolgok javuljanak, de amíg szomorkodik, a ‘hárem’ egyre értékesebbé válik. *Valami* történik is, de tudatalatt, hogyha pár hétig kibírják anélkül hogy megnyissák a böngészőt, a kicsi szörny iránti sóvárgás megszűnik. Azonban ahogy az feljebb említve lett, a dopamin és opioid elvonásból fakadó kattogás olyan enyhe, hogy a használó nincs is tudatában. Eddigre sok használó azt hiszi, hogy ‘legyőzte’, ezért vet egy pillantást hogy bebizonyítsa, és ez visszalöki őt a vízicsúszdán. Miután bejött a dopamin, van egy kis hang az agyuk mélyén, ami azt hajtogatja *“Akarsz mégegyet.”* Igaz hogy legyőzték, de közben újra ráffügtek.

Gyerekkorodban rajzfilmeket néztél, és a neurológiával összhangban idegpályák (DeltaFosB) jöttek létre. Ha el szeretnél tántorítani egy gyereket attól hogy rajzfilmeket nézzen, tanulmányoznád hogy meg vannak-e még ezek az idegpályák, és kikérdeznél felnőtteket, hogy miért nem nézik már a kedvenc gyerekkori rajzfilmjüket. Először is azért, mert elérhető jobb féle szórakoztatás, másodszor pedig azért mert a rajzfilmek már nem olyan lenyűgözőek felnőtt fejjel. Az akaraterő módszerrel megtagadod a gyerektől a rajzfilmeket, de a Járható Úttal biztosítod hogy ne is akarja nézni. Melyik a jobb?

A használó általában nem használ pornót rögtön újra, hanem azt gondolva hogy *“Nem akarok újra függő lenni!”* kihagy pár órát, napot, vagy hetet. A használó ekkor azt mondhatja: *“Hát, nem függtem rá, tehát nyugodtan nézhetem újra.”* Ugyanabba a csapdába esett bele újra, mint amikor elkezdte, és újra csúszik le a lejtőn. 

Azok a használók akik sikerrel járnak az akaraterő módszerrel, általában hosszadalmasnak és nehéznek érzik, mert a legnagyobb probléma az agymosás. Amikor a fizikai függőség már rég elmúlt, a használó továbbra is búslakodik. Idővel, miután átvészelte ezt a hosszútávú kínzást, rájön hogy nem fogja beadni a derekát, abbahagyja a búslakodást, és elfogadja hogy az élet megy tovább, és élvezetes pornó nélkül. Számottevően több a bukás mint a siker, és sokan akik sikerrel járnak, egy sebezhető állapotban élnek tovább, mert maradt még az agyukban egy kis agymosás, ami azt mondja hogy a pornó igenis egy löketet ad. Ez megmagyarázza hogy sok használó miért kezdi újra, miután huzamosabb ideig leállt.

Sok volt-használó néha alkalmanként újra használ ‘különleges élvezetként’, vagy azért hogy meggyőzze magát, milyen erős az önkontrollja. És pontosan ezt csinálja - de amint vége, a dopamin elkezd kiürülni, és a hang az elméje mélyén egy újabb használat felé tereli. Hogyha így tesz, a helyzet látszólag irányítás alatt van, nincs semmi sokkolás, eszkalálódás, vagy újdonsághajhászás, tehát azt mondja a használó: *“Remek! Mivel nem élvezem, ezért nem fogok ráfüggni. Karácsony / nyaralás / ezután a trauma után majd abbahagyom.”* Azt azonban nem tudja hogy a vízicsúszdák az agyukban még jobban be lettek zsírozva.

Késő, már ráfüggött! A csapda, amiből sikerült kimásznia, újra elkapta az áldozatát.

Ahogy már le lett írva, az élvezet nem játszik szerepet. Sosem játszott! Ha az élvezetért néznénk, senki sem maradna tovább a pornóoldalakon, mint amennyi idő a tettet véghezvinni. Egyébként is, az önkielégítés jobb, ha az emlékekből történik.  Azt feltételezzük, hogy csak azért élvezzük a pornót, mert nem hisszük el hogy olyan hülyék lennénk, hogy úgy függenénk rá, hogy nem élvezzük. A legtöbb használónak fogalma sincs a szupernormális stimulánsokról, az újdonság- vagy sokk hajhászásról, és nem hiszi el hogy a használatát a jutalmazó központ működése motiválja, még azután sem hogy olvasott róla. Ezért tudatalatti a pornó jókora része, hogyha tisztában lennél a neurológiai változásokkal, és igazolnod kéne, hogy miért jó hogy a pornó közvetve ilyen sok pénzbe kerül, az élvezetnek még az illúziója is odalenne. 

Amikor próbáljuk kizárni a rossz oldalát, hülyén érezzük magunkat. Ha szembe kéne nézni a tettünkel, az kibírhatatlan lenne! Ha megfigyelsz egy használót használat közben, észreveheted hogy csak akkor boldog, amikor nincs vele tisztában hogy mit csinál. Amint rájön, kényelmetlenül kezdi magát érezni, és védekező helyzetbe megy át. A pornó eteti a kicsi szörnyet, tehát amikor kipurgálod a testedből az agymosással ( a nagy szörnnyel eggyütt), se nem kell, se nem akarsz majd pornót nézni!
