# A használat csökkentése

Sok használó a használat csökkentéséhez nyúl ugródeszkaként, vagy a kicsi szörny kontrollálására tett kísértletként. Sokan a használat visszafogásást, vagyis a ‘pornó-diétát’ javasolják kedvserkentőnek. A használat csökkentését használni ugródeszkaként a leálláshoz ***végzetes***. Az ilyen, csökkentésre tett kísérletek azok, amelyek az életünk végéig a csapdában tartanak. A használat visszafogását általában sikertelenül végződött kísérletek előzik meg. Pár órányi vagy napnyi tartózkodás után a használó ilyesmi dolgokat kezd el mondani:

*“Nem bírok szembenézni a gondolattal, hogy az online háremem nélkül menjek aludni, tehát mostantól négy naponként használok csak pornót, vagy megszabadulok a ‘rossz pornó’ gyűjteményemtől. Ha követni tudom ezt a pornó-diétát, tarthatom ezen a szinten, vagy még jobban visszavehetem.”*

Így több borzalmas dolog is történhet:

1.    A használó a földi pokolban ragad, tehát továbbra is pornóföggő marad, és életben tartja a szörnyet nem csak a testében, hanem a lelkében is.

2.    A következő alkalomra várva tengeti a napjait

3.    Mielőtt visszavett volna a használatból, a használó bármikor, amikor meg akarta látogatni a háremét, bekapcsolta a böngészőt, és legalább részben enyhítette az elvonási kattogást. Most a mindennapi stressz mellett még az elvonási kattogástól is szenved élete hátralévő részében, ami miatt még nyomorultabb és még rosszabb kedvű lesz.

4.    Amíg rendszeresen használta, se nem élvezte a legtöbb alkalmat, se nem jött rá hogy szupernormális stimulánst használ. Automatikus volt, és az egyetlen hárem látogatás amit élvezett, az az volt, amit némi tartózkodás előzött meg.  Most hogy vár egy órát minden látogatás előtt, ‘élvezi’ mindet. Minél tovább vár rá, annál ‘élvezetesebb’ a használat, mert az élvezet a használatban nem maga a használat  - hanem a nyugtalanság megszűnte, amely nyugtalanságot a sóvárgás okozta -- legyen az enyhe fizikai vágyakozás, vagy búslakodás. Minél tovább szenved az ember, annál ‘élvezetesebbnek’ tűnik a használat.

A legnagyobb nehézség a leállásban nem a neurológiai függőség, mert az egy könnyű rész. A használók bizonyos alkalmakkor különösebb nehézség nélkül leállnak -- egy szerettük halála, családi, vagy munkaügyek miatt, stb. Végigcsinálnak, mondjuk tíz napot, amíg nem férnek hozzá, és nem zavarja őket. De ha ugyenezt a tíz napot kellene kibírniuk, úgy hogy hozzá tudnak férni, kitépnék a hajukat.

Sok használó munka közben lát egy lehetőséget a használatra, és tartózkodik, átmegy a Victoria’s Secreten, uszodákon és miegymáson, különösebb kényelmetlenség nélkül. Sokan tartózkodnak, hogyha a kanapén kell aludniuk, hogy helyet csináljanak egy vendégnek, vagy éppen ők maguk vannak látogatóban. Még go-go bárokban vagy nudista strandokon sem voltak zavargások. A használók szinte örülnek, ha valaki vagy valami megakadályozza hogy pornót nézzenek. Sőt, azoknak a használóknak,  akik le akarnak szokni a pornóról, nekik egy titkos élvezet az, amikor sok ideig nem néznek pornót, abban reménykedve, hogy egy nap majd nem is akarják többet nézni. 

A valódi probléma a leállásnál az agymosás, annak az illúziója, hogy az internetes pornó valamiféle támasz vagy jutalom, és az élet nem lesz ugyanolyan nélküle. A visszavágás nemcsak hogy nem szoktat le a pornóról, hanem csupán annyit ér el, hogy bizonytalanul és nyomorultul érzed magad tőle, és ez meggyőz arról, hogy a legértékesebb dolog a világon az az új videó amit kihagytál, és hogy semmiképpen sem lehetsz boldog, ha nem nézed meg.

Nincsen szánalmasabb a használatból visszavágó használónál. Attól a tévképzettől szenved, hogy minél kevesebb pornót néz, annál kevésbé akarja az online háremet meglátogatni. Ennek az ellenkezője igaz, minél kevesebb pornót néz, annál jobban szenved az elvonási kattogástól, és annál jobban ‘élvezi’, amikor enyhítheti.  Azonban észre fogja venni hogy a kedvenc műfaja már nem az igazi. De ez nem fogja semmiben sem meggátolni, hogyha a pornóoldalak egy adott sztárnak vagy műfajnak lennének fenntartva, senki sem menne oda egynél többször. 

Nehéz ezt elhinni? Mi a legrosszabb rész az önkontrollban? Várni négy napot, majd klimaxolni. Mi a legértékesebb pillanat a pornó-diétán lévő használóknak? Bizony, ugyanaz a klimax, négy nap várakozás után! Tényleg azt hiszed hogy azért maszturbálsz, hogy élvezd az orgazmust, vagy a racionálisabb magyarázatot hiszed el, tehát hogy enyhítened kell az elvonási kattogást, azon illúzió alapján hogy jogosult vagy erre?

Szükséges az agymosást eltávolítani ahhoz hogy a pornóról való illúziókat is felszámoljuk, mielőtt véghezviszed az utolsó alkalmat. Hacsaknem már megszűntetted az illúzióját annak hogy élvezed, mielőtt becsukod a böngészőt, nem tudod bizonyítani utólag, anélkül hogy újra ráfüggenél.

Amikor a könyvjelzőket és a lementett képeket nézegeted, kérdezd meg hogy hol van ebben a dicsőség. Lehet hogy azt hiszed hogy bizonyos videók ízlésesek, például a szokásos, vagy gyakran nézett témájúak. Ha tényleg azok, akkor miért nézel más videókat, vagy témákat? Mert rászoktál? Miért tenné tönkre bárki is az agyát megszokásból, és tenné tönkre magát is? Egy hónap alatt nem változik semmi, miben különbözne hát egy pornóvideó?

Ezt magad is tesztelheted, keress egy videót, ami egy hónapja nagyon tetszett, hogy bebizonyítsd, hogy más. Aztán, állítsd be egy emlékeztetőt, és nézd meg ugyanazt a videót, egy hónapnyi tartózkodás után. (Majdnem) ugyanúgy fog hatni, mint múlt hónapban. Ugyanaz a videó más lesz egy társasági esemény után, ahol egy lehetséges társ elutasított vagy tesztelt. Azért, mert a függő nem lehet teljesen boldog, amíg a kicsi szörny nem elégedett.

És hol van az elégedettség? Csupán az van, hogy a használó nyomorultul érzi magát, amíg nem enyhítheti az elvonási tüneteket. A különbség a pornónézés és a nem nézés között, azonos a boldogság és a nyomor közötti különbséggel. Az internetes pornó ezért tűnik jobbnak. Míg a használók, akiknek reggel az első dolguk hogy pornót nézzenek, nyomorultul érzik magukat, akár nézik, akár nem.

A visszavágás nemcsak hogy nem működik, hanem a legborzalmasabb kínzás is. Nem működik, mert eleinte a használó azt reméli, hogy minél kevesebbszer csinálja a szokását, annál kevésbé akarja majd. Csakhogy nem szokásról, hanem függőségről beszélünk.  És a függőség olyan, hogy egyre többet akar az ember, nem egyre kevesebbet. Tehát, azért hogy visszavegyen a használatból, a használónak a hátralévő életében akaraterőt és fegyelmet kell gyakorolnia. Tehát a használat csökkentése egy életen át tartó akaraterőt és fegyelmet jelent. A teljes leállás sokkal könnyebb, és kevésbé fájdalmas, szó szerint több tízezer eset van, amikor a csökkentés kudarcot vallott.

A probléma a leállás során nem a dopaminfüggőség, mert azzal könnyű elbánni. Hanem a téveszme, hogy a pornó örömet okoz. Ezt eleinte az az agymosás okozza, ami még az előtt történt, hogy rászoktunk, és ezt megerősíti a valódi függőség. A csökkentés csak tovább erősíti ezt a téveszmét, olyan mértékben, hogy a pornó kezdi el a használó életét uralni, és arról meggyőzni, hogy a legértékesebb dolog a világon az a függősége.

Az a kevés eset, amelyik így sikerrel végződött, egy aránylag rövid ideig tartó visszavágással, és utána pedig teljes tartózkodással lett elérve. Ezek a használók a csökkentés ellenére, és nem miatta tudtak leállni. A csökkentés nem tett mást, csak meghosszabbította az agóniát, és a sikertelen kísérletek idegronccsá változtatják a használókat, akik így még jobban meg lesznek győződve, hogy egy életre függők. Ez elég szokott lenni arra, hogy visszavigye a használót az online hárembe az ‘örömért’ meg a ‘támaszért’, vagy hogy még egy alkalomért a következő próbálkozás előtt

Azonban, a csökkentés nagyon jól illusztrálja hogy a pornó milyen felesleges, és megmutatja hogy a hárem látogatás nem élvezetes még tartózkodás után sem. Egy falhoz kell verned a fejed (elvonási kattogástól szenvedni) ahhoz hogy jó érzés legyen amikor abbahagyod. Tehát a következők a választásaid:

1.    Csökkenteni a használatot egy életre, és így önmagadat kínozni, amire úgysem leszel képes.

2.    Növekvő mértékben kínozni magadat, ami értelmetlen.

3.    Tenni magadnak egy szívességet, és teljesen megszabadulni a pornótól.

A másik, amit a használat csökkentése demonstrál, az az hogy nincs olyan, hogy egyszeri, vagy alkalmi látogatás a hárembe. A pornó egy láncreakció, ami egy életen át tart, hacsaknem teszel aktívan azért hogy megtörd. 

**Emlékezz: A használat csökkentése csak ártani fog.**
