# Csak egy pillantás

A 'csak egy pillantás' egy mítosz, amit el kell felejtened:

-   *Csak egy pillantás* miatt kezdjük egyáltalán el.

-   *Csak egy pillantás*t akarunk vetni, hogy átsegítsen egy nehéz helyzeten, és ez az ami a legtöbb próbálkozás kudarcát okozza.

-   *Csak egy pillantás* az, ami visszalök a csapdába, miután legyőztük a függőséget. Néha a használó csak azért teszi, hogy bizonyítsa hogy már nem függő, és a látogatás pont ezt teszi

A pornó utóhatásai borzalmasak lesznek, és ez meggyőzi a használót arról, hogy soha többet nem lesz függő -- de már függő lett. A használó azt érzi hogy valami ami miatt ilyen nyomorultul, és bűnösen érzi magát, nem szabadott volna, hogy újra rávegye a használtatra, de mégis.  

Az ‘egyetlen különleges alkalom’ gondolata az, ami sokszor megakadályozza a használót a leállásban, annak az alkalomnak, ami a hosszú konferencia utat, a nehéz napot a munkában, a veszekedést a gyerekekkel követi, vagy azt amikor a párod elutasítja szexet. Vésd *jól* az elmédbe, hogy nincs olyan hogy ‘csak egy pillantás’. Csak láncreakció van, ami egy életen át fog tartani, hacsaknem töröd meg. A különleges alkalmakról szóló mítosz miatt búslakodnak a használók, miután leálltak. Szokj át arra, hogy nem látod a ‘nem nagy ügy’-alkalmat, mert az csak a képzelet szüleménye. Bármikor, amikor a pornóra gondolsz, láss magad előtt egy mocskos életet, amiben végtelen időt töltesz a képernyő előtt, hogy részesülhess abban a kiváltságban, hogy elpusztítsd magad mind mentálisan, mind fizikailag, egy életnyi rabsággal és reménytelenséggel nyakonöntve. Ha a merevedésed megbízhatlan, nem bűn, de hogyha hosszútávon boldogabb lehetnél, de te úgy döntesz hogy ezt feláldozod rövid távú ‘örömért’, az az.

Az rendben is van, hogy nem tudunk mindig valami elfoglaltságot találni az űrnek; nem is lenne mindig lehetséges. Sok dolgot előre tervezhetünk, de valamit nem. Vannak jó és rossz időszakok, a pornótól függetlenül. De vésd jól az elmédbe: **a pornó nem egy jó elfoglaltság**. Vagy egy életen át szenvedsz, vagy egyáltalán nem, nem vennél be ciántablettát, mert szereted a mandula ízét, tehát ne büntesd magad tovább a ‘nem nagy ügy’-alkalommal. Kérdezz meg egy használót: *“Hogyha lehetőséged lenne arra hogy visszamenj abba az időbe, mielőtt rászoktál, rászoktál volna?”* A válasz elkerülhetetlenül az hogy *“Te most viccelsz!”* A használóknak mégis van erre lehetősége, minden nap, miért nem él hát vele? A válasz a félelem. Fél attól hogy az élet nem lesz ugyanolyan pornó nélkül.

Ne hülyítsd magad! Képes vagy rá, mindenki képes rá. Nevetségesen könnyű, de ahhoz hogy annak is érezd, van néhány alapvetés amit jól  a fejedbe kell vésned.

1.  Nincs mit feladni, csak hatalmasat lehet nyerni.

2.  Soha ne győzd meg magad a ‘nem nagy ügy’ vagy ‘csak egy pillantás’- alkalmakról.Egyik sem létezik. Csak egy életnyi mocsok és rabság van. 

3.  Ilyen szempontból nem vagy különleges, bármelyik használó könnyen leszokhat.

Sok használó azt hiszi, hogy ő megrögzött függő vagy addiktív személyisége van. Ez általában a túl sok sokkoló neurológia írás olvasásának a következménye. Ilyen dolgok szerencsére nincsenek, senki sem születik úgy, hogy videókra akarjon önkielégíteni. A drog tesz függővé, nem a személyiséged. A függőséget okozó szupernormális stimuláns ellenben az utóbbit hiteti el veled. Mindazonáltal, rendkívül fontos hogy megszabaduljunk ettől a tévhittől, mert ha azt hiszed hogy függő vagy, az is leszel, még akkor is, ha a kicsi szörny már rég halott. Tehát létfontosságú megszabadulni ettől az agymosástól.
