# Alkalmi használók

A súlyos használók hajlamosak irigyelni az alkalmi használót, akit bizonyára ismerünk: *“Ó, egy hétig kibírom nélkül pornó nélkül, nem is zavar”*. Azt kívánjuk bárcsak ilyenek lennénk. Ezt lehet nehéz elhinni, de egy használó sem szeret használó lenni. Ne felejtsd:

|   *Egy használó sem döntött úgy hogy ő pornóhasználó lesz,* ***tehát,***

|       *Minden használó hülyén érzi magát,* ***tehát,***

|         *Minden használó hazudik magának és másoknak, a hülyesége igazolására tett felesleges kísérletképp.*

A golf-fanatikusok azzal hencegnek hogy milyen gyakran szoktak játszani, és mennyire szeretnek játszani, tehát akkor a használók miért hencegnek azzal, hogy milyen keveset maszturbálnak? Hogyha  ez a kritérium, akkor az igazi elismerés biztos az, ha egyáltalán nem maszturbálnak, nemde? 

Ha valaki azt mondaná neked hogy *“Egy héten át kibírom anélkül hogy répát ennék, és egyáltalán nem zavar”*, azt hinnéd hogy valami lököttel beszélsz. Ha szeretem ha répát, miért akarnám egy hétig nélkülözni? Ha meg nem szeretem, akkor miért mondanék ilyet? Tehát amikor egy használó arról beszél hogy egy hétig kibírja használat nélkül, akkor saját magát --és téged-- próbálja meggyőzni arról hogy nincs semmi baja. De nem kellene ilyen állítást tennie, ha nem lenne baja. Lefordítva, ez a mondat azt jelenti hogy: *“Sikerült egy hétig túlélnem pornó nélkül.”* Mint minden használó, ő is azt reméli hogy ezután az élete hátralévő részét túl tudná így élni. Ha csak egy hetet túl tud élni, el bírod képzelni hogy milyen értékesnek érződhetett a használat utólag, egy hét megvonás után?

Ez az, amiért az alkalmi használók tulajdonképpen függőbbek mint a súlyos használók, nem csak az öröm illúziója nagyobb, hanem kevesebb motivációjuk is van arra hogy leszokjanak, mert kevesebb időt töltenek el a használattal, ezért nem is olyan kiszolgáltatottak az egészségügyi kockázatoknak. Időnként lehet tapasztalnak szexuális zavarokat, de nem biztosak benne hogy mi okozta, tehát más dolgokra fogják. Emlékezz, a használók egyetlen öröme a pornó keresésével járó dopamin adag, és az elvonási kattogás enyhítése, mint ahogy az ki lett fejtve. Az öröm egy illúzió, képzeld el a kicsi szörnyet egy közel észrevehetetlen viszketésként, amit többnyire észre sem veszünk.

Ha valami folyamatosan viszket, a természetes reakció erre az, hogy megvakarod. Ahogy a jutalmazó központ fokozatosan hozzászokik a dopaminhoz és az opioidokhoz, az a természetes tendencia hogy elhúzod, egyre eszkalálódó dolgokat nézel, ráadásul sokat, új és sokkoló dolgokat keresel, stb. Négy tényező van, ami meggátolja hogy a használó lánc-pornónéző legyen .

**Idő.**
A legtöbb embernek nincsen.

**Egészség.** 
Ahhoz hogy enyhítsük a viszketést, fel kell használni az összes elérhető anyagot, és még egy kicsit. Az hogy ezt ki hogy bírja, személy-, idő-, és alkalomfüggő. Ez sokszor meggátolja a használókat.

**Önuralom.** 
A társadalom, vagy a használó munkája, barátai, rokonai, vagy akár maga a használó kényszeríti magára az agyában folyó kötélhúzás eredményeként. 

**Képzelet.**
A képzelet hiánya szubjektív módon csökkenti a videó sokk, újdonság, és egyéb hatásait.

Könnyű dolog gyengének, meg olyannak nézni a nem alkalmi használókat, akik nem értik hogy mások hogy tudják korlátozni a fogyasztásukat. Azonban a súlyos használók ne feledjék, hogy a legtöbb alkalmi használó egyszerűen nem tud láncban pornót nézni, mivel az erős képzeletet és állóképességet követel. Néhány ilyen heti egyszeri használó, akiket a súlyos használók hajlamosak irigyelni, fizikailag egyszerűen nem képes többet nézni, vagy a munkája, a társadalom, vagy a saját félelme attól hogy függő lesz, megakadályozza.

Lehet jó lenne egy pár definíció.

**A nem-használó**

Olyasvalaki aki még nem esett bele a csapdába, de azért még ne legyen túl önelégült. Ő csak a szerencsének köszönheti, hogy nem esett bele. Az összes használó meg volt róla győződve, hogy ő sosem lesz függő, és vannak olyan nem-használók, akik időről időre kipróbálják a használatot.

**Az alkalmi használó**

Ezt a kategóriát kétféleképpen is meg lehet határozni.

1.  A használó aki beleesett a csapdába, de nem veszi észre -- ne irigyeld ezeket a használókat. Ő csak a nektárt kóstolgatja a húsevő növény szélén, és minden valószínűség szerint hamarosan súlyos használó lesz.  Emlékezz, mint ahogy az összes alkoholista alkalmi ivóként kezdte, úgy az összes használó is alkalmiként kezdi. 

2.  A használó aki korábban súlyos használó volt, és így azt hiszi hogy nem tud leállni. Ezen használók a legszomorúbbak, és számos kategóriába sorolhatók, amelyek közül mindegyik külön kommentárt igényel.

**A napi egyszeri használó**

Ha ő úgy élvezi hogy jogosult az orgazmusra, akkor miért csak naponta egyszer használja? Ha meg nem nem érdekli annyira, akkor miért foglalkozik ezzel? Emlékezz, a ‘szokás’ igazából az hogy a falba vered a fejed, hogy aztán jó legyen abbahagyni. A napi egyszeri használó minden nap egy óránál kevesebb ideig enyhíti az elvonási kattogását. Bár nincs ezzel tisztában, de a napja többi része azzal telik, hogy a fejét a falba veri, és ezt csinálja az élete nagy részében. Azért használ naponta egyszer, mert nem kockázatná a lebukást, vagy azt hogy teljesen odalegyen a mentális egészsége. A súlyos használót könnyű meggyőzni hogy ő nem is élvezi, de az alkalmi használót sokkal nehezebb. Mindenki aki próbált már visszavenni a használatból, tudja hogy az a legrosszabb kínzás, és hogy ez szinte garantálja hogy az élete végéig függő maradjon.

**A visszautasított használó**

Ő követeli az orgazmushoz való jogot, de a társa nem tudja mindig teljesíteni a kérését. Eleinte a hiány pótlására néz pornót, de amint megszokja a ‘vízicsúszdát’, bent ragad az újdonság, sokkolás, szupernormális képek és a többi körében. Sőt, örül is ha a társa visszautasítja, mert az ürügyet biztosít a használatra. Ha a pornó ennyire sokat ad, akkor miért bajlódsz a társaddal egyáltalán? Engedd őt inkább el. A használó nem is élvezi a használatot, amikor a társára kell gondolnia. Néha már kifejezetten próbálja a társát rávenni hogy adjon neki valami ürügyet arra, hogy az internet sötét bugyraiba mehessen.

**A pornó-diétán lévő használó**

Úgy is ismeretes hogy **“Bármikor le tudok állni. Már több ezerszer csináltam!.”** 

Ha azt gondolja, hogy a diéta segít abban, hogy olyan hangulatba kerüljön hogy társakat szedjen fel, akkor miért használ egyáltalán minden negyedik nap? Senki sem lát a jövőbe, mi van akkor hogyha egy órával a beütemezett használat után pont belefutott volna a lehetséges társába? Valamint, hogyha az alkalmi ‘takarítás’ jó arra hogy enyhítse a feszültséget, akkor miért nem takarít minden nap? Be lett bizonyítva hogy az önkielégítés nem szükséges a nemi szervek rendben tartásához, és az internetes pornó pedig pláne nem szükséges. Még hogyha a pornó diétás módszer működne is, egyetlen csajozó ‘guru’ sem ajánlaná hogy szuperstimuláló pornót nézz, ha olvasott a neurológiai károkról, amit a pornó okoz. Az igazság az, hogy ez a használó továbbra is függő. Bár a fizikai függőségtől megszabadult, de az elsődleges probléma, az agymosás továbbra is fennáll. Mindig azt reméli, hogy most végleg le fog állni, de rövidesen beleesik ugyanabba a csapdába. 

A legtöbb használó valójában irigyli ezen kategóriába eső használókat, és azt gondolja hogy milyen ‘szerencsés’ a diétázó, hogy kontrollálni tudja a használatát. Azonban, azt nem veszik észre hogy a diétázó nem kontrollálja a használatát -- amikor használ, azt kívánja bár ne tenné. Átvészeli a leállással járó sok fejfájást, ezután úgy érzi, meg van fosztva valamitől, és aztán újra beleesik a csapdába, azt kívánva, bár ne tette volna. Mindkét résznek csak a rossz oldalát tapasztalja. Ha belegondolsz, ez igaz a használók életére, amikor használhatnak pornót -- jogosultnak érzik magukat rá, vagy utólag megbánják. A pornó csak akkor válik értékessé, ha a használó meg van tőle fosztva. A ‘tiltott gyümölcs’ szindróma a használó egyik borzalmas dilemmája. A használó sosem nyerhet, mert egy mítoszért, egy illúzióért sír. Csak egyetlen módja van a győzelmének, az hogyha leáll a sírással, úgy hogy leáll a pornóval!

**A *“csak képes/szelíd/házikészítésű pornót nézek”* használó**

Igen, mindenki ezzel kezdi, de nem-e lenyűgöző hogy ezeknek a videóknak a sokkolás-faktora milyen gyorsan növekszik, és még észre sem vesszük, de már megfosztottnak érezzük magunkat (tolerancia) ?  A képes pornóban nincs semmi újdonság, tehát szépen bezsírozzuk a vízicsúszdát, és lecsúszunk rajta a neheztelés és a bűntudat felé. A legrosszabb amit tehetsz, az az hogyha a társad képeit használod önkielégítésre (az engedélyével természetesen). Miért? Mert ahogy csinálod, áthuzalozod az agyad a dopamin-löket fogadására. Kémiául, a sokat emlegetett vízicsúszda az a DeltaFosB, és ennek következtében a társaddal a valós együttlét nehézséget fog jelenteni.

Ebben a kategóriában van még egy csapda, az ‘amatőr’ és ‘házi készítésű’ pornó. A legtöbb kamu, és ezt te is tudod, és nem is fogsz megállni a legelsőnél amit látsz, hanem tovább fogsz kutakodni. Emlékezz, az agy nem csak az orgazmust keresi, hanem a vadászat során tapasztalható újdonságfaktort, ami miatt olyan izgalmas a csúszdán lecsúszni. Nem a pornótartalommal[^7] van a baj - legyen szó amatőr vagy profi anyagokról -- hanem a dopamin löketekkel, amik toleranciát és dopaminnal való jóllakottságot okoznak. A pornó tönkreteszi az agy normális működését, az önkielégítés összezavarja az izmoknak az agyi jelekre való reagálását; az orgazmus opiodokkal árasztja el az agyat, és megkönnyíti hogy máskor is ugyanez történjen.

**A *“leálltam, de néha azért rákukkantok”* használó**

Egy bizonyos értelemben a vissza-vissza néző használók a legszánalmasabbak mind közül. Vagy abban a hitben élik le az életüket hogy hiányérzetük van, vagy ami gyakoribb, az egy pillantásból kettő lesz. Visszacsúsznak a lejtőn, és előbb-utóbb ismét súlyos használók lesznek. Újra visszaesnek a csapdába, amibe már korábban beleestek.

Az alkalmi használóknak két további kategóriája van. Az első az, aki legutóbb kiszivárgott celeb szexvideókra végez önkielégítést, vagy valamire amit ‘hazahozott’, miután ‘véletlenül’ belefutott a munkahelyén vagy az iskolában.  Ezek az emberek valójában egyszerű nem-használók, akik úgy érzik hogy valamiből kimaradnak. Részesei akarnak lenni a ‘klubnak’, és a legtöbbünk így indul el a lejtőn. Ezután, figyeld meg hogy a celeb akiről fantáziálsz, már nem az igazi. Minél ‘elérhetetlenebb’ a fantáziád tárgya, annál frusztrálóbb az orgazmus elvonása.

A második kategória mostanában egyre több figyelmet kap, és legjobban egy online megosztott történet segítségével lehet leírni.

Egy diplomás nő sok éven át internetes pornográf történeteket olvasott, egy éjszaka egyet, se többet, se kevesebbet. Történetesen ő egy erős akaratú hölgy volt. A legtöbb használó csodálkozna, hogy ő miért is akart leszokni egyáltalán -- nagy örömmel rámutatva hogy ilyen helyzetekben a pornó okozta merevedési zavar (az ő esetében korai ejakuláció) veszélye nem áll fenn (ez nem így van). Alanyunk nem is képeket használt, hanem történeteket, amik sokkalta szelídebbek mint bármilyen anyag amit a használó szokott naponta nézni.

A használó téved, amikor azt hiszi hogy az alkalmi használók boldogabbak, és jobban az uralmuk alatt tartják a helyzetet. Lehet hogy jobban irányítják a helyzetet, de biztosan nem boldogok. Ezen hölgy nem volt elégedett se nem a társával, se nem a valódi szexxel, és igen ingerlékeny volt, amikor a mindennapi stresszhatásokra reagált. A kedvese pedig nem tudta kitalálni hogy mi a gond. Amikor ez a hölgy elkezdte racionalizálni a használatot, hogy ne féljen tőle, még akkor sem tudta élvezni a valódi kapcsolatokat, amikben mindig vannak jó és rossz napok. A sok dopamin miatt pedig az agyának a jutalmazó központja nem tudta kihasználni a normális stresszoldókat. Az agy receptorainak leépülése többnyire melankolikussá tette. Sokakhoz hasonlóan ő is félt a pornográfia sötét oldalától, és attól ahogy ott a nőkkel bánnak -- legalábbis mielőtt először használta volna. Idővel meg áldozatul esett a társadalom agymosásának, és felkeresett egy pornóoldalt. A legtöbbekkel ellentétben, akik megadják magukat és lánc-nézők lesznek -- ő ellenállt a csúszdának, amint meglátta a sok alantas, erőszakos videót.

A pornóban sosem élvezel mást, csak az előtte kezdődött sóvárgás megszűntét, legyen az a majdnem észrevehetetlen fizikai sóvárgás, vagy az a mentális kínzás, amikor nem vakarhatod meg a viszketést. A pornó egy méreg, és ezért van az hogy csak tartózkodás után tűnik úgy hogy élvezed. Az éhséghez vagy a szomjúsághoz hasonlóan, minél tovább szenvedsz tőle, annál jobb érzés enyhíteni. Elkövetve azt a súlyos hibát, hogy azt hiszi hogy a pornó csak egy szokás, a használó azt gondolja. *“Hogyha le tudom vinni a használatot egy bizonyos szintig, vagy ha csak különleges alkalmakkor használom, az agyam és a testem el fogja tudni fogadni. Akkor majd használhatom abban a mértékben, vagy tovább csökkenthetem, ha szeretném.”*

Vésd jól az eszedbe, a ‘szokás’ nem létezik. A **pornófüggőség: drogföggőség**, amivel kapcsolatban a természetes tendencia az, hogy enyhíted, és nem az hogy átvészeled. Ahhoz hogy a mostani szinten tartsd a használatot, elképesztő mértékű fegyelmet és akaraterőt kéne alkalmaznod egész hátralévő életedben; mivel az agyad jutalmazó központja immunissá válik a dopaminra és az opioidokra, tehát egyre többet akar, és nem egyre kevesebbet.

Ahogy a pornó fokozatosan elpusztítja az idegrendszered, a bátorságod, az önbizalmad és az ingereid kontrollját, egyre kevésbé leszel képes egy adott szinten tartani a használatok közti időt. A korai napokban ezért tudjuk még abbahagyni.  Hogyha úgy látjuk hogy valami mentálisan vagy fizikailag nincs rendben, egyszerűen abbahagyjuk. Ne irigyeld ezt hölgyet, amikor csak 24 óránként egyszer nézel pornót, akkor a világ legfontosabb dolgának tűnik, a pornót tiltott gyümölccsé téve. Sok éven keresztül ez a szegény nő a kötélhúzás közepében volt.

Nem tudott leállni, és mégis félt videókat nézni. A nap huszonhárom órájában és tíz percében a kísértéssel, és a barátja iránti érzések hiányával kellett küzdenie. Hatalmas akaraterő kellett ahhoz hogy azt tegye valaki amit ő tett, és még így is sírnia kellett. Az ilyen esetek ritkák, de nézd logikusan: vagy van valamilyen támasz vagy öröm a pornóban, vagy nincs. Ha van, akkor ki akar várni vele egy órát, napot, vagy akár egy hetet? Miért tagadod meg ez idő alatt akkor ezt a támaszt vagy örömöt? Ha meg nincs benne semmi ilyesmi, akkor meg minek használod?

Itt egy másik eset, ami egy négy naponta használó férfié:

> "*Negyven éves vagyok, és pornó okozta merevedési zavartól szenvedtem valódi nőkkel, és még pornóhasználat közben is, tehát az idő nagy részében. Már egy jó ideje nem volt teljes merevedésem. Mielőtt elkezdtem volna a négy naponta egyszer-diétát, a használat után jól aludtam. Most pedig óránként felkelek, és csak erre tudok gondolni. Amikor alszom, akkor is a kedvenc videómról álmodok. A beütemezett használatot követő napokon eléggé magam alatt vagyok, mert a diéta az összes energiámat felhasználja. A társam pedig magamra hagy, mert olyan rosszkedvű vagyok, és ha nem tud kimozdulni, akkor nekem kell elmenni. Elmegyek futni, de akkor is csak a pornóra tudok gondolni.*
>
> *Aznap, amikorra beütemeztem, már kora este elkezdek tervezgetni, és nagyon mérges leszek ha valami a terveimmel szemben alakul. Kihátrálok a beszélgetésekből, és (későbbi megbánásra) a munkahelyen meg otthon is használok.  Nem vagyok egy vitatkozós ember, de nem akarom hogy a téma vagy maga a beszélgetés ott tartson. Emlékszem alkalmakra, amikor hülyeségeken összevesztem a társammal. Megvárom amíg tízet üt az óra, és amikor eljön a pillanat, a kezeim irányíthatatlanul remegni kezdenek. Nem látok neki azonnal -- mert hozzáadtak azóta új videókat -- és inkább körbenézek előbb. Az agyam azt mondja hogy mivel négy napig éheztettem magam, ezért megérdemlek egy ‘különleges’ videót, aminek meg kárpótolnia kell a kereséssel eltöltött időt. Idővel találok egy vagy két videót, de szeretném hogy sokáig tartson az alkalom, hogy ‘túléljem’ a következő négy napot, tehát tovább húzom a tett befejezését.*"  

A többi baja mellett, még az is ott van, hogy ez a szegény ember nem is tudja hogy mérget adagol magának. Először, a ‘tiltott gyümölcs szindrómában’ szenved, és utána pedig dopaminnal öblíti le az agyát. Az ő dopamin-receptorai még aránylag jó állapotban vannak, de a pornó-vízicsúszdán ő is sokat csúszik, keresi az anyagot, és az elhúzást, az újdonságot, a változatosságot, sokkot, és nyomasztást, hogy túl tudja élni  következő négy napot. Ezt a férfit valószínűleg egy szánalmas kis kreténként képzeled el, de ez nem így van. Egy volt sportoló, aki tengerészgyalogosként szolgált, ő nem akart semmire sem ráfüggeni. Azonban, amikor visszajött a háborúból, át lett képezve informatikai technikusnak egy veterán-rehabilitációs program keretein belül.  

Miután átkerült a polgári szférába, jól fizetett informatikus lett egy banknál, és kapott egy céges laptopot, amit hazavihetett. Ez abban az évben volt, amikor sok celeb “kiszivárogtatta” a szexvideóit online, és sok helyütt lehetett erről hallani. Emberünk ekkor lett függő, és úgy tűnt hogy az élete hátralévő részében végig magát fogja károsítani, mind anyagilag, mind fizikailag, mind mentálisan. Ha egy állat lett volna, már rég elaltatták volna, hogy véget vessenek a szenvedésének, de mi mégis hagyjuk hogy minden szempontból egészséges kamaszok függők legyenek. Gondolhatod azt hogy ez az eset el van túlozva, és bár némileg tényleg extrém, de ez az eset messze nem egyedi. Több tízezer hasonló történet van. A barátai, ismerősei szerinted biztosan irigyelték őt, mert csak minden negyedik nap használt? Ha azt hiszed hogy ez veled nem történhet meg, **ne áltasd magad.**

**MÁR FOLYAMATBAN VAN.**

A többi függőhöz hasonlóan a pornóföggők is hazudoznak, még maguknak is. Muszáj nekik. A legtöbb alkalmi használó sokkal többször használ, mint amennyit bevall. 'Heti kétszeri' használókkal folytatott beszélgetések során kiderült hogy hetente több mint háromszor-négyszer is szoktak használni.  Olvass utána a Redditen, a NoFap fórumokon, és 'újraindítási' történeteket alkalmi használóktól, és látni fogod, hogy vagy a napokat számolják, vagy a bukásra várnak. Nem kell irigyelned az alkalmi használókat, és használnod sem kell, az élet végtelenszer jobb nélküle.

“*Azzal az egyszerű kihívással kezdődött, hogy egy napig ne érjek hozzá az ágyékomhoz, de nem tudtam megcsinálni. Most már nem is gondolok az önkielégítésre, az eszembe se jut. És ez ígérem,lehetséges. A kincsek, amik azokra várnak, akik képesek rá -- hihetetlenek.*”

A kamaszokat általában nehezebb meggyógyítani, nem azért mert nehezebbnek érzik hogy leálljanak, hanem mert nem hiszik el hogy függők, vagy hogy a csapda korai fázisában vannak. Általában attól a tévelygéstől is szenvednek, hogy automatikusan le fognak állni a második fázis előtt. 

Az internetes pornót gyűlölő gyerekek szülei ne ringassák magukat hamis biztonságérzetbe. Az összes gyerek gyűlöli az internetes pornó sötét oldalát, mielőtt ráfüggene. Egyszer te is így voltál vele. Ne tévesszen meg a félelemkeltés se, a csapda ugyanaz, mint ami mindig is volt. A gyerekek tudják hogy az internetes pornó egy szupernormális stimuláns, de azt is tudni vélik hogy egy ‘látogatás’ vagy ‘pillantás’ nem tesz semmit. Egy szakaszban pedig a társuk, egy osztálytársuk, vagy kollégájuk is befolyásolhatja őket.

Kérlek ne legyél elégedett ez ügyben. Az, hogy a társadalom nem tudja megakadályozni hogy a serdülők ráfüggjenek a pornóra, és egyéb drogokra, az ennek a függőségnek  talán a leginkább felkavaró része. A serdülők agya jóval képlékenyebb, tehát szükséges őket oktatni és védeni. Ha nem vagy benne biztos hogy hol kezdd, a “YourBrainOnPorn”-könyv egy jó olvasmány, hogy egy képet kapj a neurológiáról. Ha csak sejted is, hogy a kamasz gyereked már függő, ez a könyv alapvető megértést biztosít ahhoz hogy segíts neki kiszabadulni. Egyébként meg, ajánld neki ezt a könyvet!

[^7]:Inkább *nem csak* azzal.
