# Egy társasági szokás? ?

Az elme és a test egészsége az elsődleges okunk *kellene legyen* a leállásra -- de mindig is ez volt. Nincs is szükségünk tudományos kutatásokra és neurológiai szaktudásra, hogy tudjuk hogy a pornó addiktív és tönkreteheti az életünket. A testünk a legösszetettebb szerkezet a Földön, és a használó már az első használat után tudhatja, hogy a stimuláns nagy mennyiségben mérgező.

Az egyetlen ok, amiért közünk lesz a pornóhoz, az az hogy a fogyasztási kör meg az evolúciós programozásunk egybevág. Az internetes pornó könnyen hozzáférhető, ingyenes, és a nap 24 órájában rendelkezésre áll. A pornót egykoron ártalmatlannak gondolták, de ez akkor volt amikor nyomtatott képek voltak csak, és a videókat kazettán kellett beszerezni.

A pornót manapság -- még a használók is -- szupernormális stimulánsnak és függőséget okozónak tartják. Régen az erős férfiak nem vallották be hogy maszturbáltak, nem véletlen a “rejszolás”, “recskázás” szavak negatív csengése. Minden kocsmában, szórakozóhelyen, a férfiak nagyon szívesen hazavittek egy nőt, és szexeltek. Manapság, a pornófüggő számára a helyzet a teljes fordítottja, a mai férfi kezdi úgy érezni hogy neki nincs is szüksége nőkre. Online csoportosulásokban megvitatja a tapasztalait, stratégiákat eszel ki, és átgondolja a lehetőségeit. A mai erős férfi nem akar drogfüggő lenni. A társadalmi változások miatt minden használó komolyan elgondolkodik azon hogy leálljon a pornóval és az önkielégítéssel. A mai használók a pornót egy haszontalan és káros tevékenységnek tartják.

A legjelentősebb trend az ezzel foglalkozó fórumokon a pornó antiszociális hatásain lévő egyre nagyobb hangsúly, azok a napok amikor egy férfi azzal hencegett, hogy ő minden nap szexel, és orgazmusa van, kezdenek elmúlni, és az emberek kezdenek rájönni hogy a pornó szörnye milyen szörnyű rabigába taszította őket.

Az egyetlen ok, amiért az emberek tovább használják, azután hogy már tisztán látják a képet, az az hogy nem sikerült leszokniuk, vagy félnek próbálkozni. Sokféle irányzat van az ügyben, néhányan tartózkodnak  a pornótól, az önkielégítéstől, és az orgazmustól (*Vagyis a PMO-tól*) -- a társukkal vagy nélküle. A szex tantrikus és szaporodási részét elválasztó gyakorlatok, mint például a sperma-visszatartás, vagy a Karezza egyre ismertebbek, és sokan használják is őket. Sok sikertelen próbálkozás a valóságban nem teljes bukás, és valamilyen módon segíti a használót. Amint rálépsz a neked leginkább megfelelő  PMO-mentes útra, érdemes egy saját tervet készíteni az orgazmusokra, miután megéretted, és megvalósítottad a szex fajtáinak különválasztását. Bármit is választasz, értékelni fogod hogy milyen jó dolog, amikor ritkábban öblíted le az agyad vegyi anyagokkal az orgazmuson keresztül, és soha többet nem fogod a pornót, a szexet, és az orgazmust örömként vagy támaszként látni.

Számos, nem-használók által alapított közösség van, melynek nem csak a pornóról, hanem az önkielégítésről való leszokás a célja. Ezek a közösségek hasznosak a használóknak, de többnyire az akaraterőre támaszkodnak. A szériákkal való megszállottság következménye a jókedv hiánya, és az önsajnálat. Mindeközben, az agymosás is él és virul. Csak idő kérdése hogy valaki megtörjön, és ezt elmesélje, és ilyenkor többen is rájönnek hogy nincsenek ezzel egyedül. Azonban nem dolgozott senki sem hiába, mindenki egy kicsit kijjebb araszolt a csapdából, de ez sok szenvedéssel járt, ugyanis ők csak a böngészőt kapcsolják le, de nem a vágyukat és a szükségüket a pornóra. A Járható Út fordítva működik, lekapcsolja a vágyat és a szükséget, mielőtt a böngészőt kapcsolná le. Minden nap egyre több használó hagyja el a süllyedő hajót, és mindenki, aki rajta maradt retteg attól, hogy ő lesz az utolsó.

**NE TE LEGYÉL AZ!**
