# Időzítés 

Azt leszámítva, hogy a pornó nem tesz jót, és most a legjobb abbahagyni, az időzítés így is fontos. A társadalom nem veszi az internetes pornót komolyan, és csak egy enyhén ellenszenves szokásnak tartja, ami nem is káros az egészségre. Ez azonban nem így van. A pornófüggőség drogfüggőség, betegség, és a kapcsolatok pusztítója. A legtöbb használó életében a legrosszabb dolog az volt, hogy ráfüggtek erre az ocsmányságra. Ha függők maradnak, borzalmas dolgok fognak velük történni. Az időzítés tehát igen fontos, hogy ki tudd kúrálni magad. 

Először is, azonosítsd azokat az alkalmakat, amikor a pornót fontosnak látod. Ha te egy üzletember vagy, és a pornót stresszoldás illúziója miatt használod, akkor válassz egy laza időszakot, vagy amikor szabadságon vagy. Ha a pornót unalmas vagy nyugodt időszakokban használod, akkor az ellenkezője. Mindenesetre, vedd komolyan, és legyen a kísérletet a legfontosabb dolog az életedben.

Tervezz három hétre előre, és készülj fel az olyan eseményekre, amik kudarchoz vezethetnek. Hogyha konferencia utad lesz, a párod elutazik, stb., még nem kell megijedned, feltéve hogy számítasz ezekre, és nem fogod azt hinni, hogy megvonnak tőled valamit. Ne kíséreld meg csökkenteni addig a használatot, mert az csak egy illúziót fog teremteni, mégpedig azt hogy a megvonás élvezetes. Sőtmitöbb, ez segíteni fog hogy minél több pornót nézz és használj. Amikor legutoljára használod, ne feledkezz meg a csalódásról, a szanitáció, a betöltetlen várakozások, bármiféle fájdalom, az elvonás hatásai, a nyűgösség, és a melankólia miatt. Gondolj bele, milyen jó lesz, amikor végre nem kell majd használnod.

**DE BÁRMIT IS TESZEL, NE ESS BELE ABBA A CSAPDÁBA, HOGY AZT MONDOD: “NEM MOST, INKÁBB KÉSŐBB”, ÉS EL IS FELEDKEZEL RÓLA. DOLGOZD KI MOST A MENETRENDET, ÉS ÖRÜLJ HOGY MEG FOGSZ SZABADULNI.**

Emlékezz, *nem adsz fel semmit.* Épp ellenkezőleg, hatalmasat fogsz nyerni.

Az orvosi szakma sok évig a pornót ártalmatlannak tekintette, anélkül hogy különbséget tett volna a régi állóképes pornó, és a mai VR-streamelős között. A baj pedig az, hogy bár minden használó csak a dopamin-sóvárgás enyhítésére fogyaszt pornót, nem a kémiai függőség tartja őket leláncolva, hanem a függőségből eredő önagymosás. Egy okos embert is át lehet verni, de csak egy bolond dőlne be sokadjára is a trükknek, miután rájött hogy átverik. Szerencsére a legtöbb használó nem bolond; csak azt hiszi. Minden használónak van egy saját agymosása. Ezért tűnik úgy hogy olyan sok féle függő van, és mindez csak tovább bonyolítja a helyzetet.

Míg az eredeti könyv célja a nikotinról való leszokás volt (ami az egyik leggyorsabban, és leginkább függővé tevő drog), igen meglepő volt hogy az eredeti könyv filozófiája az adaptáció után is működik. A Carr és jómagam által  elvállalt kihívás, és tudás az hogy, hogyan kommunikáljuk ezt a tudást minden egyes használónak. Az hogy tudom, hogy minden egyes használó nem csak könnyen le tud szokni, hanem hogy élvezni is tudja a folyamatot, nemcsak hogy felesleges, hanem igencsak frusztáló is, ha a használó nem jön rá. Az eredeti könyvében, Allen Carr így magyarázza a tanácsát:

>"Sokan mondták már nekem: ‘*te azt mondod hogy dohányozzunk, amíg be nem fejüzzük a könyvet. Emiatt a dohányosnak sok időbe telik amíg elolvassa, vagy be se fejezi. Tehát meg kéne változtatnod az utasítást.*' Ez logikusnak hangzik, de tudom, hogyha az lenne az utasítás hogy ‘*Azonnal hagyd abba!*’, sok dohányos el se kezdené olvasni. A korai napokban konzultáltam egy dohányossal. Azt mondta hogy ‘*Nem örülök hogy segítségért kell folyamodnom, tudom hogy erős akaratom van. Az élet többi területén én irányítok. Miért van az hogy a többi dohányos le tud szokni az akaraterejét használva, és nekem mégis hozzád kell fordulnom?’* Úgy folytatta *hogy 'Meg tudnám én is csinálni, ha közben dohányozhatnék.'\"*

Sokan azt hiszik, hogy a dohányzásról leszokni rendkívül nehéz, tehát mi kell a dohányosnak, amikor valami nehéz? A kis barátja, támasza. Leszokni a dohányzásról duplán nehéznek tűnik, nem csak hogy egy bonyolult feladatot kell elvégezni - ami önmagában is elég nehéz - de még a támaszunk is elérhetetlen. Lehet hogy a módszer valódi szépsége az az hogy nem kell ‘feladnod’ semmit a folyamat során; először inkább megszabadulsz a kételyektől és a félelemtől, és így amikor befejezed az utolsó alkalmadat már élvezed a szabadságodat.

Tehát ebben a hack-könyvben ugyanez az elgondolás. Mindegy, hogy hányszor lett már elmondva hogy könnyű és élvezetes lesz, sokan nem fogják tudni ezt elfogadni, mert átmosták a saját agyukat, azzal hogy milyen nehéz leszokni.

Az ‘*Időzítés*’ az egyetlen fejezet, ahol komolyan kétségbe vonom Allen eredeti tanácsát. Először is, ha az irodai stressz miatt hajlamos vagy használni, csináld akkor amikor szabadságon vagy, és vice versa. Ez nem a legkönnyebb módszer, az az lenne ha a szerinted legnehezebb időszakot választod. Legyen az stressz, társasági kötelezettségek, koncentráció vagy unalom, amint bebizonyítottad hogy kibírod a legrosszabb helyzeteket is, és tudod azokban is élvezni az életet, minden más élvezetes lesz. De ha ez lenne a tanács, próbálkoznál egyáltalán?

Álljon itt egy analógia, a húgom és én úszni szeretnénk. Ugyanakkor szoktunk megérkezni az uszodába, de csak nagyon ritkán úszunk ténylegesen együtt. Azért, mert a húgom a vízbe teszi a lábujját, és rá fél órával úszik is. Ez lassú kínzás, és én tudom hogy előbb vagy utóbb, mindegy milyen hideg a víz, bele kell menni. Tehát kitanultam, hogy kell könnyen: belemegyek egyből. Képzeld el, hogyha ragaszkodnék ahhoz hogyha a húgom nem ugrik be egyből, nem is úszhatna. Ha ez lenne, nem is úszna. Látod mi itt a baj?

A visszajelzések alapján sok használó arra használta az eredeti tanácsot, hogy elhalassza a szerinte “gonosz napot”. Ezután arra gondoltam, hogy ‘*A pornóhasználat előnyei*’ fejezethez hasonló technikát alkalmazok, valami olyasmit hogy - *“Az időzítés nagyon fontos, és a következő fejezetben arról olvashatsz, hogy mikor érdemes megpróbálni leszokni”*, és a következő oldalon csak az van, jó nagy betűkkel hogy **“MOST!”** Ez lenne a legjobb tanács, de megfogadnád? Lehet hogy a csapda legalattomosabb aspektusa az, hogy amikor tényleg stresszelünk, akkor az nem a megfelelő idő, de amikor meg nem, akkor meg nem is akarunk a kínzásnak véget vetni. Kérdezd meg magadtól a következőket:

1.    Amikor először láttál pornót, eldöntötted, hogy az életed végéig függeni fogsz rajta, anélkül hogy le tudnál állni? **Persze hogy nem!**

2.    Úgy fogod leélni az életedet, hogy nem tudsz leállni? **Persze hogy nem!**

Mikor fogod tehát abbahagyni? Holnap? Jövőre? Jövő utánra? Nem ezt kérdezgeted magadtól, mióta rájöttél hogy függő vagy? Azt reméled, hogy egy reggel úgy ébredsz majd fel, hogy nem akarsz több pornót nézni? Ne áltasd magad, minden függőség olyan, hogy egyre függőbb leszel, és nem egyre kevésbé. Addig fogsz várni, amíg úgy érzed, hogy nehezebb kikelni az ágyból, mint csak maszturbálni? Annak nem sok értelme lenne.

Az igazi csapda azt hinni, hogy most nem megfelelő - holnap mindig könnyebb. Azt hisszük hogy az életünk stresszes, de igazából nem az. A valódi stressz nagy része eltűnt az életünkből. Amikor kilépsz a házból, nem félsz attól hogy megtámad egy vadállat, a legtöbbeknek nem kell aggódni, hogy honnan szereznek élelmet, vagy hogy lesz-e tető a fejük felett. Gondolj bele, milyen egy vadon élő állat élete, amikor a nyúl kijön az üregéből, a pokollal néz szembe. De a nyúl kibírja, van neki adrenalinja, és egyéb hormonai, és nekünk is vannak. Igazából az összes lény életének a legstresszesebb időszaka a kora gyermekkor, és a serdülőkor. De a három milliárd évnyi természetes kiválasztódásnak köszönhetően tudunk bánni a stresszel, és sokaknak, akiknek nehéz gyerekkora volt, teljesen normális felnőtt életük van.

Az hogy *“ha nem vagy egészséges, nincs semmid”* hatalmas közhely, de teljesen igaz. Ha testileg és lelkileg erős vagy, kibírod mind a jó, mind a rossz időket. Sokan összekeverik a stresszt a felelősséggel, de a felelősség csak akkor lesz stresszes, ha nem érezzük magunkat elég erősnek hozzá. A legtöbb embert nem a stressz, a munkája, vagy a kora teszi tönkre, hanem a képzelt támaszok amikhez fordulnak.

Próbáld meg így nézni, már eldöntötted hogy nem fogsz életed végéig a csapdában maradni. Tehát előbb vagy utóbb, akár könnyűnek találod, akár nehéznek, át kell esned a szabadulás folyamatán. A pornó se nem egy szokás, vagy élmény, hanem drogfüggőség és betegség. Már megállapítottuk hogy, nem hogy holnap könnyebb lenne, egyre rosszabb lesz. A legjobb idő a szabadulásra **most** van - vagy olyan hamar, ahogy csak lehetséges. Gondolj bele, hogy minden hét milyen gyorsan telik el, csak ennyi kell. Gondolj bele, milyen jó lesz leélni az életet, feletted lógó árnyékok nélkül. Feltéve hogy követed az összes utasítást, nem is kell öt napot, vagy három hetet várnod. Nemcsak hogy könnyen le fogsz tudni szokni, **még élvezni is fogod!**
