# Kimaradok a jóból?

**Nem!**  Amint meghal a kicsi szörny, a tested már nem vágyik a dopamin után, és a pornó-vízicsúszdák gyorsan elfakulnak a ‘zsírozás’ hiánya miatt, és az összes megmaradt agymosás el fog tűnni. Nemcsak hogy mind testileg, mind lelkileg jobban fogod tudni kezelni az élet nehézségeit, de a jó dolgokat is sokkal jobban fogod élvezni.

Egyetlen egy veszély van még, azoknak a hatása, akik a szexet továbbra is a támaszukként, és az örömükként használják. *“A szomszéd fűje mindig zöldebb”* egy igen gyakori, és könnyen megérthető jelenség. A pornó esetében a volt használó miért irigyli azokat akik még mindig a szexre és a pornóra támaszkodnak, miközben a pornó hátrányai mellett eltörpülnek a képzelt ‘előnyei’?

A sok agymosás miatt érthető, ha beleesünk a csapdába. Miért van az hogy, -miután rájöttünk hogy mekkora átverés a pornó, és miután leszoktunk róla- visszaesünk ugyanabba a csapdába? Ez a társadalom agymosásának a terméke, ami összekeveri a pornót a szexxel, és normálisként mutatja be. A volt-használónak kattogása van! Az a bizonytalan érzés, hogy egyedülálló (ami egyébként nem bűncselekmény) szorongást okoz, és ez visszaviszi emberünket a vízicsúszdára. Ez valóban egy érdekes anomália, különösen, ha figyelembe vesszük, hogy nem csupán minden nem-használó örül, hogy nem használ, hanem hogy az összes használó, még a nyugalom tévképzetében szenvedő használó, a függő, agymosott, elfogult agyával azt kívánja, bár ne függött volna rá a pornóra. Akkor miért irigykednek a volt-használók?

1.  Csak egy pillantás. Emlékezz, olyan nincs. Ne úgy nézd, mint egy elszigetelt esetet, hanem úgy mint ahogy használó látja. Lehet hogy te irigyled őket, de nekik nem tetszik amit csinálnak, és téged irigyelnek. Bár tudnál nézni egy másik használót, mert az lehetne a legnagyobb motivációd a szabadulásra. Látod milyen gyorsan nyitnak meg sok-sok böngészőlapot és ablakot? Ahogy előretekernek a fontos részekhez, ahogy gyorsan megunják a videókat, ahogy átfutnak az újdonságot, sokkot, nyomasztást tartalmazó műfajok sokaságán. Figyeld meg, hogy mindez ráadásul automatikusnak tűnik. Emlékezz, hogy ők sem élvezik, csak nem érzik nélküle jól magukat. Következő reggel pedig gyenge akarattal, energia nélkül, csipás szemmel felkelnek, és a stressz első jelére tovább pusztítják magukat. Egy életnyi mocsokkal, rossz mentális egészséggel, és gyenge önbizalommal néznek szembe- egy életnyi önpusztítással. És mindezt miért? Annak az illúziójáért, hogy megkapod ami “jár neked”, és valami hülye örömért?

2.  A második ok, amiért néhány volt-használónak kattogása van, az az hogy a használó csinál valamit, -- például önkielégít -- és a nem-használó pedig nem, ezért úgy érzi, megfosztják valamitől. Vésd jól az eszedbe, hogy nem a nem-használót fosztják meg bármitől is, hanem a szegény függőt fosztják meg az:
    
    -Egészségétől
   
    -Energiájától
    
    -Önbizalmától
   
    -Nyugalmától
   
    -Bátorságától
    
    -Szabadságától
    
    -Önbecsülésétől

    Ne irigyeld a használókat, lásd őket olyannak amilyenek, nyomorult, szánalmas kis lényeknek. Tudom, egykoron én is ilyen voltam. Ezért te olvasod ezt könyvet, és nem azok, akik nem bírnak szembenézni a helyzetükkel, és tovább szórakoznak magukkal.

Nem irigyelnél egy heroinfüggőt, és ahogy a többi drogfüggőség sem lesz idővel jobb, úgy a tied sem. Minden évben csak egyre rosszabb lesz - ha ma nem jó használónak lenni, holnap sokkal rosszabb lesz. Ne irigyeld a használókat, inkább sajnáld őket. Hidd el: ***szükségük van a sajnálatodra.***
