# Szét lehet-e tagolni a függőséget?

Ezt a mítoszt többnyire az akaraterő-módszerrel leállni szándékozó használók terjesztik, akik csűrik-csavarják a valóságot, és egy Jekyll és Hyde-műveletbe kezdenek: *“A pornó a másik énemnek van, és a valódi románc a kapcsolatos énemnek.”* Ennél semmi sem állhatna messzebb az igazságtól - a vízicsúszdák, a DeltaFosB, és a neurológiai változások tönkreteszik a valódi románcot, és kevésbé lesz tőle vonzó. Mr. Hyde mindenképpen felül fogja írni Dr. Jekyll utasításait.

Ha internetes pornót használsz, a kukkoló szerepére képzed magad, vagy arra hogy amint minimálisan csökken a dopamin-szinted, valami izgatóbbra kattints. Vagy arra, hogy folyamatosan keresd a megfelelő jelenetet a maximális hatásért. Ezenfelül, lehet hogy görnyedve végzed az önkielégítést, vagy éjszaka az ágyban nézed a telefonodat, ami ahhoz vezethet, hogy ezekre az ingerekre jobban vágysz majd, mint a valódi stimulánsokra. A szex az online háremmel teljesen ellentétes, és esélye sincs, ha összehasonlítják. A fiatalkorban képződött emlékek erősek, és sokáig megmaradnak, tehát a pornó-vízicsúszdák bezárása, és az újak építése több időbe telik. Ez azonban nem azt jelenti hogy a szabadulás nehezebb lenne.

Minden egyes alkalommal, amikor lecsúszol a ‘pornó-vízicsúszdán’, bezsírozod, és frissen tartod a felelős idegeket. Amikor egy gyorsétterem mellett parkolsz, a sütő illata beszivárog az orrodba, és a terméket már el is adták. A vízicsúszdák az agyban is hasonlóan működnek, azok is mindig be tudnak szívni, és mindig nyitva is vannak. Minden egyes inger bekapcsolja a jutalmazó központot szex ígéretével - csakhogy ez nem szex. Az idegsejtek ennek ellenére új idegi kapcsolódások létrehozásával megerősítik ezeknek az ingereknek szexxel asszociálását. Minél több pornót nézel, annál erősebbek ezek az idegi kapcsolódások. Ez meg abban ér véget, hogy a végén egy kukkolóvá *kell* válnod, egyre eszkalálódó és új anyagra kell kattintanod, pornó fog kelleni az elalváshoz, vagy meg kell találnod a legjobb anyagot, hogy el tudd végezni a munkádat.

Ahogy az összes függőségnél, a test itt is immunitást épít ki, és a drog többet nem enyhíti a kattogást. Amint a használó a végére ér a használatnak, akar még egyet, és az állandó éhség kielégítetlen marad. A természetes reakció erre az eszkaláció, hogy meglegyen a dopamin-adag. A legtöbb használó azonban nem teheti, a következő okok valamelyike miatt.

**Pénz:** Nincs pénzük feliratkozni fizetős oldalakra.

**Egészség:** A testnek van egy tűréshatára a dopamin adag vagy az orgazmus tekintében. Plusz az orgazmus olyan vegyi anyagokat szabadít fel, amik csökkentik a dopamin adagot. Muszáj neki, a test egyszerűen így működik.

Amint elhagyja a tested a kicsi szörny, a bizonytalanság véget ér. Visszatér az önbizalmad, az önbecsülés csodálatos érzésével együtt, és így végre kezedbe tudod venni az irányítást, és szembenézni a többi problémával. Ez az egyik nagy előnye annak ha megszabadulsz a függőségtől.

A széttagolás mítosza a kicsi szörny egyik trükkje a sokból. Ezek a trükkök megnehezítik a leállást - az állandó éhség kielégíthetetlen volta miatt - és sok használót a dohányzás, az ivás, vagy a kemény drogok felé terelnek, hogy ki tudják tölteni az űrt.

Az emberek ítélkeznek, mind saját maguk, mind mások felett. Pornót nézni a társaddal nem kielégítő, mert mind a ketten a látottakhoz fogjátok a másik teljesítményét mérni. Brad Pittet akarod a hálószobádban, még akkor is, hogyha a poszteren van? Senki sem ér fel a hárem szintjéhez, ahol mindent profik játszanak el, írnak és rendeznek, és a nap huszonnégy órájában elérhető.
