# Nem megfelelő ösztönzések

Sokan, akik az akaraterő-módszert használják, nem megfelelő a dolgokkal próbálják magukat ösztönözni. Ennek egy tipikus példája az, amikor megajándékozzák magukat valamivel, miután egy hónapig nem néztek pornót. Ez logikusnak és ésszerűnek tűnhet, de nem az, mivel bármelyik használó, akinek van egy csöpp önbecsülése is, inkább nézne pornót minden nap, mint hogy megajándékozza magát. Ez kétségeket ébreszt a használóban, nem csak azért, mert harminc napig  tartózkodnia kell, hanem mert nem is biztos benne, hogy élvezi-e a pornómentes napokat. Nincs meg az egyetlen öröme vagy támasza! Ez meg nem tesz más, mintsem hogy növeli a használó által képzelt áldozat méretét, ami így még értékesebbnek tűnik a fejében.

További példák::

-   Le fogok szokni, hogy arra kényszerítsem magam, hogy legyen társasági és szexuális életem.

-   Le fogok szokni, hogy legyen valamiféle varázserőm, ami segítségével a riválisokat legyőzve megszerezhetem a vágyott partneremet.

-   Le fogok szokni, hogy ne pazaroljam el az energiámat a pornóra, és ezáltal kiéheztessem magam.

Ezek mind igazak, hatékonyak is lehetnek, és lehet sikerrel is jársz velük -- de egy pillanatra gondolj bele. Ha eléred azt, amit akartál, és eltűnik az újdonság hatása, megvonást fogsz érezni; ha meg nem, akkor nyomorultul. Mindenesetre, előbb vagy utóbb vissza fogsz esni a csapdába.

A leszokás nem megfelelő dolgokkal való ösztönzése csak növeli a kételyeket, mert ha nem éred el azt, amit akartál (és akkor is ha eléred), kételyeid fognak támadni, és ilyeneket kezdesz el gondolni: *“Tényleg jobb lesz az élet, ha felhagyok a használattal?  Ha sikeresen leszokok, és nem azt kapom, amit szerettem volna, jól használtam a módszert?”* Az ilyesmi gondolatok növelik az áldozathozatal érzését, és így kattogást okoznak.

Egy másik tipikus példa a különböző fórumokon kötött paktumok, amiknek megvan az az előnye, hogy egy időre megszüntetik a kísértést. Azonban, ezek többnyire sikertelenek a következők miatt: 

1.  Nem megfelelő dolog motiválja őket, miért akarnál leszokni, csak azért mert mások is azt csinálják? Ezzel csupán növelik magukon a nyomást, és az áldozathozatal érzését. Az rendben van hogy minden használó le akar állni egy adott pillanatban -- de nem lehet őket rákényszeríteni, pedig titokban szeretnének leállni. Amíg nincsenek felkészülve, a paktum csak további nyomást tesz rájuk, ami miatt még inkább szeretnének pornót nézni. Ettől titokban fogják nézni, ami csak növeli a függőség érzését.

2.  Mivel egymástól függenek, az akaraterő-módszert használva úgy érzik, mintha vezekelenének, ami során kivárják, hogy eltűnjenek az ingerek. Ha meg beadják a derekukat, azt kudarcnak érzik. Az akaraterő-módszert használva az egyik résztvevő mindenképpen fel fogja adni, és így a többieknek végre lesz ürügye, hogy ők is feladják. Nem az ő hibájuk, ők kitartottak volna, csak ‘Fred’ cserben hagyta őket. Az igazság az, hogy a legtöbbjük már eleve csalt.

3.  Ha megosztják egymás közt a dicsőséget, az az egymáson való függőség ellentéte. A pornóról leszokni hatalmas sikerélmény, és ha egyedül csinálod, a barátaid és az online cimboráid elismerése hatalmas lökést adhat az első pár napra. Azonban ha együtt csinálják, a dicsőség eloszlik a résztvevők között, és a lökés ezáltal kisebb lesz.

4.  Egy másik klasszikus példa a guru-ígéret. Ha leállsz, boldog leszel, mert nem veszel részt a kötélhúzásban, az agyad újrahuzalozódik, és újra kezelni tudja majd az impulzusokat. Azonban, ne felejtsd, hogy ettől nem leszel se nem szex-isten, se nem lottónyertes. Téged leszámítva senkit sem érdekel, ha leszoksz a pornóról. Nem vagy egy gyenge ember, ha naponta háromszor használsz pornót, és merevedési zavarod van, és nem vagy erős, ha függő vagy, és mégse használsz.

Ne áltasd magad. Ha a 10 hónapnyi munkáért 12 hónapnyit fizető állásajánlat, vagy az agyad tűrőképességének a tönkremenése, vagy a mervedési zavar kockázata, vagy az életen át tartó lelki, fizikai kínzás és rabság elkerülése nem elég motiváció nekik, akkor a fenti néhány hamis ösztönző aligha fog számítani, egyedül abban segítenek, hogy az áldozat nagyobbnak tűnjön. Ehelyett, koncentrálj a másik oldalra:

\"Miért jó ez nekem? Miért kell pornót néznem?\"

Nézd a kötélhúzás másik oldalát, és kérdezd meg magadtól, mit kapsz a pornótól. **SEMMIT**. Miért kell ezt csinálnom? **NEM KELL! CSAK MAGADAT BÜNTETED**. Ez egy Pascal-fogadás: Semmi vesztenivalód nincs (gyenge merevedés), jó esély arra hogy nagyot nyerj (teljes és megbízható merevedés, mentális jólét és boldogság), és semmi esély arra hogy veszíts.

Akkor miért ne meséljek el a szabadulásomról a barátaimnak és a családomnak? Nos, egy büszke volt-függő, vagy volt-használó leszel tőle, és nem egy boldog nem-használó. Ezzel meg is ijesztheted a társadat, mert azt hiheti hogy ez valami new-age módszer arra hogy több szexhez tudj jutni. Attól is félhet hogy egy szex-géppé fogsz változni, ezt nehéz elmagyarázni, hacsaknem nyitott rá.

Minden arra tett kísérlet, hogy a többiek segítsenek leszokni, csak megerősíti a kicsi szörnyt. Ha megpróbálod kilökni a fejedből, és figyelmen kívül hagyni, az olyan mintha megpróbálnál *nem* is gondolni rá. Legyél inkább figyelmes, és amint észreveszed a gondolatokat és jeleket (otthon vagy egyedül), mondd azt magadnak *\“De jó, hogy már nem vagyok a pornó rabszolgája. Szabad vagyok és boldog, és ismerem a különbségeket a szexben!”\"* Ezzel megfojtod a gondolatot, és az már nem fog sóvárgáshoz vezetni. Ezzel kapcsolatban  a tudatos meditáció hasznos lehet a gondolatok személytelenítéséhez.
