# A leszokás könnyű útja.

Ezen fejezetben instrukciókat találsz arról, hogy lehet könnyen leszokni. Feltéve hogy követed az instrukciókat, a leszokás az aránylag könnyűtől az élvezetesig bárhol lehet! Feltéve hogy követed a lenti instrukciókat, nevetségesen könnyű lesz leszokni a pornóról, és mindehhez csak két dolgot kell tenned.

1.  Döntsd el, hogy soha többet nem nézel pornót.

2.  Ne szomorkodj emiatt. Örvendezz.

Valószínűleg azt kérdezed: *“Miért kell akkor a könyv többi része? Miért nem ezzel kezdted?”* A válasz az, hogy idővel elkezdtél volna szomorkodni, és így meggondoltad volna magad. Ezt valószínűleg már többször csináltad. 

Mint ahogy már el lett mondva, a pornó egy alattomos csapda. A legnagyobb probléma a leszokás során nem a dopamin függőség -- ami bár egy probléma, de nem az elsődleges -- hanem az agymosás. Ezért először el kell pusztítani a mítoszokat és a tévképzeteket. Értsd meg az ellenséged, ismerd a taktikáját, és könnyen le fogod tudni győzni. Sok időt töltöttem depressziósan, amíg leszokni próbáltam, és amint megszabadultam, egyből nullára mentem, egy zökkenő nélkül. Az egész elvonási időszak  is élvezetes volt, és azóta sem kattogtam. Sőt, a szabadulás volt az egyik legjobb dolog az életemben.

De az utolsó kísérletem más volt. Az összes mai használóhoz hasonlóan, én is sokat gondolkodtam a problémán. Addig ugyanis, miután elbuktam, azzal vigasztaltam magam hogy legközelebb könnyebb lesz. Azzal sose számoltam, hogy ezt kellene életem végéig csinálnom, és ennek a gondolata megrémített, és én elkezdtem gondolkodni  nagyon mélyen erről a témáról.

Ahelyett hogy gondolkodás nélkül beizzítottam volna a böngészőt, elemeztem az érzéseimet, megerősítve azt, amit már eddig is tudtam. Nem élveztem a pornót, és mocskosnak, undorítónak találtam. Elkezdtem a világ más részein élő nem-használókat, vagy pornóoldalakat nem ismerő öregeket tanulmányozni. Addig a nem-használókat sótlan, barátságtalan, kényes embereknek tartottam. Azonban, jobban megvizsgálva őket, sokkal inkább erősebbnek és nyugodtabbnak tűntek. Úgy tűnt, hogy jobban bírják az élet nehézségeit, és a használóknál jobban élvezik a társasági helyzeteket. Határozottan több volt bennük az életerő.

Elkezdtem beszélni volt-használókkal. Addig azt gondoltam, hogy ők csak egészségügyi vagy vallási okok miatt adták fel, és hogy titokban egy háremlátogatásra vágytak. Egy páran azt mondták *“Néha kattogok, de olyan kevésszer, és olyan ritkán hogy nem aggódok miatta.”* De a legtöbben azt mondták: *“Hiányzik? Te most viccelsz! Az élet soha sem volt jobb!”* Hogyha elbuktak esetleg, akkor sem omlottak össze, nem ítélték el magukat, és ehelyett feltétel nélkül elfogadták magukat. Mint egy edző, aki elfogad egy hibát egy tényleg kiváló játékostól. Egy másik mítosz is meg lett semmisítve, amikor a volt-használókkal beszéltem, mégpedig az hogy van bennem egy gyengeség, amíg rájöttem, hogy mindenki átmegy ezen a rémálmon. 

Alapvetően, azt mondtam magamnak: *“Emberek tömegei szoknak le, és élnek teljesen boldog életet, mielőtt elkezdtem volna, nem kellett PMO-znom, és sokat kellett ahhoz dolgoznom, hogy hozzászokjak ehhez a mocsokhoz. Tehát, miért kell ezt csinálnom?”* Egyáltalán nem élveztem sose a pornót, utáltam az egész mocskos rituálét, és nem akartam az életem hátralévő részét ennek az undorító függőségnek a láncaiban tölteni. Ekkor azt mondtam magamnak:

*"“Ha tetszik, ha nem, most használtál utoljára.”"*

Onnantól kezdve tudtam, hogy soha többet nem fogok használni. Nem számítottam arra hogy könnyű lesz, hanem épp ellenkezőleg. Azt hittem, több hónapnyi mélységes-mély szenvedésre jelentkeztem, és hogy életem végéig néha kattogni fogok. Ehelyett, ez a kezdettől maga volt az álom.

Sokáig tartott, míg rájöttem hogy miért volt olyan könnyű, és miért nem szenvedtem a szörnyű kattogástól. Azért, mert a kattogás nem létezik , a kétely és a bizonytalanság hozza létre. A gyönyörű igazság az, hogy ***a pornóról könnyű leszokni***. Egyedül a habozás és a búslakodás nehezíti meg. Még a függők is el tudnak lenni pornó nélkül bizonyos időkben. Csak akkor szenvedsz, ha szeretnéd használni, de nem teheted.

Tehát, úgy lehet könnyen leszokni, ha biztos vagy benne, és a döntésed végleges. Nem reméled, hanem *tudod* hogy legyőzted a betegséget. Soha ne kételkedj, vagy kérdőjelezd meg, épp ellenkezőleg - örülj, hogy így döntöttél! Ha az elejétől fogva biztos tudsz lenni, könnyű lesz. De hogy lehetsz az elejétől fogva biztos?  Ezért kell a könyv hátralévő része. Vannak bizonyos dolgok, amiket tisztázni kell, mielőtt nekilátnál:

1.  Tudd, hogy nem lehetetlen. Te sem vagy kivétel, és az egyetlen ember aki arra kényszerít hogy nézd, az te magad vagy. A sztár a képernyő túloldalán soha nem gondolt arra, hogy a virilitás megnyirbálására használják.

2.  Nincs mit feladni. Épp ellenkezőleg, hatalmasat lehet nyerni. Nemcsak hogy egészségesebb leszel, és több pénzed lesz, de ki fogod tudni élvezni a jó időket, és ki fogod tudni bírni a rosszakat.

3.  Nincs olyan, hogy pillantás, vagy látogatás. A pornó egy drogfüggőség, és egy láncreakció, és és ha vissza akarsz látogatni, csak magadat bünteted.

4.  A pornót ne egy ‘a fiúk már csak ilyenek’ szokásként lásd, ami csak esetleg árthat meg, hanem lásd drogfüggőségként. Nézz szembe azzal, hogy akár tetszik, akár nem, **elkaptad a betegséget**. Ha a homokba dugod a fejed, attól nem gyógyulsz meg. Emlékezz, hogy az összes bénító betegséghez hasonlóan, ez is egy életen át tart, és még egyre rosszabb is lesz. Most a  legkönnyebb meggyógyítani.

5.  Különböztesd meg a betegséget -- a neurológiai függőséget -- a használó gondolataitól. Minden használó, ha lenne rá lehetősége, gondolkodás nélkül visszamenne abba az időbe, amikor még nem volt függő. Neked megvan az a lehetőség. Nehogy úgy gondolj rá, hogy te ‘feladod’ a használatot. 

Amint meghozod a végleges döntést, hogy megvolt az utolsó látogatásod, egyből nem-használó leszel. A használó egy olyan szerencsétlen aki úgy éli az életét, hogy közben pornóval tönkreteszi magát. A nem-használó pedig olyasvalaki, aki nem. Amint meghozod a végleges döntést, a célod el lesz érve. Örvendezz, ne csak szomorkodva üldögélj, arra várva hogy elmúljon a kémiai függőség. Menj ki a levegőre, és kezdd el élvezni az életet. Az élet csodálatos, még akkor is ha függő vagy, és ha nem vagy az, napról-napra jobb lesz.

Ahhoz hogy könnyű legyen, az a kulcs, hogy biztos legyél abban hogy sikeresen fogsz tudni tartózkodni az elvonási periódus alatt (legfeljebb három hét). Ha megfelelően állsz hozzá, ez nevetségesen könnyű lesz.

Mostanra, ha felnyitottad az elmédet[^8], mint ahogy azt az elején kértem, már eldöntötted hogy ki fogsz szabadulni. Most jó esetben igen izgulsz, úgy mint egy kutya aki a láncát feszíti, és várod már hogy végre felégethesd a DeltaFosB-csúszdákat, és a helyüket sóval behintsd. Ha esetleg most szomorkodsz, az a következő okok valamelyike miatt lesz:

1.  Valami még nem világos. Olvasd el újra a fenti öt pontot, és tedd fel a kérdést, hogy elhiszed-e őket. Ha bármelyikben kételkedsz, olvasd újra a könyv megfelelő részeit.

2.  Félsz a kudarctól. Ne aggódj, csak olvass tovább, és sikerrel fogsz járni. Az internetes pornó, úgy ahogy van, csak egy gigantikus átverés. Egy okos embert is át lehet verni, de csak egy bolond dől be sokadjára is, miután rájött hogy átverik.

3.  Mindennel egyetértesz, de továbbra is nyomorultul érzed magad. Hát ne érezd úgy magad! Nyisd ki a szemed, valami remek van folyamatban. A börtönből fogsz megszökni, szükséges hogy jól állj hozzá: *“Milyen jó, hogy nem-használó vagyok!”*

Most csak azt kell elérni, hogy az elvonási időszak alatt is jó legyen a hozzáállásod, és a következő pár fejezet ezt fogja lehetővé tenni. Az időszak letelte után nem kell így gondolkodnod, mert magadtól is így fogsz gondolkodni, és az egyetlen rejtély az lesz, hogy korábban miért nem jöttél minderre rá. Azonban, felhívom a figyelmed két dologra.

-   Halaszd el az utolsó látogatást, amíg nem fejezted be a könyvet

-   Sok szó esett már a legfeljebb három hetes elvonási időszakról, és fennáll a félreértés veszélye. Először is, azt hiheted, hogy három hétig szenvedned kell majd. Nem kell. Másodszor, ne ess bele abba a csapdába, hogy azt gondolod *“Három hétig valahogy tartózkodnom kell, és utána minden jó lesz”* Nem fog semmi mágikus dolog történni, nem fogod hirtelen úgy érezni magad, mint egy nem-használó, mivel a nem-használó nem érzi magát máshogy mint a használó. Ha a három hét alatt szomorkodsz a leszokás miatt, jó eséllyel utána is szomorkodni fogsz. Összefoglalva, ha most azzal kezded hogy *“Soha többet nem fogok pornót használni, nem csodálatos?”*, három hét után az összes kísértés el fog múlni. Azonban, ha azt mondod hogy *“Bár túlélnék három hetet pornó nélkül!”*,  a karodat is odaadnád egy látogatásért.

Próbálj így gondolkodni - az agyad fenn akarja tartani a fennálló állapotot, tehát ha azt hiszed hogy valami jó dolgot vesztesz el a leszokás során, nyilvánvalóan rosszul fogod magad érezni. Nem kényszerítheted magad arra, hogy egy bizonyos módon érezz, hogyha az agyad nem hiszi el. Ezért kell azzal bajlódni, hogy eltávolítsd azt az illúziót, hogy a pornó bármit is ad. Innen fogod tudni, hogy semmit sem áldozol fel.

A szexuális zavaroknak sok közük lehet az agyhoz, és a hozzáálláshoz. Az internetes pornó átprogramozza az agyad jutalmazó rendszerét, és egy ‘kételkedő’ hozzáállásod lesz tőle. Ezek a kételyek pedig vitathatatlanul szexuális zavarokhoz vezetnek. A legrosszabb ami a hozzáállásoddal történhet, az az amikor a felső részednek van vágya, de az alsó nem tud felizgulni. A libidó és a románc a fiatalság titkos elixírje, amit halálod napjáig használhatsz. Jó esélyeid lesznek erre, ha leszoksz, de nem az egyetlen, vagy a legnagyobb nyeremény. Hanem hogy szabad leszel.

[^8]: Ez nem az első (meg nem is az utolsó) alkalom, hogy a Hackauthor szabópéteres nyelvezetet használ, amit az egyszerűség kedvéért így hagyok, de megnyugtatlak, kedves Olvasó, hogy ez NEM egy olyan jellegű könyv.

