# Az elvonási időszak

Az utolsó alkalmat követő három hétben elvonási kattogás léphet fel, ami kettő különböző, azonban jól megkülönböztethető tényezőből áll.

1.  Dopamin elvonási tünetek. Egy éhséghez hasonló, üres, bizonytalan érzés, amit vágyakozásként, vagy egy “valamit tennem kell”-típusú érzésként fogunk fel.

2.  Bizonyos külső ingerek okozta pszichológiai kiváltó okok, például reklámok, online vásárlás, telefonbeszélgetések, stb.

Aki ezt a kettőt nem tudja megkülönböztetni, annak sokkal nehezebb dolga lesz az akaraterő-módszerrel, és ez az ami miatt olyan sokan újra a csapdában végzik. Igaz, hogy a dopamin elvonási tünetei nem okoznak fizikai fájdalmat, de ne becsüld le őket! Ha egy napig nem eszünk, korog a gyomrunk, de fizikai fájdalmunk nincsen. Az éhség még így is egy komoly erő, és éhesen nyűgösek is leszünk. Ez hasonlít arra, amikor a testünk egy dopamin-adagot kíván, az egyetlen különbség az, hogy a testünknek szüksége van az ételre, de méregre nincs. A megfelelő hozzáállással az elvonási kattogás könnyen legyőzhető, és gyorsan el is fog tűnni. 

Miután egy pár napig megtartóztattuk magunkat az akaraterő-módszerrel, már nem kívánjuk a dopamin-adagokat. A problémát a második tényező, az agymosás okozza. A felhasználó megszokta hogy enyhíti az elvonási tüneteit, meghatározott időnként, és helyzetekben, ami erre való asszociációkat okozhat (*“merevedésem van, így pornót kell nézzek”* vagy *“az ágyban vagyok a laptopommal,az ágyban vagyok a laptopommal, tehát használnom kell, hogy boldog legyek”*) Ennek a hatása legjobban egy példával illusztrálható: van egy autód, és az index a bal oldalon van, de a következő autódon már a jobb oldalon. Az új autóval így egy ideig a ablaktörlőt fogod nyomni, ha indexelni akarsz. 

Hasonló a helyzet ha leállsz, egy darabig ezek az ingerek működésbe fognak lépni. Arra fogsz gondolni, hogy milyen jó lenne most egy alkalom, ezért az agymosást már a legelejétől meg kell szüntetni, és így az ingerek gyorsan el fognak tűnni. Az akaraterő-módszerrel a felhasználó azt hiszi, hogy áldozatot hoz, és így szomorkodik miatta, és arra vár hogy az ingerek eltűnjenek, azonban azok nemhogy eltűnnek, hanem erősebbek lesznek. A guru-gondolkodás esetén, ehhez hasonlóan a felhasználó azon kezd gondolkodni hogy mikor válik Istenné, és azt kezdi el követelni, hogy ne is legyenek ilyesmi gondolatai, és ez öngyűlöletet és bukást eredményez.

Az egyedüllét gyakran kísértést hoz magával, különösen a társasági eseményeken. A más módszerekkel leszokni próbáló használó ilyenkor már eleve nyomorultul érzi magát, mert nem fér hozzá a szokásos támaszához vagy öröméhez. A barátai pedig a társaikkal vannak, és intim módon viselkednek. Alanyunk vagy egyedülálló, vagy nem ‘kap’ a társától, és már nem élvezi az eredetileg kellemes társasági eseményt. A meglévő vízicsúszdák a pornóhoz vezetik, ami egyszerűbb, mint udvarolni a partnerének.

Mivel a szexre való jogosultságot összeköti a jóléttel, immár egy hármas csapástól szenved, és az agymosás mértéke meg is növekszik. Ha emberünk elszánt, és elég sokáig ki tud tartani, idővel elfogadja a sorát, és továbbhalad. Azonban, az agymosás egy része megmarad, és a második legszánalmasabb rész az, hogy a használó leszokott, és még sok év után is ‘egy utolsó látogatásért’ sóvárog. Egy olyan illúzióért sír, ami csak a fejében létezik, és ezzel feleslegesen kínozza magát.

Az ingerekre való reagálás az egyik leggyakoribb oka a bukásnak, még a Járható Úttal is. A volt-használó az internetes pornóra valamilyen placebóként, vagy cukortabletta kezd el tekinteni. Azt gondolja *“Tudom, hogy a pornó nem használ, de ha azt hiszem hogy igen, bizonyos alkalmanként hasznos lesz.”* Egy cukortabletta, bár igazából nem használ, de egy erős pszichológiai eszköz lehet a valód tünetek enyhítésére, és így igazából előnyös. Az internetes pornó és a rendszeres önkielégítés azonban, nem számítanak cukortablettának. Miért? Mert a pornó okozza a tüneteket, és nem tudja őket teljesen enyhíteni.

Lehet hogy egy volt-használó, vagy egy több évig nem használó esetében  könnyebb megérteni a hatásokat. Például legyen egy olyan használó esete, aki elvesztette a társát, és ilyen helyzetben a legjobb szándékkal is könnyű azt mondani hogy *“Tégy egy látogatást, az majd segít lenyugodni.”* Ha elfogadja az ajánlatot, a látogatás nem fogja lenyugtatni, mert nincs dopaminfüggősége, ezáltal kattogása se. A pornó ilyenkor legfeljebb egy pillanatnyi pszichológiai löketet ad.

Még azután is, hogy végzett, az eredeti tragédia továbbra is megtalálható. Sőt, rosszabb is lesz, ugyanis a használó most a kattogástól is szenved, és azzal a választással szembesül, hogy vagy kibírja, vagy pár csúszdamenettel enyhíti, ami a nyomorúságát is visszahozza. A pornó kizárólag egy múló pszichológiai löketet adott, amit el lehetett volna érni egy könyvvel, vagy egy kellemes filmmel, vagy akár egy rossz filmmel is. Sok nem-használó, és volt használó újra függő lesz emiatt. Vésd az eszedbe: nem kell a dopamin-adag, és csak magadat kínzod azzal, ha valamilyen támasznak, vagy segítségnek fogod fel. Egyáltalán nem kell, hogy nyomorultul érezd magad.

Az orgazmustól egy kapcsolat nem lesz jó, sőt sokszor az rontja el. Emlékezz, hogy nem teljesen igaz az, hogy azok akik nyilvánosan mutatják ki a vonzalmukat, mindig élvezik is. Az intimitás leginkább privát körülmények között élvezhető, amikor az ember kínos érzések nélkül tud reagálni, és ezt nem segíti ha orgazmus-dopaminfüggő vagy. Ha az események következtében megtörténik, az rendben van, de nem árt ha tudod az életet nélküle is élvezni.

Miután a pornót már nem látják többé élvezetesnek, sok használó azt gondolja: “Bárcsak lenne tiszta internetes pornó.” Létezik ‘finomabb’ pornó, és aki kipróbálja, rá fog jönni hogy időpazarlás. Vésd az eszedbe, hogy csak azért használtál pornót, hogy megszerezd a dopamin-adagot. Amint megszabadultál a dopamin iránti sóvárgástól, nem érzed majd többé szükségét, hogy meglátogasd a háremed.

Akár a valódi dopamin elvonás miatt, vagy a jelek mechanizmusai miatt van a kattogás, fogadd el. Fizikai fájdalom nincsen, és ha jól állsz hozzá, ezzel nem is lesz gond. Ne aggódj az elvonás miatt, maga az érzés nem rossz. Ennek az érzésnek a vágyakozással, és az elvonással való asszociációja okoz gondot. Ahelyett, hogy siránkoznál miatta, ismerd el: *“Tudom mi ez, ez az pornó-elvonási kattogás. A használók egész életükben ettől szenvednek, és emiatt maradnak függők. A nem-használók nem szenvednek a kattogástól, ami a függőség egyik aljas hozadéka. Nem csodálatos, hogy kipurgálom az agyamból?”*

Máshogy mondva, a következő három hétben lesz benned egy kisebb sérülés, de az idő alatt, és az életed többi részében, valami csodálatos fog végbemenni. Meg fogsz szabadulni egy borzalmas betegségtől, és a kis sérülést bőven meghaladják a nyeremények, és a kattogást élvezni is fogod. Örömteli pillanatok lesznek, mint ha azzal szórakoznál, ahogy halálra éhezteted a pornó-férget a gyomrodban. Három hétig kell éheztetni, de az alatt minden cselt be fog vetni, hogy megetesd.

Időnként meg fog próbálni megnyomorítani. Időnként meg fog lepni. Lehet kapsz egy pornó linket, vagy találsz valamit online, és elfelejted, hogy leszoktál, és belédötlik az elvonás érzése. Készülj fel ezekre a cselekre, és bármekkora is legyen a kísértés, ne feledd, hogy csak a kicsi szörny miatt van ott, és mindig amikor ellenállsz a kísértésnek, egy újabb halálos csapást mértél rá.

Azonban, bármit is teszel, ne próbálj meg elfeledkezni a pornóról. Ez az egyik olyan dolog, ami sok szenvedést okoz az akaraterő-módszerrel próbálkozóknak. Minden napot úgy próbálnak túlélni, hogy idővel egyszerűen elfeledkeznek róla. Olyan ez, mint amikor az ember nem tud aludni -- minél jobban aggódik, annál nehezebb lesz. Te sem fogsz tudni elfelejtkezni róla, és a kicsi szörny folyton emlékeztetni fog, és ezt nem lehet kikerülni. Amíg laptopokkal, telefonokkal, és magazinokkal vagy körülvéve, állandóan emlékeztetve leszel. 

A lényeg az, hogy nem kell elfelejtened, mert nem történik semmi rossz. Sőt, valami csodálatos dolog van folyamatban, és még ha naponta ezerszer is gondolsz rá, ***emlékeztesd magad, hogy milyen csodálatos újra szabadnak lenni. Emlékeztesd arra magad, hogy milyen remek, hogy nem kell tovább kínozd magad***. Ahogy el lett már mondva, azon fogad magad észrevenni, hogy a kattogás örömmé válik, és meg fogsz lepődni azon,hogy utána milyen gyorsan elfelejtkezel a pornóról.

Azonban, *semmi esetre se kételkedj a döntésedben*. Amint kételkedni kezdesz, siránkozni fogsz, és utána minden rosszabb lesz. Ehelyett a búslakodást alakítsd egy lökéssé. Ha ez depresszió miatt van, emlékezz hogy a depressziót a pornó *okozta*. Ha egy barátod küld egy linket, büszkén mondd azt: *“Örömmel állítom, hogy erre már nincs szükségem”*. Ez nem fog neki jól esni, de amikor rájön, hogy ez nem is zavar, már félúton lesz ahhoz, hogy csatlakozzon.

**Ne felejtsd: rendkívül erős okaid vannak arra, hogy leszokj.** Emlékeztesd magad arra, hogy mibe kerül, és kérdezd meg magadtól, hogy vajon tényleg szeretnéd azt kockáztatni, hogy minden bajod legyen, és azt hogy láncokban élj. Vedd észre a kicsi szörny próbálkozásait, arra hogy elbagatellizálja a veszélyeket, és legfőképp, emlékezz, hogy az érzés csupán ideiglenes, és minden másodperccel közelebb vagy a célodhoz.

Néhány használó attól fél, hogy egész életükben ‘automatikus ingerek’ ellen kell harcolnia. Máshogy mondva, ez azt jelenti, hogy azt hiszi, hogy egész életében mindenféle pszichológiai módszerekkel azzal kell áltatnia magát, hogy nincs szüksége pornóra. Ez nem így van, emlékezz, hogy az optimista szerint a pohár félig tele, és a pesszimista szerint félig üres. A pornó esetében az üveg üres, és a használó szerint tele van. Az internetes pornó használatának nincsenek előnyei. A használót átmosták az agyát, ezért azt hiszi, hogy vannak. Hogyha elkezded magadnak azt mondogatni, hogy nem kell pornó, vagy nem akarsz nézni, kis idő múlva már nem is kell majd mondani, mert rájössz a gyönyörű igazságra. Ugyanis, a pornónézés az utolsó dolog, amire szükséged van, de ne az legyen az utolsó dolog, amit teszel.
