# Csak egyetlen kis pillantás

Ez sok akaraterő-módszerrel próbálkozó végzete. Három-négy napig nem néz pornót, utána meg rápillant egyet, hogy ki tudja bírni. Ennek a moráljára gyakorolt borzalmas hatásával nincs tisztában

A legtöbb használó számára az első pillantás egy pornóoldalon nem  volt olyan jó, mintha egy valódi emberrel szexelt volna. A tiszta videók igen ritkák, és ez megnyugtatja a használó tudatos elméjét. Azt gondolja hogy *“Remek, ez nem is volt olyan élvezetes. Idővel nem is lesz ehhez kedvem, és nem is szeretem ezeket a sokkoló dolgokat.”* Ennek az ellentéte igaz. Vésd az eszedbe, nem azért szoktál le a pornóról, mert élvezted az orgazmust. Ha a használók csak az orgazmus miatt használnának, nem néznének egy videónál többet. Csak azért kellett a pornó, hogy megetesd a kis szörnyet. Gondolj bele, miután több napig éheztetted, milyen értékes lehetett neki az a kis pillantás. A tudatos elméd nem tudja, de az adagnak a jele a tudatalattidba megy, és az összes felkészülés aláásódik. Lesz az agyad mélyén egy kis hang, hogy minden logika ellenére, a használat fontos, és neked kell még egy.

Annak a kis pillantásnak két romboló hatása is van:

1.    Életben tartja a kis szörnyet.

2.    Ami még rosszabb, hogy a nagy szörnyet is életben tartja. Hogyha volt egy pillantás, könnyen lehet egy második is.

A pornó egy egérfogó, sajt helyett méreggel. Az akaraterő módszerrel meggyőzöd magad, hogy ne edd meg a sajtot, de a Járható Úttal rájössz, hogy az igazából méreg. Nem is kerülöd el vele, csak nem kezded el. 

Mindenekelőtt, emlékezz:

*'Csak egy pillantás' miatt kezdjük egyáltalán el.*
