# Nekem nehezebb lesz?

Hogy milyen könnyen tud valaki leszokni, azt a tényezők végtelen számú kombinációja határozza meg. Először is, mindnyájunknak megvan a maga személyisége, körülményei, időzítése, anyagcseréje, stb. Bizonyos szakmák képviselőinek lehet, nehezebb lesz, de feltéve hogy az agymosástól megszabadulnak, ennek nem kell így lennie. Vedd például a következőt.

Időnként orvosok csak nehezen tudnak leszokni. Azt hihetné az ember, hogy az orvosoknak könnyebb, mert ők jobban ismerik a pornó hatásait, és bár ez erős okokat ad nekik, nem lesz tőle könnyebb, a következők miatt:

1.  Mivel folyamatosan tisztában vannak a kockázatokkal, elkezdenek félni, és a félelem az egyik olyan állapot, ami során enyhítenünk kell a kattogást.

2.  Az orvosok munkája rendkívül stresszes, és munkaidőben többnyire nem is tudják a kattogást enyhíteni

3.  A bűntudat miatt még többet stresszelnek, mert úgy érzik, példát kéne mutatniuk a lakosságnak. Emiatt csak nagyobb lesz rajtuk a nyomás, és ez növeli az elvonás érzését.

Egy nehéz nap után, amikor a pornó egy pillanatra enyhíti a stresszt, a stresszoldást helytelenül a használathoz kötik. Emiatt a helytelen asszociáció miatt, a pornó aratja le a babérokat, és így hirtelen nagyon értékessé válik amikor alanyunk megpróbálna leszokni, és elvonási kattogáson megy át. Ez az alkalmi használat egy fajtája, és ez alkalmazható minden helyzetre, ahol a használónak huzamosabb időre tartózkodnia kell. Az akaraterő-módszerrel a használó nyomorultul érzi magát, mert megvonnak tőle valamit, és nem élvezi a használat utáni fáradtságot és alvást, és sokkal inkább úgy érzi, hogy valamit elvesztett. Azonban, ha először megszabadulsz a pornót illető agymosástól és búslakodástól, az alvás még akkor is élvezetes lesz, ha a test közben amino-transzmitterekre vágyakozik, vagyis szerotoninra, noradrenalinra, és dopaminra.

Az unalom egy másik nehéz helyzet, különösen akkor, ha stresszel kombinálódik. Egy tipikus példa a diákok, és az egyedülálló szülők munkája, ami egyszerre stresszes és monoton. Amikor az akaraterő-módszerrel próbálkozik, az egyedülálló ember sok ideig siránkozik a ‘vesztesége’ miatt, és ettől rosszabbul fogja magát érezni. Ezt persze könnyen le lehet győzni, ha jól állsz hozzá. Ne aggódj amiatt, hogy folyton emlékeztetve vagy arra, hogy leálltál. Ezeket a pillanatokat használd fel arra, hogy örülj, hogy megszabadultál a gonosz szörnytől.

Ha jól állsz hozzá, a kattogás örömteli eseménnyé válik. Ne feledd, minden használó, kortól, nemtől, intelligenciától vagy szakmától függetlenül könnyen és élvezetesen leszokhat, **feltéve, hogy követi az instrukciókat.**

## A bukás leggyakoribb okai

A bukásnak két gyakori oka van. Az első a külső stimulánsok hatása - egy reklám, egy online cikk, internet böngészés, stb. A használót lehet hogy egy gyenge pillanatban érik, vagy féltékeny lesz, ha intimitást lát egy társasági helyzetben. Erről korábban már esett szó. Ha ilyesmi történik, használd a pillanatot arra, hogy emlékeztesd magad arra, hogy nincs olyan, hogy látogatás, vagy pillantás. Örvendezz, hogy letörted a mentális rabság láncait. Emlékezz, hogy a használó irigyel téged, és szánnod kéne a használót, ugyanis szüksége van rá.

A másik ok, pedig hogy rossz napja van. Vésd szilárdan eszedbe, hogy akár használó vagy, akár nem, lesznek jó és rossz napjaid. Mind az igazaknak, mind a hamisaknak esik. Az élet relatív, és nem lehet jó napod rossz nap nélkül. A baj az akaraterő-módszerrel az, hogy amint rossz napja van a használónak, szomorkodni kezd egy hárem-látogatásért, ami csak tovább bonyolítja a helyzetet.  A nem-használó jobban tudja a stresszt és a gyűrődést kezelni, nemcsak fizikailag, hanem mentálisan is. Ha az elvonási időszak alatt rossz napod van, próbáld meg kibírni; emlékeztesd magad arra, hogy akkor is voltak rossz napok, amikor függő voltál, ha nem lettek volna, nem döntöttél volna a leszokás mellett. Tehát, ahelyett, hogy siránkoznál, vedd észre hogy mi  is a helyzet: *“Rendben, a mai nem egy olyan jó nap, de a pornó nem fog segíteni. A holnap jobb lesz, és legalább van egy hatalmas jutalmam, hogy legyűrtem azt a borzalmas függőséget.”*

A használóknak ki kell zárniuk az agyukból a pornó negatívumait. A használóknak sosem ködös az agya, csak ‘nincsenek olyan jól’. Amikor szembekerülsz az élet elkerülhetetlen gondjaival, és arra gondolsz, hogy pornót szeretnél nézni, boldog vagy? Persze hogy nem. Miután leszoksz, minden bajt a leszokásra kennél.

Ha a munka miatt idegeskedsz, akkor azt gondolod: *“Máskor ilyenkor használtam volna”* Így van, de van egy fontos dolog, amit ilyenkor elfelejtesz, mégpedig az, hogy a pornó nem oldja meg a bajt, és azzal ha a képzelt támaszod után búslakodsz, csak magadat bünteted. Egy lehetetlen helyzetet teremtesz, ahol nyomorultul érzed magad, mert nem tudsz pornóra önkielégíteni, de hogyha megteszed, még rosszabb lesz minden. *Tudod, amikor eldöntötted hogy le fogsz szokni, jó döntést hoztál, tehát miért bünteted magad azzal, hogy megkérdőjelezed a döntésedet?*

Ne feledd, a pozitív hozzáállás **mindig** létfontosságú.
