# Helyettesítők

Példa a helyettesítésre az, ha pornó-magazinokra, képekre, pornó-diétára, stb. korlátozod magad. **NE CSINÁLJ SEMMI ILYESMIT.** Ezek csak megnehezítik a dolgodat, és nem könnyítik meg. Hogyha beüt a kattogás, és ilyen helyettesítőt használsz, az csak elnyújtja a kattogást, amitől minden nehezebb lesz. A helyettesítők használatával csak azt mondod, hogy pornóra van szükséged ahhoz hogy betöltsd az űrt. Olyan lenne, mint együttműködni egy géprablóval, vagy mintha beadnád a derekad egy gyerek hisztijének, és ezáltal gondoskodsz arról, hogy máskor is kattogj, és így elnyújtja a kínokat. A helyettesítők semmiképp sem fogják enyhíteni a kattogást. A sóvárgás az az, hogy az agyad aminosavak után vágyakozik, és ennek az az egyetlen hatása, hogy a pornóra fogsz gondolni. Emlékezz a következő pontokra.

1.  A pornónak nincs helyettesítése.

2.  Nincs szükséged pornóra. Mert nem étel, hanem méreg. Amikor kattogni kezdesz, emlékeztesd magad, hogy a használók szenvednek az elvonási kattogástól, és nem a nem-használók. Lásd annak a kattogást, ami, a drog egyik újabb aljasságaként. Fogd fel a kattogást a szörny halálaként.

3.  Az internetes pornó nem betölti, hanem létrehozza az űrt. Minél gyorsabban tanítod meg az agyadnak, hogy nem kell pornót nézned, annál hamarabb leszel szabad. Sőt, kerülj is el mindent, ami a pornóra emlékeztet, például férfimagazinokat, filmeket, romantikus regényeket, és reklámokat. Attól, hogy ezt csinálod, még nem vagy szűklátókörű, románcról és szexről beszélni lehet, de pornó nyista. Mindig meg lehet találni, hogy hol és mikor kell különbséget tenni. Igaz, hogy a softcore pornóval, vagy pornó-diétával leszokni próbálkozó használók egy kis része sikerrel jár (a saját felfogásuk szerint), és a sikerüket a használat ilyen módjának tulajdonítják. Azonban, a használat *ellenére*, és nem amiatt tudnak leszokni. Szomorú, hogy sokan még mindig ezeket a módszereket ajánlják.

Ez nem meglepő, mert ha nem érted meg teljesen a pornó csapdáját, egy diéta vagy egy helyettesítés igen logikusnak tűnhet. Azon a tévhiten alapul ez, hogy amikor leszokni próbálsz, két erős ellenséget kell legyőznöd:

-   A szokás megtörését.

-   Túlélni a borzalmas elvonási kattogást.

Ha két erős ellenséged van, értelmes dolog egyszerre csak az egyikkel megküzdeni, ahelyett, hogy a kettővel egyszerre. Tehát az itt a gondolatmenet, hogy amikor először leállsz, heti egyszeri használatra veszel vissza, vagy ‘biztonságos’ pornót használsz. Aztán meg, amint megtörted a szokást, fokozatosan csökkented a használatot, így egyesével bánsz el az ellenségekkel.

Ez logikusnak hangzik, de helytelen információn alapszik. A pornó nem egy szokás, és az elvonásból eredő valódi fizikai fájdalom majdnem érzékelhetetlen. Amikor leszoksz, azt próbálod elérni, hogy mind a testedben, mind az agyadban lévő szörny minél gyorsabban meghaljon. A helyettesítési technikák csupán elnyújtják a kicsi szörny életét, és ez közvetve az agymosást is elnyújtja. A Járható Úttal könnyen és azonnal le lehet szokni, mert elpusztítod az agymosást az utolsó használat előtt. A kicsi szörny hamarosan halott lesz, és amíg haldoklik, nem fog több problémát okozni, mint akkor, amikor még használó voltál.

Gondolj bele, hogy lehet úgy kigyógyulni egy függőségből, hogy ugyanazt ajánlod, mint amire ráfüggtél? Sok történet kering online olyanokról, akik leszoktak a hardcore pornográfiáról, de továbbra is függenek a ‘biztonságos’ alternatíváktól, de ezzel áldozatul estek a kicsi szörny trükkjeinek. Ne tévesszen meg az, hogy a biztonságos pornó nem borzalmas -- az első videó is az volt. Minden helyettesítőnek ugyanaz a hatása mint a pornónak. Néhányan kényszeres evésbe kezdenek, és bár a pornóra vágyakozás üres érzése megkülönböztethetetlen az éhségtől, az egyik nem fogja a másikat kielégíteni. Sőt, ha van olyan dolog, ami arra jó, hogy pornót akarj tőle nézni, akkor az az evés. Mint ahogy már ki lett fejtve, a pornó-diéta, és a ‘biztonságos’ pornó csak a kötélhúzás közepére fog téged rakni, és a kísértésnek való ellenállás olyan zavaró, hogy a háremet meglátogatva meg fogsz könnyebbülni.

A legnagyobb baj a helyettesítéssel az, hogy elnyújtja a valódi problémát, az agymosást. Kell helyettesíteni az influenzát, miután vége van? Persze, hogy nem kell. Amikor azt mondod, hogy helyettesítened kell a pornót, akkor igazából azt mondod, hogy áldozatot hozol.  Az akaraterő-módszerrel együtt járó depressziót az okozza, hogy a használó azt hiszi, áldozatot hoz. Ha helyettesítesz, akkor csak az egyik problémát helyettesíted a másikkal. Nincs semmilyen öröm abban, ha étellel, cigarettával, vagy alkohollal tömöd magad. Csak kövér, nyomorult leszel, és rövid idő múlva, ismét használni fogsz. 

Az alkalmi használók csak nehezen tudnak megszabadulni attól a tévhittől, hogy megvonják tőlük a kis jutalmukat, úgy mint azok, akik nem tudnak felmenni a netre utazás, családi esemény, stb. miatt. Néhányan azt mondják *“Nem tudom, hogy tudnék pornó nélkül lazítani.”* Ez bizonyítja amit mondunk, és a függő - igen, függő, mert az alkalmi használó függő - nem azért tart szünetet, mert kell neki, vagy akarja, hanem mert nagyon-nagyon meg kell kaparnia a viszketést.

Emlékezz, a pornóhasználat sosem volt valódi jutalom.  Azzal ért csak fel, hogy szűk cipőt veszel fel, azért hogy aztán jó érzés legyen levenni. Tehát, ha úgy érzed hogy kell egy kis jutalom, legyen ez a helyettesítésed: munka közben viselj egy mérettel kisebb cipőt, vagy alsóneműt, és ne vedd le őket az  ebédszünetig, amikor is csodálatos élményben lesz részed, ahogy leveszed. Lehet úgy érzed, ez elég nagy hülyeség lenne. Teljesen igazad van. Ezt nehéz elképzelni, amíg a csapdában vagy, de a használók ezt csinálják. Azt is nehéz elképzelni, hogy amint nem kell majd a kis ‘jutalom’, és amint szánni kezded a csapdában lévő barátaidat, és azon kezdesz el csodálkozni, hogy miért nem értik.

Azonban, ha tovább hülyíted magad azzal, hogy a hárem látogatás egy valódi jutalom, vagy hogy kell valami helyettesítés, megfosztva és nyomorultul fogod magad érezni, és jó eséllyel újra a mocskos csapdában fogod magad találni. Ha egy igazi szünetre van szükséged, mint a háztartásbelieknek, tanároknak, orvosoknak, és egyéb dolgozóknak, hamarosan még jobban fogod élvezni azt a szünetet, mert nem leszel már függő. Emlékezz, hogy nem kell helyettesítés. A kattogás a dopamin iránti sóvárgás, és hamarosan véget fog érni. Legyen ez a támaszod a következő néhány napra, és élvezd, ahogy felszabadulsz a rabságból.
