# Elkerüljem-e a kísértő helyzeteket?

Az eddigi tanácsok egyértelműek voltak, és inkább instrukcióként, mintsem tanácsként volt őket érdemes kezelni. Erős, gyakorlati okaik voltak nekik, és ezeket az okokat több ezer esettanulmány támasztja alá. Azzal kapcsolatban, hogy próbáld-e elkerülni a kísértő helyzeteket, más a helyzet. Minden használó döntse el maga. Azonban, van két hasznos javaslat, ami segíthet döntést hozni. A jövőbeni kattogástól való félelem miatt használnánk életünk hátralévő részében pornót, és az a félelem két jól megkülönböztethető fázisból áll.

**Első fázis - “Hogy fogok túlélni pornó nélkül?”"**

Ez az a pánikszerű érzés, ami akkor támad a használónak, amikor éppen egyedülálló, vagy ha a társa aszexuális, közönyös, vagy nem éppen elérhető. A félelmet nem a kattogás okozza, hanem a függőségtől való pszichológiai félelem, hogy nem fog tudni szex és orgazmus nélkül túlélni. Ez akkor a legnagyobb, amikor a leszokás határán van, és ekkor a kattogás is a legkisebb. Ez az ismeretlentől való félelem, az a fajta félelem, amit a fejesugrást tanulók éreznek.

Az ugródeszka fél méter magas, de öt méter magasnak tűnik. A víz öt méter mély, de fél méter mélynek tűnik.  Nagy bátorság kell ahhoz, hogy ugorj, ha meg vagy róla győződve, hogy be fogod törni a fejed. Ugrani a legnehezebb, de ha rászánod magad, a többi már könnyű! Ez megmagyarázza, hogy sok erős akaratú használó miért nem kísérelte meg a leszokást, vagy miért tud csak pár napig túlélni, ha mégis megpróbálja. Sőt, vannak olyan, pornó-diétázó használók, akik miután eldöntötték hogy leállnak, elkezdenek zsinórban nézni, és sokkal hamarabb eszkalálódnak a súlyosabb videókhoz, mintha nem döntöttek a leszokás mellett. A döntés pánikot okoz, ami egy stresszes dolog, és igen erős(nek vélt) ok egy látogatásra. De mivel most már nem lehet, ezért úgy érzi, megvonnak tőle valamit, amit a stressz is súlyosbít.

Igen gyorsan elkezdhetsz nézni, amikor valami metaforikusan berobban. Ne aggódj, a pánik csak pszichológiai. A pánik az attól való félelem, hogy függő vagy. A gyönyörű igazság hogy nem vagy az, még akkor sem, amikor még a csapdában vagy. Ne ess pánikba, és ugorj.

**Második fázis - hosszabb távú félelem** 

1.  *“Elkezdek egy négy naponta használós pornó-diétát. Magabiztosabb leszek, mert tudom, hogy ha valami baj van, benézhetek a hárembe. Ha nem sikerül, sebaj, majd hozzáadok pár napot a következő ciklushoz.”*

    Az ezt a módszert használók sokkal nagyobb arányban buknak el, mint azok, akik egy az egyben leszoknak. Ez leginkább azért van, mert hogyha az elvonási időszak során rossz napod van, könnyű megnyitni a böngészőt, és tenni egy látogatást a fenti kifogásokkal. Hogyha van annyi gerinced, hogy megszeged a saját szabályaidat, akkor egyébként is beadtad volna a derekad a kísértésnek. Mindenesetre, a kattogás már elmúlt volna, ha késleltetted volna a látogatást. Azonban, a nagyarányú bukás legfőbb oka az, hogy a használó nem is köteleződött teljesen el a leszokás mellett. Ne felejtsd, a két legfontosabb dolog ahhoz, hogy sikerrel járj a következő:

    -   Bizonyosság.

    -   *“Hát nem csodálatos, hogy nincs már szükségem pornóra?”*

   De mindenesetre, minek kell használnod? Ha továbbra is látogatásra van szükséged, olvasd előbb újra a könyvet, mert valami még nem tiszta. Szánj rá elég időt, hogy megöld a nagy szörnyet, az agymosást.

2.  *“Kerüljem-e a stresszes, vagy társasági helyzeteket az elvonási időszak alatt?*

    A stresszes helyzeteket igen. Nincs értelme annak, hogy felesleges nyomás alá helyezd magad. A társasági helyzetekkel kapcsolatban pedig ez ellenkezője igaz. Nyomás kifelé, és élvezd az életetet, nem kell neked sem szex, se nem a szex szaporodási oldala, még akkor sem, amikor még függő vagy. Menj ki, és örülj hogy nem kell semmilyen formában szexelned, és gyorsan rá fogsz jönni, hogy az élet sokkal jobb az ilyen nyomások nélkül. Gondolj bele, milyen jó lesz majd, amikor a kicsi szörny elhagyja az agyadat, a rossz gondolatokkal együtt.
