# A megvilágosodás pillanata

A szabadulástól számított három héten belül a volt-használóknak megvilágosodásban van részük. Az ég kivilágosodik, és ez az a pillanat, amikor az agymosás teljesen véget ér. Ahelyett, hogy azt mondod magadnak, hogy nem kell pornót nézned, hirtelen rájössz hogy a lánc elszakadt, és élvezheted az életed hátralévő részét pornó nélkül is. Többnyire ekkor van az, hogy a használókat igazán szánni kezded.

Az akaraterő-módszerrel próbálkozók többnyire nem tapasztalják meg ezt a pillanatot, mert bár örülnek, hogy már nem használnak, de továbbra is azt hiszik, hogy áldozatot hoznak. Minél mélyebben benne voltál a csapdában, annál csodálatosabb lesz ez a pillanat, és a megvilágosodás egy életen át tart. Igaz, hogy sok öröm van az életben, de lehetetlen megismételni az érzésüket. De annak az érzése, hogy többé nem kell pornót nézned, más, mert ha nincs jó kedved, és egy löketre van szükséged, csak emlékeztesd magad arra, hogy milyen jó érzés, az hogy nem vagy függő. A megvilágosodást sokan az életük egyik legjobb eseményének tartják. A megvilágosodás többnyire nem három hét, hanem pár nap után következik be.

Esetemben, az utolsó látogatás előtt történt. Bizonyára sok olvasó azt mondaná *“Egy szót se többet, most már mindent olyan tisztán látok, tudom hogy többé nem fog kelleni pornó”*, még mielőtt a könyv végére érne. A visszajelzések alapján ez gyakran megesik. Jó esetben, ha követed az összes utasítást, és teljesen megérted a mögöttes pszichológiát, ennek azonnal be kell következnie.

Az van itt írva, hogy körülbelül öt nap alatt múlnak el az észrevehető elvonási tünetek, és nagyjából három hét alatt tud teljesen a használó megszabadulni, az ilyen útmutatások két gondot tudnak okozni. Az első az, hogy ez sokak szerint az jelenti, hogy öt-huszonegy napig szenvedniük kell. A második pedig az, hogy a volt-használó hajlamos azt gondolni hogy “*Ha öt napig/három hétig túl tudok élni, akkor utána lesz egy nagy segítségem*”

De megeshet, hogy lesz öt kellemes napja, vagy három kellemes hete, amit pár borzalmas nap követ, olyanok, amik mindenkire hatással vannak, és történetesen nem kapcsolódnak a függőséghez, és más dolgok okozzák. Ekkor a volt-használó, aki a megvilágosodás pillanatára vár, búbánatos lesz, ami elveheti az önbizalmát. Egyúttal, ha nem volnának ilyen útmutások, a volt-használó az élete hátralévő részében várhatna a nagy semmire. Ez történik az akaraterő-módszerrel leszokók többségével. 

Az emberek gyakran kérdeznek az öt nap és a három hét jelentőségéről. Csak találomra kijelölt időszakok lennének? Nem, és bár tényleg nem pontosan meghatározott időtartamok, de az évek során összegyűjtött visszajelzéseken alapszanak. A leállás után nagyjából öt nappal van az, hogy a függőség megszűnik a volt-használó agyának a fő elfoglaltságának lenni. A legtöbb-volt használónak ilyen tájban van a megvilágosodása, többnyire stresszes vagy társasági helyzetekben, amiket korábban nem bírt volna, vagy nem találta volna élvezetesnek használat nélkül. Ekkor hirtelen rájön, hogy nemcsak hogy élvezi, vagy bírja, hanem hogy a pornóra nem is gondolt. Onnantól sima ügy. Ekkor tudod, hogy szabad vagy.

Mind én, mind sokan mások akik az akaraterő-módszerrel próbáltak leszokni, tapasztalták hogy a három hét az, amikor a legtöbb komoly próbálkozás elbukik. Ilyenkor többnyire az történik, hogy úgy érzed, hogy elvesztetted a pornó iránti étvágyad. Ezt bizonyítanod kell magadnak, tehát megnyitod a böngészőt, hogy látogatást tégy. Fura érzés, és ez azt bizonyítja, hogy legyőzted. De mindeközben bezsíroztad a DeltaFosB vízicsúszdát a friss dopamin adaggal, ami az elmúlt három hétben úgy sóvárgott a tested. Amint befejezted a műveletet, a dopamin elkezdi hagyni a tested. Ekkor a hang újra előjön: *“Nem győzted le, akarsz mégegyet.”*

Nem mész vissza azonnal, mert nem akarsz újra függő lenni, így hagyod hogy elteljen egy kis idő. Amikor újra megkísért a gondolata, azt tudod mondani magadnak: *“Nos, nem lettem újra függő, tehát nyugodtan mehetek még egy kört.”* Ekkor már csúszol lefelé. A probléma kulcsa nem az, hogy vársz a megvilágosodásra, hanem az hogy rájöjj, hogy amint bezárod a böngészőt, vége van. Megszüntetted a kicsi szörny oxigénellátását. Semmilyen erő nem tud megakadályozni abban, hogy szabad legyél, *kivéve, ha szomorkodsz miatta, vagy a megvilágosodás pillanatára vársz*. Menj, és élvezd az életet. A pillanat hamarosan el fog jönni.
