# Az utolsó látogatás

Miután döntöttél az időzítés felől, kész vagy utoljára meglátogatni a háremed. Mielőtt azonban megtennéd, győződj meg róla, hogy a két alapvető követelmény teljesül-e.

1.  Biztos vagy a sikerben?

2.  Búbánatos, vagy izgatott vagy, hogy valami csodálatosat fogsz véghezvinni?

Ha kételyeid vannak, olvasd újra a könyvet. Ne felejtsd, hogy soha nem döntöttél úgy, hogy beleesel a pornó-csapdába, hanem a csapda van úgy tervezve, hogy egy életre rabláncon tartson. Ahhoz hogy kiszabadulj, pozitív döntést kell hoznod arról, hogy le fogsz állni, és hogy sort kerítesz az utolsó látogatásra.

Emlékezz, kizárólag azért olvastad ezt a könyvet, mert minden vágyad a szabadulás. Döntsd el tehát most, esküdd meg ünnepélyesen hogy miután bezárod a privát böngészést, akár könnyűnek érzed, akár nehéznek, soha többet nem látogatod meg a háremet. Lehet hogy amiatt aggódsz, hogy már többször is megesküdtél, és mindig elbuktál, vagy amiatt, mert azt hiszed, valami szörnyű traumán kell keresztülmenned. Ne aggódj, a legrosszabb ami történhet, az az hogy elbuksz, tehát **nem veszíthetsz semmit**, de nagyon sokat nyerhetsz.

De ne is gondolj a bukásra, mert a gyönyörű igazság az, hogy nem csak hogy nevetségesen könnyű dolog leszokni, hanem kifejezetten élvezheted is. Ugyanis most a Járható Utat fogod járni! Nincs más dolgod, csak az hogy kövesd az alábbi instrukciókat.

1.  Tégy egy ünnepélyes esküt, és gondold is komolyan.

2.  Nézd a kedvenc oldaladon lévő képeket és videókat tudatosan, figyeld meg az elkeseredett próbálkozásokat az oldal adminisztrátorai, a színészek, és az amatőrök részéről, hogy növeljék a sokkot, újdonság-érzetet, és a szupernormálisságot a termékükben, és kérdezd meg magadtól, hogy mi ebben jó.

3.  Amikor bezárod a böngészőt, azt ne úgy tedd, hogy azt gondolod hogy “Soha többé nem látogathatom meg a háremem” vagy hogy *“Most már ez tilos”*, hanem azzal az érzéssel hogy végre szabad vagy, olyasmit gondolva hogy *“Nem csodálatos? Szabad vagyok! Már nem vagyok a pornó rabja! Soha többet nem kell meglátogatnom ezeket a mocskos oldalakat.”*

4.  Ne felejtsd, hogy a következő pár napban lesz még a fejedben egy kis szabotőr. Lehet, hogy csak azt veszed belőle észre, hogy használni akarsz. A kicsi pornó-szörnyre eddig a dopamin iránti enyhe fizikai kattogásként hivatkoztunk. Ez tulajdonképpen helytelen, és fontos megérteni, hogy miért. Mivel a kicsi szörny csak nagyjából három hét után hal meg, a volt-használók azt hiszik, hogy a kicsi szörny az utolsó használat után is sóvárogni fog, és ezért az idő alatt is akaraterőt kell gyakorolni, hogy ellen tudjanak állni a kísértésnek. Ez nincs így, nem a test sóvárog a pornó okozta dopamin-adagért, hanem az agy.

Ha a következő napok során mégis azon veszed magad észre, hogy akarsz vetni egy pillantást, az agyadnak kell hoznia egy egyszerű döntést. Vagy annak fogja fel az érzést, ami - egy üres, bizonytalan érzés, amit legelső látogatásod okozott, és az összes többi megerősített, és eközben azt mondod magadnak hogy ***“HURRÁ, VÉGRE NEM-HASZNÁLÓ VAGYOK!”***

Vagy sóvároghatsz is a pornó iránt, hogy aztán egész életedben szenvedj. Gondolj bele, nem lenne az hatalmas hülyeség? Azt mondani hogy *“Soha többé nem akarok pornót nézni”* és ezután egész hátralévő életedben azt gondolni hogy *“De szeretnék egy látogatást!”* Az akaraterő-módszert használók ezt csinálják, nem csoda, milyen rosszul érzik magukat. Életük hátralévő részében elkeseredetten siránkoznak valami olyasmi után, amit remélik soha nem kapnak meg.  Nem meglepő, hogy ilyen kevesen járnak sikerrel, és azon kevesek akik igen, soha nem érzik magukat teljesen szabadnak.

> *“Vésd az eszedbe ezt képet, mert igen hasznos lehet ahhoz, hogy legyűrd a külső zavaró stimulánsokat. Lásd magadat, ahogy csendben ülsz, és hagyod a telefont csöngeni, nem törődsz a hangjával, és nem reagálsz rá. Tisztában vagy a létezésével, azonban már se nem érdekel, se nem engedelmeskedsz neki. Azt is vésd az eszedbe, hogy magának a külső jelnek nincs feletted hatalma, nem tud kényszeríteni. Korábban engedelmeskedtél neki, reagáltál rá, csak szokásból. Ha szeretnél, elkezdhetsz egy új szokást, ami abból áll, hogy nem reagálsz.*
>
> "*Vedd azt is észre, hogy a nem-reagálás során nem csinálsz semmit, nem fejtesz ki semennyi erőfeszítést, nem állsz ellen, nem harcolsz, hanem egy egyszerűen nem csinálsz semmit - csökkented a valami csinálását- Nem teszel mást, csak relaxálsz, figyelmen kívül hagyod a jelet. A telefon csörgése egy szimbolikus analógia minden külső stimulánsra, aminek eddig hatalmat szoktál volt adni magad felett, és most ezt a szokást szándékosan megváltoztatnád.”*
>
> ---  — Maxwell Maltz, “The New Psycho Cybernetics”, 12-ik fejezet, a fordító saját fordítása

Egyedül a kételkedéstől és a várakozástól lesz nehéz leszokni, ***tehát sose kételkedj a döntésedben***, mert tudod, hogy az a helyes döntés. Ha kételkedni kezdesz, nyerhetetlen helyzetbe manőverezed magad. Ugyanis nyomorogni fogsz, mert akarsz tenni egy látogatást, de nem lehet. Akármilyen módszert is használsz, mit próbálsz elérni, amikor leszoksz a pornóról? Azt hogy sose nézd többet? Nem! Sok volt-használó ezt csinálja, de aztán egész hátralévő részében megvonva érzi magát.

Mi a különbség a használó és a nem-használó között? A nem-használónak se kedve, se szüksége sincs pornót nézni, nem sóvárog utána, és nem kell akaraterőt kifejtenie, ahhoz hogy ne nézzen. Te ezt próbálod elérni, és ez egy teljesen elérhető cél. Tehát nem kell arra várnod, hogy ne sóvárogj, vagy hogy nem-használó légy, ugyanis ez abban a pillanatban megtörténik, amikor végleg bezárod a böngészőt, így elvágva a dopamin-utánpótlást. ***TE MÁR EGY BOLDOG NEM-HASZNÁLÓ VAGY!***

Amennyiben

1.  Nem kételkedsz a döntésedben.

2.  Nem vársz arra, hogy nem-használó légy. Ha erre vársz, akkor a semmire fogsz várni, és egy fóbiát fogsz létrehozni. 

3.  Nem próbálsz meg *nem* gondolni a pornóra, vagy nem vársz a megvilágosodás pillanatára, mert ezzel úgyszintén egy fóbiát hozol létre. 

4.  Nem használsz helyettesítéseket. 

5.  Olyannak látod a használókat, amilyenek, és szánod, mintsem irigyelnéd őket.  

Boldog nem-használó fogsz maradni.

Akár rossz, akár jó napjaid vannak, ne változtasd meg csak azért az életed, mert leszoktál. Ha így teszel, akkor valódi áldozatot fogsz hozni, pedig nem kell. Emlékezz, nem a jó életet adtad fel. Nem adtál fel semmit. Épp ellenkezőleg, egy borzalmas kórból gyógyítottad meg magad, és kiszöktél egy alattomos csapdából. Ahogy telnek a napok, és az egészséged javulni kezd - mind testileg, mind lelkileg- , a jó napok jobbnak érződnek, és a rossz napok kevésbé rossznak, mint amikor használó voltál. Hogyha a pornóra találsz gondolni a következő napok során, gondold azt hogy:

***“VÉGRE! NEM VAGYOK HASZNÁLÓ!”***

## Egy utolsó figyelmeztetés

Ha lehetősége lenne rá, hogy visszamenjen az időben, azelőttre hogy ráfüggött volna, de a jelenlegi tudásával, egyetlen használó sem kezdené el. Több tízezren vannak azok, akik sikeresen kiszabadulnak, és utána teljesen boldog életet élnek, de aztán újra beleesnek a csapdába. Ez a könyv, abban bízok, igencsak megkönnyíti a leszokást. De légy résen, azok a használók, akik aránylag könnyen le tudnak szokni, ugyanolyan könnyen vissza is tudnak szokni. **Ne ess ennek áldozatául.** 

Mindegy, mennyi ideje leszoktál már, vagy hogy milyen biztos vagy abban hogy soha nem leszel újra függő, határozd el hogy soha, semmilyen ürüggyel nem nézel pornót. Állj ellen a médiában lévő célzásoknak, és ne felejtsd hogy a ‘nyíltság’ elképzelését úgy propagálják, hogy a pornót behozzák a mainstreambe, mit sem tudva arról, hogy a pornó, különösen az internetes, és a kényszeres önkielégítés a kapcsolatok, és a személyes jólét gyilkosai rengeteg férfi és néhány nő számára.

Emlékezz, az első pillantás vagy látogatás nem segít semmiben. Nem lesz akkor enyhítendő kattogás, és az egésztől borzalmasan fogod magad érezni. Egyedül azt fogja tenni, hogy ismét dopaminfüggővé teszi az agyad, és a kis hang újra rá fog kezdeni, hogy akarsz még egyet. Ekkor meg szembesülsz azzal a választással, hogy vagy egy darabig nyomorultul érzed magad, vagy újrakezded a mocskos láncreakciót.
