# Visszajelzés

Nem a használók ellen viselek háborút, hanem a pornóipar csapdája ellen, azon egyszerű oknál fogva, hogy élvezem. Minden egyes alkalommal, amikor arról hallok, hogy egy használó kiszabadult a csapdából, rendkívüli boldogság áraszt el. De ebben az örömben szokott lenni egy kis üröm is, amit a használók két kategóriája okoz. Az előző fejezetben lévő figyelmeztetés ellenére mindig meglep, hogy milyen sokan vannak azok, akik könnyen le tudnak szokni, de később újra rászoknak, és utána már nem járnak sikerrel. 

Olyan ez, mintha egy fuldokló embert találnál nyakig a mocsárban. Kihúzod a mocsárból, amiért hálás is, de fél év múlva újra beleugrik a mocsárba. Azon használók, akik könnyen leszoknak, majd újrakezdik, egy különleges problémát jelentenek, és miután kiszabadulsz, ***SZÉPEN KÉRLEK, NE KÖVESD EL UGYANAZT A HIBÁT.*** Sokan azt hiszik, hogy ezek az emberek azért kezdik újra, mert valójában még mindig függők, és hiányzik nekik a dopamin. Igazából azért, mert olyan könnyen leszoktak hogy már nem is félnek a pornótól. Azt gondolják ilyenkor, hogy *“Használhatok egyet, és ha újra rá is függök, könnyen le tudok majd szokni.”*

Attól tartok ez nem így működik, mert könnyű leszokni a pornóról, de a függőséget irányítani lehetetlen. A legalapvetőbb dolog a leszokáshoz, az hogy ne használd. 

A frusztráló használók másik kategóriája azok a használók, akik félnek megpróbálkozni a leszokással, vagy ha mégis megteszik, nagyon nehéznek találják. A legfőbb nehézségek a következők szoktak lenni.

**Félelem a bukástól.**

:   Elbukni nem szégyen, de meg sem próbálni hülyeség. Próbáld így gondolni rá, egyszerűen lehetetlen hogy veszíts, a legrosszabb ami történhet, hogy nem sikerül és akkor is ugyanott vagy mint most. Gondolj bele, milyen csodálatos lenne sikerrel járni. Ha meg se próbálod, garantáltan el fogsz bukni.

**Félelem a fájdalomtól és a nyomorúságtól.**

:    Emiatt ne aggódj, gondolj csak bele, milyen borzalom történhet veled, hogyha soha többé nem nézel pornót? Semmilyen. Azonban ha nézel, tényleg borzalmas dolgok fognak veled történni, olvasd csak újra mi van írva a Pascal-fogadásról. A pánikot egyébként is a dopamin okozza, és hamarosan meg is fog szűnni. A legjobb, amit nyerhetsz, az az ha megszabadulsz ettől a félelemtől. Tényleg azt hiszed, hogy a használók készen állnak arra, hogy gyenge merevedésük, megbízhatatlan teljesítményük legyen, vagy szeretik a képzelt örömöt, amit a pornótól kapnak? Ha azon veszed észre magad hogy pánikolsz, a mély lélegzetvétel segít. Ha társaságban vagy, és a társaságtól nem érzed magad jól, menj el onnan a garázsba, egy üres irodába, valahová.  

    Ha sírni van kedved, ne szégyelld. A sírás a természet adta mód a feszültség enyhítésére. Senki sem sírt még úgy, hogy utána ne érezte volna jobban magát. Az egyik borzalmas dolog amit a fiatal fiúkkal/férfiakkal teszünk, az hogy telebeszéljük a fejüket azzal hogy ne sírjanak. Sokukat látni, ahogy próbálják a könnyeket visszatartani.  Arra tanítjuk magunkat, hogy ne mutassunk ki érzelmeket, de nem erre vagyunk kitalálva. Ordíts, kiabálj, tombolj. Rúgj bele valamibe. Fogd fel úgy a nehézségeidet, mint egy bokszmeccset, amit nem tudsz elveszíteni. Az időt senki sem tudja megállítani, minden egyes másodperc alatt, ami eltelik, a kicsi szörny haldoklik. Élvezd az elkerülhetetlen győzelmedet.

**Az instrukciók be nem tartása.**

:   Meglepő, de néhány használó azt mondja, hogy a módszer nála nem működött. Ezután elmagyarázza, hogy nem csak egy instrukciót hagyott figyelmen kívül, hanem lényegében az összeset. A tisztánlátás végett az instrukciók fel vannak sorolva a fejezet végén.

**Az instrukciók félreértése**

:   A leggyakoribb problémák ezek szoktak lenni:

    "*Nem tudok nem gondolni a pornóra.*"

    :   Persze hogy nem, és ha megpróbálsz nem gondolni rá, azzal csak egy fóbiát hozol létre, így nyomorúságot zúdítasz magadra. Olyan ez, mint amikor az ember nem tud aludni - minél jobban próbálkozik, annál nehezebb lesz. Nem számít, hogy ha az életed kilencven százalékában a pornóra gondolsz, az a fontos hogy hogyan gondolsz rá. Ha azt gondolod, hogy “De szeretnék pornót nézni”, vagy hogy “Mikor leszek már szabad”, nyomorult leszel.  Ha ehelyett azt gondold, hogy “HURRÁ! szabad vagyok!”, boldog leszel. 

    "*Mikor fog a kicsi szörny meghalni?*"

    :   A dopamin-adag gyorsan elhagyja a tested, de azt lehetetlen megmondani, hogy a test mikor fog túlesni a dopamin-elvonás okozta kínon. Az az üres, bizonytalan érzés azonos a normális éhséggel, depresszióval, vagy stresszel. A pornó nem tesz mást, csak mindezt megnöveli. Az akaraterő-módszert használók ezért nem biztosak teljesen, hogy legyőzték-e, még azután sem, hogy a testük megszűnt szenvedni a dopamin-elvonástól. Ha a normális éhségtől, vagy stressztől szenved, az agya akkor is azt mondja, hogy ez egy megfelelő ok a használatra. A lényeg az, hogy nem kell várnod arra, hogy a sóvárgás eltűnjön, mert olyan enyhe, hogy észre sem lehet venni, és csak azt vesszük észre, hogy akarunk valamit. Amikor kisétálsz a fogorvostól, vársz arra, hogy az állkapcsod ne fájjon? Persze hogy nem, egyszerűen tovább haladsz. Igaz, hogy még fáj az állkapcsod, de azért még örülsz. 

        Ne várj arra, hogy elmúljon az elvonás érzése, mert kételyt hozol létre azzal, hogyha folyton azt kérdezed hogy “Meddig fog ez még tartani? Tényleg szabad vagyok, ha nem érzek különbséget?”. A valódi kattogás a félelem, tehát ha arra vársz, hogy jobb legyen a leszokás után az élet, azzal csak kételyt ébresztesz magadban. Az elvonás érzése felfoghatatlan, hacsaknem félsz tőle, és a neurológiai változások lassan mennek végbe, tehát ha arra vársz, hogy máshogy érezd magad, úgy fogod érezni, mintha semmi sem történne, és ezáltal kételyt teremtesz

    *"A ‘megvilágosodás pillanata’ nem jött még el."*

    :   Ha vársz rá, azzal csak egy újabb fóbiát teremtesz. Egyszer három hétre leálltam az akaraterő-módszerrel. Egy régi barátommal beszéltem, és ő megkérdezte, hogy bírom. *“Túléltem három hetet.”* válaszoltam. Ő visszakérdezett* “Hogy érted hogy túléltél három hetet?” *Mondtam neki, hogy *“Hát három hétig nem néztem pornót.”* Erre ő azt mondta: *“Mit fogsz most csinálni? Túléled az életed hátralévő részét? Mire vársz, megcsináltad. Nem-használó vagy.”* Azt gondoltam ekkor *“Teljesen igaza van, mégis mire várok?”* Sajnos akkor még nem értettem meg teljesen a csapdát, ezért hamarosan újra ott találtam magam, de ezt megjegyeztem. Akkor leszel nem-használó, amikor becsukod a böngészőt. Az a fontos, hogy az elejétől boldog nem-használó is légy. 

    "*Továbbra is sóvárgok a pornóért.*"

    :   Hát akkor nagyon hülye vagy. Hogyan tudod azt állítani, hogy nem-használó akarsz lenni, és közben azt mondani hogy pornót akarsz nézni? Ez egy önellentmondás. Ha azt mondod, hogy pornót akarsz nézni, akkor azt mondod, hogy használó akarsz lenni. A nem-használók nem akarják meglátogatni az undorító oldalakat. Te már tudod, mi is akarsz lenni, tehát ne büntesd tovább magad. 

    "*Úgy érzem, kiszálltam az életből*"

    :   Miért? Csak annyi a dolgod, hogy befejezed a magad gyilkolását, és elkezded felvillanyozni magad. A legkevésbé sem kell kiszálnod az életből. A következő pár napban lesz egy apró kis sérülés az életedben. Emiatt a tested a szinte felfoghatatlan zavarásoktól fog szenvedni, amit a dopamint követelő agy okoz. Ez ilyen egyszerű. De azt meg tartsd észben, hogy nem vagy rosszabb helyzetben, mint korábban. Egész életedben ettől szenvedtél, minden alkalommal amikor aludtál, amikor templomban, boltban, vagy könyvtárban voltál. Amikor még használó voltál, ez látszólag nem zavart, és ha nem szoksz le a pornóról, egész életedben ettől fogsz szenvedni. 

        A pornó és az orgazmus nem hozza össze a valódi szeretkezést, inkább megakadályozza. Még akkor is, amikor a tested még a dopamin után sóvárog, a vacsorák és a társasági helyzetek csodálatosak. Az élet csodálatos, menj társaságba, még akkor is, ha történetesen meztelen táncosok vannak ott. Emlékezz, hogy te semmitől sem vagy megvonva, de ők igen. Mindenki aki ott van, szeretne a helyedben lenni, ha tudnák. Élvezd, hogy te vagy a prima donna, és a figyelem középpontja. A pornóról való leszokás egy remek beszédtéma, és egy olyan öröm, amiben jó eséllyel csak neked van részed. A barátaid és a családod meg fog lepődni, hogy te, aki korábban szégyenlős és lepusztultképű voltál, most boldog és derűs vagy. Az életet élvezni fogod, és nem kell irigyelni a csajozóművészeket a buliban, ugyanis ők fognak téged irigyelni - ha tudnák.

    "*Nyomorú és nyűgös vagyok.*"

    :   Ez az instrukciók be nem tartására utal. Tudd meg, melyik az. Néhányan megértenek és elhisznek mindent, ami itt le van írva, de még így is csupa búbánattal indítanak, mintha valami borzalmas dolog történne. Te nem csak azt teszed éppen, amit te szeretnél, hanem azt amit a világ összes használója is szeretne tenni. Mindenféle, leszokásra irányuló módszerrel a használó egy bizonyos hozzáállást szeretne elérni, amiben minden pornóval kapcsolatos gondolat azzal ér véget, hogy *“ÉLJEN! SZABAD VAGYOK!”* Amennyiben ez a célod, minek vársz? Indíts ezzel a hozzáállással, és soha se veszítsd el, ennek nincs alternatívája. 

    "*Volt egy jó hetem/hónapom/fél évem, de újra a csapdába estem*"

    :    Emlékezz, a félelem maga a kattogás. Ha megadod magad a kattogásnak, azzal a félelem csak növekszik, és tovább eteted a kicsi szörnyet, ami meg azt hiteti el, hogy egy életre függő. vagy. Igazából az agymosás felfogása nem változott, de a dopamint adtál a gondolatfolyamba. Ez az előre-bukás klasszikus esete, de azért az instrukciók be nem tartása is. Keresd meg lent, hogy melyikről van szó, és örvendezz.

## A lista

Ha követed ezeket, nem bukhatsz el.

1.  Tégy egy ünnepélyes esküt, hogy soha, soha nem látogatod meg a háremed, **VAGY** békélsz meg képekkel **VAGY** erotikus grafikákkal, **VAGY** bármivel, ami szupernormális stimulánsokat tartalmaz, és tartsd is be az esküdet.

2.  Vésd az eszedbe: nincs mit feladni. Ezalatt nem azt kell érteni, hogy jobb dolgod lesz nem-PMO-zóként (de ezt mindvégig tudtad), és azt sem hogy annak ellenére hogy nincs semmilyen oka a PMO-zásnak, azért van benne némi örömöd, és szolgálhat támaszként is, mert máskülönben nem csinálnád. Hanem azt kell érteni ezalatt, hogy **nincs semmilyen öröm, és semmilyen támasz a PMO-ban.** Hogy lenne, az csak egy illúzió, mert olyan az egész, mintha a fejedet vernéd a falba, hogy aztán jó érzés legyen abbahagyni. 

3.  Nincs olyan, hogy megrögzött PMO-s. Te is csak egy vagy a több száz millióból, aki beleesett ebbe a cseles csapdába. Hasonlóan a több millió ex-PMO-zóhoz, akik azt hitték, hogy nem tudnak kiszabadulni, te is kiszabadultál.

4.  Ha bármikor összevetnéd a PMO előnyeit és hátrányait, mindig arra a következtetésre jutnál hogy *“Hagyd abba! Bolond vagy!”*, és ez sosem fog megváltozni. Mindig is így volt, és így is lesz. Miután meghoztad a döntést, amiről tudod hogy a helyes döntés, ne kínozd magad kételkedéssel. A Pascal-fogadás tökéletesen alkalmazható a PMO-ra, ugyanis nem lehet veszteni, és nagy eséllyel lehet nyerni.

5.  Ne próbálj meg nem gondolni a pornóra,és ne aggódj ha folyton arra gondolsz. Bármikor, ha rágondolsz, legyen az ma, holnap, vagy akármikor, gondold azt hogy ***“VÉGRE SZABAD VAGYOK A PMO-TÓL!”***

6.  **Ne** használj semmiféle helyettesítőt. **Ne** állítsd magad kihívás elé azzal, hogy éjszakára magad mellett tartod a laptopot. **Ne** kerüld el a színházba, moziba járást, és az újságolvasást. **Ne** változtasd meg az életedet, csak azért mert leszoktál. Ha a fentieket követed, hamarosan megtapasztalod a ‘megvilágosodás pillanatát’, de

7.  Ne is várj a ‘megvilágosodás pillanatára’. Folytasd az életed, élvezd a jó napokat, és bírd ki a rosszakat. A pillanat így gyorsan el fog jönni.
