# Segíts a süllyedő hajón maradtakon 

A használók manapság pánikolnak, mert érzik hogy az internetes pornóhoz egyre többen máshogy állnak hozzá. Az addiktív voltát egyre többször tanulmányozzák, és ma már helyesen eltérőnek gondolják a hagyományos pornográfiától. Az hogy azonnal és korlátlanul hozzáférhető, még a támogatói fejében is megkongatja a vészharangot. Azt is érzik, hogy a szólásszabadságért vívott keresztes hadjáratukat bizonyos elemek eltérítik. Az internet  ellenőrizetlen vadnyugatján közel lehetetlen betartatni a korhatár-korlátozásokat. Ennek sajnos egyhamar nem lesz vége, de rengeteg használó szokik le, és a legtöbb függő tisztában van a pornó és a drogfüggőség közötti hasonlóságokkal. Mindig amikor egy használó elhagyja a süllyedő hajót, a hátramaradottak annál jobban nyomorognak.

Minden használó tudja ösztönösen, hogy nevetséges dolog önmagát szabotálnia azzal, hogy a képernyőn néz kétdimenziós pixeleket, hogy ezzel megbolondítja az agyát, és olyan idegpályákat hoz létre, amik garantálják a gyenge szexuális teljesítményt. Ha továbbra se gondolod, hogy ez hülyeség lenne, próbálj egy pornómagazinhoz beszélni a város közepén, és kérdezd meg, mi a különbség. Egy dolog. Így nem részesülhetsz az intimitás örömében. Ha le tudsz állni azzal hogy bevásárlás során alkoholt vegyél, a hárem látogatásával is le tudsz állni. A használóknak nincs ésszerű okuk a pornónézésre, de ha mások is csinálják, nem érzik magukat olyan hülyén.

A használók össze-vissza hazudoznak a szokásukról, nem csak a kutatóknak és a saját környezetőknek, hanem *saját maguknak* is. Muszáj nekik, mert az agymosásra szükség van ha meg akarják tartani az önbecsülésüket.  Szükségét érzik, hogy igazolják a ‘szokásukat’, nem csak önmaguknak, hanem a nem-használóknak is. A pornó képzelt előnyeit kifinomult módszerekkel folyton reklámozzák.

Ha egy használó leáll az akaraterő-módszer segítségével, továbbra is megfosztva érzi magát, és ilyenkor hajlamos sokat sopánkodni. Ezzel csak megerősíti a többi használónak, hogy milyen jól teszik, hogy tovább használják. Ha a volt-használó sikerrel legyőzi a ‘szokást’, hálás hogy már nem kell magát szabotálnia, vagy pazarolnia az energiáját, és neki már nincs is szüksége arra, hogy igazolja önmagát. Ne felejtsd, a félelem az, ami miatt a használó fejét a homokban tartja, és ami miatt megkérdőjelezi a leszokást. Segíts a használónak azzal, hogy közreműködsz ezeknek a félelmeknek az eltávolításában. Mondd meg neki, hogy milyen csodálatos dolog az, ha az embernek nem egy börtönben kell élnie az életét, hogyha az ember ahelyett hogy gyengén és öngyűlölően kel fel, fitt és egészséges, hogyha szabad, és hogyha élvezni tudja az életét a sötét árnyékok nélkül. Vagy ami még jobb, vedd rá hogy olvassa el ezt a könyvet. 

Fontos, hogy ne szóljuk le a házas használót azzal, hogy *“direkt elrontja a házasságát”*, vagy hogy megcsalásnak vagy tisztátalannak nevezzük a szokását. Gyakori tévhit, hogy a volt-használó a legrosszabb ilyen tekintetben. Ennek van némi alapja, de ez leginkább az akaraterő-módszer miatt alakult ki. Ugyanis a volt-használó agya -- annak ellenére, hogy már legyőzte a ‘szokást’ -- egy kicsit még mindig át van mosva, és még mindig azt hoszi, hogy áldozatot hoz. Emiatt sebezhetőnek érzi magát, és a természetes védelmi mechanizmus az, hogy megtámadja a pornó-használót. 

Ez maximum a volt-használó egóján segít, de a használón biztos nem. A használó ettől csupán sarokba szorítva fogja magát érezni, és emiatt rosszul, továbbá ebből kifolyólag csak jobban fog akarni pornót nézni.  Igaz, hogy az orvosi közösség hozzáállása a fő ok, ami miatt sok használó leszokik, de ettől nem lesz könnyebb. Sőtmitöbb, ettől még nehezebb lesz. Manapság a legtöbb használó azt hiszi, hogy elsődlegesen az egészsége miatt akar leszokni. Ez nincs feltétlenül így. 

Bár a súlyos egészségügyi kockázatok mindenképpen nyomós okot jelentenek, de sok használó már sok ideje szabotálja a saját virilitását, és semmit sem javított azóta a helyzeten. A legtöbb használó igazából azért szokik le, mert a társadalom kezdi a pornót annak látni, ami: drogfüggőségnek. A társadalom hozzáállása változóban van -- sok ember társa már kérdezősködni kezdene, ha emberünk éjszaka is a laptopját bújja.

A pornó teljes betiltása bizonyos országokban, vagy az internet el nem érhetősége az utazó használó dilemmájának klasszikus példái. Többnyire úgy állnak hozzá, hogy ez majd segít csökkenteni a használatukat. De az eredmény az lesz, hogy az egy-két nap helyett - amit nem élvezett volna -- egy hétig tartózkodik. Ez idő alatt azonban, nemcsak hogy mentálisan lesz megvonási érzése a ‘jutalmára’ várva, hanem a teste is sóvárogni fog. Ó, milyen értékes lesz az a látogatás, amikor végre majd lehet.

A kikényszerített tartózkodás nem segít csökkenteni a használatot, mert a használó csak még többet fog használni, amikor végre egyedül lehet. Csupán abban segít, hogy a használó még értékesebbnek gondolja a pornót, és magát még függőbbnek. Ennek a kikényszerített tartózkodásnak a legalattomosabb része a serdülőkre gyakorolt hatása. Megendgedjük a ‘szólásszabadság’ eltérítőinek, a pornóproducereknek, hogy kamaszokat célozzanak meg, hogy aztán ők is függők legyenek. És aztán az életük legstresszesebb részében, amikor a félrevezetett agyuk azt hiszi hogy a leginkább kell nekik a pornó, arra kényszerítjük őket, hogy szokjanak le, mert ártanak maguknak.

Sokan képtelenek erre, és kényszerítve vannak, és önhibájukon kívül súlyos bűntudatuk lesz életük hátralévő részében. Sokan sikerrel járnak, örvendeznek ennek, és azt gondolják */“Rendben. Egyenlőre csinálom ezt, és miután vége, már amúgy is meg leszek gyógyulva.\”* Ekkor jön az álláskeresés és az egyéb felnőtt gondok miatti nyomás, amit az életük legnagyobb ‘csúcsa’ követ -- felvétel a munkahelyre. A nyomásnak most vége, biztonságban érzik magukat, és a régi mechanizmus újra működésbe lép. Az agymosás egy része megmaradt, és még mielőtt eltűnne az új laptop illata a céges laptopról, a használó már a hárem küszöbén van. Az alkalommal járó öröm kizárja a rossz érzést, és persze a hanszálónak nem áll szándékában újra ráfüggeni, de egy pillantás csak nem árthat\… Túl késő! Ismét beleesett a csapdába. 

A kicsi szörny újrakezdi a sóvárgást, és hogyha még nem is lesz egyből függő, a későbbi bánata valószínűleg becsalja a csapdába. Furcsa dolog, hogy bár a heroinfüggők jogilag bűnözőnek számítanak, de a társadalom segíteni akar rajtuk. Vegyük át ezt a hozzáállást szegény pornófüggőkkel kapcsolatban is. Nem azért csinálják, mert azt akarják, hanem mert azt hiszik, muszáj. Nekik ráadásul sok évnyi mentális és fizikai szenvedést is ki kell állniuk, nem úgy mint a heroinistáknak. Gyakran mondjuk, hogy a gyors halál jobb, mint a lassú, tehát ne irigyeld szegény használót. ***Megérdemli a szánalmadat.*** 
