# Tanácsok a nem-használóknak

## Vedd rá a használó barátaid, hogy olvassák el ezt a könyvet

Először is, tanulmányozd a könyv tartalmát, és képzeld magad a használó helyébe. Ne erőltesd, hogy olvassák el, azzal hogy azt mondod, hogy tönkreteszik az egészségüket, vagy a tűzzel játszanak. Ezt nálad is jobban tudják. A használók nem azért néznek továbbra is pornót, mert élvezik vagy mert szeretnék, ezt csak maguknak és másoknak mesélik be, hogy megtartsák az önbecsülésüket. Igazából azért csinálják, mert azt hiszik, hogy ellazítja, bátrabbá, magabiztosabbá teszi őket, és mert azt hiszik, hogy az élet nem lesz élvezetes ‘szex” nélkül - vagyis az ő verziójuk nélkül. Ha arra kényszerítesz egy használót, hogy szokjon le, úgy fogja érezni magát, mint egy csapdába csalt állat, és még inkább meg szeretné a háremét látogatni. Emiatt lehet hogy titkos használó lesz, és a pornó még értékesebb lesz a szemében.

Ehelyett próbáld meg ezt máshogy megközelíteni. Vidd a használót volt-használók társaságába (blogok, fórumok, Your Brain On Porn, Nofap, stb). Ők el fogják mondani, hogy azt hitték, hogy egy életre függők maradnak, és hogy mennyivel jobb az élet nem-használóként. Amint elkezdi elhinni, hogy lehetséges leszokni, az elméje fel fog nyílni. Ekkor magyarázd el a kattogás által létrehozott tévelygést. A dopamin adagok nemcsak hogy nem segítenek, hanem tönkreteszik a magabiztosságát, nyűgössé, és fáradttá teszik. 

Eddigre alanyunk már készen áll, hogy elolvassa a könyvet, de valószínűleg a megbízhatatlan felizgulásról, gyenge merevedésről, korai ejakulációról, és miegymásról szóló sok-sok oldalnyi történetre számít. Magyarázd el, hogy a könyv teljesen máshogy viszonyul a problémához, és a betegségekre utalások a könyvnek csupán töredékét teszik ki. 

Rövidre fogva, ne hagyd hogy a könyv árnyékban maradjon. Mondd el a barátaidnak, de ne csináld nagyon furcsán. Ha megpróbálod ‘megnyerni’ a beszélgetést, vagy vitát csinálsz ebből, azzal csak elidegeníted őket, és tovább növeled a félelmüket. 

## Elmondjam a társamnak?

Elmondjam-e a feleségemnek, barátnőmnek, páromnak a szokásomat? Ezt ugye többnyire azért kérdik, hogy segítsen a leszokásban. Ez ügyben több tényező is szerepet játszik. 

Ha az akaraterő-módszerrel eddig nem jártál sikerrel, és már elmondtad, akkor erről az új megközelítésről is mesélj, és segítsd a társadnak, hogy kíművelje magát ez ügyben azzal, hogy elolvassa a könyvet. A társad segítségedre lehet, és motiválhat az elvonási időszak alatt, és segíthet, amikor a kicsi szörny el akar gáncsolni.

Ha csupán nemrégiben fedezted fel a pornó képezte csapdát, és korábban még nem próbálkoztál a leszokással, először csak egyedül használd a Járható Utat. Ahogy ez ki lett fejtve, ennek egy élvezetes dolognak kéne lennie. De, ha nehéznek érzed, kérj segítséget. Legyél nyílt és sebezhető a társaddal, és ez meg fogja erősíteni a kapcsolatotokat. 

Feltéve, hogy élvezed a szabadulást, és nem nehezíted meg a dolgodat a döntésképtelenséggel, nincs sok ok arra, hogy elmondd a társadnak. Ha korábban sem volt a függőség probléma, hagyd csak magad mögött. Azonban, arra legyél felkészülve, hogy a társad meg fog lepődni, hogy miért javult ennyit a kinézeted, a kedved, és a teljesítményed!

## A társam szokik le a pornóról

A pornográfia a kapcsolatok perverz pusztítója, és bár a leszokás azonnal is végbevihető, a gyógyulás időt vesz igénybe. Sok használó a függőségéből eredő ésszerűtlen tévhitek miatt a társán és a szerettein vezeti le a dühét. Ezen viselkedés hazudozásban és manipulatív viselkedésben manifesztálódik. Ezt nem csak a használók csinálják, de a betegség későbbi fázisaiban egyre gyakoribb. Bár ezek a viselkedési formák a pornófüggőségből eredeztethetőek, fontos tudni róluk, és ha felismered őket, érdemes felkeresnie egy szexuális jellegű függőségekkel foglalkozó szakembert.

Ha a társad az elvonási időszakban van, számolj azzal hogy szenved, akár így van, akár nincs. Ne próbáld meg minimalizálni a gondját, azzal hogy azt mondod neki hogy könnyű leállni, mert ezt saját maga is meg tudja csinálni. Mondd neki inkább azt, hogy milyen büszke vagy,  hogy ő mennyivel jobban néz ki, mennyivel jobb most vele lenni, és általában is mennyivel nyugodtabb. Ezt rendszeresen mondani különösen fontos, mert amikor a használó megkísérel leszokni, a próbálkozás eufóriája és a társai dicsérete hatalmas segítség. Azonban, a használók hajlamosak hamar felejteni, tehát dícsérd meg rendszeresen.

Mivel alanyunk ilyenkor nem beszél a pornóról, ezért azt is hihetnéd, hogy elfelejtette, és hogy nem akarja hogy emlékeztesd rá. Ennek többnyire az ellentéte áll fenn az akaraterő-módszernél, ugyanis a volt-használónak ez esetben csak a pornó körül forog az agya. Tehát hozdd fel a témát nyugodtan, és magasztald a társad, mert ha nem akar hallani a témáról, azt el fogja mondani.  

Ne sajnáld az erőfeszítést, hogy enyhíts a gondjain az elvonás időszak alatt, gondolj bele, hogy hogyan tehetnéd az életét érdekesebbé és élvezetesebbé. Ez az időszak az olyan nem használóknak is megpróbáltató lehet, akik sosem voltak függők. A rosszkedv ragályos, tehát ha a csoport egyik tagja nyűgös, akkor a környezetének sem lesz jó kedve. Számíts erre, mert ha a volt-használó nyűgös, lehet hogy rajtad fogja levezetni, de nem vágj vissza, mert ebben az időben kell neki legjobban a dicséreted és a szimpátiád. Ha meg te vagy nyűgös, ami érthető, próbáld meg nem kimutatni.

Az akaraterő-módszerrel próbálkozó használó egyik trükkje az az, hogy hisztizni kezd, azt remélve, hogy a társa vagy a barátai azt mondják hogy *“Nem bírom nézni, ahogy így szenvedsz. Az ég szerelmére, vedd már be azt a mérget.”*  A volt-használó így megússza arcvesztés nélkül, nem ‘feladja’, hanem erre kérték. Ha a volt-használó ezt a cselt alkalmazza, semmiképpen se buzdítsd a visszaesésre. Mondd inkább azt hogy *“Ha ezt teszi veled a pornó, hála az égnek hogy hamarosan szabad leszel. Milyen csodálatos, hogy volt elég bátorságod feladni.”*

Ne felejtsd, a felépülés során két fél is gyógyul. Amikor a társad leszokik a pornóról, fontos hogy legyen egy saját ‘hátországod’, öngondoskodó rutinjaid, és határaid. Ez a folyamat nem egyik napról a másikra megy végbe, bizalmat, kommunikációt, és felelősséget kíván meg. A naplóvezetés, a saját szenvedélyeid kialakítása, és leginkább a terápia, sokat tud segíteni. 

## Megcsúszás (visszaesés)

Ezen alfejezet létezése szolgáljon figyelmeztetésül a szabadulóknak. Én személy szerint sosem estem vissza, ezért itt a közösség meginterjúvolt tagjainak a tapasztalataira, és a kognitív viselkedésterápia eszköztárára fogok hagyatkozni a szemléltetés során. 

Először is, visszaesésnek nevezni kontraproduktív. Csupán annyi történt, hogy megcsúsztál, és megetetted a kicsi szörnyet, ami így elindítja a nagy szörnyet, az agymosást. A használók, akik megcsúsznak (ami az előre bukás klasszikus esete), többnyire egy egész sor féle tévhitben élnek:

  - "*Sosem leszek szabad*" - **Kétségbeesés**
  - "*Minden egyes nap edzenem, tanulnom, kell, és tevékeny kell hogy legyek*" **túlgondolás**
  - "*Ma PMO-ztam, minek is olvasom a könyveket és a fórumokat… Az volt a célom hogy ne maszturbáljak, de mégis visszaestem.”*" - **Gyenge csalódottságtűrés**
  - "*A barátaim / a fórumozók / a többiek nem PMO-znak x napig, de én erre nem vagyok képes, tehát veszett ügy vagyok. Tegnap jól éreztem magam, mert tanultam rendesen, és tevékeny is voltam, de ma nem… Csúszok lefelé.*" **Önmagad másokhoz mérése**
  -*"Nem szabadna szexuális gondolataimnak lennie"* - A használó, a szülei, vagy a társadalom **rugalmatlan dolgokat** hitettett el magával, a szexualitással kapcsolatban. Vizsgáld meg, hogy az önostorozás segít-e, és ha igen, élvezed-e?

Minden egyes használó agymosását látszólag végtelen féle tényező segítheti elő. Magadat mindenki másnál jobban ismered, és tudod, hogy a megcsúszást az instrukciók végre nem hajtása idézi elő. Értéket láttál a pornográfiában, de hogyan?

Amiről gyakran elfeledkezünk, az az hogy az agymosás visszafordítása időbe telik. Ettől nem lesz nehezebb véghezvinni, de majdnem minden iparág szex segítségével hirdet, és az ellen-agymosás egy tudatos folyamat (legalábbis az elején), tehát egy kis időbe telhet, amíg az itt olvasottak teljesen megszilárdulnak. Ezért érdemes többször is elolvasni a könyvet előre ugorhatsz azokhoz a fejezetekhez, amikkel küszködsz), és így nem szabadna túl sokáig tartania.

A csapdát elhagyó vallásos használók meglepően gyakori tapasztalata, az az hogy azt szeretnék, hogy fájjon egy kicsit, afféle vezeklésképpen. Könnyen le tudnak szokni, és aztán bűntudatuk van ezért. De minek szabotálni magunkat, és megnehezíteni a leszokást? A kicsi szörny ebben a tekintetben nagyon trükkös. 

Válaszd magadat el a kicsi szörnytől, mert azt a pornóipar helyezte oda még jó régen. Képzeld el, hogy van egy zaklató, aki belédköt az iskola udvarán. Mit mondasz neki? Hogyha teljesíted a követeléseit, attól csak még nagyobb lesz az arca. Néhány leszokó beadja neki a derekát, és ezáltal növeli az agymosás mértékét, de a csapdáról való felfogásuk nem változott. Tehát szedd csak magad össze, találd meg mi ment félre, és élvezd a szabadságot!

Nem vagy azonos az ingerrel. A tudatos jelenlét meditáció a gondolatok észrevételének a gyakorlata, és az elméről így sok fontos dolgot meg lehet tudni. Meditálni általánosságban véve is igen ajánlatos, és teljesen össze is egyeztethető bármilyen vallással. Magaddal vagy a kicsi szörnnyel nem tudsz harcolni. Feltétel nélkül szeretned kell magadat, és a folyamatot.

De ne is gondolj a bukásra. Álljon itt egy részlet a *“Meditations of a Porn Addict”*  c. könyvből Gulliaco tollából (megtalálható a könyv végén, a további olvasmányok fejezetben)


> Mivel a pornónézésnek nincs semmi előnye, csak fájdalmat okoz, és teljesen nevetséges dolog ilyesmit akarni, a fehérítőiváshoz fogom hasonlítani. Tessék: 
>
> **A fehérítő nem ivásának nehéz utazása**
>
> Helló! Mi vagyunk NoFehérítő, és újraindítási kihívásoknak adunk helyet, ahol a résztvevők (“Fehérítőnauták”) egy ideig tartózkodnak a fehérítőivástól. Akár csak az önuralom tesztjeként, alkalmilag szeretnél részt venni a havi kihívásban, akár probléma lett az életedben a túlzott fehérítőivás, és hosszabb időre abba szeretnéd hagyni, itt egy támogató közösségre, és sok kapcsolódó anyagra találsz.
>
> - “*Néha megengedek magamnak egy-két pohár fehérítőt. Tudom hogy a ‘csak egy csepp’ egy hazugság, de egy pohár nem árthat. Egy pohártól csak nem fog az összes idő kárba veszni, amíg nem ittam fehérítőt."*
> - “*Le tudok állni a fehérítő ivásával, de néha látok embereket az utcán palackból vizet inni, és azt elképzelem hogy a palackban fehérítő van. Ekkor sóvárogni kezdek, és miután magammal vitatkozok sokáig, hogy igyak-e vagy sem, este beadom a derekam, és iszok egy pohárnyit."*
> - “*Nézd, a bajom az hogy néha, amikor egyedül vagyok a konyhában, elkezdem nézegetni a poharakat, és elfog a kísértés hogy kinyissam a dobozt, ahol a fehérítőt tárolom, néha meg is szagolom, és… hát ugyanott vagyok, mint ahonnan elindultam. Ezt elkeseredetten abba akarom hagyni, de nem tudom, képes leszek-e rá*”
> - “*A fehérítőivást abbahagyni lehetetlen, mert hát, mindig van szám, érted? Hogyan tudnám abbahagyni, hogyha mindig van egy torkom, ami emlékeztet arra, hogy tudok fehérítőt inni?*”
> - “*Pedig olyan jól ment, 19 napig nem ittam fehérítőt. Az a fontos hogy tanuljak a kudarcból! Most már tudom is, mit kell elkerülni: a tisztítószerek nézegetését a boltban. Most megcélzok egy hónapot! Vissza is állítom a számlálót. Kívánjatok sok szerencsét!*”
> Ha ingered van, nyugi! Emlékezz, mit mond a hackkönyv:
>
> “*A fehérítőt nehéz feladni, mert attól félünk, megfosztjuk magunkat az örömünktől vagy a támaszunktól. Attól félünk, hogy bizonyos helyzetek soha nem lesznek utána ugyanolyanok. Félünk, hogy nem fogjuk tudni kezelni a stresszes helyzeteket. Máshogy fogalmazva, ezek az agymosás hatásai, amik azt hitetik el velünk, hogy a fehérítő vásárlása, és továbbgondolva a megivása kötelező mindenkinek. Sőt, még azt is, hogy a fehérítőben van valami benne rejlő dolog ami kell nekünk, és hogy amikor leállunk a használattal, ezt megtagadjuk magunktól, és egy űrt képzünk. Vésd szilárdan az eszedbe: a fehérítő nem betölti, hanem létrehozza az űrt!*”
> 
> Én pedig azt mondom:
> *“Tegyük fel, hogy nézned kell öt percig egy fehérítővel teli poharat. Próbálj meg emlékezni azokra a márkára és illatokra, amiket annyira szerettél. Az emlékbe lehet, hogy belefűződik  némi hang, vagy lehet hogy csak bizonyos részletekre emlékszel. A fehérítő ott van, és nem tudod becsukni a szemed, vagy elfordítani a fejed, mert a fehérítő az agyadban van, egy emlékként.*

> *Érzel sóvárgást? Érzel bármit is a nyelveden, vagy változást a légzésedben? Mit érzel azzal az emlékeddel kapcsolatban? Azonosítsd ezeket, a fehérítő össze akarja ezeket kavarni, meg akar téveszteni, hogy aztán elkapjon.”*
>
> A föntiekkel nem az érzéseidet akarom kicsúfolni, és még kevésbé szeretném azt mondani hogy *“hahaha, én milyen okos vagyok, te meg milyen hülye!”*, hanem perspektívába szeretném helyezni, hogy milyen nevetségesen könnyű (és milyen könnyű is lesz) legyőzni ez a függőséget. A pornónézés nem olyan, mint egy ki-be kapcsoló, hogy azt mondd hogy *“Hát, most x helyzet van, tehát nézek egy kis pornót”*.  Képzelgések! Hazugságok! Milyen gyakran engedsz meg magadnak egy pohár fehérítőt? Soha? Miért? Mert egy borzalmas dolog, azért! Hogyan szokhatnál le, ha nem jössz rá, hogy a PMO egy borzalmas dolog?

## Mi van az MO-val (maszturbálás, orgazmus)

Az emberek az idők kezdete óta zsebhokiznak különösebb probléma nélkül. A baj a pornóval van. 

De, még így is ráfügghetsz az MO-ra ugyanazért, amiért a pornóra szoktak, például a ‘muszáj hogy orgazmusom legyen’ mentalitás, a mentális eszkaláció, a test szexre kényszerítése, és az egyszerű hedonista élvezethajhászás. 

Igen valószínű, hogy a pornó és az önkielégítés összefonódott az elmédben. Sok használó szerint a pornó okozta fantáziákra való önkielégítés vezetett a visszaesésükhöz. Ahogy az agyad áthuzalozódik, észre fogd venni, hogy ez az agymosás idővel eltűnik, de érdemes egy darabig szüneteltetni az MO-t. Ezidőtájt a valódi szexet is érdemes keresni, hogy meggyorsítsa a folyamatot. 

Ez nem egy instrukció, de azért gondolj bele. Az ondó-visszatartásnak a beszámolók szerint sok előnye van - jobb fókuszálás, több energia, az ‘agyköd’ megszűnése, és nagyobb magabiztosság, és még sok más. A tapasztalataim alapján van azért különbség, ami azon múlik hogy hogyan alakítod át a több energiádat. 

Ez csak spekuláció ami nélkülözi a pontos tudományos tudást, de az előnyök több tényezőn múlhatnak.

- Orgazmus után az agy prolaktint szabadít fel, ami lelassítja a dopamin felaszabadítását. 

- A nagy dopamin adagok hiánya lehetővé teszi hogy felvedd a mindennapi tevékenységekből jövő dopamint.

- A véráram nagyjából 78 nap után újra leköti az ondót, ami az egyik legjobb tápanyag a testnek. 

- A szexuális energia produktív szokásokba való átalakítása csak tovább növeli a produktivitást. 

Szexelhetsz is akár orgazmus nélkül, ami, mint ahogy az korábban lett említve, egy csodálatos élmény. Az erre való képességedet fejlesztheted az úgynevezett Kegel-gyakorlatokkal. A saját tapasztalataim alapján, a legkönnyebb és a leghatékonyabb módja a megfelelő izmok edzésének az, hogyha megállítod a vizeletet vizelés közben. A tantrikus és a szaporodási célú szex elválasztása a PMO csapdából való szökéssel járó egyik bónusz ( amit a partnereim is imádtak!).

## Eltérések a standard tanácstól

Ez az alfejezet új, és kicsit aggódva írom le; ennek ellenére is szót érdemel. 

Néhány Járható Utat járónak annyira nem lesz kedve pornót nézni, hogy nem is tudja rávenni magát az utolsó használatra. **Ez rendben is van**, de ne becsüld alá az utolsó használat erejét. A tudatos böngészés, hogy tudatosítsd, mennyire nem szereted a PMO-t, egy igen erős eszköz. Személy szerint igen hasznosnak találtam, és utána örömmel mostam ettől a szokástól  tisztára a kezeim. Meg voltam könnyebülve, hogy soha többé nem kell csinálnom. Mindazonáltal, nem mindenkinek feltétlenül hasznos.

Ha egy ideje már szabad vagy, és most csak agymosás-ellenes hadjáratot folytatsz, nem kell megetetni a kicsi szörnyet, mert csak zavarna. Helyette élvezd a szabadságot!

## Segíts véget vetni ennek a botránynak!

Az internetes pornó a szabad társadalmakra leselkedő nagy veszélyek egyike, ami az egyéni szabadságra való törekvéseket használja ki. A civilizáció alapja, az ok amiért az emberiség eddig fejlődött, az az hogy képesek vagyunk kommunikálni a veszélyeket és a tapasztalatokat, nem csak egymásnak, hanem a következő generációknak is. Még az állatok is szükségét érzik, hogy figyelmeztessék az utódaikat az élet buktatóira.

A pornóproducerek ezt nem jóindulatból teszik, őszintén abban a hitben hogy segítik az emberiséget, főleg most hogy a pornófüggőséget széles körben tanulmányozzák. Lehetséges hogy régen az emberek tényleg azt hitték, hogy a pornó tanítani tud az intimitásról, de a hozzáértők tudják hogy ez nem így van. Egyetlen pornóoldal sem mond semmit az oktató jellegről. Az egyetlen dolog amiről mondanak bármit is, az a sokk, az újdonság, és a tartalmaik eszkalálódó természete.

Az álszentség mértéke is hihetetlen, a társadalom mindig felkapja a vizet, ha az iskolai zaklatásról vagy  az emberi test tárgyiasításáról  van szó. De ezek a problémák teljesen bagatellek az internetes pornóhoz képest. A függők száma  minden évben rekordokat dönt, milliók pazarolják az idejüket, az egészségüket, a virilitásukat, azzal hogy pixelekre butított mű vagy igazi embereket bámulnak. A kapcsolatok legnagyobb gyilkosa ez, és minden évben több százezer ember élete megy tönkre a függősége miatt. A producerek nem hirdetnek a mainstream kiadványokban - nincs rá szükségük, a biológiai szükségletünk vezet oda a háremük küszöbére, ahol ingyenes termékmintát adnak, mint valami drogdíler. Mostanában nem is pakolják annyira tele a polcokat, mert már a használót bátorítják arra hogy tartalmat tegyen közzé.

Milyen elmés, hogy a pornóoldalak 18+-os jelzésekkel próbálják eltántorítani a kiskorú használókat, de ráadásul nem is mindegyik. Az internetes pornó mindenkire hatással van. De  ők úgy állnak hozzá, hogy *"Mi szóltunk, ez már a te döntésed."* Tesznek bármit is azért, hogy a igazolják a felhasználók a korukat? Dehogyis, azzal elriasztanák a használókat. Meg ha esetleg valahol be is vezetik a kötelező életkor-megerősítést, akkor keresnek egy másik országot, ahonnan működhetnek. Vagy esetleg fizetnek valami 'neves' újságírónak, hogy írjon arról, hogy az amerikai szesztilalom hogyan vezetett az alkoholcsempészethez és a maffia létrejöttéhez. Amiről gyakran elfeledkeznek, az az hogy a szesztilalom vége után miért nem csökkent az alkoholhoz köthető halálesetek száma, vagy hogy a maffia megerősödéséhez milyen sok köze volt a rendőrség hatékonytalanságának.

A problémát máshogy is meg lehet oldani, úgy hogy oktatjuk a fiatal generációt. Ha ki tudják kerülni vásárlás közben az alkoholt, akkor ugyanezt meg tudják tenni az internetes pornóval. A társadalmi változás jelei már észlelhetőek, például hogy a 'no nut november' és a 'coomer' mémek egyre mainstreamebbek. A használónak meg csak annyira van választása, mint a heroinfüggőnek. A használó nem dönt úgy, hogy függő lesz, hanem becsalják egy alattomos csapdába.  Ha a használók hirtelen, varázsütésre le tudnának állni, holnap már csak a most kezdő serdülők lennének használók, akik azt hiszik, hogy bármikor abba tudnák hagyni.

De minek a kettős mérce? A heroinfüggőket miért látják bűnözőnek, de közben miért tudnak függőként regisztrálni, metadon-kezelést, és rendes orvosi ellátást kapni hogy meg tudjanak szabadulni a függőségtől? Próbálj meg pornófüggőként regisztálni, ha el is mész az orvoshoz, vagy azt fogja mondani hogy *"Ne csinálja annyit, csak mértékkel"*, ami tudod hogy nem használ, vagy felír gyógyszereket a 'depressziód' ellen. Ami még rosszabb, az a tanács, hogy keress valódi társat, most komolyan? Hallott-e már az orvos azokról a használókról akik a pornót részesítik előnyben, és a társuk háta mögött csinálják? Sokan nem ismerik a problémát elég jól, vagy csak nem értik. 

Az ijesztegetés sem segít leállni, sőt inkább megnehezíti. A használókat csupán megrémíti, amitől méginkább használni akarnak. A kamaszokat sem tudja megakadályozni, hogy ráfüggjenek. Ők tudják, hogy a pornó tönkreteszi a libidójukat, de azt is tudni vélik, hogy egy pillantás nem számít. Mivel a függőség olyan gyakori, előbb vagy utóbb ki fogja próbálni - vagy a társas nyomás miatt, vagy kíváncsiságból. Mivel igen borzalmas, valószínűleg rá is fog függeni.

Miért hagyjuk, hogy ez a botrány folytatódjon? A kormányok miért nem folytatnak ez ellen kampányokat? Miért nem hallani arról eleget, hogy a pornó egy drog, egy méreg, hogy nem lazít el, nem ad magabiztosságot, ellenben hogy tönkreteszi a jellemed, és egyetlen pillantástól függő leszel? Miért nem tudnak életkor-megerősítést bevezetni regisztrált bankkártyával, vagy esetleg egy harmadik fél által? A Mindgeek nevű cég, sok nagy pornóoldal tulajdonosa, arra akarja rávenni a kormányokat hogy a saját életkor-ellenőrző rendszerét vezessék be - ne hagyjuk! H.G. Wells *Az időgép* c. regénye leír egy esetet a távoli jövőben, ahol egy ember belezuhan a folyóba, a társai pedig csak ülnek a folyóparton, mit sem törődve a segélykiáltásaival. Ez embertelen és felkavaró, csak úgy mint a társadalom hozzáállása a pornó-krízishez. 

A társadalomban a változás szele fúj. Egy hógolyó indult le a hegytetőről, és ez a könyv remélhetőleg segít, hogy lavina legyen belőle. Te is segíthetsz, ha terjeszted az üzenetet. 

Ezért, ha látsz valakit az akaraterő módszerrel szenvedni, vagy látod hogy le szeretne szokni, finoman irányítsd át ehhez a módszerhez. Azonban, a valódi feladat az, hogy megváltoztassuk a pornó körüli hozzáállást. Tehát ha lehet, csinálj abból szokást, hogy ha online belefutsz, vagy akár közvetlenül érzékeled a pornó normalizációját, *udvariasan* próbáld meg felvilágosítani és így felszabadítani az illetőket. 

Esetenként belefuthatsz negatív reakciókba, de néha csak egy hozzászólás kell.  Ahogy előtted már sokan mások, te is számíthatsz a hálálkodó üzenetekre azoktól, akik ennek köszönhetően felszabadultak. 

## Még egy figyelmeztetés 

Most már élvezheted az életet, mint egy boldog nem-használó. Ahhoz hogy ez biztosan így legyen, ezt a pár egyszerű utasítást kell követned.

1.  Könyvjelzőzd be ezt az oldalt, és hivatkozz rá annyiszor, amennyiszer csak kell.

2.  Ha irigyelni kezdenél egy használót, jusson eszedbe hogy ő irigyel téged. Te nem fosztod meg magad semmitől. Ő meg igen.

3.  Emlékezz, hogy nem volt jó használónak lenni. Ezért szoktál le. Nem-használónak lenni pedig jó. 

4.  Emlékezz hogy a 'csak egy pillantás' nem létezik. 

5.  Soha ne kérdőjelezd meg a döntését, hogy nem nézel pornót soha többé. Tudod hogy ez a helyes döntés.

6.  Ha nehézségeid vannak, keress fel egy terapeutát, aki ért az internetes pornóhoz. Egy kereséssel könnyen megtalálhatóak. 
