# Az instrukciók

1.  Kövesd az összes instrukciót.

2.  Legyél nyitott.

3.  Kezdj egy örömteli érzéssel. 

4.  Hagyj figyelmen kívül minden tanácsot és befolyást, ami szembemegy a Járható Úttal.

5.  Utasítsd el az az időleges örömet nyújtó használat ígéretét.

6.  Vésd az eszedbe: a pornó se nem hoz örömöt, se nem nyújt támaszt, és nem hozol áldozatot. Nincs mit feladni, és nincs oka hogy úgy érezd, valamitől megvonod magad.

7.  Ne várj arra hogy leszokj, tedd meg most!

8.  Határozd el hogy soha többé nem nézel pornót, és ezt ne kérdőjelezd meg.

9.  Emlékezz, hogy a 'csak egy pillantás' nem létezik.

10. Ne nézz soha többet pornót.

## Megerősítések

-   Nem vagyok már a pornó rabja.

-   Könnyű figyelmen kívül hagyni a pornóval kapcsolatos gondolataimat.

-   Az ilyen jellegű gondolatok, az ingerek, és a sóvárgás is elmúlt.A tudatalattimra fókuszálok hogy le tudjam győzni a pornófüggőséget

-   A pornó megfoszt az időmtől, az energiámtól, és az életerőmtől.

-   A pornó legyőzése napról-napra egyre könnyebb, minden aspektusban.

-   Élvezem és nagyra értékelem a pornómentes, erőteljes, és könnyű életmódomat.

-   Visszagondolva a haladásomra, örülök és büszke vagyok magamra.

-   Mindig amikor pornóhasználókat látok, egyre motiváltabb leszek hogy letörjem a láncaimat.

-   Az eddig visszatartott energia meggyógyítja a testem és a lelkem. Így produktív és kihívást jelentő munkát tudok végezni az értékeim és a céljaim érdekében.

-   Az agyam visszatér a régi jó állapotába, és azzal erősítem, hogy nem teszem azt, amit korábban tettem. 

-   Az eddig visszatartott akaraterőt arra használom, hogy az élet nehézségeit és stresszes helyzeteit legyűrjem.

-   Remek, szabad vagyok, és nem a pornó rabja!
