# A könyv vége és utószó

## Hackauthorš üzenete

*A következőkben Hackauthorš üzenetét tolmácsolom, pár szükséges módosítással.*

Szia, itt újra Hackauthorš. Először is, rendkívül hálásan köszönöm hogy elolvastad a könyvet. A szabadság csodálatos! Az eredeti Hackauthor könyve megváltoztatta az életemet, és azóta minden sima. Elmondom újra, hogy Allen Carr micsoda egy remek fickó, aki számtalan embernek segített kiszabadulni a függőség csapdájából. 

Ha ez a hack-könyv segített, egy pár dologgal te is besegíthetsz:

:   **Fejleszd a könyvet.** A Járható Út nyílt forráskódú, és R Markdownban íródott. Ha valami javítanivalót észlelsz, könnyű kijavítani, és ebben a videóban meg is található a mikéntje. MÉG NINCS KÉSZ!

:   **Fordítsd le!** *A kedves Olvasó ennek a termékét látja* -  a ford.

:   **Terjeszd az igét.** Igaz hogy korábban is kértem, hogy oszd meg a könyvet, de most az ezt olvasó zoomerekhez szeretnék szólni, hogy milyen menő lenne, ha a pornográfia káros következményeiről az iskolában is elindítanál egy párbeszédet, és hogyha a szexuális felvilágosító órákon is szó esne róla. A Tiktok fortnite memelordoskodás, a duobledoorok le-AWPzása, a hosszú órákon át Youtube nézés, és közben ugyanezt csinálókkal Discordon dumálás helyett csinálhatnál is valamit. Szállj le az internetről, és próbáld meg megtalálni a módját, hogy hogyan tehetnéd jobbá a világot, és hogyan ne legyél a cégek árucikke.

    És ezt jóindulatból mondom. Félelmetes, hogy mennyi időt töltöttem régen a gép előtt, és a szüleiteknek sajnos igazuk volt, hogy számítógép = rossz. De mi lenne ha máshogy töltenéd azt a sok időt? Tanulj meg hasznos készségeket, segíts másokon, fejleszd magadat, stb. A rendszert ez sokként fogja érni, de ez a jó benne. Gondolj bele, mi hasznosat csinálhatnátok a srácokkal. Faültetés? Szemétszedés? Készségek tanulása? Nem tudom, végtelen számú dolog van, és ugye nem az én életem. De sikerülni fog!

:   **Adományozz Alexander Rhodes jogi megsegítésére.** A pornóipar és csatlósai a Nofap alapítóját rágalmazzák, és elég súlyos a dolog. Bár  remélhetőleg már nem hiszel az akaraterő-módszer hatékonyságában, és a könyv az összes platformukról ki van tiltva, de ez akkor is egy súlyos ügy. Mivel tudod hogy milyen sok pénzt spórolsz meg a leszokással, segítsd meg Alexet egy kis összeggel (vagy egy nagy összeggel). https://nofap.com/defend-alex/

A covid előtt Új-Zélandon voltam. Tudtad, hogy a jetlaget úgy lehet a legjobban megelőzni, hogy nem eszel és iszol felkelés előtt tizenhat órán át? És ez nem csak a jetlagre jó, hanem ha bármilyen módon kizökkentetted a  cirkadián ritmusod, például ha késő estig pornót néztél, ez akkor is használ.

Le van írva, hogy ne változtasd meg **csak azért** az életedet, mert leszoktál, és ez így igaz. Azonban, a függőségektől való megszabadulás lehetővé teszi hogy olyan életed legyen, amiről nem is tudtad, hogy szeretnéd.

Azt például tudtad, hogy egy bizonyos mennyiségű információra is rá lehet függeni? A közösségi média úgy van terveze, hogy egy félkarú rablóra emlékeztessen. A folyamatos információval való bombázás csökkenti a képességed hogy koncentrálj, hogy elbírj a stresszel, és a hangulatod is lelombozza.  Ami még alattomosabb, egy önkényes értékrendszerbe helyezi az önértékelésedet. De ami még fontosabb, mit érzel, amikor ezt olvasod? Félelmet?

Minden közösségi média használóhoz hasonlóan téged is becsaltak az ember vagy a természet által valaha is felállított legalattomosabb, és legnehezebben észrevehető csapdába, a függőség csapdájába. Egy pillanat erejéig, gondolj bele, hoztál-e már olyan “pozitív” döntést, hogy *szükséged* van  közösségi médiára, életed végéig, és nélküle bizonytalan és kétségbeesett vagy?

Jó első lépés, ha számolod, mennyi időt töltesz ***bármiféle*** technológián, ha letörölsz appokat, és ha szürkeárnyalatosra állítanád a telefonod képernyőjét. Írd le az olyan minőségi, offline tevékenységeket, amiket csinálhatsz a jelentős mennyiségű megtakarított időben, és listázd azokat a dolgokat, amiket **muszáj** csinálni a gépen (tanulás, munka stb.), és optimalizáld hogy mivel mennyi időt töltesz (és a snapchat nem számít prioritásnak). Ahhoz hogy ez menjen, akarnod is kell, de van egy olyan sanda gyanúm, hogy rá fogsz jönni, hogy a sok telefon-nézést igazából nem is élvezed. Egy harminc -vagy több- napos detox után fokozatosan vezesd vissza a technológiát. 

A meditáció itt már sokat lett reklámozva, de tényleg érdemes csinálni. Ez nem egy vallásos dolog, és fontos megkülönböztetni a meditációt - a gondolatok észrevevését - az előre belegondolt buddhista eszméktől. Nem fizetnek hogy reklámozzak, de személy szerint a *Waking Up* nevű appot és kurzust ajánlom, amihez kaphatsz egy ingyenes hónapot az alábbi linken. Sam Harris akkora egy király arc, hogy kérhetsz egy ingyenes évet ha nincs rá pénzed. https://share.wakingup.com/a13290 

A szabadság a pornográfiától esélyesen megnyitja a kapcsolatok világát, vagy legalábbis sokat segít.  Ha gondban vagy az ismerkedéssel és a párkapcsolatokkal - akkor is ha nem - ***rendkívül ajánlom*** Mark Manson *‘Models’* c. könyvét, ami a párkapcsolatokban lévő sebezhetőséget vitatja meg. Nagyon örülök hogy nem estem bele se a ‘csajozóművészek’ se az incelek csapdájába, egyik sem egészséges. 

Kezdj el edzeni is, a kedvenc könyvem a témában a  “The Leangains Method” Martin Berkhantól. Férfiak és nőknek egyaránt, kortól függetlenül az erőemelés a legjobb módja annak, hogy megőrizd az egészséged. Ha nincs hozzáférésed edzőtermi felszereléshez, saját testsúlyos edzéssel is remek haladást lehet elérni (ennek a reddites közössége egész jó).

Máskülönben, ha valami rövidebbet keresel, jelenleg a kedvenc írásom az ["Exiting Modernity"](https://www.meta-nomad.net/exiting-modernity/) Meta Nomadtól. Ha csak egy dolgot akarsz innen megfogadni, akkor legyen az, hogy elolvasod ezt az írást. De vigyázz, mert ez egy igen konfrontálódó egy írás, de egy felvilágosító élmény. Ha hagyod.

> *“A túl késő nem egy időszak, vagy egy időpont; a túl késő akkor van, amikor a kimerültség behódodáshoz vezet, és az ember teljesen elfelejtkezik magáról, amikor egy potenciális ember a semmibe foszlik”.*
>
> --- Meta Nomad, *Exiting Modernity*

De ezek végülis csak javaslatok. Mit szeretnél megvalósítani? Kiszabadultál a csapdából, és ezzel úgy élhetsz, ahogy szeretnél. 

A pornográfia hüdrája túl nagyra nőtt. Bár a társadalom lassan reagál, de te azért legyél optimista, ugyanis minden egyes ember aki kiszabadul, felgyorsítja a hógolyót. Sose feledd, hogy mi mindent lehet elérni azzal, ha valamire ráirányítod a figyelmedet, kampányolj azok miatt a dolgok miatt, amik érdekelnek, például fenntarthatóság, szexuális felvilágosítás, stb. Ne panaszkodj, ne legyél passzív, és tedd fel a kérdést, hogy hogyan tudnád befolyásolni a körülötted lévő világot.  Ne feledd, hogy a változás sosem felülről indul, ellenben kezdődhet veled is. 

Végül itt vannak a linkek a könyv elejéről, ha meg szeretnéd osztani a tapasztalataidat.

*Plusz egy magyar [discord szerver](https://discord.gg/D54n6E4A7D), direkt ehhez a könyvhöz : https://discord.gg/D54n6E4A7D*

*és az eredeti angol nyelvűek:*

[coomer meme-tár](https://coomer.org) | [analitikák az oldalhoz](https://plausible.io/easypeasymethod.org) | [matrix](https://matrix.to/#/!xmJZznbJXuwzEGSEti:matrix.org?via=matrix.org) | [discord](https://discord.com/invite/bCXEnf9) | [reddit](https://reddit.com/r/pmohackbook)

Megtalálhatsz [YouTube-on](https://www.youtube.com/channel/UChMZhvS7eV-WoLDu_mRjEEw), ahol a támogatásodat nagyra értékelem

Ha nehezen tudod alkalmazni a könyvben lévő leckéket, érdemes a discordon vagy a subredditen posztolni, ahol a egy remek közösség nagyon szívesen megválaszol minden kérdést. (*Igaz mind az angol, mind a magyar változatra -  a ford.*)

Ha kapcsolatba szeretnél velem lépni, vedd figyelembe, hogy szándékosan nehezen elérhető próbálok lenni. Ha van egy olyan ajánlatod, lehetőséged, vagy valamihez való bemutatásod, ami szerinted érdekelne, küldj egy emailt a **interesting [kukac] easypeasymethod.org** címre, vagy küldj egy üzenetet Urbiton ~mislyr-midnyt címre. A fönti okok miatt csak az olyan ajánlatokra fogok reagálni, amik az érdeklődési körömbe és az időmbe is beleférnek.

Cheers mate,

[Fraser Patterson](https://snug.gy)

## A fordító utószava

Szia! Örülök, nem hiszed el hogy mennyire örülök, hogy elolvastad a könyvet. De te még jobban örülj, ugyanis szabad vagy (és az is maradsz, ha jól csinálod). A pornó egy alattomos, ocsmány csapda, amiben az egyetlen jó dolog, hogy ki lehet belőle szabadulni, amit meg is tettél. A könyvről annyit, hogy nem vagyok se műfordító, se tolmács, így a fordítás nem tökéletes, de szerintem azért egész jó. Ha javítanivalót találsz rajta, ne habozz, és javítsd ki, nyílt forráskódú ugyebár.

A fordításnak 2020 novemberében vagy decemberében álltam neki, és a következő év február tizenegyedikén, csütörtökön, pontban délben nyomtam le a pontot a rendes szöveg utolsó mondatának végén. Hosszú hónapok teltek el a kettő között, de egymillió százalékosan megérte. Nem tudok itt sok újat mondani, ami fontos, már le lett írva. Minden jót kívánok, és csatlakozz a [discord szerverhez](https://discord.gg/D54n6E4A7D) 
https://discord.gg/D54n6E4A7D

-Üdv, a Fordító

*Jelen fordítás a hetedik fejezetig az ‘EasyPeasy Method’ (https://easypeasymethod.org/) 2020 11. 11-es, onnantól pedig a 2020 12. 19-es változatán alapul, kivéve a legvégét, mert az a fordítás átdolgozásának időpontjában fenn lévő verzión (2021 február vége-március eleje)*

Egyébként van még egy további fejezet, benne a könyhöz kapcsolódó további olvasmányokkal.
